silx/io/setup.py
=> Allow build under windows.

silx/gui/plot/test/testPlotWidget.py, silx/gui/test/utils.py
- Close and delete PlotWidget in tests.
- Init a list of exisiting widgets that are not under silx control before running the tests.
Then use this list when checking if tests are leaking widgets.
=> Update Qt test to support Qt5

.travis.yml, ci/appveyor.yml, setup.py, silx/io/__init__.py, silx/io/dictdump.py, silx/io/spectoh5.py, silx/io/test/test_dictdump.py, silx/io/test/test_specfile.py, silx/io/test/test_spectoh5.py, silx/io/test/test_utils.py, silx/io/utils.py
- removed `h5py` from install requirements in `setup.py`
- added `@skipIf(…)` for tests requiring `h5py`
- added error message logging and `ImportError` raising when trying to use a module or function requiring `h5py`
- added a line in Travis and AppVeyor config files to manually install `h5py` and keep running the tests, as it is no considered a mandatory dependency when running `pip install silx`
=> Make h5py an optional dependency

silx/io/configdict.py, silx/io/dictdump.py, silx/io/test/test_dictdump.py
- Make `ConfigDict` an OrderedDict. This results in internal changes only, it does not affect the API. Files written with previous versions of  `ConfigDict` can still be read back. The relative order of values in a section is preserved, and the relative order of sub-sections in a section is preserved, but due to the output file format we cannot preserve the relative order between a value and a sub-section in a section (subsections are written after all top level values) 
- Update docstrings.
=> Make ConfigDict ordered

silx/io/spech5.py, silx/io/test/test_spech5.py
Fix for #91
Added unit tests for spec_date_to_iso8601.
**Nominal** tests only.
The **zone** keyword is **not** tested. I haven't added tests for the **error** cases either.
I checked that the new tests fail with the previous version of the function.
BTW the function only works if the provided spec dates are in english (Mon, Apr, Aug, Sun, ....). Are we sure this will always be the case?
=> Fix #91 (spec_date_to_iso8601)

README.rst, ci/appveyor.yml
This PR enables use of the Pro Appveyor plane:
- change appveyor badge in README
- Use a specific worker (required for now to download from silx.org)
=> [CI] Appveyor switch to Pro plane

requirements.txt, silx/gui/qt.py
List all project's dependencies.
Closes #101 
Some points to discuss:
- If a wheel is available for PyQt/PySide it installs it, otherwise it does not install PyQt/PySide. Do we want that?
Alternative 1: Do not put pyqt/pyside in requirements.txt and add a requirements-qt.txt for this.
Alternative 2: Choose one e.g., PyQt5 and enforces it (in requirements.txt only)
- if h5py is not installed and no wheel is available, it will not be installed
=> Add a requirements.txt

doc/source/install.rst
Source archive filename is different on github than on PyPi
=> correct ambiguous download instruction in install.rst

requirements.txt, run_tests.py
Addresses #136
My current change https://github.com/silx-kit/silx/commit/d6cbd0334e7583332828443b2a5def12b6607a02 does not modify the previous behavior of printing dots for successful tests, `s` for skipped tests, `E` for errors and `F` for failures.  It just adds the option to increase the verbosity of the tests themselves (not only the logging verbosity) with option -vv.
The test verbosity parameter can be:
- 0 (quiet): you just get the total numbers of tests executed and the global result
- 1 (default): you get the same plus a dot for every successful test or a F for every failure
- 2 (verbose): you get the help string of every test and the result
To summarize:
- `python run_tests.py` sets `logging` level to _WARNING_ and `unittest.TextTestRunner` verbosity to _1_
- `python …
=> Test verbosity

doc/source/install.rst
This is my suggestion to emphasize the importance of python 64 on Windows. But I don't think most windows users will read it, especially if they already have python installed.
=> [install doc]emphasize importance of Python 64-bit

silx/gui/plot/PlotActions.py
Related to #131:
- enable/disable reset zoom action depending on autoscale + change tooltip
- behavior change: reset zoom when checking an autoscale action + update tooltip
=> [Plot] Add more info to reset zoom/autoscale tools + change behavior of autoscale buttons

silx/gui/qt.py
This order is sync with IPython order on Debian 8 which is not checking for PyQt5.
=> [GUI] Change qt binding preference order 

CHANGELOG.rst
* Added configuration dictionary dumping/loading to/from JSON and INI files in silx.io.configdict
* Added bilinear interpolator and line-profile for images to silx.image
* Added Levenberg-Marquardt least-square fitting algorithm to silx.math.fit
* Histogramnd changed to become a class rather than a function, API and return values changed
* Added HistogramndLut, using a lookup table to bin data onto a regular grid for several sets of
data sharing the same coordinates
* Added legend widget and bottom toolbar to PlotWindow
* Added a line-profile toolbar to PlotWindow
* Added ImageView widget with side histograms and profile toolbar
* Added IPython console widget, to be started from PlotWindow toolbar
* Added Plot1D widget for curves and Plot2D widget for images
* Added ROI widget for curves …
=> changelog for release 0.2.0

silx/gui/plot/test/testPlotTools.py
On some systems, a "NameError: name 'numpy' is not defined" is raised when running tests using code from PlotTools docstrings.
These docstring tests are duplicate of the test suites in testPlotTools.py, so this removal does not affect test coverage of real code.
It affects test coverage of docstrings, so this issue should still be investigated.
=> Disable doctest for PlotTools because of exotic error message

silx/gui/plot/test/testColormapDialog.py, silx/gui/plot/test/testPlotTools.py, silx/gui/plot/test/testPlotWindow.py, silx/gui/testutils.py
Activate window and raise it to top when waiting for it to be exposed.
Closes #133
=> [Plot] Makes sure Qt window is activated and on top for tests

silx/math/fit/leastsq.py, silx/math/test/test_fit.py
The uncertainties calculation for `infodict['uncertainty']` had a loop on the wrong range, the length of the second dimension of `constraints` instead of the first dimension.   `constraints` has been transposed when it was included in _silx_.
=> Fix index issue in leastsq()

silx/gui/plot/test/testPlotTools.py, silx/io/spectoh5.py
This PR improves documentation of `silx.io.spectoh5` regarding string encoding in generated HDF5 files.
=> Document hdf5 string encoding

silx/io/spech5.py
This fixes a bug causing a `TypeError:  list indices must be integers, not str` when opening a specfile with no scan header.
=> Fix bug (use file_header_dict instead of file_header to get date)

doc/source/modules/io/index.rst, doc/source/modules/io/octaveh5.rst, silx/gui/plot/test/testPlotTools.py, silx/io/octaveh5.py, silx/io/test/__init__.py, silx/io/test/test_octaveh5.py
A simple class to make communication between Octave and Python (using hdf5 structures).
Mainly developed by CaptainNemoz.
For Octave version < 3.8 we need to add a small hack to make sure we don t loose information (adding an extra character for sq_string values )
=> Add octaveh5 file and the corresponding unit tests.

silx/gui/qt.py
qt.Property was missing on PyQt4 and 5
That's a copy-past of the Signal management (pySide-like)
=> Support qt.Property with PyQt

doc/source/install.rst
Minor documentation fix: h5py now provides wheels for MacOS X (and also for manylinux, btw)
=> Fix Mac OS X h5py install instructions (h5py now provides wheels)

silx/gui/plot/PlotActions.py
A "cosmetic" fix that surrounds the filter's extension with parentheses, similar to other software, e.g. Qt Designer.
=> Add parentheses around the file extension of the filters

silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/testutils.py
This PR attempts to fix issue #218 by adding qWait(20) to all mouse and keyboard simulation event methods of the TestCaseQt class.
Closes #218
=> [CI] (Hopefully) fix random bugs on GUI test on Travis-CI

silx/gui/plot/PlotActions.py
This fixes a small bug introduced in #216.
=> Remove parentheses in the extension extracted from the name filter.

silx/io/test/test_utils.py, silx/io/utils.py
Additional fix for #223. 
#225 fixed the issue only when `save1D` is called by a PlotWindow, by making sure xlabel or ylabel is never None.
This PR fixes the problem by setting default labels when `autoheader==True` and labels are `None` (or unspecified).
=> handling of default parameters for save1D

doc/source/modules/io/octaveh5.rst
Sphinx was raising a warning due to the underlining being shorter than the title
=> [octaveh5] correct section title and underlining in rst doc

copyright, silx/gui/_pyside_dynamic.py, silx/gui/qt.py, silx/gui/test/test_qt.py
This PR adds uic.loadUi to qt.py.
For PySide, it provides an alternative implementation which only has the 2 first arguments of loadUi implemented (and warnings when the 2 last are set).
Closes #230
=> [Gui] Add loadUi to qt.py

silx/gui/hdf5/Hdf5TreeView.py
On Retina mac, python 3, Qt5 it was display as 32x32 pixels
=> Force Hdf5TreeView icons to 16x16 (close #278)

silx/gui/console.py
Remove logger error inside `except` clause just before raising the error, because the logger error cannot be quieted when the error is caught and handled downstream.
This closes #263.
Change handling of import, try ipython.qtconsole when qtconsole is present but has no RichIPythonWidget.
=> [console] Improve ImportError handling

silx/gui/plot/ImageView.py, silx/gui/plot/PlotWidget.py
Closes #291 
setFocus in `__init__` and in `main()` of ImageView.
=> [Plot] Fix pan with arrow keys disabled at start-up.

silx/resources/opencl/sift/convolution.cl
OpenCL 2D convolution kernels were re-written to be more readable.
They are also compatible with scipy.ndimage for even-sized convolution filters.
=> OpenCL convolution: more readable kernels

silx/image/sift/test/test_gaussian.py, silx/image/sift/test/test_matching.py, silx/image/sift/utils.py
This PR fixes two errors with the sift tests:
- Fix error with array.sum() for new versions of pyopencl
- Do not perform test_matching if there is no "feature" module
Also, another (equivalent but more numerically stable) least squares routine is used for the linear alignment.
=> Fix errors in SIFT tests

silx/gui/plot/ColormapDialog.py, silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/ImageView.py, silx/gui/plot/LegendSelector.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/Plot.py, silx/gui/plot/PlotTools.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/test/testCurvesROIWidget.py, silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/plot/test/testPlotTools.py, silx/gui/plot/test/testPlotWidget.py
This PR:
- Changes parameter order of plot widgets arguments to have parent first: Related to #280 
- Adds support of single float value for addImage origin and scale arguments: Closes #290
=> [Plot] plot widgets have parent=None first + addImage origin and scale support float

silx/io/spech5.py, silx/io/test/test_spech5.py, silx/io/test/test_utils.py, silx/io/utils.py
Provide a generic loading API for HDF5-like files. It supports h5 files and spec files.
- Create `load` API
- Create `h5py_class` method to flag mimicked objects with the referenced class
=> Feature h5 load API

silx/gui/plot/Plot.py, silx/gui/plot/test/testPlot.py
This PR adds possibility to call getCurve and getImage withou argument, which returns the active curve|image if available, else the last updated (and visible) curve|image.
It adds a few tests for getCurve, getActiveCurve, getImage, getActiveImage
Closes #244
=> [Plot] Add default argument for getCurve and getImage

silx/gui/plot/BackendMatplotlib.py, silx/gui/plot/Plot.py, silx/gui/plot/test/testPlotWidget.py
This PR updates and fix plot addMarker method:
- When symbol is None the text is placed at the x,y position, closes #282
- Fix marker text placement incorrect when zooming
- Fix bug when legend was not provided
=> [Plot] Fix addMarker + change text position if symbol is None

silx/math/fit/test/test_fitmanager.py
Delete temporary pyc files automatically created during import in tests.
=> Delete temporary pyc files created during import in tests

silx/math/marchingcubes/marchingcubes.cpp, silx/math/marchingcubes/marchingcubes.pyx, silx/math/test/test_marchingcubes.py
This PR fixes a cython assert of the image shapes that might fails while shape are the same.
It also changes the API from property vertices, normals and indices to methods get_* to allow future features (such as copy a argument).
=> Update Marching cube

silx/io/spectoh5.py, silx/io/test/test_spectoh5.py
Now that SpecH5Dataset is no longer a numpy array, we need to write the `.value` attribute to HDF5, and not the dataset itself.
=> [spectoh5] Fix critical bug when writing SpecH5Dataset to HDF5

doc/source/Tutorials/fit.rst, doc/source/modules/gui/fit/index.rst, doc/source/modules/math/fit/index.rst, silx/gui/console.py, silx/gui/fit/FitConfig.py, silx/io/configdict.py, silx/io/specfilewrapper.py, silx/io/spech5.py
Put `parent=None` as first parameter in widgets of `silx.gui.console` and `silx.gui.fit.FitConfig`.
Closes #280 _First parameter of widget must be parent widget_ 
I also fixed  minor documentation typos in this PR. It would be preferable to merge this prior to the coming release.
=> [gui] Widget signature (parent=None as first param)

silx/gui/hdf5/test/test_hdf5.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/test/testPlotWindow.py
This PR:
- Closes #344 : aspect ratio and y axis orientation can be hidden as before
- Closes #345 : Replace non standard decorator module by contextlib
- Change PlotToolButton constructor parameters to have parent as first argument
=> [Plot] Fix not possible to hide toolbar tool buttons

run_tests.py
Using `-m` with `run_tests.py` was not anymore displaying fail results
=> Fix run tests log

silx/math/fit/leastsq.py, silx/math/fit/test/test_fit.py
Reduce number of warnings during test. One warning is enough for testing its generation.
=> Fit logger

requirements-dev.txt, setup.py
This PR bumps minimal version of Cython to 0.21.1 (as in Debian 8)
Closes #354
=> Bump Cython version

silx/gui/plot/BackendMatplotlib.py, silx/gui/plot/Interaction.py, silx/gui/plot/Plot.py, silx/gui/plot/PlotInteraction.py
This PR adds events to the interaction state machine when the mouse enters/leaves the plot area.
To handle them, add onEnter(x, y)/onLeave(x, y) methods to the interaction state machine.
To avoid confusion, previously existing methods enter/leave called when a state is entered/leaved has been renamed enterState/leaveState.
Closes #338
=> [Plot] Add enter/leave events to 

silx/gui/plot/BackendMatplotlib.py, silx/gui/plot/Plot.py
This PR uses Qt mouse leave and move events rather than matplotlib enter/leave events to trigger enter/leave events in state machine.
This avoids missing leave events when there is no mouse move event in the outer part of the plot.
=> [Plot] Fix leave event not generate for fast mouse movement

silx/gui/plot/BackendMatplotlib.py, silx/gui/plot/Plot.py, silx/gui/plot/test/testPlotWidget.py
This PR fix display of negative values with log scale.
It replace values <= 0 with nan to show discontinuities.
It also filter xerror and yerror values if any of those is spanning error bars below 0 but changing those to nan.
Values stored with curves remains unchanged.
Closes #330
=> [Plot] Fix display of negative values with log scales

silx/math/fit/test/test_bgtheories.py
Don't loop over a list while modifying it. Loop over a copy of the list that we want to modify, instead.
Some bad anchors that should have been removed were skipped in the loop, because the previous element had been removed in the iterated list.
=> [bugfix] fix snip and strip background tests

silx/image/sift/plan.py, silx/image/sift/test/test_preproc.py, silx/resources/opencl/sift/preprocess.cl
It would be preferable to handle image with these 2 dtypes, as numpy uses them as default in some situations. For example, when attempting naive conversion from RGB to black and white:
- numpy.sum(..., axis=-1) on RGB images (shape=(h, w, 3), dtype=uint8) returns uint64
- numpy.mean(..., axis=-1) on uint8 returns float64
=> [sift] handle dtypes uint64 and float64

silx/io/dictdump.py
Use "w" by default. "a" (append) causes loading issues with ini files, when the same dictionary is appended to a file: duplicated section headers.
=> [dictdump] Uniformize default file mode for various formats

silx/gui/plot/Plot.py
Add missing parameter in `:return:` line
Closes #404
=> [Plot] fix docstring of getCurve

silx/gui/plot/Plot.py, silx/gui/plot/test/testPlot.py
Hidden curves were taken into account by Plot.getDataRange.
This PR does not take them into account for the data range and marks the data range as dirty when a curve is hidden or shown.
Closes #414
=> [Plot] Fix data range not correct when some curves are hidden

silx/gui/qt.py
One can do `import PyQt4, PyQt5` without any trouble, so probe for Py*.QtCore module which cannot be loaded from different bindings.
This should close #415 ... though I could not reproduce the original issue....
=> [Gui] Change the way to probe already loaded Qt binding

doc/source/conf.py, doc/source/modules/gui/hdf5/getting_started.rst, setup.py
- HDF5 tree documentation
- Fix wrong documentation
- Add extra information to point H5Node documentation
- Add comment and difference between obj.h5py_object and obj.value
- Use testcode and testsetup for some tests
- Use `sphinx.ext.doctest`
- Add `test_doc` as a new `setup.py` target
=> Update project documentation process + Fix of HDF5 tree documentation

doc/source/modules/io/spectoh5.rst, silx/io/spectoh5.py
Create a writer class initialized with all parameters needed for the conversion. 
These parameters are now instance attributes rather than global variables accessed in sub-functions.
The actual conversion method then needs only a SpecH5 and a h5py.File. This simplifies the ``with ...:`` block that ensures that the HDF5 file is always closed.
Closes #409.
See also #411
=> Refactor spectoh5 to avoid using nested functions & semi-global vars

silx/gui/plot/PlotActions.py
When users click the fit icon in a PlotWindow, fit only data in the visible X limits.
Currently, the limits are only set when the Fit icon is clicked. 
For future reference, it is technically possible to set the limits automatically, with a callback, when the zoom is changed (see commented code in https://github.com/silx-kit/silx/commit/7c84dced3e9bc26ebf84ea391b52d167f1856151).
=> Set data range in FitAction

doc/source/Tutorials/array_widget.rst, doc/source/modules/gui/widgets/arraytable.rst, doc/source/modules/math/fit/leastsq.rst, silx/gui/widgets/ArrayTableModel.py, silx/gui/widgets/ArrayTableWidget.py
Add two comboxes to select the array dimensions corresponding to the table rows and the table columns. This allows changing the perspective directly from the gui.
Closes #432
=> [ArrayTableWidget] Add dimensions selector widget

silx/io/__init__.py, silx/io/test/test_utils.py, silx/io/utils.py
`silx.io.open` allow to read h5py-like file, but it was not possible to check node types easily. This PR provides a small API to check nodes: `is_file`, `is_group`, `is_dataset`.
=> Create is_dataset, is_file, is_group in the silx.io API

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/PlotActions.py
Handling of multiple curves, none activated: if there is only one, take it.
Else, prompt the user to select a curve.
See #391 (in the future, no curve will be activated until one is explicitely clicked or programmaticaly activated)
=> Minor refactoring of FitAction

silx/io/spech5.py
This PR allow to use `[...]` or `[()]` to reach a scalar value, while `.value` is deprecated.
I am using `[...]` for scalar in `h5py.Dataset`, and the h5py documentation contains:
> To retrieve the contents of a scalar dataset, you can use the same syntax as in NumPy: result = dset[()]. In other words, index into the dataset using an empty tuple.`
Here is the result:
```
In [1]: import silx.io
In [2]: a = silx.io.open("../data/SpecFile/nofhdr.dat")
In [3]: a["1.1/title"][()]
Out[3]: '1  ascan  ss1vo -4.55687 -0.556875  40 0.2'
In [4]: a["1.1/title"][...]
Out[4]: '1  ascan  ss1vo -4.55687 -0.556875  40 0.2'
```
=> Support ellipsis to reach scalar from spech5 datasets

silx/sx/__init__.py, silx/test/__init__.py, silx/test/test_sx.py
It looks to fix a dead lock occured at the end of run_tests on Windows PyQt5.
- A deprecated ipython import is removed
- Order import to be sure the first QApplication is created by the tests (and not by sx module)
- Execute sx tests before gui tests
It looks to fix the issue on our new Windows laptop, but it is difficult to know if it change anything.
=> Fix deadlock on gui tests

silx/utils/array_like.py, silx/utils/test/test_array_like.py
Fix a problem when transposing a view that was already transposed (#495). Add tests for this issue.
Implement `.T` as an alias for `.transpose()`.
=> [array_like] fix double transposition issue

silx/gui/plot/StackView.py, silx/gui/widgets/DataViewer.py, silx/gui/widgets/DataViewerSelector.py, silx/gui/widgets/NumpyAxesSelector.py, silx/gui/widgets/test/test_dataviewer.py
This pull request provide the stack view in the data viewer
It contains few changes on the StackView to be able to integrate it
- Switch StackView as a widget if it is defined with a parent (the code is a copy-paste from other plot widget)
- A method to hide the default browser and axes selector (this information is already provided by the DataViewer)
- And a method to programatically set the visible frame
There is few changes on the DataViewer
- Be able to name an available axes and custom its value at the same time
=> Use StackViewer as a view for the DataViewer

silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py
Make getStack return the original data, no matter what the current view is.
Add getCurrentView() method to: return the view currently displayed in the widget.
=> [StackView] Make getStack return same object set in setStack

silx/gui/plot/PlotWindow.py
Create the console widget only after the corresponding menu is clicked, not when the menu is populated.
Closes #499
=> [plot] Create the console widget only when required

silx/gui/widgets/DataViewer.py
Closes #515 
DataViewer behavior is correct with images (when dimensions change there is a zoom reset and it is not the case when we are on the same dimensions).
=> Call resetZoom on addCurve in order to respect user interface.

silx/gui/_utils.py, silx/gui/plot/BackendMatplotlib.py, silx/gui/plot/Colors.py, silx/gui/plot/PlotActions.py, silx/gui/plot3d/Plot3DActions.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/_font.py, silx/gui/test/__init__.py, silx/gui/test/test_utils.py
In the SaveAction:
- Add save of plot as SVG, closes #503
- Add save of active image with colormap applied as RGB in PNG and TIFF, closes #437
This PR also contains some refactoring:
- New module: silx.gui._utils with QImage<->numpy.array
- Moved colormap functions from matplotlib backend to silx.gui.Colors
=> [plot] Add more formats to plot SaveAction

doc/source/modules/gui/plot3d/index.rst, silx/gui/data/DataViewer.py, silx/gui/plot3d/__init__.py, silx/gui/plot3d/test/__init__.py, silx/gui/qt/_qt.py, silx/gui/test/__init__.py
This PR adds a function to check if plot3d can run (i.e., PyOpenGL and QtOpenGL are available).
This function is used by plot3d tests and DataViewer.
Closes #532, closes #540
=> [plot3d] Handle missing PyOpenGL or QtOpenGL

silx/gui/plot/PlotActions.py
This PR adds option to save plot image as ASCII and ',' ';' and tab-separated CSV files.
Closes #556
=> Add option to save image from plot as ASCII or CSV file

silx/io/fabioh5.py, silx/io/spech5.py, silx/io/test/test_spech5.py, silx/io/test/test_utils.py, silx/io/utils.py
Addresses #562. The basic feature is easily achieved by using silx.io.open.
The display format of datasets is still inconsistent between HDF5 datasets and SpecH5Dataset objects:   `str(h5f[key])` returns a string representation of the complete data array for SpecH5Dataset. FabioH5 objects are still  to be tested.
=> [h5ls] Support spech5 and fabioh5

silx/gui/data/RecordTableView.py, silx/io/fabioh5.py
Some file header from FabIO provide python object from headers, while most of format provide key-value as string-string.
This patch convert most of python object to numpy object.
It fix the issue #580 from PiRK.
=> Fix fabioh5 with special TIFF

silx/gui/plot/PlotWindow.py
Restore properties recently replaced by getters (but deprecate them). closes #547
=> [PlotWindow] backward compatibility

silx/gui/plot3d/SFViewParamTree.py
This PR solves issues that might occur on MacOS with the plot3d parameter tree widget:
- Size of icons too large on retina display
- Buggy color dialogs
closes #555
=> [plot3d] Fix color dialog issue on MacOS

silx/gui/plot/BackendBase.py, silx/gui/plot/BackendMatplotlib.py
This PR fixes an issue with Plot.resetZoom method with data margins and keep aspect ratio on: Closes #452
=> [plot] resetZoom with data margins and keep aspect ratio on

doc/source/modules/gui/widgets/periodictable.rst, silx/gui/widgets/PeriodicTable.py, silx/gui/widgets/test/test_periodictable.py
Add example in documentation to explain adding of custom data to elements.
Make `bgcolor` attribute a simple RGB string rather than a `QColor`
Closes #558
=> [PeriodicTable] mostly documentation

silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/PlotActions.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWindow.py, silx/gui/plot3d/Plot3DActions.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/Plot3DWindow.py, silx/gui/widgets/TableWidget.py
Change context of shortcut ctrl-c, ctrl-v... only when the expected widget have the focus. Else all shortcut of all widget are overwriten, and it is not possible anymore to copy a single text.
- Tested on the Plot2d and it's status bar of the plot2d (arrow keys too)
- Tested on the Plot3D and its toolbar (arrow keys too)
- Tested on the ArrayTableView
- Mask tools was tested (the action context for them was not changed)
But the last commit can be problematic for people who use it. I remove a `setFocus`. It do not have to be there, but maybe there was a good reason for that?
=> Fix shortcut context

README.rst, setup.py
Remove non-breakable space from README.rst, specify encoding=utf-8 in setup.py when reading README.RST
Addresses #601
=> Double fix README encoding issue

ci/appveyor.yml
This adds python3.6 as an environment to test on Windows.
Still need to check the availability of wheels for project dependencies
=> [CI] Add python3.6 to appveyor

README.rst, doc/source/install.rst
Max IV is providing CentOS 7 and Fedora 23 packages.
=> Add links to Max IV Fedora repository

silx/io/dictdump.py, silx/io/test/test_dictdump.py
This will make it easy to load the content of any hdf5-like group as a python dictionary, while filtering out datasets by name. The goal is to easily load subsets of header info from a data file.
=> [h5todict] Accept fabioh5 and spech5 data

examples/stackView.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/Profile.py, silx/gui/plot/ProfileMainWindow.py, silx/gui/plot/StackView.py, silx/gui/plot/test/testProfile.py
Addresses #628, and more refactoring.
- New class `ProfileMainWindow`, for a better handling of switching between Plot1D and Plot2D.
- New getters: `getProfilePlot()` and `getProfileMainWindow()` (provides a uniform API for both `ProfileToolBar` and `Profile3DToolBar`, and reduces the number of methods to be overloaded).
- Deprecate `profileWindow` attribute in favor of `getProfilePlot()` method
- Remove `getProfileWindow1D()`, `getProfileWindow2D()` and `_ndProfileWindow`
I still need to work on getting rid of event filters, if possible.
=> [ProfileToolBar] refactoring

silx/gui/data/Hdf5TableModel.py
key in lambda function was fixed to its value in the last iteration of the "for" loop, when getting HDF5 attrs. This caused the same attribute value to be displayed for all attributes in the HDF5  DataViewer.
=> Fix bug in Hdf5TableModel callback

silx/math/test/test_medianfilter.py
=> Fix median filter test for numpy 1.6.2 (Debian 7)

silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py
Combo-box was not updated when the perspective was changed through `setStack`. 
Closes #676
=> [StackView] update perspective selector when calling setStack()

setup.py
I also would like to:
- Move cmdclass declaration to the bottom
- And remove all those "###########" separator,  cause now the file is much more declarative and executive, then it looks already very readable.
=> Improve setup.py to be able to use pip install while numpy is not here

silx/gui/data/DataViewer.py, silx/gui/data/DataViewerFrame.py, silx/gui/data/test/test_dataviewer.py
- Allow to inherite `createDefaultViews` from `DataViewerFrame`
- Provide an API to `addView` and `removeView` on runtime
- Improve the way the default view is selected by reusing user choices when it is possible
=> Improve dataviewer

doc/source/modules/gui/plot/items.rst, silx/gui/plot/ImageView.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/Plot.py, silx/gui/plot/PlotActions.py, silx/gui/plot/Profile.py, silx/gui/plot/StackView.py, silx/gui/plot/items/__init__.py, silx/gui/plot/items/image.py, silx/gui/plot/items/scatter.py
This PR splits Image class into ImageBase which is inherited by ImageData (2d data + colormap) and ImageRgba (RGB(A) image).
It follows API proposed in issue #686 except for `getGrayscaleImageData` which is not available (there are different ways to compute a grayscale image + this can be added later if needed).
So `Image.getPixmap` is no more available.
Closes #686
=> [plot] Split Image class

silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testPlot.py
This PR adds the possibility to change the symbol size for scatter and curve items. 
i'm not sure about `_DEFAULT_SYMBOL_SIZE = 1.0`. I wasn't able to find the matplotlib default value for markersize (confusing documentation).
=> [plot] symbolsize for scatter and curve

silx/gui/hdf5/NexusSortFilterProxyModel.py, silx/gui/hdf5/test/_mock.py, silx/gui/hdf5/test/test_hdf5.py
This PR sorting items by `start_time` amd `end_time` only for `NXentry` classes. It is efficient and more generic (we can custom other classes if expected) than the proposal on #336.
Closes #336
=> Improve sorting by filtering NX_class types

silx/io/fabioh5.py, silx/io/test/test_fabioh5.py
Here is the first implementation.
- A `sample` group is created only if expected and contains few informations from `UB_pos/mne` and `sample_pos/mne`.
- It only reach data from the first header (i do not check hole the frames for efficiency)
- Nexus requests float for this datasets. `numpy.array` used by it-self `float64`. I think it's fine.
- I add `interpretation=scalar` for this 3 datasets. Like this we display it as raw data.
- I use `medipix.edf` to create a unittest. I think it is a very old data, then it would be nice to test the result with an up-to-date file.
=> [fabioh5] Support UB matrix

silx/gui/plot/PlotActions.py
Ensure the fit curve keeps the same color by reusing a curve object
Also, remove the display of the estimation curve. To do it properly, one would need to update the plot also when the estimated parameters are manually modified.
Closes #742
=> [FitAction] keep a constant color for fitted curve

examples/stackView.py, silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py
closes #567 by displaying the image coordinate as the plot title. This is the image index by default, but can be a calibrated value if a calibration is provided for the image index dimension.
=> [StackView] Image index calibration in plot title

silx/third_party/six.py
- Fix absolute import of six
- Add module documentation
=> Fix absolute import of six with Python 2

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/test/testCurvesROIWidget.py
This PR
[x] closes #770
[x] implements a non-regression test
[x] provides a simpler access to the ROIs (setRois, getRois, calculateRois).
The later can be removed if considered convenient.
=> Correct bug affecting calculation of ROIs

silx/gui/_glutils/VertexBuffer.py, silx/gui/plot/backends/glutils/GLPlotCurve.py
Closes #802 
This fixes support of RGB(A) uint8 color array internally to support color produced by applying colormap to scatter plot.
=> Fix scatter plot with colormap for OpenGL backend

package/debian8/control, package/debian9/control
The dependency was previously on `setuptools`. But debian packages `pkg-resources` into a specific package.
It closes #809
=> Fix dependency from silx package to python3-pkg-resources

silx/opencl/common.py
This PR removes duplicated init code in opencl.common.
It is workaround for issue #813 as it avoids pyopencl's seg fault when imported twice with python2.7-dbg on Debian 8...
But the root of issue #813 which is not in silx remains unsolved.
=> Clean pyopencl import

silx/io/test/test_nxdata.py
A simple assertEqual is good enough, in this case.
=> Issue with debian7: numpy.array_equal not implemented for list of strings

silx/gui/plot/items/curve.py, silx/gui/plot/items/image.py
These warnings were added for detecting usages of the old plot API between releases 0.4 and 0.5
=> [plot.items] Remove deprecation warnings

.travis.yml, setup.py
- Fix flag compiler to have expected behaviour with `--debug`
- Fix flag compiler according to the use of `python-dbg`
- Configure Travis Linux Python 3.4 to be compiled and tested with asserts
It closes #796
It closes #810
=> Update a Travis test to use silx compiled with asserts

silx/__init__.py, silx/image/bilinear.c, silx/image/bilinear.pyx, silx/image/test/test_bilinear.py, silx/opencl/__init__.py, silx/opencl/common.py, silx/opencl/medfilt.py, silx/opencl/processing.py, silx/opencl/sift/alignment.py, silx/opencl/sift/match.py, silx/opencl/sift/plan.py, silx/opencl/sift/test/test_gaussian.py, silx/sx/__init__.py, silx/utils/decorators.py
This PR closes #825 by:
- Removing `logging.basicConfig()` from silx (replaced by do nothing logging handler).
- Calling `logging.basicConfig()` in `sx` module when used from the console. 
- Creating all module's logger using `logging.getLogger(__name__)`
- Renaming deprecation logger to `"silx.DEPREACTION`"
=> Clean-up logging

doc/source/Tutorials/fitconfig.rst, silx/gui/fit/FitConfig.py, silx/gui/plot/ColormapDialog.py, silx/gui/plot/PlotTools.py, silx/gui/plot/_BaseMaskToolsWidget.py, silx/gui/plot3d/SFViewParamTree.py
Hey guys,
I tried to use latest silx and got an error message about `QDoubleValidator()` signature ; it seems it is
invalid to call `QDoubleValidator()` constructor without at least a parent object or `None`, look:
```
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4.QtCore import QT_VERSION_STR
>>> from PyQt4.Qt import PYQT_VERSION_STR
>>> from sip import SIP_VERSION_STR
>>>
>>> print("Qt version:", QT_VERSION_STR)
('Qt version:', '4.6.3')
>>> print("SIP version:", SIP_VERSION_STR)
('SIP version:', '4.10.2')
>>> print("PyQt version:", PYQT_VERSION_STR)
('PyQt version:', '4.7.3')
>>> from PyQt4.QtGui import QDoubleValidator
>>> v=QDoubleValidator() …
```
=> QDoubleValidator() cannot be used without passing parent object

silx/io/specfile/specfile.c, silx/io/specfile/specfile.pyx, silx/io/spech5.py, silx/io/spectoh5.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py
Addresses #858
CHANGELOG: SpecH5Group.visit and .visititems now provide the relative name/path to the callback function (same behavior as h5py.Group.visit and .visititems)
=> [SpecH5] specfile segfault and SpecH5.visit behavior

silx/gui/plot/PlotInteraction.py
This PR implements the _At least_ option of #865 by calling `resetZoom` when the history of zoom levels is empty.
To be compatible with previous event behaviour, when zoom history is empty, it only sends `mouseClicked` event when `resetZoom` didn't changed the limits.
=> Add resetZoom on right click to zoom interation mode

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/Plot.py, silx/gui/plot/ScatterMaskToolsWidget.py, silx/gui/plot/_BaseMaskToolsWidget.py
Adds `resetSelectionMask` to dock widget API.
Fixes also a few  minor sphinx warnings.
EDIT: Initially this PR was meant to close #834, but this will need a bit more work than expected.
=> [mask] minor mask improvements

silx/gui/_glutils/FramebufferTexture.py, silx/gui/_glutils/OpenGLWidget.py, silx/gui/_glutils/VertexBuffer.py, silx/gui/_glutils/__init__.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/Plot3DWindow.py, silx/gui/plot3d/__init__.py, silx/gui/plot3d/scene/window.py
This PR adds support of Qt>=5.4 QOpenGLWidget (which deprecates QGLWidget), closes #793.
It does so by providing a common OpenGLWigdet used by OpenGL plot backend and plot3d which inherits either from QGLWidget or QOpenGLWidget and support High-DPI with Qt5.
It also improves the support of cases where OpenGL is not available (PyQt4.QtOpenGL not installed, OpenGL2.1 not available,...).
In those cases, it displays an error pop-up once and displays an empty widget instead of the OpenGL rendering.
=> Add support of Qt5.4's QOpenGLWidget to OpenGL plot backend and plot3d

silx/gui/plot/MaskToolsWidget.py
- Support TIFF images. It was not the case before, but the tiff extension was provided (maybe a regression)
- Display all available extensions by default
#872
=> Load mask extensions

silx/io/dictdump.py
Use context managers in `dicttoh5` and `h5todict`. Closes #883
=> [dictdump] Make sure files are closed even if an error occurs

silx/app/view.py, silx/gui/data/DataViews.py, silx/gui/data/Hdf5TableView.py, silx/gui/hdf5/Hdf5HeaderView.py, silx/gui/hdf5/Hdf5Item.py, silx/gui/hdf5/Hdf5Node.py, silx/gui/hdf5/Hdf5TreeModel.py, silx/gui/hdf5/NexusSortFilterProxyModel.py, silx/gui/hdf5/_utils.py
- Broken nodes are now selectable
- HDF5 property view displays a little more information
- There is a new column for the kind of links
- I remove the `description` and the `node` columns from `silx view`
Closes #888 
Closes #886 
Closes #885
=> Improve HDF5 property view

silx/gui/plot/ColorBar.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/_utils/__init__.py, silx/gui/plot/test/testColorBar.py
This PR fixes issues in the ColorBarWidget. It fixes most of #889 issues. 
Issues:
Improvements:
Refactoring:
=> [Plot] Fix ColorBarWidget

silx/test/__init__.py, silx/utils/deprecation.py, silx/utils/test/test_deprecation.py
- Add unittest for deprecation module
- Fix empty lines on the output
- Log by default deprecations only once
- Do not display the full backtrace but only the previous caller (which should/must only be outside our lib)
- Fix test suite: test_utils was executed 2 times
=> [utils] Improve deprecation log

silx/io/specfile/specfile.c, silx/io/specfile/specfile.pyx, silx/io/test/test_spech5.py
This makes it easier to catch exceptions without need to import `silx.io.specfile`.
Closes #912
=> [specfile] Make custom errors also inherit standard python errors

silx/io/spech5.py, silx/io/test/test_spech5.py
Don't create  `sample/unit_cell*` datasets if all values are 0 in G1 header line.
Don't create  `sample/ub_matrix` dataset  if all values are 0 in G3 header line.
Don't create `sample` group if both  UB matrix and unit cell are all zeros.
Closes #899 .
=> [spech5] all 0 values in unit cell or UB matrix

.travis.yml
This PR updates travis config to use Ubuntu 14.04 image and should solve PyQt5.9 link issue.
=> [CI] Update travis

silx/opencl/backprojection.py
This PR fixes a bug in the Backprojection class when using it to reconstruct multiple slices.
=> Bugfix in backprojection

silx/opencl/medfilt.py
This PR adds a small bugfix in the OpenCL median filter which was not actually taking into account the kernel size.
=> medfilt2d: take kernel_size into account

doc/source/modules/gui/plot/stackview.rst, silx/gui/data/NXdataWidgets.py, silx/gui/plot/Profile.py, silx/gui/plot/StackView.py
Implement a `getPlot()` method, remove dependency on legacy `StackView` functional API in `Profile3DToolbar`.
Closes #927
=> [StackView] implement getPlot()

ci/appveyor.yml, silx/gui/widgets/TableWidget.py, silx/io/test/test_spech5.py, silx/io/test/test_utils.py
If mode is set to `NoSelection`, the "Copy selected cells" action does not work and raises an error. 
This PR addresses this situation by providing a "copy single cell" action instead, when mode is NoSelection.
=> [TableWidget] copy single cell action

silx/gui/plot/backends/glutils/GLPlotCurve.py
Scatter plot colors were not properly displayed due to a code typo introduced when renaming normalisation to normalization.
To reproduce:
```
from silx import sx
w = sx.Plot1D(backend='gl')
w.show()
x = numpy.arange(256)
w.addScatter(x, x, x)
w.resetZoom()
```
=> [plot gl] Fix bad scatter plot color display

.travis.yml, ci/appveyor.yml, run_tests.py, silx/gui/plot3d/test/__init__.py, silx/gui/plot3d/test/testGL.py, silx/gui/plot3d/test/testScalarFieldView.py, silx/opencl/common.py
This PR sets-up Travis and Appveyor to have OpenGL > 2.1 available:
- Out-of-the bos for Travis/MacOS
- By installing packages on Travis/Linux
- By downloading a pre-compiled Mesa DLL for Appveyor
It adds a test logging OpenGL version and a test for plot3d.ScalarFieldView.
It fixes a minor issue with OpenCL tests (when disabled).
It uses requirements.txt in appveyor configuration.
Close #959
=> [CI] Add OpenGL to test environments

build-deb7.sh
The `setup.py` was cleaned-up. `--no-cython` is an argument of the build target
=> Fix build-deb7

silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/SFViewParamTree.py, silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/scene/axes.py, silx/gui/plot3d/scene/window.py
This PR adds API to ScalarFieldView and Plot3dWidget and checkbox in the ParamTree -> Style to:
- Show/Hide the bounding box, its axes and grid
- Show/Hide the top-right orientation indicator
=> [plot3d] Show/Hide bounding box and orientation indicator

silx/io/fabioh5.py, silx/io/utils.py
Closes #1000 
Importing `fabioh5` without `fabio` being installed now only raises an `ImportError`, without first logging an error message.
`silx.io.open` now only logs warning messages if both `fabioh5` and `spech5` have failed opening the file.
=> [silx.io.open] change logging behavior when library is missing

silx/io/specfile/specfile.c, silx/io/specfile/specfile.pyx, silx/io/spech5.py
This PR will improve the computation time of SpecH5 in the context of the Hdf5Tree.
- SpecH5 have enough information to return request using `getlink` and `getclass` without loading the data at this level. This patch takes care of it.
- SpecH5 will also cache datasets per files
- Links to the same dataset will only be computed one time
=> Improve computation time of SpecH5

silx/resources/__init__.py, silx/test/test_resources.py
- Skip tests if silx.org is not available
- while it is an external system it better to skip tests here
- It should allow Debian to package the lib
- Clean up to have independent tests
Relative to #1009
=> Fix external download

run_tests.py
Implement:
- Bufferization to avoid verbosity in tests (it is disabled when using -v or -vv)
- Display test results when using CTRL-C
Relative to #1012 
Closes #1013
=> [tests] Improve run tests

examples/plotLimits.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/_utils/panzoom.py, silx/gui/plot/test/__init__.py, silx/gui/plot/test/testLimitConstraints.py
`setLimitConstaints` allow to add constaints a-la PyQtGraph, to avoid to move the view outside of an expected zoom or box.
The provided example shows 4 use cases.
Closes #632
=> API to add constraints on plot axes

doc/source/modules/io/spech5.rst, silx/io/commonh5.py, silx/io/spech5.py
These optimizations mostly solve #995.  
The previous PR #1048 already took care of caching the data, to ensure it is loaded only once. 
Now the MCA dataset is also lazy loaded, so the HDF5 tree will not become unresponsive when opening a group containing a heavy MCA dataset (unless we want to see the actual data).
The issue causing the loading to take 5 times longer than usual in a Qt application is still not fixed.
=> [spech5] Lazy mca loading

silx/gui/hdf5/Hdf5Item.py, silx/io/commonh5.py, silx/io/test/test_commonh5.py
- Avoid to store on datasets `object` and `unicode` types (not supported by HDF5)
- Patch the GUI to display datasets as broken if an exception occurs while reaching the data
=> [io] Protect common dataset

silx/gui/hdf5/Hdf5Item.py
- Prefetch data when displaying items of the tree view
- Avoid to load too much or to decompressed data
- An error is displayed on the tooltip
- The exception is displayed if it is used with `silx view --debug`
Closes #1055
=> Prefetch data to display error on the dataset

silx/gui/hdf5/_utils.py, silx/gui/hdf5/test/test_hdf5.py, silx/io/commonh5.py, silx/io/test/test_commonh5.py, silx/io/test/test_fabioh5.py, silx/io/utils.py
- Fix the way node paths are computed with our commonh5 objects (now it match h5py)
- Fix the physical path, which is the hdf5 path when every intermediate links are removed
- A lot of test cases to be sure it is h5py compliant, and that we display the right thing
The screenshot shows that the path `/soft_link_to_group/dataset` is a link to `/group/dataset` and it is not trivial. Previous computation was based on wrong assertion.
Closes #1059
=> [silx view] Fix physical/access path

silx/__main__.py, silx/app/test_.py
- Create `silx test` app
- Reuse only few command lines from run_tests
- CTRL-C cancel tests but display the current result
- Skipped tests are displayed like other output ERROR/FAILED
- Reduce logs by using unittest buffer
- By default nothing is displayed (but `.EFs`) all informations of fails and errors will be displayed at the end (with associated log and stdout)
- `-v` displays for each tests the name then log and stdout
- `-vv` displays for each tests the name then log (with debug level) and stdout
```
> silx test --help
usage: silx test [-h] [-v] [-x] [-g] [-o] [-l] [--qt-binding QT_BINDING]
[test_name [test_name ...]]
Launch unittests of the library
optional arguments:
-h, --help            show this help message and exit
-v, --verbose         Increase verbosity. Option -v prints …
```
=> [test] Create test app

silx/gui/_glutils/OpenGLWidget.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot3d/Plot3DWidget.py
This PR refactors `OpenGLWidget`, the Qt OpenGL wrapper widget used by both plot OpenGL backend and plot3d widgets.
It adds handling of GLX forwarding disabled when connected through ssh with PyQt4 and PySide.
The probing of this situation with PyQt5 seems "beyond repair" as Qt OpenGL widget `__init__` never returns...
The `_OpenGLWidget` inherits either from `QGLWidget` (Qt<5.4) or `QOpenGLWidget` (Qt>=5.4) and provides a wrapper API.
The `OpenGLWidget` is a `QWidget` have either `_OpenGLWidet` (when it works) or a `QLabel` (displaying an error message) as child. It provides a subset of `QOpenGLWidget` API.
=> [plot gl][plot3d] Check GLX forwarding disabled

silx/gui/plot/backends/BackendOpenGL.py
Still need to be tested on macOS and  windows.
closes #996
=> Read from internal framebuffer rather than from widget framebuffer

silx/test/test_resources.py
Socket timeout is not part of six exception.
This PR fix the issue.
=> Fix timeout on test of external resources

.travis.yml, ci/appveyor.yml, ci/close_popup.py, silx/gui/hdf5/test/test_hdf5.py, silx/gui/plot/test/testItem.py, silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/plot/test/testPlotInteraction.py, silx/gui/plot/test/testPlotTools.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/testScatterMaskToolsWidget.py, silx/gui/plot/test/utils.py, silx/gui/plot3d/test/testGL.py, silx/gui/test/utils.py
Tests on GUI using mouse click often fail on Windows and Mac OS plus changes on Appveyor/Travis makes the things more difficult for GUI tests.
This PR try to improve the state of GUI testing by:
- Providing an application to close system popup before executing our tests
- Check reception of MPL events when using mouse interaction over the silx Plot
- [removed] Check reception of Plot events  when using mouse interaction over the silx Plot
- If the event is not received a screenshot is taken in case of further problem with another popup
- Appveyor will expose screenshot as artifact, Travis will display then in the log in base64
Here is output from CI before testing:
```
$ python ci/close_popup.py
INFO:close_popup:Popup database: 2.
INFO:close_popup:Check and close popups. …
```
=> Robustness on GUI unittests

silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/items/core.py
This PR should fix errors spotted by CI that happens with new version of matplotlib: v2.1.0rc1:
- silx.gui.plot.test.testPlotWidget.TestPlotCurveLog.testPlotCurveErrorLogXY
- silx.gui.plot.test.testPlotWidget.TestPlotCurveLog.testPlotCurveToggleLog
It does not change anything about PySide that also seems to be broken on CI...
=> Fix plot errors with latest version of matplotlib

silx/gui/hdf5/Hdf5Node.py, silx/gui/hdf5/test/test_hdf5.py
Use weakref for parent. It allows to destroy everything without use of the gc.
Closes #1073
=> Fix hdf5node tree

silx/io/specfile/include/Lists.h, silx/io/specfile/include/SpecFile.h, silx/io/specfile/include/SpecFileP.h, silx/io/specfile/src/sfdata.c, silx/io/specfile/src/sfheader.c, silx/io/specfile/src/sfindex.c, silx/io/specfile/src/sfinit.c, silx/io/specfile/src/sflabel.c, silx/io/specfile/src/sflists.c, silx/io/specfile/src/sfmca.c, silx/io/specfile/src/sftools.c, silx/io/specfile/src/sfwrite.c
The ancient header information refers to 1995 and not to 2004. The 2004 date is in fact the copyright date for PyMca. The SpecFile C code is much older.
=> Correct incoherence in copyright dates (See header files).

silx/io/test/test_specfile.py, silx/io/test/test_spech5.py, silx/math/fit/test/test_fit.py, silx/test/utils.py
Addresses #1012 : reduce number of warnings printed during tests.
This PR should be discussed in a meeting, because when running tests in verbose mode it would make sense to display warnings.
Commit https://github.com/PiRK/silx/commit/bf264c67d4cdf1edb967161039aba77c211ec07e is probably controversial too. If one tries to add `@utils.test_logging(logger.name, info=1)` to a test, the success depends on running the test in verbose mode (because in standard mode, the INFO messages are never emitted so the count is wrong. But maybe this is a feature, because test succes should be designed to not depend on the logging level? In that case, `@utils.test_logging(logger.name, warning=...)` should also be considered wrong.
Alternatively, we could possibly change the logging level to emit all logs …
=> Silent warnings

LICENSE, README.rst, copyright, doc/source/license.rst
This PR removes LGPL license from the licence doc page and the readme.
=> [doc] Update license information in doc and README

silx/gui/plot3d/SFViewParamTree.py, silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/scene/function.py
This PR adds the support of virtually any colormap (rather than a subset).
It adds the new matplotlib colormap (viridis and co) to the colormap options in the plot3d parameters tree.
Closes #956
=> [plot3d] Add support of any colormap

silx/math/combo.c, silx/math/combo.pyx
This PR avoids copying the array if it is not necessary in `min_max` function.
=> [math] Avoid array copies in min_max

doc/source/Tutorials/specfile_to_hdf5.rst
Replace `spectoh5` module with `convert`. Closes #1161
=> Update SPEC as H5 tutorial

silx/app/view.py, silx/io/rawh5.py, silx/io/test/__init__.py, silx/io/test/test_rawh5.py, silx/io/utils.py
This PR allow to load `npz` files using `silx.io.open`.
numpy supports more types than h5py can support, especially 'U' (UTF-32 strings) and 'O' (python object), then we can't be sure everything will be displayed properly. But for common data types it should be fine.
`npy` files still using FabioH5 and then are exposed using the NeXus layout.
Closes #1152
=> [io] Support npz in silx.io.open

silx/io/commonh5.py, silx/io/rawh5.py, silx/io/test/test_commonh5.py, silx/io/test/test_rawh5.py
This PR improve compatibility of commonh5 with h5py:
- Allow to use `create_group` with paths like `a/b/c`
- Allow to set a dataset using set item: `group["a"] = 10`
- Altogether allow to use `file["a/b/c"] = 10`
This make the fix on `npz` format trivial.
Closes #1180
=> Support for directory in npz

silx/gui/hdf5/Hdf5TreeView.py, silx/gui/hdf5/test/test_hdf5.py
This API allow to select an item of the Hdf5TreeView using an h5py node. This can be useful for dialog windows.
Feature requested by Alessandro Mirone.
- If the item is found, parent items are expended, and then the item is selected.
- If the item is not found, the selection do not change.
- A none argument allow to deselect everything
=> [treeview] Provide an API to select a single tree node item

silx/gui/hdf5/Hdf5TreeModel.py
Here is a PR to close H5 file on model destruction, based on Alessandro Mirone work.
It also remove a cross reference between QObject, which is always good.
=> [treeview] Model now closes files that have been opened 

silx/gui/plot/Profile.py
Fix profile interaction mode by unchecking line profile actions (see #1195 for how to reproduce).
closes #1195
=> [plot] Fix profile interaction mode

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot3d/scene/window.py
Some areas of the 3D view with transparent isosurface were really transparent and showing the underlying widget in `silx view` with PyQt5...
This PR makes sure the displayed image is opaque with `Plot3DWidget` (and with plot GL backend).
closes #1126
=> [plot3d] Fix display issue in silx view due to transparency

silx/gui/data/ArrayTableModel.py, silx/gui/data/DataViewer.py, silx/gui/data/DataViews.py, silx/gui/data/Hdf5TableView.py, silx/gui/data/HexaTableView.py, silx/gui/data/RecordTableView.py, silx/gui/data/TextFormatter.py, silx/gui/data/test/test_textformatter.py, silx/gui/hdf5/Hdf5Formatter.py, silx/gui/hdf5/Hdf5Item.py, silx/gui/hdf5/Hdf5TreeModel.py
Folling the presentation of Gerd Heber on HDF5, it is more or less possible to display and store ASCII and UTF-8 properly using `h5py`.
This document http://docs.h5py.org/en/latest/special.html explains how to store and retrieve HDF5 datatypes which are not supported by numpy. Mostly enum, ref and UTF-8 variable-length.
The current master:
- Store UTF-8 as HDF5 ASCII type, which is very bad
- Tries to decode ASCII as UTF-8, which is also bad
- Do not support ref, enum, UTF-8 properly
This PR improve things:
- Fixes the formatter to display special types properly (enum, ref, strings, vlen)
- Fixes informations displayed in the tree (which can be tested using `/tmp_14_days/valls/all_types.h5`)
- Fixes informations displayed in the HDF5 info view (now the real HDF5 type is also displayed)
- …
=> Rework for h5py types

silx/gui/data/DataViews.py, silx/io/nxdata.py, silx/io/test/test_nxdata.py
Reading a byte string from an attribute and comparing it with a unicode string caused an error in python 3, while trying to find a dataset with a specific `@long_name` attribute.
=> [nxdata] Fix decoding attributes

silx/gui/data/Hdf5TableView.py
The size is now displayed together with the shape. That's clearer. Previously the size was on another field, and was quite confusing (size of what? in KB?).
Closes #1209
=> Improve the rendering of the shape in the HDF5 info viewer

silx/gui/plot/items/image.py
Save image data as PNG was broken (related to introduction of `Colormap` object)
This PR fixes it.
=> [plot] Fix save image data as PNG 

silx/app/test/test_view.py, silx/app/view.py, silx/gui/hdf5/_utils.py, silx/io/test/test_utils.py, silx/io/utils.py, silx/utils/proxy.py, silx/utils/test/__init__.py, silx/utils/test/test_proxy.py
Merge first https://github.com/silx-kit/silx/pull/1223, i can then rebase this PR if you like.
- Add a generic proxy for python object (`silx.utils.proxy.Proxy`)
- Implement `filename::path` in `silx.io.open()`
- The implementation returns a proxy to the target node which also owns the opened file
- This proxy provides API of the target object, plus common API of opened files (`close` method and context management)
- Update `silx view` to avoid to check files before using `silx.io.open`
- As result the viewer is always displayed anyway the files from the command line exist or not.
Closes  #1157 
```
valls@linkdick ~/workspace/silx.git (support-path-in-filename) $ ./bootstrap.py silx view 201606id01-FZP-S0013-result-new.npz::obj ../all_types.h5::float toto ../data/cant_be_read.h5 …
```
=> [silx view/io] Support filename::path

silx/gui/plot/MaskToolsWidget.py
In silx view hideEvent can be called twice, this PR handles it.
closes  #1230
=> [plot] MaskToolsWidget allows to call hideEvent twice

silx/gui/plot3d/SFViewParamTree.py
This PR adds a workaround for python3/PySide for the ScalarFieldView parameter tree, where signal connections were failing.
It solves this by wrapping the calls the methods in a lambda function....
Not really nice, but not really other option unless we drop PySide...
Closes #991
=> [plot3d] Avoid failures of the parameter tree with python3/PySide

silx/gui/plot3d/test/testScalarFieldView.py
This PR fixes ScalarFieldView test on windows, python2.7 pyqt4.
It removes the parameter tree view widget from ScalarFieldView test.
Closes #1250
=> [plot3d] Fix ScalarFieldView test

silx/gui/plot/backends/BackendMatplotlib.py
This PR refactors the way replot/draw of matplotlib backend is handled.
It avoids recursive repaint with matplotlib v2.1.0 and PyQt5.
Closes #1273
=> [plot] Refactor matplotlib backend draw control

silx/gui/_glutils/gl.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/scene/viewport.py
This PR improves the look of the top-right axes orientation indicator by displaying the axes in a semi-transparent circle rather than in an opaque square.
Closes #993
=> [plot3d] Improve axes indicator

silx/gui/plot3d/SFViewParamTree.py, silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/scene/function.py
This PR adds an option to the `ScalarFieldView` API and a checkbox to the associated parameter tree to toggle the rendering of values <= colormap min on the cutting plane.
Closes #1169
=> [plot3d] Plot3d plane transparency

silx/gui/plot/PlotTools.py
Previous refactoring broke the "mouseMoved" callback.
This commit should be included if v0.6.1 is released.
=> Fix bug with crosshair cursor

silx/gui/plot/LegendSelector.py
If a curve is active, make sure it is still active after renaming it in the legend selector.
=> [LegendSelector] keep a curve active after renaming it

silx/io/commonh5.py, silx/io/test/test_specfile.py, silx/io/test/test_specfilewrapper.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py
This PR closes files properly in tests, so that we don't need to call `gc.collect()` before deleting the test files.
There is still a problem with `test_spectoh5`, caused by `convert(self.spec_fname, self.h5_fname)`. This line still requires a `gc.collect` for a reason unknown.
=> [specfile tests] Close specfile objects

silx/gui/plot/PlotWidget.py
This PR ensures that calling `addCurve(replace=True)` has the same effect as `clear() + addCurve(replace=False)` on the next curves' color and style.
=> [plotWidget] reset color and style cycling

silx/gui/plot/items/image.py
The typo maybe causes an extra copy when data is already in uint8, but it still does the job.
=> [image] typo "uin8" -> "uint8" in _convertImageToRgba32

silx/gui/data/NXdataWidgets.py
Even if x values are not monotonic, it can still be a curve (mesh scan, parametric data...)
It makes more sense to add 1D data always as curves, and add a scatter only in the case of 2 axes and one signal dataset (x, y, values). Users can toggle the curve style to display points, if they want.
=> [NXdataView] Add 1D data as curve, not scatter

package/debian8/rules, package/debian9/rules
Define SPECFILE_USE_GNU_SOURCE to enable specfile locale fix.
=>  specfile locale fix in our debian packages

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendMatplotlib.py
Change the way to fix #1081 because `cla()` caused lots of side effects.
I kept `>= "2.0.0"` as a condition because of #1136. We need to test if this issue is still solved.
=> Matplotlib 2.1.0 bug with log scale

ci/appveyor.yml
So we only test latest python3 version and win 25% of Windows CI time.
=> Remove Python3.5 from Appveyor tests

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/items/axis.py, silx/gui/plot/items/curve.py
This PR complements PR  #1307 with an extra `PlotWidget._forceResetZoom` method and a workaround for matplotlib 2.1.0 when both axis limits are <=0 when setting log scale.
=> Additional workaround for matplotlib 2.1.0

README.rst, doc/source/index.rst, setup.py
This PR point project URL to www.silx.org and update zenodo URL to point to silx umbrella DOI (so it will always point to the latest release).
Related to #1292
=> Update project homepage and zenodo URL

silx/gui/plot/ColorBar.py, silx/gui/plot/Colormap.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/test/testColormap.py, silx/gui/plot3d/ScalarFieldView.py
This PR adds a `Colormap.getNColors` method that returns an array of color sampled linearly from the colormap LUT (not taking into account normalization and range).
This allows to share code between `ColoBar`, plot OpenGL backend and plot3d.
Closes  #1132
There is an issue while getting the color LUT this way, see #1317
=> [plot] Add a method to sample a Colormap into a color array

silx/gui/plot/_utils/test/test_ticklayout.py, silx/gui/plot/_utils/ticklayout.py
This PR makes the axis ticks layout function `ticks` works with empty range (when min==max).
This case can happen in plot3d (e.g. when displaying a single image, the axis orthogonal to the image has an empty range).
=> [plot] Fix ticks layout when range is empty

silx/gui/plot/backends/BackendMatplotlib.py
This issue occurs with matplotlib 1.5.x and 2.0.x but not with 1.4.2 and 2.1.0.
The moment at which matplotlib is changing the limits in the case of a resize of the widget when keeping aspect ratio of the plot is different from one version of matplotlib to another.
This patch fixes this issue by storing the limits during `resizeEvent` and checking it after redraw.
I tested it on Debian 8 with matplotlib: 1.4.2 (py2), 1.5.3 (py3), 2.0.0 (py3), 2.0.2 (py3), 2.1.0 (py3).
Closes #1330
=> [plot] Fix resize with keep aspect ratio not sending limits changed signal

silx/gui/plot/items/core.py
This PR adds a `getSupportedSymbols` class method to plot items with symbols.
The supported symbols can be modified by subclasses (useful for reuse of item mixin class in plot3d).
=> [plot] Add getSupportedSymbols method to items with symbols.

bootstrap.py, run_tests.py
Use a "-pydebug" suffix in case of Python debug interpreter, else the synchronization is not done at the right place
=> Fix PATH when using a python in debug mode

README.rst, doc/source/install.rst
These are typos fixed whilereleasing 0.6.1, to be merged into the master.
=> 0.6.1 cherry picks to master

silx/gui/plot3d/scene/cutplane.py
This PR fixes a bug with scalar field view cut plane with nearest interpolation.
The offset to avoid texture glitches is now applied in the vertex shader rather than on the vertices.
It does not accumulate anymore.
Closes #1340
=> [plot3d] Fix bug when cut plane is on array edges by adding offset in shader

ci/appveyor.yml, silx/gui/hdf5/Hdf5TreeModel.py, silx/gui/hdf5/test/test_hdf5.py, silx/gui/icons.py, silx/gui/qt/_utils.py, silx/gui/widgets/ThreadPoolPushButton.py, silx/gui/widgets/test/test_threadpoolpushbutton.py
Last Qt 5.9.[1-2] segfault in some cases in Windows
- If you reuse more than one time index generated by `createIndex`
- If you use the global thread pool provided by Qt
- You have to explicitly set the max thread of the thread pool
- You must not use `Qt.QIcon(filename=)` (you have to use an intermediate pixmap)
This PR:
- creates a `qt.silxGlobalThreadPool` to avoid to use the one from Qt
- Clean up the Hdf5Model and tests to avoid to reuse indexes on a sequence of methods
Both problem looks anyway to be an issue relative to PyQt5. And it should be fixed there. I stiil have to send a feed back to the PyQt mailing list.
Close #936
=> Fix qt5 tests

silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/marker.py
This PR improves matplotlib plot backend marker text support:
- Closes #1348: Marker text does not move with marker 
- Hides marker text when marker is not visible in the plot area
- Update line marker text position when plot limits change
- Refactor marker in the backend
- Remove unused overlay argument in backend addMarker
=> [plot] Improve marker implementation in matplotlib backend

doc/source/modules/gui/gallery.rst, doc/source/modules/gui/plot3d/index.rst, doc/source/modules/gui/plot3d/scalarfieldview.rst, doc/source/modules/gui/plot3d/viewer3dvolume_example.rst, doc/source/sample_code/index.rst
This PR removes the sample code available from silx.gui.plot3d module documentation page.
It was duplicating the sample code gallery.
=> [plot3d] Update plot3d sample code documentation

silx/gui/plot3d/SFViewParamTree.py
This PR allows to set any value for isosurface level from the parameter tree widget rather than limiting resolution to 10e-2.
closes #1280
=> [plot3d] Fix isosurface level editor in parameter tree widget

silx/io/specfile/src/locale_management.c
xlocale.h is removed in GLIBC 2.26 but strtod_l has been moved inside stdlib.h
closes #1357
=> [IO] Take strtod_l from stdlib.h if GLIBC >= 2.26

examples/fftPlotAction.py
This PR fixes an issue with python3 and numpy not taking float as indices.
=> Fix fftPlotAction example with python3 and latest numpy

silx/gui/plot/actions/io.py, silx/gui/plot/test/__init__.py, silx/gui/plot/test/testSaveAction.py
When a curve does not define a specific label for an axis, use the graph label instead of None.
This was already done for saving single curves as SPEC.
=> [SaveAction] Axis labels when saving multiple curves as SPEC.

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/data/NumpyAxesSelector.py, silx/io/nxdata.py
When two axes use the same @long_name attribute, we got  an error because we relied on these names to be unique.
This PR fixes this bug and adds an assertion in `NumpyAxesSelector.setAxisNames` to enforce unicity of names.
It also fixes the bug of the signal name being used by mistake as ylabel instead of the Y axis name , and adds support of a `@long_name` attribute on the signal dataset.
=> [NXdataView] Fix issues with non unique axis labels

silx/io/fabioh5.py, silx/io/test/test_fabioh5.py
Support file series from FabIO.
About the implementation:
- It only support 1 frame per images (else an assertion will be raised). We can change that but it have a pre-computation cost.
- It was not done to be efficient (but to be implemented fast), files are read 3 times. We can improve that, but let see what's happen on real examples.
I would like to re-implement file_series in fabio as a container of frames. It can create something much more convenient to use. In the mid time i hope the current implementation is enough.
=> Support fabio file series on FabioH5

silx/app/test/test_convert.py, silx/test/utils.py
This test was never executed, except in a virtual environment without h5py. 
This PR adds a context manager for testing missing optional dependencies, even if they are actually installed.
=> [test] Fix a poor test and provide a new context manager

doc/source/modules/index.rst, doc/source/modules/io/index.rst, doc/source/modules/io/url.rst, silx/gui/dialog/ImageFileDialog.py, silx/gui/dialog/test/test_imagefiledialog.py, silx/io/__init__.py, silx/io/test/__init__.py, silx/io/test/test_url.py, silx/io/test/test_utils.py, silx/io/url.py, silx/io/utils.py
Here is an implementation of a `DataUrl`.
Closes #1389
Closes #1390 
- It was designed to reach data from `fabio` or `silx.io.open` with support of slicing.
- It can parse regular files
- It supports absolute (`silx:///data.h5`) and relative (`silx:data.h5`) file path
- It supports Windows drives
Here is few examples, but you better to check the tests:
```
DataUrl("fabio:///data/image.edf::[2]")
DataUrl("fabio:///C:/data/image.edf::[2]")
DataUrl("silx:///data/image.h5::/data/dataset[1,5]")
DataUrl("silx:///data/image.edf::/scan_0/detector/data")
DataUrl("silx:///C:/data/image.edf::/scan_0/detector/data")
DataUrl("silx:./image.h5")
DataUrl("fabio:./image.edf")
DataUrl("silx:image.h5")
DataUrl("fabio:image.edf")
DataUrl("./foo/bar/image.edf")
DataUrl("C:/data/")
```
It is a redesign of the …
=> Rework ImageFileDialog URLs

silx/gui/plot/Colormap.py, silx/gui/plot/ColormapDialog.py, silx/gui/plot/test/testColormap.py
This PR adds a common place where to store a list of preferred colormaps to propose to the user.
It also update the `ColormapDialog` to use it. @payno let me know if you prefer that I remove this commit from the PR.
Close #1411
=> Add function preferredColormaps to Colormap module

silx/gui/plot/items/core.py, silx/gui/plot/test/testItem.py
This PR adds an API to get some long names for symbols of plot items.
The `setSymbol` method also take those names as input.
This simplifies setting markers with a ComboBox while not changing the previous behavior.
=> [plot] Add human-readable names for plot symbol

silx/gui/plot/Colormap.py, silx/gui/plot/ColormapDialog.py, silx/gui/plot/actions/control.py, silx/gui/plot/test/testColormapDialog.py
=> [gui]Colormap dialog modal

silx/io/nxdata.py, silx/io/test/test_nxdata.py
Closes #1407 
This PR adds support for legacy NXdata specifications, if there is no `group@signal` attribute and/or no `group@axes` attribute.
=> [nxdata] Support older NXdata specification

ci/amd_sdk.sh
Workaround issue:
```
ERROR: cannot verify developer.amd.com's certificate, issued by ‘/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3’:
Issued certificate has expired.
```
=> [CI] Fix Travis-Linux build

silx/gui/plot/matplotlib/Colormap.py
This PR uses `Colormap.getColormapRange` method to initialize matplotlib colormap used in the backend.
This avoids copies of code doing the same stuff, and the code preparing matplolib colormap was doing it poorly regarding autoscale of only one boundary (which is now available from the colormap dialog).
=> [plot] Colormap

silx/gui/plot/actions/control.py
add the plot as the colormap dialog parent. This way when the plot is deleted will delete the colormap dialog to.
=> [colormap action] fix #1423

silx/gui/plot/actions/control.py
In the colormap action, set the colormap only if it is not the one already set.
Allow to reset the colormap from the first set from the colormap dialog
=> [colormap action] fix #1427

silx/gui/plot/ColormapDialog.py
When a boundary (min, max) is edited if the associated boundary is None let the user edit it freely.
Previously if one boundary was none, forced the user to be booth None.
=> [colormap dialog] fix #1435

silx/gui/plot/PlotWindow.py
This PR fix an issue of `PlotWindow` which was not always shown when activated from the Option menu
Closes #1459
=> [plot] Fix console dock widget not showing

doc/source/modules/index.rst, doc/source/modules/opencl/fbp.rst, doc/source/modules/opencl/index.rst, doc/source/modules/opencl/medfilt.rst, doc/source/modules/opencl/sift/align.rst, doc/source/modules/opencl/sift/index.rst, doc/source/modules/opencl/sift/match.rst, doc/source/modules/opencl/sift/plan.rst
This PR adds a minimalistic silx.opencl doc.
It is not complete, but provides a placeholder.
It builds over PR #940
=> [doc] Minimal bootstrap of silx.opencl doc

silx/app/convert.py
Make sure all input files are readable before opening output file, to avoid creating a dummy file.
Add a helpful message suggesting to install fabio
close #1456 and close #1457
=> [convert] improvements

run_tests.py
The use of `__import__` was not working cause the behaviour between `importlib` and `__import__` is not the same.
It fix run_tests when using a very old Python (before 2.7)
=> Better support for Python without importlib

silx/app/convert.py, silx/app/test/test_convert.py, silx/io/spech5.py
Appending the complete command to the @creator attr can cause important file leaks when the output file is used to incrementally save a long series of scans.
This PR simplifies the creator to *"silx convert (v0.7.0-dev0)"*. In case multiple versions of silx are used to append to the same file (probably not a good idea), the creator can still be modified, but this will not happen often :  *"silx convert (v0.7.0-dev0); silx convert (v0.7.0)"*
=> make a simpler @creator, to avoid file leaks

examples/colormapDialog.py, silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/data/test/test_dataviewer.py, silx/gui/plot/Colormap.py, silx/gui/plot/ColormapDialog.py, silx/gui/plot/actions/PlotAction.py, silx/gui/plot/actions/control.py, silx/gui/plot/actions/fit.py, silx/gui/plot/actions/medfilt.py, silx/gui/plot/test/testColormapDialog.py
Using the fact colormap object is now interactive (get/set/events) we can provide a convenient unique colormap for all the views. It avoid the user to custom everytime the same thing, with many popups.
This PR
- provides a unique default color maps from the `DefaultView` class
- Any view can use it
- Most of the views have been patched to use it (2d, stack, NX, complex)
- Colormap dialog supports no colormap
Close #1425
Close #1424
=> [silx view] Use a common colormap for all the views

silx/gui/data/DataViews.py, silx/io/nxdata.py
Closes #1471.
If a NXentry provides a @default pointing to a valid NXdata group, we can open it with an appropriate NXdata viewer.
=> [DataViewer] view NXentry like a NXdata

silx/gui/plot3d/ParamTreeView.py, silx/gui/plot3d/_model/core.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/core.py, silx/gui/plot3d/scene/cutplane.py
This PR adds a few features and a fix to plot3d parameter tree:
- Enable/disable scatter2D symbol and line properties depending on visualization mode
- Add display/edit of 3x3 matrix transform of nodes
- Separate autoscale for colormap min and max in the model (and the tree view)
- Add cutplane clip values below min parameter
- Fix cut plane interpolation parameter that was not properly synchronized.
=> [plot3d] Update scene parameter tree

silx/gui/plot/ColormapDialog.py, silx/gui/plot/items/core.py, silx/gui/plot3d/SceneWindow.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/core.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/tools/GroupPropertiesWidget.py
#1463 should be merged first
This PR adds a widget to set the colormap, marker and line width for all items of a SceneWidget.
It is available in SceneWindow as a tabbed dock widget.
=> [plot3d] Add a widget to set properties globally in a SceneWidget

silx/app/test/test_convert.py, silx/gui/plot/_utils/test/test_ticklayout.py, silx/gui/plot/test/testColormap.py, silx/gui/plot/test/testColormapDialog.py, silx/gui/plot/test/testColors.py, silx/gui/plot/test/testComplexImageView.py, silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/plot/test/testPlotTools.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/testPlotWidgetNoBackend.py, silx/gui/plot/test/testProfile.py, silx/gui/plot/test/testScatterMaskToolsWidget.py, silx/gui/plot3d/scene/test/test_utils.py, silx/gui/plot3d/test/testScalarFieldView.py, silx/gui/widgets/test/test_threadpoolpushbutton.py, silx/image/test/test_shapes.py, silx/io/test/test_dictdump.py, silx/io/test/test_specfile.py, silx/io/test/test_spech5.py, silx/math/fit/test/test_fit.py, silx/math/medianfilter/test/test_medianfilter.py, silx/math/test/benchmark_combo.py, silx/math/test/test_combo.py, silx/math/test/test_marchingcubes.py, silx/test/utils.py, silx/utils/test/test_deprecation.py, silx/utils/test/test_launcher.py, silx/utils/testutils.py
This function are generic and can be reused by other projects. Moving it to `silx.utils` freeze the API.
Close #1469
=> Move useful test functions into silx.utils.testutils

silx/resources/__init__.py, silx/test/test_resources.py
Remove tempdir concept from the `ExternalResource`. This kind of concept is not supposed to have relation with external resources, then it is not convenient to found it here. Plus it is not yet used.
=> Clean up tempdir from ExternalResource

doc/source/modules/opencl/codec_cbf.rst, doc/source/modules/opencl/index.rst, silx/opencl/codec/byte_offset.py, silx/opencl/codec/test/test_byte_offset.py
This PR adds OpenCL compression to the `ByteOffset` class through an `encode` method with some tests.
There is still some TODOs (see in source file) for the API, reusing buffers, etc.. and a sample code.
Code in the test class can be reused across different tests.
=> [opencl] CBF compression

silx/io/nxdata.py
String comparison was failing when h5py returned an attribute as bytes in python 3.
=> [nxdata] Fix PY3 bug when reading attr

silx/gui/plot/actions/control.py, silx/gui/plot/items/complex.py
Merge #1496 first.
This PR adds a specific case to the plot ColormapAction for complex images: If the image is in a mode combining a colormap for the phase and transparency for the amplitude, the histogram is set from the phase in the ColormapDialog.
closes #1493
=> [plot] Fix ColormapDialog for complex images

doc/source/applications/convert.rst, silx/app/convert.py, silx/app/test/test_convert.py, silx/io/convert.py
Closes #1498.
Change default behavior : don't add an extra group at the root, unless explicitly requested. 
Remove `--no-root-group` option, add `--add-root-group` option.
After this PR, users should ensure that they are not merging scans with the same scan number.
At the moment the only proper way to merge EDF files is for file series, with the `--file-pattern` option. `silx convert *edf` should only be used with option `--add-root-group`. The same goes for appending EDF files to an existing file. This is because `fabioh5` currently assigns the name `scan_0` to all entries.
=> [convert] no extra root level

.travis.yml, ci/appveyor.yml
The script looks to segfault (an update of Qt5 ?) on some env, and is fortunatly not needed now. This PR remove it everywhere but on Mac OS X.
=> Remove ci_popups when it is not needed

.travis.yml, ci/before_install-osx.sh
This PR proposes to remove Travis macos python2/pyqt4 test environment.
macos is still tested with python3/pyqt5.
macos CI tests are quite delayed on Travis and as time pass, python2/pyqt4 is becoming less and less the main target...
Unless someone has an opinion against that, I propose to merge that
closes #1480
=> [CI] Remove travis macos python2 test environment

silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/utils.py
This can help us to debug CI environment, which is usually a very boring thing.
```
testFoo (silx.gui.plot.test.testPlotWidget.TestPlotWidget) ... FAIL
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testPlotWidget.TestPlotWidget.testFoo.png
ERROR:silx.gui.plot.test.utils:Plot is still alive
```
=> Take screenshot on MPL fail

silx/gui/data/NumpyAxesSelector.py, silx/gui/data/test/test_numpyaxesselector.py
This occur when are more requested axes  than the available axes.
This PR detect the inconsistency and cancel the selection.
=>  Fix transitional inconsistency on NumpyAxesSelectior

silx/gui/data/DataViews.py
My last PR (#1516)  broke PyMca because a widget was reimplemented completely in PyMca, in order to add features to the viewer.
It should be fixed in the next PyMca release. But silx will probably be released prior to PyMca, so this fix will be needed during at least one release cycle, to ensure a smooth transition..
=> [NXdataView] support old API for setting a curve

run_tests.py
Here is the result of a `./run_tests.py --no-opencl --no-gui`
```
ss...............................................................................................................................................................................................s..................................................................................................................s......................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```
=> Group skipped tests by reasons in test results

silx/gui/plot3d/SFViewParamTree.py, silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/scene/transform.py, silx/gui/plot3d/scene/utils.py
This PR adds support of a 3x3 matrix in the data transformation (`get|setTransformMatrix`).
This is meant to display a dataset defined in a non-orthogonal coordinate system.
The displayed axes with ticks are the orthogonal axes and by default the cutting plane can be set to the direction of the 3 orthogonal axes (you can define other cut plane orientation from the API).
This PR breaks the API because the cutting plane was previously defined in the "array" coordinates and it is now defined in "data" coordinates with transformations applied.
This PR updates the `CutPlane` class API.
closes #951
=> [plot3d] ScalarFieldView support transforming data with a 3x3 matrix (for non orthogonal support)

silx/app/convert.py, silx/app/test/test_convert.py, silx/io/convert.py, silx/io/spech5.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py
This PR introduces a change in the way `spech5` exposes strings (bytes -> unicode) and in the way `convert` writes them to HDF5 (ASCII -> utf-8).
=> [convert & spech5] Use utf-8 text

silx/io/test/test_url.py, silx/io/test/test_utils.py, silx/io/url.py, silx/io/utils.py
- Use `?` or `::` as separator
- Use `path=` and `slice=` for data selection
- Implement `__str__, __repr__, __eq__, __ne__` for convenience
- Support `silx:` from `silx.io.open`
- Remove the old `silx.io.load` (which was an alias to `silx.io.open`)
Closes #1392
=> Update DataUrl to support our specification

silx/app/test/test_convert.py, silx/io/convert.py, silx/io/fabioh5.py, silx/io/spech5.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py
Closes #1537 
In a file series, don't fill the file_name attribute.
Also, add another layer of checking attribute types in `silx.io.convert`, to ensure they are encoded as utf-8 in the HDF5 output, so we can always read them back as unicode. This was not necessarily the case with `fabioh5` objects converted with python2.
=> [convert] fix bug with None @file_name

silx/app/test/test_convert.py, silx/gui/plot/backends/glutils/PlotImageFile.py, silx/gui/qt/_qt.py, silx/io/configdict.py, silx/io/specfile.pyx, silx/io/test/test_specfile.py, silx/io/test/test_specfilewrapper.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py
I coded a lot of `sys.version < "3.0"`, so I fixed all of them in silx. 
I did not touch the *third_party* subpackage.
=> Forward compatibility with Python 10.0

.travis.yml, ci/travis-xorg.conf
This workaround a seg fault in Qt most probably due to a bug in Qt 5.10.0 when RANDR extension is missing.
Closes #1521
=> [CI] Xorg rather than Xvfb on travis linux

.travis.yml
I made the wheel for pyopencl 2018.1 for python3.6, let's try to use it....
=> [CI] Use a different version of pyopencl depending on wheel availability

silx/gui/console.py
Before this commit, I got the warning displayed below when importing from `silx`.
```
/usr/lib/python3/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
"You should import from qtconsole instead.", ShimWarning)
```
Stack trace of import resulting in the warning below:
```
from silx.gui.plot.PlotWidget
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in …
```
=> Fixed deprecated import from IPython which caused a warning.

silx/gui/_glutils/OpenGLWidget.py
Fixes issue #1455.
Matplotlib backend always sends mouse move events. Opengl backend by default does not.
This fix configures Qt to send the mouse move events to the opengl backend.
=> Fixed opengl backend not receiving mouse move events, causing state lockups

doc/source/modules/gui/plot3d/items.rst, examples/plot3dSceneWindow.py, silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/__init__.py, silx/gui/plot3d/items/core.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/scene/axes.py, silx/gui/plot3d/scene/primitives.py
This PR:
- Adds a bounding box to each data item.
- Separates text color from foreground color (used for bounding boxes)
- Updates the model to add bounding box and text color control in the tree view.
- Adds a convenient `Item3D.root` method to retrieve the root of a tree of item.
=> [plot3d] Add bounding boxes to SceneWindow items

silx/sx/__init__.py, silx/sx/_plot3d.py, silx/test/test_sx.py
This PR adds 2 functions to the `sx` module wrapping `silx.gui.plot3d`:
- `contour3d` (for isosurfaces)
- `points3d` (for 2D/3D scatter plots)
The signature of those functions is a subset of mayavi.mlab functions.
This PR also provides corresponding tests
=> [plot3d] sx function for plot3d

silx/io/convert.py
Unless passing by numpy, a unicode string was generating problems to h5py.
This PR forces bytes and text types to go through the h5py conversion and not just bytes.
=> [convert] h5py could not handle the "interpretation"="image" attribute

silx/gui/plot/PlotWidget.py, silx/gui/plot3d/tools/toolbars.py
This PR renames Plot3**d**WidgetToolBar to Plot3**D**WidgetToolBar and provides a more generic way of setting the `Plot3DWidget` controlled by toolbar actions.
closes #1554
=> [plot3d] Refactor plot3d toolbar

silx/gui/plot3d/ParamTreeView.py, silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/SceneWindow.py, silx/gui/plot3d/_model/__init__.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/_model/model.py, silx/gui/plot3d/items/core.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/scene/viewport.py
Merge #1570 (cherry-picked here)
This PR adds a single item selection management to `SceneWidget` (through a `SceneSelection` object accessible with `SceneWidget.selection()`.
A corresponding selection model is available to sync the treeview selection with it.
Upon selection, Item bounding box is shown and color is changed by the selection management. I am not convinced by this mode but it is simple, so this can be disabled and the API leaves room to implement other modes of highlight.
=> [plot3d] Add selection support to SceneWidget

silx/gui/data/DataViews.py
`numpy.complex` is actually just a reference to the builtin python complex.  `numpy.complexfloat` is the correct ancestor to use when testing for complex data with `issubdtype`
=> [DataViews] fix numpy 1.14 warning

examples/fileDialog.py, silx/gui/dialog/DataFileDialog.py, silx/gui/dialog/test/test_datafiledialog.py
Allow to specify even more the objects the dialog can return.
Can be used like that
```
def customFilter(obj):
if "NX_class" in obj.attrs:
return obj.attrs["NX_class"] in [b"NXentry", u"NXentry"]
return False
dialog = DataFileDialog(self)
dialog.setFilterMode(DataFileDialog.FilterMode.ExistingGroup)
dialog.setFilterCallback(customFilter)
```
Closes #1599
=> Add pythonic callback to DataFileDialog to custom selectable data

silx/gui/data/DataViews.py
The message must be reinitialized every time a new data is provided, because the view is reused between two invalid NXdata groups that have different issues. Closes  #1594
=> [NXDataView] update troubleshooting message in InvalidNXdataView

doc/source/modules/sx.rst, silx/sx/__init__.py, silx/sx/_plot.py, silx/test/test_sx.py
This PR adds `sx.ginput` that uses a PlotWidget to get a set of points given by the user.
The function plugs an object on a PlotWidget to handle the interaction and use its status bar to provide indication to the user.
It operates by default the most recent visible plot created with either `sx.plot` or `sx.inshow`.
It blocks until one of the following occurs: the user select all the required points, the PlotWidget gets hidden or a timeout is triggered.
It returns a list of (x,y) coordinates of all the points.
Points can be undo with either Delete, backspace or Ctrl-Z.
Points can only be set while in zoom mode.
I didn't succeeded so far in writing an interactive test for it... 
Closes  #1614
=> [sx] Add ginput

silx/io/nxdata.py
Closes #1636 
Log an info, and not a warning, when old spec is met. Now, warning is only printed in cases when `is_valid_NXdata()` returns `False`, to help troubleshooting.
I also improved the warning prefix, to mention the name of the problematic group, to avoid seeing the exact same message multiple time when opening different groups.
=> [nxdata] Improve logging

package/debian8/control, package/debian9/control, silx/gui/_utils.py, silx/gui/test/test_utils.py, silx/third_party/_local/concurrent_futures/__init__.py, silx/third_party/_local/concurrent_futures/_base.py, silx/third_party/_local/concurrent_futures/process.py, silx/third_party/_local/concurrent_futures/thread.py, silx/third_party/concurrent_futures.py
This PR adds a function `silx.gui._utils.submitToQtMainThread` which allows to run a function in Qt main thread from any thread (asynchronously if it is not initiated from the main thread).
This function returns a `concurrent.futures.Future` object that allows to wait for and get the result asynchronously.
As `concurrent.futures` is only available for python>=3.2, I added its backport to `silx.third_party` (it is under the PSF license) and as a dependency for python2 Debian packages.
Are you OK with that?
=> Add a function to run a task in Qt main thread from any thread

silx/gui/hdf5/Hdf5TreeView.py, silx/gui/hdf5/test/test_hdf5.py
The used index was only valid when the view was not using proxy models.
Now we reach the index from the model connected to the view.
Closes #1634
=> Fix hdf5tree selection

silx/gui/plot/Interaction.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/actions/mode.py, silx/gui/plot3d/scene/interaction.py
This PR adds support of a second interaction when Ctrl  (command on macOS) is pressed:
- For scene rotation, Ctrl switches to scene panning
- For scene panning, Ctrl switches to scene rotation
- For plane panning (so far only available in ScalarFieldView), Ctrl switches to scene rotation.
closes #1131
=> [plot3d] Add alternative interaction when ctrl is pressed

silx/sx/__init__.py
This PR is related to #1633, but instead of removing pylab, it enables it but disable `from numpy|matplotlib import *` which avoids confusion between namespaces...
closes #1633
=> [sx] Do not populate the global namespace with pylab

silx/io/nxdata.py
Found a bug when trying to run `examples/hdf5Widget.py`, `NXdata/1D_spectrum`. Single unicode string attr was not cast as list because I'm testing for type `str`.
=> [nxdata] bug when reading back unicode and testing for str type (PY2)

silx/gui/plot3d/ScalarFieldView.py, silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/SceneWindow.py, silx/gui/plot3d/_model/core.py
This PR adds support for pan interaction of the selected plane (clip plane or cut plane) in `SceneWidget`.
It adds a QAction in `SceneWindow` to toggle this interaction mode.
This QAction is not in the public API yet as I am not very happy with the way it is done, but the functionality is available:
The user can pan the selected plane in the parameter tree with the mouse.
For now, if the user press Ctrl and drag the mouse, it rotates the scene... In the future I might use Ctrl to interactively rotate the plane...
I also optimized the model structure as during plane interaction most of the time was spent in `QObject.parent()` up to the point that interaction was not smooth!
=> [plot3d] Add pan selected plane interaction to SceneWindow

silx/app/test/test_view.py, silx/app/view.py, silx/gui/dialog/AbstractDataFileDialog.py, silx/gui/dialog/test/test_datafiledialog.py, silx/gui/dialog/test/test_imagefiledialog.py, silx/gui/hdf5/Hdf5TreeModel.py, silx/gui/hdf5/test/test_hdf5.py, silx/gui/plot/test/testUtilsAxis.py, silx/gui/plot/utils/axis.py, silx/gui/test/utils.py
It definitly looks very dangerous to use `__del__` on QWidget, while it is very dependent to the MV/OS... This PR.
- Try to use `destroyed` signal on `Hdf5TreeModel` and `AbstractFileDialog`. That's not so easy, but it looks to work ()
- `TestCaseQt` was patched to be able to use `qWait` and a new `qWaitForDestroy` as class method (usable in the `tearDownClass`).
- Rework `SyncAxes` which was segfaulting on PyQt5 (due to an update of qWaitForDestroy)
- Rework `qWaitForDestroy` which was segfaulting on Windows PySide
- Fix `Hdf5TreeModel` to take care of onwed openned files (it was not fully implemented for item synchronization and item remove)
Closes #1638
=> Use destroyed signal instead of __del__ for QWidget

silx/app/view.py
=> [0.7] PyQt5 is now the default binding used by silx view

silx/io/nxdata.py
I did not access scalar ndarrays properly, causing an IndexError when reading any object with attributes in PY3 with silx view.
This bug was introduced after last release, when we changed the encoding of all strings to utf-8 rather than ASCII.
Closes #1693
=> [0.7][nxdata] fix PY3 bug when parsing scalar ndarray  attribute

doc/source/modules/gui/plot/getting_started.rst, silx/gui/qt/__init__.py, silx/gui/qt/_qt.py, silx/sx/__init__.py
This PR tries to load PyQt5 first, then PyQt4, PySide and PySide2.
Doc is updated accordingly to acknowledge pitfalls with IPython.
sx module is also updated to perform imports as %pylab but to avoid the initialization of Qt by IPython.
=> [gui] Change PyQt preference order

silx/utils/debug.py, silx/utils/test/__init__.py, silx/utils/test/test_debug.py
It was very useful to debug segfaulting and deadlocking Qt class, then i think it can be helpful for everybody.
It can be used like that:
```
@log_all_methods
class Foobar(object):
def a(self):
return None
def b(self):
return self.a()
```
A simple example
```
f = Foobar()
f.b()
```
Here is the output when calling the `b` method.
```
WARNING:silx.DEBUG:Foobar.b
WARNING:silx.DEBUG:  Foobar.a
WARNING:silx.DEBUG:  return  (Foobar.a)
WARNING:silx.DEBUG:return  (Foobar.b)
```
Closes #1673
=> Proposal for a silx.utils.debug module

setup.py
This PR changes build option on unix to avoid possible symbol collision with manylinux build.
It is a copy-paste from pyFAI setup.py
closes #1070
=> [build] Avoid symbol collision with manylinux1

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/test/testCurvesROIWidget.py
Do not ask for a new ROI when doing the deferred initialization (only if no ROI are existing yet)
Add unit test for @alemirone issue. /closes #1710
=> [CurvesROIWidget] fix #1710

silx/gui/plot/actions/io.py, silx/gui/plot3d/actions/io.py, silx/gui/printer.py, silx/gui/widgets/PrintPreview.py
This PR adds a `silx.gui.printer` module with functions to access a shared `QPrinter` instance.
It is used in `PrintAction` in `plot` and `plot3d` and in `PrintPreview`.
It also switch from `printer` property to `getPrinter` method in plot PrintAction.
To make `PrintAction` more generic, it is possible to add a `setPrinter` in order to allow using a different printer from the default one of silx. If desired, let me know.
=> [gui] Add a shared QPrinter instance in silx.gui

.travis.yml, ci/appveyor.yml, ci/requirements-pinned.txt
This PR proposes to add a file `ci/requirements-pinned.txt` for temporary version pinning or additional dependencies.
As we test with pre-released version of our dependencies, we regularly fall into issues with such versions.
While this is the purpose of testing, the idea here is to **temporarily** pin a version/add a dependency in a single file until the issue is fixed upstream.
=> [CI] Add pinned requirements file

silx/gui/plot/actions/io.py
This PR removes the option to save a data image as a RGB TIFF from the plot SaveAction.
There is still an option to save the image data as TIFF, this PR only removes the option to save an image with colormap applied as TIFF.
It was using Qt to save such image and TIFF support is optional... so it might not be there
As there is still an option to save an image with colormap applied as RGB PNG (always available in Qt), I don't see it as a big loss of functionality...
Is it OK to drop it?
=> [plot] Remove save RGB image as TIFF from SaveAction

silx/gui/plot/PlotWidget.py
This PR allows to unselect active curve with a left click in empty area of the plot.
It does not interfere with drag operation
closes #1612
=> [plot] Unselect active curve when clicking on empty space

bootstrap.py, run_tests.py
In Python3, packages without binary extension land in "build/lib" and
not in "build/lib.linux-x86_64-3.5"
=> Allows Compatibility with "simple" projects (like Dahu)

silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py, silx/gui/widgets/FrameBrowser.py, silx/gui/widgets/test/test_framebrowser.py
This PR extends `StackView` API:
- `getFrameNumber` to get current frame
- `sigFrameChanged` emitted when frame changes
It also updates `FrameBrowser`:
- Clip value provided by `setValue` to the range
- deprecate duplicated/inconsistent API: `setLimits`, `getCurrentIndex`
- adds `getRange`, `getValue`
=> [plot] StackView/FrameBrowser API update + fix

silx/gui/plot3d/scene/primitives.py
This PR does not render points that have a fully transparent color.
It is the case for a mask on a scatter plot.
=> [plot3d] Improve rendering fully transparent points

setup.py
This PR adds the version of numpy the setup.py is run with as the minimal required version.
Thus, when generating wheels, the wheel will advertise the version of numpy used when running `python setup.py bdist_wheel`.
related to #1740
=> [build] Define requested minimal version during wheel build

setup.py, silx/image/marchingsquares/_mergeimpl.pyx, silx/image/marchingsquares/setup.py, silx/third_party/setup.py, silx/utils/_have_openmp.pxi, silx/utils/include/silx_store_openmp.h
This flag the C-module binary with a variable.
```
In [1]: from silx.image.marchingsquares import _mergeimpl
In [2]: _mergeimpl._COMPILED_WITH_OPENMP
Out[2]: 1
```
It also can be used in the module to custom the process.
=> Allow to flag Cython modules if OpenMP is used at runtime

silx/io/specfile.pyx
Addresses #1759: SpecH5 sometimes raised an error when encountering an empty scan in a large specfile. 
Unfortunately, the error was intermittent. I have no idea how I could write a unittest for this issue.
Also, I still don't understand why the error was intermittent. I seems to be related to memory usage. But I never caused a segfault, and it only ever happened on empty aborted scans (AFAIK). 
The source of the intermittent error seems to be that `SfData` may return -1 without setting an error code, which seems inconsistent. https://github.com/silx-kit/silx/blob/master/silx/io/specfile/src/sfdata.c#L244.
When running a memory profiling tool on a script that used to reproduce the error, nothing unusual shows up.
```
$ python  -m memprof --plot spech5_memleak.py 
...
Nothing with more …
```
=> [specfile]improve handling of empty scans

silx/gui/data/DataViewer.py
This PR cache DataInfo in the DataViewer. As result we do not analyze many time the same dataset. Now it is only done a single time (it was done 3 times previously).
Relative to #1640 
It maybe not fully fix this issue, but improve the state.
=> Cache DataInfo in the DataViewer

silx/gui/widgets/BoxLayoutDockWidget.py, silx/gui/widgets/test/__init__.py, silx/gui/widgets/test/test_boxlayoutdockwidget.py
This PR adds a dock widget which updates the direction of the box layout of its widget.
It can be useful for e.g. the mask dock widget.
=> Add dock widget that update widget's layout direction

.travis.yml, ci/before_install-linux.sh
AMD APPSDK is again broken.
This PR
- Allow to skip the APPSDK installation if OpenCL tests are skipped
- Disable OpenCL for all the Linux platform
- Create a new target including OpenCL tests to check if APPSDK is back
=> Disable OpenCL on Travis Linux targets

silx/sx/_plot.py, silx/sx/test/test_sx.py
This PR allows to pass` origin='lower'` or `'upper'` to `sx.imshow` in order to toggle the Y axis orientation.
It DOES NOT change the default Y axis orientation (upward) in order to avoid inconsistence with all plot widgets and other plot functions in `sx`... So it remains inconsistent with matplotlib default.
I think it is how we said we wanted to address #1744
=> [plot] Allow to set origin = upper or lower in sx.imshow

silx/gui/plot/PlotWindow.py
Use a deprecation phase for `PlotWindow.panModeAction` and `PlotWindow.zoomModeAction`.
Addresses https://github.com/vasole/pymca/issues/220
The code will also be modernized on the PyMca side, but it is a good idea to maintain the previous API for a couple of releases.
=> [PlotWindow] Deprecate pan and zoom actions

silx/io/nxdata/_utils.py
same patch as #1814, but applied on the refactored code (after #1778).
=> [nxdata] always fetch a copy of attrs

silx/app/view/Viewer.py, silx/gui/hdf5/Hdf5TreeModel.py, silx/gui/hdf5/Hdf5TreeView.py, silx/gui/hdf5/test/test_hdf5.py
Add signals to `Hdf5Model` to be able to manage the life-cycle of the files. Then use it to improve `silx view` (consistency between the data viewer and the tree ).
The PR #1800 have to be merged first.
Closes #268
Closes #1794 
Closes #1803
=> Hdf5tree file event

silx/gui/plot/backends/glutils/GLPlotCurve.py
This PR fixes a bug with OpenGL backend not showing last point of scatter
closes #1831
=> [plot gl] Fix missing last point of scatter with OpenGL backend

silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/items/axis.py
This PR fixes an issue with matplotlib >= 2.0 when in log scale, there is errors with picking during mouse move.
This was due to right axis (even if not shown) to have a negative bound.
This PR makes sure both Y axes have strictly positive bounds before switching to log scale (at the expense of a flicker redraw)
closes  #1708
=> [plot] Fix picking issue by making sure Y axes are positive when log scale

silx/io/nxdata/parse.py
Fixes a crash when attempting to validate the number of axes when no signal is defined.
Consider n-D (n >1) axes invalid.
=> [NXdata] improve validation

silx/gui/plot3d/SceneWindow.py
This PR adds a method that was missing to access a widget of the `SceneWindow` main window.
=> [plot3d] Add missing method to access Global scene parameters widget

silx/gui/plot/ColorBar.py, silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/_BaseMaskToolsWidget.py, silx/gui/plot/items/axis.py, silx/gui/plot/utils/axis.py
This PR fixes circular reference at Python level in `PlotWidget`, `PlotWindow`, `Plot1D` and `Plot2D` by using `weakref`.
Related to #1872
=> [plot] Fix circular reference in plot widgets

silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py
This PR adds a `select-draw` interactive mode which provides items (e.g., markers) selection and dragging and shape drawing interaction at the same time.
This would be useful for PR #1758.
=> [plot] Add select-draw interaction mode to PlotWidget

silx/io/fabioh5.py, silx/io/test/test_fabioh5.py, silx/utils/number.py, silx/utils/test/__init__.py, silx/utils/test/test_number.py
- Take care of exponent to choose floating-point size
- Use `numpy.longdouble` if available (instead of `float128`/`float96`)
- Fallback using `float64`
- Create a dedicated module `silx.utils.number`
Relative to #1829
Closes #1830
=> Fix fabioh5 float conversion

silx/gui/plot3d/scene/utils.py
This PR remove a fallback for debian 7 and the associated version check which was erroneous.
This drops the support of the numpy version of debian 7.
=> [plot3d] Fix numpy version checking by removing it: Drop support of debian 7

silx/gui/hdf5/Hdf5Formatter.py
It is still not accurate (we do not display the type stored by HDF5) but it is less wrong.
Closes #1861
=> Display float80 in the GUI instead of float128

silx/gui/plot/test/testStats.py
The code was segfaulting on a `gc.collect` of the `TestCaseQt.tearDown`. Maybe cause a Python widget object was still there while the Qt object was already released.
- Add a processEvents to flush something... no idea
- Add few `DeleteOnClose` for consistency (but not relative to the segfault)
As result, no more segfault.
=> Fix segfault on PySide + matplotlib 2.2.2

silx/app/view/Viewer.py, silx/gui/hdf5/Hdf5TreeModel.py
The PR clear the models when closing silx view.
This avoid to trust Python for releasing objects, which can introduce unpredictable behaviors.
Relative to https://github.com/silx-kit/fabio/issues/220
=> Clear silx view

silx/gui/plot/PlotWindow.py, silx/gui/plot/tools/PositionInfo.py, silx/gui/plot/tools/test/testTools.py
Merge #1902 first.
This PR adds an `updateInfo` method to `PositionInfo` widget and makes use of it in `Plot2D` to update the displayed info when the active image changes.
closes #1682
While it would be worth to refactor/improve the `PositionInfo` widget, this PR only fixes the active image update issue.
=> [plot] Fix position info update when active image changes

examples/findContours.py, examples/scatterMask.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/ScatterMaskToolsWidget.py, silx/gui/plot/_BaseMaskToolsWidget.py
This PR changes the returned value of `getSelectionMask` to None when there is no mask and makes `setSelectionMask` accept None as input to reset the mask.
closes #1765
closes #834
Please check if it breaks anything in applications before merging.
Maybe not merge for v0.8?
=> [plot] Make set|getSelectionMask support/return None

silx/gui/plot/tools/profile/ScatterProfileToolBar.py, silx/gui/plot/tools/test/testScatterProfileToolBar.py
This PR:
- Extend the time to wait for asynchronous profile interpolator init
- Split scatter plot tests into different functions
=> Improve scatter profile test and scatter profile thread life-cycle

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotFrame.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLSupport.py, silx/gui/plot/backends/glutils/GLText.py, silx/gui/plot/items/core.py
This PR overcomes the float32 precision issue occurring for data with difference only visible with double precision. This is due to sending float32 to OpenGL and using data coordinates as coordinates for the display.
It is not complete and not tested (TODOs: error bars, images, shapes, log scale,...) but it works for the case of #1772.
closes #1772
=> [plot gl] Overcome float32 precision 

silx/gui/plot/PlotWindow.py, silx/gui/plot/ScatterView.py, silx/gui/plot/tools/PositionInfo.py
This PR allows a better control of the snapping of the position used by the `PositionInfo` widget through a `setSnappingMode` method.
It also adds support of snapping on scatter plots.
When used inside `PlotWindow`, it remains consistent with the previous automated snapping mode.
closes #1611
=> [plot] Refactor PositionInfo widget snapping mode

silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/ScatterMaskToolsWidget.py, silx/gui/plot/_BaseMaskToolsWidget.py
This PR makes the scatter mask tool pencil size relative to the extent of the scatter data.
This makes this tool more usable with scatter plots of different data range
related to #1796
To me, this is a temporary solution for the 0.8 release. The ideal solution is that the pencil shape is defined in screen coordinates rather than in data coordinates.
=> [plot] Scatter mask pencil

silx/io/convert.py
Close #1976 
When initializing the output dataset prior to writing frames, the dtype must be specified.
=> [convert]preserve dtype for file series

run_tests.py
Just a test.
If it's fine we could merge it.
Else this command is still working:
```
python -Wd ./run_tests.py
```
=> Capture all warnings from the `warnings` module

silx/image/marchingsquares/__init__.py
As discussed with @t20100 a long time ago, our scipy implementation is here but hidden. We only have one engine, then it is maybe not really needed to provide an attribute for that.
=> Remove engine param as we only have a single engine

silx/io/commonh5.py, silx/io/fabioh5.py, silx/io/test/test_fabioh5.py
- Rework `commonh5` to use `H5Type` (expose `h5_class` properties to all common objects)
- Fix a typo on fabioh5
- Check that `FrameData` do not aggregate any numpy cube when using `dtype` or `shape`.
=> Fix FrameData cache

silx/gui/data/test/test_dataviewer.py, silx/gui/data/test/test_textformatter.py, silx/gui/dialog/test/test_datafiledialog.py, silx/gui/dialog/test/test_imagefiledialog.py, silx/gui/hdf5/test/test_hdf5.py, silx/gui/plot/test/testPlotWidget.py, silx/image/test/test_bilinear.py, silx/io/test/test_fabioh5.py, silx/io/test/test_utils.py, silx/utils/test/test_html.py, silx/utils/test/test_launcher.py, silx/utils/test/test_weakref.py
This PR replaces deprecated `TestCase.assertEqauls` by `assertEqual` throughout silx.
This avoids warnings when running the tests.
=> [test] replace deprecated assertEquals by assertEqual

silx/app/view/About.py, silx/gui/data/Hdf5TableView.py
- In the silx view About box (instead of `hdf5plugin`)
- For each compressed datasets with the list of filters
This feature is only enabled with HDF5 >= 1.10.2
Closes #1064
Closes #1315
=> Display HDF5 filter availability

silx/gui/plot/actions/io.py, silx/io/__init__.py, silx/io/utils.py
Until now, we activated "curve" filters if there was an active curve or a single curve, and we activated "curve**s**" filters when there was at least curve.
There is an issue if one wants to add a function that can save indifferently one or more curves. The only solution with silx <= 0.8 is to add the filter twice.
This PR activates "curves" filters for  plot with one or more curves. As far as I can tell, the only function currently provided for multiple curves can already handle one or more curves.
=> [SaveAction] Activate "curves" filter even for single curve

silx/math/medianfilter/include/median_filter.hpp, silx/math/medianfilter/medianfilter.pyx, silx/math/medianfilter/test/__init__.py, silx/math/medianfilter/test/test_medianfilter.py
This PR adds support of NaNs by ignoring them in cpp median filters.
In case of an even number of values on which to do the median, it gets the highest of the 2 central values.
closes #2016
=> Add support of NaN in cpp median filter

bootstrap.py
Add support of entry_point optional extra requirement declaration
See https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies
=> bootstrap.py: Support entry_point optional "extras" declaration

silx/app/convert.py, silx/io/configdict.py, silx/io/spech5.py, silx/io/test/test_utils.py, silx/math/calibration.py, silx/math/fit/fittheory.py, silx/utils/number.py
From python 3.6, using \ in a string, when it is not an escape sequence, is deprecated.
Addresses most of the warnings in #2029 , but not all.
=> Fix warnings about invalid escape sequence

silx/gui/plot3d/SFViewParamTree.py, silx/gui/plot3d/test/testScalarFieldView.py
This PR adds the option to set a normalization (linear or arcsinh) to the sliders controlling the level of isosurfaces in the ScalarFieldView parameter tree.
=> Add iso level slider normalization setting in ScalarFieldView param tree

silx/gui/plot/PlotWindow.py
Use the legacy pymca condition w > 1.25*h to initialize docks in the RightDockWidgetArea instead of the BottomDockWidgetArea.
Closes #2011.
Closes https://github.com/vasole/pymca/issues/277
=> [plot]change condition for choosing the dock widget area

LICENSE, ci/info_platform.py, doc/source/install.rst, doc/source/virtualenv.rst, run_tests.py, silx/app/test_.py, silx/gui/qt/_pyside_dynamic.py, silx/gui/qt/_qt.py, silx/gui/widgets/__init__.py
This PR marks PyQt4 as deprecated, removes it from the documentation and also replaces a few occurrence of PySide with PySide2.
closes #2015
=> Deprecate pyqt4

silx/gui/data/TextFormatter.py
Unittest was not working anymore with Python3 and numpy 1.15.0.
=> Fix void reader when using numpy 1.15.0

silx/gui/hdf5/Hdf5Item.py, silx/gui/hdf5/Hdf5Node.py, silx/gui/hdf5/NexusSortFilterProxyModel.py
When using a proxy model, `hasChildren` and `rowCount` must be reimplemented, else the default behaviour is used and children are populated.
Closes #2017
=> Improve tree sorting

silx/gui/plot/ColorBar.py
There is a small bug in the `Colorbar.getLegend`. You can reproduce it with the following example.
```
from PyQt5.QtWidgets import QApplication
from silx.gui.plot.ColorBar import ColorBarWidget
app = QApplication([])
colorbar = ColorBarWidget()
colorbar.setLegend('Hi there')
print(colorbar.getLegend())
```
This PR fixes the bug.
=> Fixes AttributeError in Colorbar.getLegend

silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py
The condition `perspective != self._perspective` was always False (attribute already updated when reaching this code).
Thus, the drop-down list was not updated properly.
=> [stackView]Fix perspective change in setData

silx/gui/plot/PlotWidget.py
If the plot is hidden, there is no need to repaint the plot. Until the next `showEvent`.
Closes #2081
=> Postpone refresh of hidden plot to the next showEvent

doc/source/modules/gui/utils.rst, silx/gui/_glutils/font.py, silx/gui/plot/actions/io.py, silx/gui/plot/test/testStats.py, silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/actions/io.py, silx/gui/utils/image.py, silx/gui/utils/test/test_image.py, silx/gui/widgets/RangeSlider.py
This PR makes QImage <-> array conversion available in the public API and add support for RGBA data/ARGB32 and RGBA8888 QImage format.
closes  #2082
=> Make QImage<->array conversion public

silx/io/specfile/src/sfinit.c
This PR proposes a patch for the C specfile library to avoid segfault when opening a spec file without scans. It also fixes a small memory leak.
As I am not familiar with specfile, I think a lot of proof-reading is needed.
closes #2110
=> Fix opening spec file without scans

doc/source/modules/gui/plot/plotwidget.rst, silx/gui/plot/PlotWidget.py, silx/gui/plot/test/testPlotWidget.py
This PR adds a `PlotWidget.getItems` method which returns all items of the plot.
In the long term, this is a replacement for `getAllCurves`, `getAllImage` and any missing `getAll*` methods.
One can then filter out what he wants from the returned tuple.
Use case: PR #2112 add some methods to marker items, but there is no way from the public API to retrieve the marker items....
=> Add PlotWidget.getItems

silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/items/core.py
This PR changes the way to handle the top-level group of the SceneWidget so that applied transforms are taken into account in the axes.
Before applying a transform at the top level had no visible effect, while now it is visible in the value of the axes.
=> [plot3d] Add a special item for the top group of the scene

silx/gui/qt/_pyside_dynamic.py, silx/gui/test/test_qt.py
This PR adds the support of the `Line` class which is produced by the Qt designer but is not supported by PySide2 (it's not a Qt widget).
With this, one can use Line in the Qt designer and use PySide2
=> Improve support of Qt designer with PySide2

silx/gui/icons.py
The idea is to release on our own Python object binding before Qt release itself C++ objects.
The  bug was occurring 1 time every 10 launchs.
This patch looks to fix the problem. No bugs through about 30 launchs.
Closes #1771
=> Clean up the icon cache

silx/gui/qt/inspect.py, silx/gui/test/test_qt.py
This PR adds a `silx.gui.qt.inspect` module which provides 3 functions to check the state of a wrapped C++ QObject: `isValid`, `createdByPython` and `ownedByPython`.
It makes API consistent across PyQt* and PySide* by taking PySide2 names.
For PySide(1), it does its best to load shiboken... but it might not be available (I could not find it on Debian8).
=> Add a silx.gui.qt.inspect module

silx/app/view/Viewer.py, silx/gui/hdf5/Hdf5TreeModel.py
- Close and reload files (hack allowing to synch file)
- As result, virtual HDF5 or displayed data are not updated but removed
- This issue needs a bigger understanding and rework to be fixed
- Returns expanded tree and selection
- Icon to sync a file (to work, the root of the tree have to be selected)
Closes #298 (not part of the treeview, but part of silx view)
Closes #2083 
Closes #2087
=> Improve file synchronization

silx/gui/plot/CompareImages.py, silx/image/medianfilter.py, silx/opencl/sift/alignment.py, silx/opencl/sift/match.py
This PR removes duplicated warnings about `pyopencl` not being available.
The only remaining warning about a missing dependency in silx is when importing `silx.opencl` when `pyopencl` is missing... which makes sense to me (To me it should even raise an `ImportError`).
This PR also reworks the way `CompareWidgets` and `silx.image.medianfilter` are probing the availability of OpenCL as `ImportError` is not raised.
To me it closes #2023
=> Update dependencies warning

silx/gui/plot3d/items/mesh.py, silx/gui/plot3d/test/testSceneWidgetPicking.py, silx/gui/plot3d/tools/PositionInfoWidget.py
Merge PR #2129 first!
This PR adds support of Mesh, Box, Cylinder and Hexagon items + some associated tests.
It provides the indices of the picked triangles for Mesh and the indices of the picked elements for Cylinder and Hexagon + a single position (the closest) for each elements.
closes #2135
=> [plot3d] Add picking of Mesh, Box, Cylinder and Hexagon items

silx/gui/plot/test/testPlotWidget.py
This PR adds some `qWait` in the resize/change aspect ratio test of the PlotWidget which leaded to random seg fault when running the tests with the OpenGL backend on macos on travis (I could not reproduce locally).
Hopefully closes #2134
=> (hopefully) fixes travis macos tests

silx/gui/plot/ScatterView.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testScatterView.py
It adds the possibility to give a transparency channel in addition to the value.
A minimal example to see its behaviour:
```
import numpy as np
from silx import config
from silx import sx
from silx.gui.plot.ScatterView import ScatterView
samps = 1000
levels = 100
fwhm = 50
cen = 500
x = np.random.rand(samps)*levels
y = np.random.rand(samps)*levels
v = np.random.rand(samps)*levels
x0, y0 = x[cen], y[cen]
a = np.exp(-4*np.log(2) * ((x-x0)**2 + (y-y0)**2) / fwhm**2)
config.DEFAULT_COLORMAP_NAME = 'viridis'
#without transparency
s1 = ScatterView()                                                
s1.setData(x, y, v)
s1.show()
#with transparency
s2 = ScatterView()
s2.setData(x, y, v, alpha=a)
s2.show()
```
=> Add alpha channel to ScatterView

silx/sx/test/test_sx.py
This PR fixes tests on sx.contour3d with PyQt4 on Python2.7 on Windows.
closes #1699
=> Make sx tests works with PyQt4/python2.7 on Windows

package/debian8/control, package/debian9/control
=> devscripts is needed on debian for automatic packaging

ci/appveyor.yml
Stop testing PySide as it is no more a target and this should speed-up appveyor builds.
=> Stop testing PySide with CI

silx/gui/plot/ImageView.py
This PR adds `PlotWindow`'s `ColorBarWidget` to `ImageView` central widget layout, otherwise it is deleted as `ImageView` changes the content of the `PlotWindow` central widget
This is probably the cause of #2202 and anyway makes the colorbar available in the `ImageView` widget (disabled by default).
If this is solving #2202, I would be in favor of integrating in 0.9.
=> [plot] Add ColorBarWidget to ImageView

silx/gui/dialog/SafeFileSystemModel.py
This PR makes directory enabled in dialogs with PyQt4 on macOS and avoids the following test errors:
```
======================================================================
FAIL: testFilterExtensions (silx.gui.dialog.test.test_datafiledialog.TestDataFileDialogInteraction)
----------------------------------------------------------------------
File "/Users/tvincent/venv/silx-release-py27/lib/python2.7/site-packages/silx/gui/dialog/test/test_datafiledialog.py", line 547, in testFilterExtensions
self.assertEqual(self._countSelectableItems(browser.model(), browser.rootIndex()), 4)
AssertionError: 3 != 4
======================================================================
FAIL: testFilterExtensions …
```
=> Fix dialogs directory enabled for macOS/pyqt4

silx/gui/utils/testutils.py
This PR proposes to only check for remaining widgets that were created by Python after each test.
=> [test] Only test remaining widgets created by Python

silx/gui/plot/PlotWidget.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/test/testPlotWidget.py
This PR removes some (not all) deprecated (at the very least since a year) methods/signals/arguments in `PlotWidget` and `PlotWindow`.
As a side effect, it closes #1677
=> [plot] Remove some old deprecated methods/arguments

silx/gui/colors.py, silx/gui/plot/_BaseMaskToolsWidget.py, silx/gui/plot/matplotlib/Colormap.py, silx/gui/test/test_colors.py
This PR reworks `silx.gui.colors.Colormap` implementation and deprecates `silx.gui.plot.matplotlib.Colormap` (which is no longer used within silx).
It:
- Removes the strong dependency to matplotlib in `silx.gui.colors`: closes #1859
- Improves `Colormap.getNColors`  to return the same number of colors as the LUT (and not a hard-coded 256): closes #2217
=> Refactor colormap

silx/gui/data/NXdataWidgets.py
Improves upon #2213 
The PR only fixes the issue for NXdata widgets, by not putting the sliders in a dock widget (this was asking for trouble).
It does not address the general question of the dock widget position and how to let applications specify a preferred initial location.
=> [NXdataWidgets]Improve sliders location for data selection 

silx/gui/colors.py, silx/gui/dialog/ColormapDialog.py, silx/gui/test/test_colors.py, silx/sx/_plot.py, silx/sx/test/test_sx.py
- Avoid to to use both `name` and `colors` in the constructor (`colors` is ignored + deprecation warning)
- Now `Colormap(colors=ndarray)` do not create anymore a default gray LUT
- `imshow` supports `Colormap` inside the argument `cmap`
- Improve the `Colormap` object API (`copy`, `__eq__`, `setFromColormap`)
- Get ride of dict in `ColormapDialog` to avoid exception when using colormap with custom LUT
- Some small clean up
=> Robustness on colormap

silx/io/nxdata/parse.py
Avoid IndexError if axes names and uncertainties names do not have the same size
```
ERROR:silx.gui.qt._qt:<class 'IndexError'> list index out of range   File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/app/view/Viewer.py", line 749, in displaySelectedData
self.__dataPanel.setData(data)
File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/app/view/DataPanel.py", line 119, in setData
self.__dataViewer.setData(data)
File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/data/DataViewerFrame.py", line 173, in setData
self.__dataViewer.setData(data)
File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/data/DataViewer.py", line 508, in setData
self.__updateView()
File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/data/DataVi …
```
=> Avoid iterate uncertainties if not enough names are provided

examples/imageview.py, silx/_config.py, silx/gui/colors.py, silx/gui/dialog/ColormapDialog.py, silx/gui/dialog/test/test_colormapdialog.py, silx/gui/test/test_colors.py
Some clean up and improvement around `silx.gui.colors`
- Fix ColormapDialog
- Display plot in log in colormap uses log
- Avoid extra computation while the ColormapDialog is not displayed
- Merge LUT descriptions
- provide an API to register new LUTs
Closes #2231
Closes #2230
Closes #2235
=> Improve colordialog

silx/app/view/Viewer.py, silx/app/view/main.py, silx/gui/data/DataViewer.py, silx/gui/data/NXdataWidgets.py, silx/io/fabioh5.py
- `silx view` now display the file opened on the data view (previously it was only displayed on the side tree)
- `fabioh5` provides an `NXdata` containing the image (this NXdata is defaulted by the root and the entry)
- As result loading an EDF file displays an image (sounds original)
- Fix bug, as some fabio files was not closed
Closes #2238 
Closes #2225
=> Improve silx view loading

silx/gui/colors.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/test/testPlotWidget.py
Add `setBackgroundColor` and `setDataBackgroundColor` to the plot API
- `setBackgroundColor` allow to custom the full background of the widget (including the background bellow the plot data)
- `setDataBackgroundColor` allow to custom the background bellow the plot data only
Closes #2220 
The OpenGL backend is not part of the PR
=> Support background color

requirements-dev.txt
I also saw that `scipy` was on the requirements.txt but from my point of view it should be in requirements-dev.txt no ?
=> include requirements.txt in requirements-dev.txt

examples/syncPlotLocation.py, silx/gui/colors.py, silx/gui/plot/test/testUtilsAxis.py, silx/gui/plot/utils/axis.py
This PR add another way to sync axes.
- `syncCenter` allow to synchronize axes to the value displayed in there center
- `syncZoom` allow to sync the pixel size of axes, reaching displayed pixels used to display the axes
As result `limits` of all axes can be different according to the size of the widget. Fixed limits was creating a lot of inconsistencies in case of use of fixed aspect ratio, or in case a lot of widgets are synchronized (widget size could not always match). Both constrains are still useful, depending on the context.
As it is mostly designed to sync Plot2D (displaying images), only a subset was implemented.
- Can only be used with linear axes
- Can be used to constrains `center` or `center+zoon`, but not `zoom` only
Closes #2243
=> Sync center of axis

setup.py
Boring but working.
Support old version of `setuptools`. It should fix the nightly build of debian packages
closes #2288
=> Support old setuptools

doc/source/modules/gui/plot/roi.rst, silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/test/testCurvesROIWidget.py
The roles between CurvesROIWidget and ROITable are:
* ROITable: display ROIs and insure connection with the plot (curves) and rois
* CurvesROIWIdget define behavior to have and clicking 'add ROI' and 'remove ROI'
=> [plot] rework ROI curve widget with object (Fix 1711)

examples/plotInteractiveImageROI.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotFrame.py, silx/gui/plot/backends/glutils/GLSupport.py, silx/gui/plot/items/roi.py, silx/gui/plot/items/shape.py
This PR adds support of `linestyle` and `linewidth` to plot `items.Shape` and X and Y markers in OpenGL (closes #2089).
It also adds support for `linestyle`, `linewidth`, `symbol` and `symbolsize` to `items.roi` classes (related to  #2255).
It also remove support for non-orthogonal axes in the OpenGL backend: this feature is not used and was making this change more complicated.
I can split this PR if needed.
=> More style support for plot items and ROIs

examples/printPreview.py, silx/gui/plot/PrintPreviewToolButton.py, silx/gui/widgets/PrintPreview.py
This addresses #2300 by providing two methods that can be implement in a subclass to provide custom comment and title to be printed below and above the plot.
=> [PrintPreview]API for comment and title

ci/info_platform.py, ci/requirements-pinned.txt, requirements.txt
This PR removes version pin-pointing for pyopengl and pyopengl as new versions are available.
=> Unpin pyopengl and pyopencl versions

silx/math/fft/__init__.py, silx/math/fft/basefft.py, silx/math/fft/clfft.py, silx/math/fft/cufft.py, silx/math/fft/fft.py, silx/math/fft/fftw.py, silx/math/fft/npfft.py, silx/math/fft/setup.py, silx/math/fft/test/__init__.py, silx/math/fft/test/test_fft.py, silx/math/setup.py, silx/math/test/__init__.py
This PR adds a FFT with multiple backends: numpy, FFTW, OpenCL and CUDA. The idea is to have the same API for all the underlying backends. All the boring work (plans computation, axes, data type, memory alignment) is taken care of.
The numpy backend serves as a reference to compare the 3 other against. 
Therefore, the numpy backend is tested separately. 
All comments/suggestions on the API are welcome.
- 1D -> ND transforms (all what the underlying backend can support)
- Batched transforms
- R2C, C2C modes, with float32 and float64 data types
- For GPU backends, input and/or output can be a device array.
- In-place transforms
- Hermitian transforms
- For CUFFT backend, batched transform where batch is other than dimension 0.
- Nice-to-have: transforms with "easy" zero-padding
```python …
```
=> Multi-backend FFT

bootstrap.py, examples/bg_color.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotFrame.py
This PR implements foreground color (issue #2296).
I implemented a separate `foregroundColor` and `gridColor`, similar as the existing `backgroundColor` and `dataBackgroundColor`. It is implemented for both backends (OpenGL en Matplotlib).
Note that setting the `dataBackgroundColor` makes the grid lines invisible in the GL backend (the MPL backend works fine). This bug was already present before this PR and I didn't see an obvious fix.
If fixed another bug though: the `backgroundColor` didn't work in the MPL backend.
I added `bg_color.py` to the `examples` directory for if you want to test it. Feel free to remove this demo script if it's no longer necessary.
=> Foreground color

silx/gui/colors.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/core.py, silx/gui/plot/items/shape.py
Here is a patch to allow to display dotted lines in 2 colors.
- The Matplotlib backend is based on a custom `_DoubleColoredLinePatch` customing the rendering method. And other expected methods.
- Tested only on matplotlib 3.0.2, and Debian8 one
- There is no OpenGL backend
- `line`/`vline`/`hline` do not uses patches, then there is no special rendering for this.
- It could be fixed
Closes #1270
=> Improve drawmask selection2

silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/items/core.py, silx/gui/plot/items/shape.py
This PR follows PR #2266 and:
- adds implementation in the OpenGL backend of line background color,
- moves `get|setLineBgColor` from `LineMixIn` to `Shape` item as it is only implemented here for now, and
- adds a warning in matplotlib backend where it is not available (i.e., `line`, `hline` and `vline` shapes)
- fixes `hline` and `vline` shapes in the OpenGL backend.
The implementation of the dash line background color in the OpenGL backend is different than that of the matplotlib backend in that it fills the holes of the dash line with the second color rather than being a true background color (different behavior when there is some transparency).
This can be easily changed, but I think it is more the desired behavior.
=> [plot] Implement line bg color for shapes

.travis.yml, ci/appveyor.yml, setup.py
This PR makes updates to `setup.py` to work with `numpy.distutils` from v1.16.0rc[1|2].
It also uses pre-release of numpy and cython during build not just during testing.
=> Make setup.py compatible with numpy 1.16.0rc1|2

silx/gui/plot/items/complex.py
Phase colormap is now editable, before it was bound to HSV colormap in [-pi, pi].
closes #2234
=> Allow to edit phase colormap for complex

package/debian8/control, package/debian8/rules
This PR removes debian 8 debug packages from the nighlty build.
=> remove debug packages from debian 8 build

examples/dropZones.py, silx/app/view/main.py, silx/gui/hdf5/Hdf5Item.py, silx/gui/hdf5/Hdf5TreeModel.py, silx/gui/hdf5/_utils.py
- Implement `url` from H5Node (object provided to user on tree interaction)
- Implement generic mimetypes for item of the tree
- `text/uri-list` was NOT implemented as the behaviour with most application was not very nice
- `text/plain` containing the URL, convenient to drag and drop thing to any application
- `application/x-silx-uri` also containing the same URL, convenient for application that really expecting an URI from silx
The Qt drop code is easy to write. And silx provides API to read the URI in case:
```
import silx.io.url
dataurl = silx.io.url.DataUrl(url)
import silx.io
dataset = silx.io.get_data(url)
import silx.io
with silx.io.open(url) as h5:
```
Closes #2355
=> Allow to drop URI from hdf5 tree to external applications

silx/gui/icons.py
filename was overwritting and wait button was limited to one frame.
=> [icons] Fix typo MultiImageAnimatedIcon

silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/__init__.py, silx/gui/plot3d/items/mesh.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/test/testSceneWidgetPicking.py
This PR mainly adds `indices` to `Mesh` and a `ColormapMesh` item for the `SceneWidget`.
It also improves the handling of data range in the model which has some issue for `Scatter2D|3D` and `ColormapMesh`.
=> plot3d items: add ColormapMesh and add indices to Mesh

silx/math/__init__.py, silx/math/fft/clfft.py, silx/math/fft/test/test_fft.py
This PR aims at solving #2383. It also removes the non-lazy import of FFT in `silx.math.__init__.py`, fixing #2375.
=> FFT/clfft: choose best device based on ocl class

silx/opencl/backprojection.py, silx/opencl/sinofilter.py
This PR adds a compatibility with the previous  `filter_projections` and `fourier_filter` functions.
=> Backprojection: compatibility with previous version

silx/gui/plot/ComplexImageView.py
`ComplexImageView.setVisualizationMode` is using `enum` and doc was saying it uses `str`.
This fix it and makes it clear how to use it with a sample code.
Related to #2420
=> Update ComplexImageView doc

silx/gui/plot/_BaseMaskToolsWidget.py
Few small changes on the threshold tools to improve usability.
It was difficult to know how to use it.
- Split other tools on another group (make the group consistent)
- Setup the text button to know what it will do
- Select a tool by default (the `bellow` tool)
- Hide unused configuration widgets
- Plus some clean up on the layouts
On a side note application could need to add new tools (for pyFAI we could want to add filter designed to remove cosmic rays). With the new group it is more easy to add this kind of buttons.
=> Improve mask tools GUI

silx/_config.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/scatter.py, silx/gui/plot3d/items/mixins.py, silx/sx/_plot.py, silx/sx/_plot3d.py
This extends and modify a bit what's been introduced in PR  #2419.
It makes sure `silx.config.DEFAULT_PLOT_SYMBOL` is used:
- in `plot3d` scatter items
- as the default symbol for `sx.scatter` and `sx.points3d` functions.
There is a change of behavior from the initial PR: What was set by the initial PR was the symbol of curves only, while here it changes the symbol of scatters.
@maurov, is that OK for you?
If you need to set a default symbol for curves as well, I would be in favor of introducing a `silx.config.DEFAULT_PLOT_CURVE_SYMBOL` (default to '') because 2 different default are needed for scatter and curves...
=> Update default symbol

silx/gui/plot/ColorBar.py
This fixes a issue when there is a scatter plot and one changes the default colormap.
This issue shows in the ScatterView.
closes #2424
=> Fix update of colorbar

silx/app/convert.py
The command line argument is converted to int, if possible.
=> [silx convert] Allow to use a filter id for compression

silx/gui/data/DataViewer.py, silx/gui/data/DataViewerFrame.py, silx/gui/data/DataViewerSelector.py, silx/gui/data/DataViews.py, silx/gui/data/Hdf5TableView.py
This could be merged in the master if you think it is safe enough for the 0.10.
It prepares #2415
Here is an example: the `NxDataView` could provide 2 views for a 3D data (displayed at the same time). This new views are not part of the PR.
```
self.addView(_NXdataCurveView(parent))
self.addView(_NXdataXYVScatterView(parent))
self.addView(_NXdataImageView(parent))
self.addView(_NXdataStackView(parent))
nx3dViews = SelectManyDataView(parent)
nx3dViews.addView(_NXdata3dView(parent))
nx3dViews.addView(_NXdata3dAs2dView(parent))
self.addView(nx3dViews)
```
=> Feature a SelectManyDataViews object

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py
As it is, it is never used as the stack has more priority...
To be effective, this feature needs to be combined with PR #2433 so that both stack and 3d views are available for NXdata.
Also, the 3d view has the same priority as the stack.
Maybe when interpretation=vertex, one wants to favor the 3d view...
related to #2415
=> Add a 3d scalar field view to the NXdata views zoo

silx/gui/data/DataViews.py, silx/io/nxdata/parse.py
This PR allow to display an NXdata containing a volume using a 2D view or a 3D view.
This is the result of #2455 and #2433 
As commended https://github.com/silx-kit/silx/pull/2455#issuecomment-464116563, the NXdata interpretation have to be "scalar" (or no interpretation), the signal must have 3dim, and axes must have the right dimension (according to the signal).
The default selected view is the 2D one, as it is faster and it do not have dependency with OpenGL.
Closes #2415
=> Support 2dview for 3dnxdata

silx/gui/plot/PlotWidget.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/ScatterView.py, silx/gui/plot/StatsWidget.py, silx/gui/plot3d/Plot3DWindow.py, silx/gui/plot3d/actions/mode.py, silx/utils/proxy.py, silx/utils/test/test_proxy.py
This PR provides a `@docstring` decorator that allows to duplicate a docstring from a function or method.
This is convenient when overriding method or making proxy for object composition.
Usage:
```
from silx.utils.proxy import docstring
class B(A):
@docstring(A)
def overridden_method(self):
pass
```
This PR makes use of it throughout silx.
closes #2443
=> Docstring decorator

silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/scene/core.py, silx/gui/plot3d/scene/cutplane.py, silx/gui/plot3d/scene/function.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/scene/viewport.py, silx/gui/plot3d/test/__init__.py, silx/gui/plot3d/test/testSceneWidget.py
This PR adds the option to render the scene with linear fog.
As it is, it is an on/off linear fog across the whole scene.
It is possible to add different kind of fog, to allow to set the range over which to apply it or to specify a fog color.
To try it, use `examples/plot3dSceneWindow.py`, and in the `Object parameters` dock widget on the right, expand the `Settings` node and toggle the `Fog` checkbox.
closes #2414
=> [plot3d] Add scene fog

silx/_config.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/actions/control.py
This PR fixes the issue with default symbol in plot widget.
To me the `silx.config.DEFAULT_PLOT_CURVE_SYMBOL` feature is a bit ambiguous, any better idea welcome.
closes #2488
=> Fix plot default symbol

silx/math/fft/test/test_fft.py
This PR fixes an error occurring when testing silx without OpenCL.
=> FFT: skip OpenCL backend when no openCL or skip opencl

silx/app/view/main.py
This PR makes sure `hdf5plugin` is loaded before anything else is loading `h5py` in silx view.
Without this, the bitshuffle/lz4 plugin is not available in silx view even if installed (tested on macOS).
=> load hdf5plugin before silx in silx view to make sure it is loaded first

silx/gui/dialog/ColormapDialog.py
This PR avoids an assert when opening the `ColormapDialog` for an image with all 0 and a log scale colormap.
=> fix set data range when all values are 0 and log scale

silx/gui/dialog/AbstractDataFileDialog.py, silx/gui/dialog/ImageFileDialog.py, silx/gui/dialog/test/test_datafiledialog.py, silx/gui/dialog/test/test_imagefiledialog.py
It was not possible to select the image of a cube with shape like `1,y,x`.
Plus few clean up
Closes #2484
=> Fix ImageFileDialog selection

silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/__init__.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/test/testSceneWidgetPicking.py
This PR adds a `ComplexField3D` item to the `plot3d.SceneWidget` to display 3D array of complex.
It extends the `ScalarField3D` item by allowing to select a different display mode (i.e., real part, imaginary part, amplitude, phase, amplitude**2) for isosurfaces and the cut plane.
It does NOT provide yet:
- the display of a color-mapped isosurface e.g., an isosurface in the amplitude and colored with the phase.
- the integration in `silx view`.
There is also some work to make the `plot.items` and `plot3d.items` API regarding complex consistent (`getVisualizationMode` in `plot` and `getComplexMode` in `plot3d`).
All this will be done in other PRs.
related to #2323
=> [plot3d] Add complex 3D volume item to SceneWidget

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/data/_VolumeWindow.py, silx/gui/plot3d/SceneWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/__init__.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/test/testSceneWidgetPicking.py
Merge PR #2512 first!
This PR replaces the `ScalarFieldView` widget in `silx view` 3D plotting with `SceneWindow`.
This brings support for 3D complex field visualization.
The pitfall is that `SceneWindow` is more generic and thus the parameter tree is more complicated...
Usability of it in this specific case can be improved, see #2518.
related to #2323
=> [silx view] Use SceneWindow for 3D to enable 3D complex field visualization

examples/plot3dSceneWindow.py, silx/gui/plot3d/SceneWindow.py
This PR adds a `PositionInfoWidget` in `SceneWindow` by default rather than having to add it manually as like before in `plot3dSceneWindow.py` example.
=> [plot3d] Add PositionInfoWidget to SceneWindow

tools/create_h5_sample.py
- It allows to write dataset already encoded on our side.
- Unfortunately `h5py` do not allow to create an empty dataset with a filter which is not installed. Yet i don't know if it is a HDF5 or h5py limitation.
- Maybe it is possible to write already encoded datasets if at least the decoder is present (and not the encoder one)
- Rework the generation of different kind of links
=> Add encoded data and links

silx/gui/data/_VolumeWindow.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/mixins.py
This PR makes some improvements of ``silx view`` 3D volume view and ``SceneWidget`` model.
It:
- Adds a drop down menu in the parameter to set the cut plane // to each axis
- Expands the parameter tree when loading
- Sets the interaction mode to plane panning and select the cut plane when it is made visible.
- Initialize the plane position as going through the center of the dataset
- Renames the complex mode from ``Absolute`` to ``Amplitude``
- Uses ``Amplitude`` as the initial complex mode
- Renames ``Values<=Min`` to ``Show <=Min``
related to #2518
=> [plot3d] 3D volume visualization/parameter tree improvements

silx/gui/data/_VolumeWindow.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/mixins.py
Merge PR #2523 first !
This PR optimizes the ``plot3d`` parameter tree update by requesting model update only when the right event is received (before it was updated for any event for a given item).
It also fixes a few issues with model not sending correct update events (for item visibility, isosurface color and light direction), resulting in tree widget not being synchronized until the mouse hovers it.
closes #2513
=> [plot3d] Optimize parameter tree updates and fix synchronization

silx/gui/plot/Profile.py, silx/gui/plot/ProfileMainWindow.py
When using the OpenGL backend of the Plot2D widget, the profile window still uses the default matplotlib backend. Additionally, the profile is updated every time the image changes, even when the profile window was never shown.
The first commit adds the backend parameter to the ProfileMainWindow and forwards to it the backend of the main plot. This already leads to a noticeable speedup.
The second commit updates the profile only when the profile window is visible. As I haven't spent much time looking for side effects, this approach might be too simple.
Unfortunately, the test suite segfaults on my Debian 9 installation. Therefore, I have run only the Profile tests.
=> Some performance improvements

doc/source/modules/opencl/convolution.rst, doc/source/modules/opencl/index.rst, doc/source/modules/opencl/processing.rst, doc/source/modules/opencl/statistics.rst, silx/opencl/convolution.py, silx/opencl/processing.py, silx/opencl/test/__init__.py, silx/opencl/test/test_convolution.py, silx/resources/opencl/convolution.cl, silx/resources/opencl/convolution_textures.cl
This PR adds a general-purpose OpenCL convolution in silx.
- <del> Modify kernel and/or axes on-the-fly </del> --> not relevant, lot of compiled code depend from axes.
- <del>Put convolution kernel in constant memory</del> --> not relevant with textures
=> OpenCL convolution

silx/gui/plot/PlotWindow.py, silx/gui/plot/Profile.py, silx/gui/plot/_BaseMaskToolsWidget.py
Non-parented `QAction` creates memory leak.
This following code can be used to help to catch this problems.
```
def assert_qaction_parent():
from PyQt5.QtWidgets import QAction
qt_qaction_constructor = QAction.__init__
def my__qaction__constructor(self, *args, **kwargs):
parent = None
if "parent" in kwargs:
parent = kwargs["parent"]
if len(args) != 0:
parent = args[-1]
if len(args) + len(kwargs) != 0:
assert(parent is not None)
return qt_qaction_constructor(self, *args, **kwargs)
QAction.__init__ = my__qaction__constructor
```
Closes #2538
=> Fix plotaction parent

silx/gui/_glutils/Context.py, silx/gui/_glutils/Program.py, silx/gui/_glutils/__init__.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLText.py
This PR avoids to keep reference to objects related to a given OpenGL context after this was destroyed.
It replaces the use of ``dict`` with ``WeakKeyDictionary`` to circumvent this.
It also includes the renaming of 2 functions used internally.
related to #2538
=> Avoid object leak at destruction of PlotWidget with OpenGL backend

silx/opencl/convolution.py
This PR attempts to fix a bug occurring with pyopencl 2014.x, crashing the continuous integration on edna-site.
=> pyopencl: Dont use numpy.int32 for workgroup param

silx/gui/_glutils/Texture.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/matplotlib/__init__.py, silx/gui/plot3d/items/scatter.py, silx/gui/plot3d/scene/primitives.py, silx/io/commonh5.py, silx/sx/_plot.py, silx/sx/_plot3d.py
This PR makes `silx` compatible with python3.8 which provides abstract base classes only in `collections.abc` (and no longer in `collections`).
This could be simpler if we'd drop python2.7 (as it does not provide a `collections.abc` module)...
=> python 3.8 compatibility

.travis.yml, ci/requirements-pinned.txt, silx/gui/plot/matplotlib/__init__.py
This PR tries to run CI with latest version of `PyQt5` and `PySide` (CI is currently using fixed versions).
Merge PR #2549 first (it is included here).
closes #2354
=> [CI] Remove PyQt5 and PySide2 version pinpointing

silx/gui/plot3d/Plot3DWidget.py, silx/gui/plot3d/items/mixins.py, silx/utils/enum.py, silx/utils/test/__init__.py, silx/utils/test/test_enum.py
This PR adds a subclass of `enum.Enum` in `silx.utils` with a few extra convenient class methods.
It makes use of it in `silx.gui.plot3d` and removes some code duplication.
=> Add an Enum subclass to silx.utils

silx/gui/console.py, silx/gui/plot/matplotlib/__init__.py
This PR adds an import of `RichJupyterWidget` from `qtconsole.rich_jupyter_widget` to avoid a deprecation warning.
Merge PR  #2549 first (it is included here).
=> qtconsole support: avoid deprecation warning

silx/gui/plot/backends/glutils/GLTexture.py
This PR fixes an issue in the plot OpenGL backend for large images (when using tiles) where both texture data and shape were provided.
closes #2557
=> [plot] Fix issue in large image display with OpenGL backend

silx/gui/plot/actions/control.py
Use backquotes for link to class docstring.
Alphabetical order for actions.
=> minor typo in RST

silx/gui/qt/_qt.py
When using PySide PySide2 is proposed as replacement. However, there is a warning when using PySide2.
closes #2565
=> [GUI[ Remove warning concerning PySide2 usage.

silx/gui/plot/_utils/delaunay.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testItem.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot3d/items/scatter.py
This PR extends the 'scatter' item of the `PlotWidget` to support Delaunay triangulation based display of scatter plots.
It adds `set|getVisualization` and `supportedVisualizations` methods to `scatter` items.
It avoids code duplication with `plot3d` through a `triangulation` function.
Related to #2324 but not closing it:
- OpenGL backend implementation is not done yet (to do in another PR).
- `get|setVisualization` API needs to be reworked for consistency with `plot3d` (issue #2554)
=> [plot] add surface visualization to scatter item

silx/gui/_glutils/__init__.py, silx/gui/_glutils/utils.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py, silx/gui/plot/backends/glutils/__init__.py, silx/gui/plot/items/scatter.py, silx/gui/plot3d/items/mesh.py, silx/gui/plot3d/items/scatter.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/scene/utils.py
This PR adds the implementation of `addTriangles` method to the plot OpenGL backend, thus allowing to display scatter plots as surfaces with the OpenGL backend.
Picking still needs to be done.
closes #2324
=> [plot] OpenGL implementation of scatter plot displayed as surface

silx/_config.py, silx/gui/colors.py, silx/gui/plot/PlotWidget.py
This PR makes `matplotlib` an optional dependencies when using the `PlotWidget` OpenGL backend.
I'm not really for optional dependencies, but it's actually a small change set (actually there were places where it was already handled).
=> [plot] Allow to use plot OpenGL without matplotlib

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/plot/ComplexImageView.py, silx/gui/plot/actions/control.py, silx/gui/plot/items/complex.py, silx/gui/plot/items/core.py, silx/gui/plot/test/testComplexImageView.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/items/volume.py, silx/gui/plot3d/test/testSceneWidgetPicking.py, silx/gui/plot3d/test/testSceneWindow.py, silx/utils/proxy.py
This PR makes `plot` and `plot3d` items API consistent concerning complex data visualization mode.
It moves the `ComplexMixIn` from `plot3d` to `plot` and uses it in `ImageComplexData` plot item.
API of `ComplexImageView` is updated to be synchronized with `ComplexMixIn`.
Backward compatibility is kept (with deprecation warnings).
Also by using `silx.utils.Enum` it is now possible to set the complex mode with a `str` (e.g., 'phase') as well as an `Enum` member.
=> plot/plot3 complex visualization mode API consistency

README.rst, doc/source/install.rst
This PR changes the debian version that is advertised for packages provided by www.silx.org to debian 9.
=> [doc] Update debian version of nightly builds to debian 9

silx/gui/plot/items/__init__.py, silx/gui/plot/items/core.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testItem.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot3d/_model/items.py, silx/gui/plot3d/items/scatter.py
This PR adds a `ScatterVisualizationMixIn` class to have a consistent API for 2D scatter plots in both `plot` and `plot3d` items.
This introduces an API break in `plot3d` 2D scatter items, as `supportedVisualizations` and `getVisualization` methods were returning `str` and now returns the corresponding `Enum`.
The `setVisualization` method is backward compatible.
closes  #2554
=> Make plot/plot3d scatter visualization mode consistent

silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py
I have a use case where I need multiple sets of ROIs (one set for each image in a list of images) associated with a single PlotWidget. When I change the image in the plot widget, I want to show only the ROIs specific to the new image.
This PR adds a public API to class `RegionOfInterest` to show or hide it in the plot:
`roi.setVisible(False)`
Alternative APIs that would also work for me, in case you don't like this one:
`roimanager.setRoisVisible(False)`   (this works because I have one ROI manager per image)
`item.setVisible(False) for item in roi.getPlotItems()`
=> add a setVisible method to ROI objects

silx/gui/plot/PlotWidget.py
This PR changes the way to handle Y axes limits when the Y axes have no content displayed.
When the Y axis on the left has no content while the right Y axis as some curves, the limits on the left defaults to the one on the right. This is meant to avoid missleading [0, 100] limits displayed on the left.
closes #2563
=> [plot] Change the handling of default y axis limits

silx/gui/plot/items/__init__.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/items/marker.py
This PR adds a common API (`drag` method) to move `DraggableMixIn` items.
It also make the base class of markers available.
This is to prepare for larger modifications of the plot.
=> [Plot] common API for draggable item

silx/gui/plot/items/__init__.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testItem.py
This PR renames the `Points` item base class to `PointsBase` and make it available in the items `__init__.py`.
=> [plot] Points item base class made accessible

doc/source/ext/snapshotqt_directive.py
This PR removes some patching of the environment in the snapshot qt directive that is not friendly with debian packaging.
closes #2603
=> Remove patch of sys.path and PYTHONPATH which are not needed

silx/gui/plot/CompareImages.py
This PR makes `CompareImage` taking into account the optional availability of the `sift` package (under Debian).
closes #2605
=> Take into account optional sift module (for debian packaging)

silx/gui/data/test/test_dataviewer.py, silx/gui/test/test_colors.py
This PR removes deprecation warning from `silx` while running the tests.
=> Remove silx deprecation

silx/math/fit/bgtheories.py
Avoid `DeprecationWarning: elementwise comparison failed; this will raise an error in the future`
=> Avoid deprecation warning in silx.math.fit.bgtheories

silx/image/tomography.py, silx/opencl/sinofilter.py, silx/opencl/test/test_backprojection.py
One might need to use functions like `compute_fourier_filter` without needing OpenCL.  
However, in the current state of things, any import of an opencl-related module will eventually build an `OpenCL` object through `common.py` : `ocl = OpenCL()`. Building this object will attempt to use pyopencl to query available devices.  
This PR moves some non-opencl code to from `silx.opencl.sinofilter` to `silx.image.tomography`.
As a side note, executing 
```python
from silx.opencl.sinofilter import compute_fourier_filter
```
on our Power9 testing platform *does* create contexts on all the visible GPUs. This results in errors if we try to create a CUDA context afterwise. This does not happen on X86 since the OpenCL contexts, if created, are cleaned.
=> SinoFilter: Move non-opencl related functions to silx.image.tomography

silx/math/medianfilter/include/median_filter.hpp
This PR avoids build warnings by using a specialized template inline function to get NaN with float/double and fail when called for integers (which should not happen).
closes #2607
=> Avoid build warning in median filter

silx/app/view/About.py, silx/gui/data/ArrayTableModel.py, silx/gui/data/test/test_textformatter.py, silx/gui/hdf5/test/test_hdf5.py, silx/gui/test/test_colors.py, silx/io/fabioh5.py, silx/io/test/test_specfile.py, silx/io/test/test_spech5.py, silx/io/test/test_spectoh5.py, silx/io/test/test_utils.py, silx/math/test/test_HistogramndLut_nominal.py, silx/math/test/test_histogramnd_nominal.py, silx/utils/test/test_weakref.py
This PR aims at avoiding (most if not all) deprecation warnings from our dependencies during the tests.
Check commit messages for the issue that it fixes.
=> Fix deprecation warnings from numpy/python/pkg_resources/h5py

silx/gui/plot/backends/BackendMatplotlib.py
This PR removes a deprecation warning from matplotlib >=3.1 related to accepted error arrays.
=> Remove (N,1) error array deprecation with matplotlib 3.1

silx/math/fft/test/__init__.py, silx/math/fft/test/test_fft.py
This PR reworks the tests of `silx.math.fft` to use `unittest.TestCase.subTest` instead of parametric `TestCase`.
This reduces the logs.
=> reword fft test to use subTest approach

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/core.py, silx/math/test/test_colormap.py, silx/math/test/test_combo.py
This PR avoids some (not all) `numpy` `RuntimeWarning` related to NaNs or divide by zero, while those cases are acceptable in the condition they are used.
=> Silent/avoid irrelevant RuntimeWarning

silx/gui/plot/items/image.py, silx/gui/plot/test/testPlotWidget.py
This PR adds the option to provide an alpha image to plot `Image` items.
This is available through `Image.setData`.
Sample code:
```
import numpy
from silx import sx
data = numpy.random.random((10, 10))
alpha = numpy.linspace(0, 1, 100).reshape(10, 10)
plot = sx.Plot2D()
plot.addImage([()], legend='image')  # Create an empty image
image = plot.getActiveImage()
image.setData(data, alpha=alpha) # Fill the image with data and transparency
plot.resetZoom()
plot.show()
app.exec_()
```
closes #2620
=> [plot] Add option to provide an alpha image in plot image item

silx/utils/test/test_number.py
This PR uses a value to test conversion that does not fit even in a 128 bits mantissa to make sure the warning is raised with any kind of `float128` dtype (which is not necessarily a padded 80 bits float depending on the platform e.g., ppc64, arm64).
closes #2606
=> Uses a more precise value to ensure warning is raised

silx/opencl/sparse.py, silx/opencl/test/__init__.py, silx/opencl/test/test_sparse.py, silx/resources/opencl/sparse.cl
This PR aims at bringing sparse matrix compaction/decompaction in the Compressed Sparse Row (CSR) format with OpenCL.
Work in progress:
Questions:
- Do we implement generic matrix-vector, matrix-matrix in this processing ?
- Do we include more specialized code (ex. decompaction of `op(csr1, csr2)` where `op` is an elementwise operation) ?
=> [OpenCL] CSR utilities

silx/gui/plot/backends/glutils/GLPlotTriangles.py
This PR fixes an issue with the OpenGL backend triangles item used by scatter items displayed as a surface. The `GLTriangles` class had no `xMin`, `xMax`, `yMin`, `yMax`, which broke the OpenGL backend when getting its data bounds.
=> [plot] OpenGL backend triangles item had issue with data bounds

silx/gui/plot3d/scene/camera.py, silx/gui/plot3d/scene/viewport.py
This PR improves the handling of reset zoom when one or more dimension is null.
=> [plot3d] Improve reset zoom with 2D (and 1D) data sets

silx/io/utils.py
It resolves #2640. If `h5py` raises `OSError` on opening a file the PR opens the file in the SWMR mode.
=> add support for swmr files

silx/gui/plot/_utils/delaunay.py, silx/gui/plot/items/scatter.py, silx/gui/plot/tools/profile/ScatterProfileToolBar.py, silx/gui/plot/tools/test/testScatterProfileToolBar.py, silx/gui/plot3d/items/scatter.py
This PR moves the management of Delaunay and interpolator into plot scatter item, so that it is shared by both rendering and profile to avoid duplicated long computation.
This implementation is based on Python's Future and a "greedy" thread pool executor.
closes #2594
=> [plot] scatter item shared Delaunay triangulation/interpolator

silx/gui/plot3d/items/mixins.py
This PR fixes an issue with `@docstring` for classes with the latest version of `PySide2`.
=> Do not use @docstring for class

silx/gui/data/_VolumeWindow.py
This PR fixes default reset zoom of `silx view` with 3D data on macos (where it is done before setting the data...).
=> fix first time reset on macos

silx/math/fft/test/test_fft.py
Fix import error during the tests of `silx.math.fft`.
=> test_fft: catch scipy importerror

silx/opencl/sparse.py
Fix import error on old versions of pyopencl.
=> GenericScanKernel: use pyopencl.sparse instead of pyopencl.algorithm

silx/gui/plot/PlotWidget.py
Fix "not all items were formated" error in PlotWidget when no supported backend was found.
=> PlotWidget: fix valuerror formating

silx/gui/qt/_qt.py
Python 2.7 tests do not pass under windows if not done.
=> Allow to set sip API when using PyQt4.

silx/gui/plot/tools/roi.py
This PR makes sure we are handling a signal from a QAction when dealing with ROI action.
Related to #2655 (might be closing it).
=> Defensive code for ROI QAction signal handling

silx/opencl/common.py
Hello,
I am trying to deal with the issue number #1272 of silx-kit/pyFAI.
We get this : 
```LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR```
when using pyopencl even if  it is not possible to use it.
Thus I tried to fix this issue with a test being ran just after the importation of pyopencl.
Tell me what you think about it.
Cheers,
Alex
=> Testing if pyopencl can be used on the machine after importation

silx/math/interpolate.pyx, silx/math/setup.py, silx/math/test/__init__.py, silx/math/test/test_interpolate.py
This PR adds a `silx.math.interpolate` module with a `interp3d` function for trilinear interpolation in a regular equally spaced grid.
This functions is similar to [`scipy.interpolate.interpn`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html#scipy.interpolate.interpn) except that the grid is equally spaced and it only handles 3D dataset.
It provides almost a x10 speed-up over `interpn` and almost x50 with OpenMP * (with `method=linear_omp`).
I need it for #2323
*: On my machine
=> Add a trilinear interpolator

silx/io/dictdump.py, silx/io/test/test_dictdump.py
This PR adds an `asarray` argument to `h5todict` which is `True` by default and keeps the legacy behavior, but when set to `False` provides the behavior that for me should have been the only one: scalars are converted to scalars in the output `dict` rather than arrays.
closes #2689
=> h5todict asarray=True argument

silx/opencl/sparse.py, silx/opencl/test/test_sparse.py, silx/resources/opencl/sparse.cl
This PR enables to use the GPU CSR utilities on other data types (float64, (u)int8,16,32,64).
Complex and half float are not supported as data types.  
Due to a pyopencl limitation in `GenericScanKernel`, indices data type must have its size divisible by 4 bytes.
=> [Opencl] CSR: add support for data types other than float32

silx/gui/qt/_utils.py, silx/gui/utils/__init__.py, silx/gui/utils/test/test.py
This PR adds a `blockSignals` context manager that allows to block signals for one or many `QObject`s.
This is not much code, but it allows to replace:
```
previous = obj.blockSignals(True)
obj.blockSignals(previous)
```
with:
```
with blockSignals(obj):
```
which makes it more readable.
=> silx.gui.utils.blockSignals helper

silx/gui/plot/backends/BackendMatplotlib.py
This PR makes sure that the grid is displayed below plot items with `z`>=0 (and above items with `z`<0).
This is done through a call the `Axes.set_axisbelow(True)` which sets the grid zorder to 0.5 and by adding 1 to `z` of all items (`z` is an integer in `silx`).
Tested with matplotlib 2.2.3 and 3.1.1.
closes #2687
=> Display the grid below items by default

silx/gui/plot/PlotWindow.py
When we try to call the getStatsWidget() the _statsDockWidget.widget() is None. This came from the merge of PR #2674 because `self._statsDockWidget.setWidget(statsWidget)` need to be set before any other call to `getStatsWidget()` which is made by getStatsAction() and bring some incoherence.
this PR fix it
=> [PlotWindow] fix call to getStatsWidget.

silx/gui/plot/ScatterMaskToolsWidget.py
Attempting to disconnect a non-connected method raises a type error.
According to this old post, there is no way to know it the slot was connected or not
https://forum.qt.io/topic/6667/i-strongly-need-to-know-slot-where-signal-is-connected-to/11
=> [Scatter Mask] Prevent unhandled exception

silx/gui/data/DataViewer.py, silx/gui/data/NumpyAxesSelector.py, silx/gui/data/test/test_numpyaxesselector.py
This PR makes the data viewer (and so `silx view`) keeping the same selection of axes when switching between datasets which have the same shape. It also keeps the selection between views with similar dimensions for the same dataset (e.g., between image view and array view).
This is changing quite a bit the internals which are not that simple, so it needs a serious look at it.
related to #2683, but not closing it: (NX)StackView need specific care and this PR is not addressing it.
=> silx view: keep the same axes selection whenever possible

silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/ScatterView.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/items/roi.py, silx/sx/_plot.py
This PR provides a refactoring of the `PlotWidget` picking machinery to make it more generic.
The initial need for this comes from displaying scatter plot as images (for density plot) which requires a split between plot items and the backend that was not possible with the previous picking implementation.
`PlotWidget` provides 2 methods: `_pick` and `_pickTopMost` to do the picking (to become public at some point and probably return some `PickingResult` objects as in `plot3d` and `sx.ginput`).
Plot items provide a `pick` method returning `None` if not picked and otherwise the indices of the picked data points.
=> [plot] Refactor picking

bootstrap.py
- chdir was already used, the location is already fine
=> Allow to use bootstrap from another dir location

silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/ScatterView.py, silx/gui/plot/items/_pick.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot3d/items/_pick.py, silx/sx/_plot.py
This PR makes `PlotWidget.pickItems` and items' `pick` method returns a `PickingResult` object rather than a tuple (item, indices) or indices. This enables to provide richer picking information in the future without breaking the API and is consistent with the picking API of `plot3d`.
The `PickingResult` class of `plot3d` inherits from the new one of `plot` and extends it as more features are available for now in `plot3d` picking.
=> PlotWidget.pickItems returns objects

bootstrap.py
This PR fixes issues with `bootstrap.py` and IPython (e.g., defined variables not available in `globals()`).
It was using `embed` while `start_ipython` is preferable.
=> Fixes bootstrap.py starting IPython the wrong way

silx/gui/plot/backends/BackendMatplotlib.py
This PR uses the matplotlib `Axes.apply_aspect` method to synchronize plot limits rather than doing a full replot.
This avoids to replot when getting the limits of a plot with keep aspect ratio.
=> Avoid some synchronization replot in matplotlib backend

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/marker.py
This PR reworks completely the order in which the plot items are rendered and picked:
- Picking order was not consistent with rendering order after merging PR #2602 which didn't care about the item ordering on screen.
- Rendering order was not ideal because:
-  for a given z value, the rendering order was defined by the order of updates of items rather than the order of addition to the plot.
- for overlaid items (i.e., markers and draggable shape items), the z value was not taken into account.
Now the rendering order is defined by:
- first, whether or not the item is an overlay,
- then by the z value,
- and finally by the order of addition of items in the plot.
Rendering order of items is no longer managed by the backend, instead, the backend are asking the order to the PlotWIdget. …
=> Rework PlotWidget rendering/picking order

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/marker.py
Merge PR #2730 first!
Following the refactoring of picking and z order management in the plot, this PR makes some clean-up in the backends.
Indeed, some information is no longer need in the backend.
Also for the OpenGL backend, some of the code that was initially duplicated between the backends and `PlotWidget` was not removed. This PR removes some of this (e.g., checks in `dataToPixel` and `pixelToData` methods).
More rework/clean-up can be done, but that will be for another time...
=> Refactoring plot backends

examples/plotInteractiveImageROI.py, silx/gui/plot/items/roi.py
This PR changes the default symbol used for `PointROI` in `plot` back to '+', and updates the ROI example script.
Some changes made the default symbol used for `PointROI` a 'o' as a side effect.
'+' sounds better and this PR restores it as a default.
=> Point roi symbol

silx/gui/data/DataViews.py
Allow to display custom NXdata as a scatter.
Else it is displayed as an `NXCurveView`.
I guess a better thing to do is to use a curve only if it uses a single axis.
But here it works.
=> Tune the scatter priority

silx/utils/files.py
This PR makes URL goes through the filename expansing function by adding filenames with magic that cannot extends.
Not sure it is the best (it would be better to check that it is a URL), but at least it keeps it simple.
closes #2749
=> Allows URL to go through filename expansion

silx/io/fabioh5.py, silx/io/test/test_fabioh5.py, silx/utils/number.py, silx/utils/test/test_number.py
- Tune magic coef to allow to discrete float precision expected more than 16bit but less than 64bit bits
- Fix precision for scalar in many frames (1)
- Fix precision for list of numbers (2)
- Fix precision for list of numbers in many frames (3)
Add regression test.
Spotted by @juliagarriga 
It would be good to rework this code to allow to take care of the three use cases (1) (2) (3) in specialized functions. This could create a more readable code.
Closes #2736
Closes #2737
=> Fix float32

silx/io/dictdump.py
This PR fixes a bug in `h5todict` with argument `asarray=False` where there was an issue during the recursive calls.
=> fix h5todict with asarray=False

silx/gui/plot/actions/control.py
Here is one way to fix #2764
I think the colordialog size is set with a plot size of 0x0.
And then the plot take all the expected size when the colormap is set to the dialog which create the graphical glitch.
In between i think:
- plotwidget sizehint is maybe wrong
- colormap sizeHint is wrong
I think this patch only fix one of the cases. And the problem still exists.
Closes #2764
=> Update the dialog then show

examples/exampleBaseline.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/histogram.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testPlotWidget.py
This is the PR related to #2714 to add a baseline parameter.
this include
If such a parameter is added then we could reconsider the usage of the 'fill parameter'.
/close #2714 
small script to test, for now fails in the addHistogram, with the current values:
``` python
from silx.gui import qt
from silx.gui.plot import Plot1D
import numpy
qapp = qt.QApplication([])
x = numpy.arange(0, 10, step=0.1)
my_sin = numpy.sin(x)
y = numpy.arange(-4, 6, step=0.1) + my_sin
mean = numpy.arange(-5, 5, step=0.1) + my_sin
baseline = numpy.arange(-6, 4, step=0.1) + my_sin
edges = x[y>=3.2]
histo = mean[y>=3.2] - 1.8
plot_ogl = Plot1D(backend='opengl')
plot_ogl.addCurve(x=x, y=y, baseline=baseline, color='grey', legend='std-curve', fill=True)
plot_ogl.addCurve(x=x, y=mean, color='red', legend='mean') …
```
=> [Plot] add "baseline" option in addCurve

silx/gui/data/NumpyAxesSelector.py
This PR fixes the slow down introduced in PR #2701, which added some useless copy of the h5py dataset through the use of `self.data()`.
closes #2775
=> Fix silx view being slow because of copying data

silx/image/utils.py, silx/opencl/convolution.py, silx/opencl/test/test_convolution.py, silx/opencl/utils.py
In `silx`, importing anything using `silx.opencl.common` creates an OpenCL context on all possible devices on certain machines (see #2703). This is due to `common.py` creating a `OpenCL()` singleton when imported.
However if another module wants to use non-opencl utilities (ex. `ConvolutionInfos`, `gaussian_kernel`), a context should not be created on devices. To ensure so, these features are moved in a module not importing `silx.opencl.common`.
=> [Opencl] Move non-opencl utilities

silx/opencl/convolution.py
Fix a bug when we don't want to allocate any memory outside of necessary temporary buffer.
=> [Opencl] Convolution: allow for extra option allocate_X_array=False

silx/gui/plot/actions/histogram.py
For a very high peak in at the min data, and mostly nothings for other bins, the plot looks empty (basically a black image with a small beam).
This PR make the result a little more readable by introducing a margin around the data.
=> Add margin around data for readability

silx/io/url.py
A small modification to be able to compare other type with Dataurl type.
Previously was failing with 
``` python
url = DataUrl(...)
url == None
```
=> [dataurl] add a test on the type of other in `__eq__`

examples/compositeline.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/items/core.py
This PR provides more markers for both OpenGL and Matplotlib backend.
It also provides a small example as a usecase.
There is some glitches cause of the hi-dpi, some lines can be displayed or not according to the screen resolution... But everything is there.
I think it is good enough for me.
Closes  #2740
=> Support more marker symbols

examples/simplewidget.py, silx/gui/plot/LegendSelector.py, silx/gui/widgets/LegendIconWidget.py
- Create a dedicated module for the `LegendIcon` -> `silx.gui.widgets.LegendIconWidget`
- It was created to have no dependency with plot objects
- Support `colormap` (including grayed when disabled)
- Support `symbolColormap` to display style for scatters (including grayed when disabled)
- `LegendIcon` still exists, it provides the link between plot items and `LegendIconWidget`.
- Update of the `simplewidget` example
- Module attributes was set private
- Accesses (from `LegendModel`) like `linestyle in LegendIconWidget.NoLineStyle` was replaced by `isEmptySymbol` and `isEmptyLineStyle`
- Automatically call `update` when an attribute was changed, instead of forcing the user to do so
- Some unittest or code coverage?
- line
- symbol
- line + symbol
- colormap
- symbol using colormap
- …
=> Improve legend widget

silx/utils/test/test_testutils.py, silx/utils/testutils.py
This PR improves few things of the `TestLogging `
- Add unittests
- A single exception to summarize all the problems
- Add function for early break of active loops (it could be improved, but it is good enough for valid usecase)
- Create a `get_count_by_level` method
- Support `with as` syntax
I also break the attribute `count_by_level`, to rename it as `expected_count_by_level`. 
A `count_by_level` could be re-defined for compatibility, but i expect no body was using it. Let me know what you prefer.
=> Improve TestLogging API

silx/gui/_glutils/OpenGLWidget.py
Related to #2797 
The problem appears with PyQt 5.9.2 on the anaconda installation of lid21nano.
This patch allows to initialize the widget by clearing the previous errors.
=> [OpenGL] Clear errors prior to initialize widget

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/items/core.py, silx/gui/plot/items/roi.py
This PR is a follow-up of PR #2684 to make ROI base class a QObject and provide a `sigItemChanged` signal as plot items.
=> Make ROI inherit from QObject + provide sigItemChanged

setup.py
This PR proposes to add `Cython` to `setup_requires` and to remove the `--no-cython` build option (and the `WITH_CYTHON` environment variable).
This is following discussion in #2793 and would prevent such issue at the expense of adding `Cython` as a build dependency.
I like the fact that it removes more than 100 lines of code... and probably more if we simplify the debian_src command.
What's you opinion? Is it a good idea?
=> Add Cython to setup_requires

silx/math/fft/basefft.py, silx/math/fft/fftw.py
This PR fixes a bug when using `silx.math.fft` with the FFTW backend, when we try to avoid memory copies.
=> [math] FFTW: bugfix + avoid copies when possible

silx/gui/hdf5/Hdf5Item.py
This PR adds makes `silx.gui.hdf5` and so `silx view` a bit more robust against malformed `NX_class` by making it case-insensitive.
No sure we want to go into this direction... but I encountered this case.
What do you think?
I'm fine to drop this.
=> Make reading NX_class from silx.gui.hdf5 a bit more robust to errors

silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py
This PR reworks the `matplotlib` rendering.
The way used in PR #2730 had some short-comings (e.g., see #2785 + when saving as image, the content was different from what the widget displayed...)
The idea here is to decouple the z order in `PlotWidget` from that in `matplotlib`.
Each matplotlib item is given a different z order (which order is set according to this order in the `PlotWidget`).
The drawback of this method it that items associated with left and right axes are no longer interleaved regarding z as matplotlib `Axes` are one on top of the other... but trying to avoid that (as in #2730) is quite tricky and (as shown by the issues it implies) not really robust.
closes #2785
=> Rework matplotlib backend rendering (and picking)

silx/gui/plot/ScatterView.py, silx/gui/plot/tools/profile/_BaseProfileToolBar.py
This PR fixes an issue in the `ScatterView` with the profile tool.
Initially raised here: https://github.com/silx-kit/silx/pull/2810#issuecomment-562220610
It was not possible to start a profile while hovering a point of the scatter plot (this was due to the scatter item being selectable and so taking focus of the mouse press event).
The scatter item is no longer selectable and so no longer takes the focus of mouse events
=> Fix scatterview profile interaction
