silx-kit/silx

setup.py
silx/io/setup.py
silx/io/specfile/specfile.c

Issue #13: Function ``fake_cythonize`` rejected ``.c`` files at the same time as it was renaming ``*.pyx`` into ``*.c``. (found by @kif)

Fix issue #13: C source files not included in extension

---

setup.py

Fix #15 : WITH_CYTHON environment variable check

---

silx/math/test/test_histogramnd_vs_np.py

#29 
Printing the RNG state in case of failure.
Forced some sums to float64.

Fix for #29

---

README.rst
copyright

Update readme and copyright

---

CHANGELOG.rst
silx/gui/plot/PlotActions.py
silx/third_party/EdfFile.py
silx/third_party/TiffIO.py

[Plot] Add save to TIFF and EDF + add changelog

---

doc/source/modules/io.rst
silx/io/configdict.py

configdict documentation was missing in PR #52

Documentation of configdict

---

silx/io/configdict.py
silx/io/test/test_dictdump.py

ConfigDict bug fix 

---

doc/source/install.rst

supported python versions include 3.4

Minor fix to installation doc

---

bootstrap.py
silx/image/bilinear.c
silx/image/bilinear.pyx
silx/image/setup.py
silx/image/test/__init__.py
silx/image/test/test_bilinear.py
silx/test/__init__.py

This pull-request add a line-profile with associated tests.

43 bilinear

---

README.rst
silx/gui/plot/LegendSelector.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotTools.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/PlotWindow.py

Closes #60 
Closes #61 
Closes #62

[Plot] Add snap to curve with crosshair cursor + fix a few issues

---

doc/source/install.rst
doc/source/modules/gui/index.rst
doc/source/modules/io/index.rst
setup.py

Moved check_cython() & check_openmp() before configuration()
Minor documentation correction.

Setting environment variables in setup.py

---

doc/source/index.rst
doc/source/modules/image/bilinear.rst
doc/source/modules/image/index.rst
silx/image/bilinear.c
silx/image/bilinear.pyx
silx/image/test/test_bilinear.py

- Add support for line profile of even width
- Add bilinear module to sphinx doc

Update line profile of bilinear module

---

package/debian/rules

disable Qt testing while packaging

---

doc/source/install.rst

relies on edna-site nightly builds

update doc about installation on debian 

---

doc/source/modules/math/fit.rst
doc/source/modules/math/fit/leastsq.rst
doc/source/modules/math/index.rst
silx/math/fit/__init__.py
silx/math/fit/leastsq.py
silx/math/setup.py
silx/math/test/test_fit.py

- new `silx.math.fit` package created
- previous `silx.math.fit` module moved to  `silx.math.fit.leastsq`
- in `__init__` of new package `silx.math.fit`, import:
- `leastsq` function
- `chisq_alpha_beta` function
- constraint codes constants `CFREE, CPOSITIVE, CQUOTED, CFIXED, CFACTOR, CDELTA, CSUM ,CIGNORED`
- minor PEP8 changes (highlighted by my editor)

refactoring of silx.math.fit

---

silx/gui/plot/Plot.py
silx/gui/plot/test/testPlotWidget.py

[Plot] Fix curve negative values lost when toggle log axis

---

silx/gui/plot/Interaction.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotInteraction.py

When drawing a polygon, this adds the possibility to end drawing the polygon by clicking with the left button near the first point of the polygon.
It is still possible to end drawing with a right click.

[Plot] Update polygon interaction

---

silx/gui/plot/PlotWindow.py

Closes #97 
Move option button and position from toolbar to central widget

[Plot] PyMca-like PlotWindow option button and position layout

---

silx/gui/plot/BackendBase.py
silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotTools.py

Related to #84
- Disable profile actions when no image is displayed
- Update profile when image is updated
- Fix support of image with origin and scale

[Plot] Profile tool update

---

doc/source/conf.py

Use 'default' theme

---

README.rst

Replace edna-site by silx in address.

Get rid of edna-site reference.

---

silx/gui/testutils.py

This allows to build the doc even without X server

Lazy init of QApplication and QWidget in GUI test class

---

silx/gui/plot/PlotActions.py

grabWidget is not available under Qt5.

---

doc/source/install.rst

a bit of documentation  about this bug...
I am not sure we should fix it from inside python ...

134 bug osx

---

doc/source/modules/gui/plot/getting_started.rst
silx/gui/plot/Plot.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testPlotWidget.py

Addresses the following issues :
- Doc typo: #153,
- Plot2D: add profile toolbar #138, add image value in position information bar #151
- Plot addCurve/addImage xlabel/ylabel default behavior change: #139

[Plot] Fixes

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testMaskToolsWidget.py

- Rename getMask and resetMask to getSelectionMask and resetSelectionMask
- Add setSelectionMask
- Add get/setSelectionMask to PlotWindow (and so Plot2D)

[Plot] Update mask tool API

---

silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/Colors.py
silx/gui/plot/ImageView.py
silx/gui/plot/PlotActions.py
silx/gui/plot/PlotTools.py

- Add profile toolbar to ImageView
- Fix a bug in valueChanged signal with non default scale or origin

[Plot] Fix ImageView bug + add profile tools

---

requirements-dev.txt

This is a proposal to add a file with development requirements.
This documents needed packages for dev beyond the compiler.

Add development requirement file

---

setup.py
silx/gui/qt.py

Add build_doc even if sphinx is not installed

---

silx/math/test/histo_benchmarks.py
silx/math/test/test_histogramnd_error.py
silx/math/test/test_histogramnd_vs_np.py

Using randint instead of random_integers.

---

ci/appveyor.yml

Make sure using build wheel (disable all other sources)
Add use of appveyor proxy

[CI] Update appveyor

---

.travis.yml
silx/gui/plot/test/testPlotTools.py
silx/gui/testutils.py
silx/testutils.py

This PR adds support of GUI tests on Linux with Python3.5 and PyQt5 by using X virtual framebuffer and PyQt5 `manylinux` wheel.
Related to #176

[CI] Travis update

---

bootstrap.py

Clean up bootstrap

---

silx/io/test/test_octaveh5.py

Clean. Remove the h5py dependancy

---

silx/test/__init__.py
silx/utils/setup.py
silx/utils/test/__init__.py
silx/utils/test/test_weakref.py
silx/utils/weakref.py

- Create silx.utils module
- Create a WeakMethod (class with callback)
- Create a WeakList

Feature weakref module

---

silx/gui/qt.py

Same fix as `Property` or `Signal`

Add Slot to PyQt

---

silx/utils/test/test_weakref.py
silx/utils/weakref.py

- Fix sort
- Add reversed
- Add get/set/del slice
- Add str/repr

Fix weaklist

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/PlotActions.py
silx/gui/plot/PlotEvents.py
silx/gui/plot/PlotInteraction.py
silx/gui/plot/PlotWidget.py

- Fix issue with middle click during drag
- Fix issue with saving curve without labels, Closes #223 
- Fix issues raised by flake8

Plot fixes

---

examples/simplewidget.py
silx/gui/setup.py
silx/gui/widgets/ThreadPoolPushButton.py

- Some fixes on python packages
- Create ThreadPool PushButton
- Update simpleexamples with it

Create thread pool push button

---

silx/gui/plot/PlotActions.py

Fix arrow-keys icon name typo

---

silx/gui/plot/BackendMatplotlib.py

Using reshape to get a reshaped view without modifying the input data.

---

silx/gui/plot/PlotInteraction.py

Fix small bug in the polygon drawing state machine.

---

silx/gui/fit/FitWidget.py
silx/gui/fit/FitWidgets.py
silx/gui/plot/PlotActions.py
silx/math/fit/fittheories.py

Closes #241 (move AutoFwhm checkbox to from function selector to configuration dialog) 
Partially addresses #249  (warning and curve labels)

Fit improvements

---

silx/gui/plot/Plot.py
silx/gui/plot/test/testPlot.py

Issue : #252
I couldn't find any method to get the actual data range (not the "view" or axis range).
Tests not written yet (nor the issue report), waiting for comments (or for someone to tell me that this feature is already available).

[Plot] Method to retrieve the displayed data range.

---

MANIFEST.in
doc/source/Tutorials/Sift/sift.rst
doc/source/Tutorials/specfile_to_hdf5.rst
doc/source/tutorials.rst

So far this tutorial contains explanations about SPEC data files and about how they are exposed in `spech5`, and minimalistic code examples.

Tutorial on spech5 and spectoh5

---

silx/gui/hdf5/Hdf5TreeView.py

- Using CopyAction make it working on Windows

Fix external file drop on Hdf5TreeView

---

silx/image/sift/plan.py

try to allow plan work with limited workgroup size

---

silx/gui/plot/PlotInteraction.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testPlotInteraction.py

Fix some issues with drawing polygons:
- Some click were not creating new points (bug in testing if close to previous point)
- There were issues when dragging the mouse while closing the polygon

[Plot] Fix polygon interaction

---

silx/gui/hdf5/Hdf5TreeView.py

- It was only working with 0 or 1 proxies

Fix findHdf5TreeModel

---

silx/image/sift/test/test_transform.py

Fix simple skipUnless missing

---

silx/gui/plot/Plot.py

Fixed typo : rezetZoom -> resetzoom.

---

run_tests.py
silx/io/setup.py

This issue may be solved automagically with numpy 1.12. I have not been able to check it (other bug appeared)

issue 310 py3 osx unicode

---

run_tests.py
silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/Plot.py
silx/gui/plot/_utils.py

311 memprofile

---

silx/io/octaveh5.py

mainly pep8

---

silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/test/testPlotWidget.py

Closes #347 : Bug with aspect ratio + add some tests for it

[Plot] Fix aspectratio

---

silx/gui/test/__init__.py
silx/gui/widgets/setup.py
silx/gui/widgets/test/__init__.py
silx/gui/widgets/test/test_threadpoolpushbutton.py

There is an issue on our laptop relative to the behaviour or QThreadPool.
It still must be fixed, based on this tests.

Test before fixing issue on out Mac OS laptop

---

silx/gui/plot/PlotToolButtons.py

modified tipo error ration

---

examples/fftPlotAction.py
examples/hdf5widget.py
examples/imageview.py
examples/shiftPlotAction.py
examples/spectoh5.py
silx/gui/_pyside_dynamic.py
silx/gui/fit/FitConfig.py
silx/gui/fit/FitWidget.py
silx/gui/fit/FitWidgets.py
silx/gui/fit/Parameters.py
silx/gui/fit/test/testFitConfig.py
silx/gui/hdf5/Hdf5TreeModel.py
silx/gui/plot/ImageView.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotActions.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testColors.py
silx/gui/plot/test/testLegendSelector.py
silx/gui/plot/test/testPlot.py
silx/gui/plot/test/testPlotInteraction.py
silx/gui/plot/test/testPlotTools.py
silx/gui/qt.py
silx/gui/testutils.py
silx/gui/widgets/ThreadPoolPushButton.py
silx/gui/widgets/test/test_threadpoolpushbutton.py
silx/sx/_plot.py
silx/test/test_sx.py

- Filter and test logging message (close #352)
- Ignore unreleased error widgets if the test fail
- Fix bunch of warnings (unused var, lib, space, trailing space...)
- Refactoring main function from ImageView as an example

Code quality

---

run_tests.py
silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotInteraction.py

This PR display the shape preview of the pensil on the mask tool
There is efficiency problems with the pencil. That's why it is in WIP. It must be investigated.

Display pencil preview in mask tool

---

silx/gui/plot/Colors.py
silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/PlotTools.py

- Use QLabel for status bar
- Update default mack color according to colormap
- Rework doMask to take care of realtime changes (fix #364)
- Avoid to draw 2 times updateDisk at the same place

Improve masking tool

---

silx/math/fit/fitmanager.py
silx/math/fit/leastsq.py

Closes #367 (at least for the time being)

Do not free fixed parameters when calculating covariance matrix.

---

silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/_matplotlib.py

Cherry-picked from https://github.com/silx-kit/silx/pull/369
- 389bb0b
- 4ad741c
- 744c196
Plus typo

Feature matplotlib init

---

silx/io/octaveh5.py

Modification to be able to read string when they are stored as numpy.ndarray of chars (yes It sound like it could happen)

Fix reading strings

---

silx/gui/plot/BackendMatplotlib.py

[Plot] Fix concatenation of a tuple with a list.

---

silx/io/spectoh5.py
silx/math/fit/fitmanager.py
silx/math/fit/fittheory.py

[fitmanager] fix bug in addtheory

---

silx/gui/hdf5/Hdf5HeaderView.py

Fix hdf5 set section

---

doc/source/install.rst
doc/source/virtualenv.rst

This is a PR to add a  documentation page for installing silx in a virtualenv, for users with no sudo privileges.
It addresses #378  
The section about PyQt is still work in progress. We probably need to create our own PyQt manylinux wheels for python 2.7 and python 3.4.
Regarding the rest of the paragraphs, do we need more details?

[WIP][doc] installing silx in a virtualenv

---

silx/gui/plot/Plot.py
silx/gui/plot/test/testPlot.py

[plot] Add getAllImages method and a simple test for it

---

silx/io/spectoh5.py

This is a attempt for a fix, it still smells. I believe a class would be better on.

attempt to address issue #409

---

silx/io/specfile/specfile.c
silx/io/specfile/specfile.pyx
silx/io/test/test_spech5.py

Test for presence of #S or #F at the beginning of the file before opening the file.
Closes #424

[specfile] prevent segfault when file is not a spec file

---

silx/image/sift/test/test_image.py
silx/image/sift/test/test_image_setup.py

[sift] skip tests depending on scipy, if not installed

---

.travis.yml
ci/appveyor.yml
run_tests.py
silx/gui/hdf5/test/test_hdf5.py

- Display test name before testing (with -v)
- Update CI to use -v instead of -m
- Try to fix random issue on tests of hdf5tree by using mkstemp instead of NamedTemporaryFile + closing h5file from the model

Improve tests

---

silx/sx/__init__.py

Not sure the NameError is still useful ?

catch import Error

---

MANIFEST.in
stdeb.cfg

debian7 configuration files.

---

silx/math/fit/test/test_filters.py
silx/testutils.py

3 functions to add random noise to synthetic data, for testing filters, smoothing, fitting...

[testutils] adding noise to synthetic data

---

silx/gui/widgets/ArrayTableWidget.py
silx/gui/widgets/FrameBrowser.py

Hi Pierre,
Let me know if it is working as you expect. I only try the Array, not the Frame

Use spacer instead of widget

---

silx/image/sift/plan.py

This PR implements an extra check when passing non-contiguous numpy.ndarray to a SIFT plan.

Fix data contiguity check in SIFT

---

silx/gui/test/utils.py
silx/gui/widgets/test/test_threadpoolpushbutton.py

It allows to check after execution the content of signal parameters

Create SignalListener to help testing Qt Signals

---

silx/gui/plot/PlotWindow.py

Only 2 changes
- The statusbar use a spacer (instead of 0)
- The option button is displayed "raised": no button border while the mouse is not over
- The option button display a little arrow "v", to show that there is a menu

Update plot1d statusbar

---

silx/gui/fit/FitConfig.py
silx/gui/fit/FitWidget.py
silx/math/fit/fittheories.py

[fit] autoscaling

---

examples/hdf5widget.py

This make the auto-generated data more interesting to visualize in the data viewer widget.
Closes #484

[DataViewer] Enhance hdf5widget.py example

---

README.rst
doc/source/install.rst

Links to external packages added to install.rst and README.rst..

Links to CentOS and Arch packages in doc

---

silx/gui/widgets/DataViewer.py
silx/gui/widgets/DataViewerSelector.py
silx/gui/widgets/DatabaseTableView.py
silx/gui/widgets/RecordTableView.py
silx/gui/widgets/test/test_dataviewer.py

RecordTableView allow to display
- Structured numpy arrays (https://docs.scipy.org/doc/numpy/user/basics.rec.html) which are also provided by HDF5
- And 1D numpy array as a vertical table
The file `compound_array.h5` from my `tmp 14 days` provides some examples of records

Use RecordTableView as view of DataViewer

---

examples/fftPlotAction.py
examples/hdf5widget.py
examples/imageview.py
examples/periodicTable.py
examples/shiftPlotAction.py
examples/simplewidget.py
examples/stackView.py
silx/gui/qt/_qt.py

Implement default exception hook

---

silx/io/spech5.py
silx/io/test/test_spech5.py

[spech5] handle scans with only mca 

---

examples/fftPlotAction.py

[examples] Correct missing import error.

---

silx/gui/plot/PlotWindow.py
silx/gui/plot/Profile.py
silx/gui/plot/StackView.py
silx/gui/plot/test/testPlotTools.py
silx/resources/__init__.py

Closes #501 (make plot API more Qt-like with getters for actions and dock widgets)

[Plot] PlotWindow API

---

silx/sx/__init__.py
silx/sx/_plot.py

- Add color, linestyle, linewidth and marker keywords to sx.plot, closes #511 
- Add a warning when sx is imported in a notebook: silx.gui not loaded, closes #426 
- Test sx with different (I)python with and without notebook, closes #482

Update sx package

---

silx/utils/array_like.py
silx/utils/test/test_array_like.py

Don't use `sys.maxint`, as it is not available in python 3.

[DatasetView] Fix python 3 incompatibility, add test

---

silx/gui/plot/BackendMatplotlib.py

Prevent matplotlib 2.0.0 deprecation warning.

[plot] Get rid of matplotlib 2.0 deprecation warning.

---

silx/gui/data/DataViewer.py
silx/gui/data/DataViewerFrame.py
silx/gui/data/DataViewerSelector.py
silx/gui/data/NumpyAxesSelector.py
silx/gui/data/RecordTableView.py
silx/gui/data/test/test_dataviewer.py
silx/gui/hdf5/Hdf5Item.py
silx/gui/plot/StackView.py
silx/gui/qt/_pyside_missing.py
silx/gui/qt/_qt.py
silx/gui/widgets/FrameBrowser.py

Fix a bunch of issues concerning the dataviewer

Improve data viewer

---

silx/gui/data/ArrayTableWidget.py
silx/gui/data/DataViewerFrame.py
silx/gui/data/test/test_numpyaxesselector.py
silx/gui/fit/Parameters.py
silx/gui/plot/BackendMatplotlib.py
silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/Plot.py
silx/gui/plot/PlotTools.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testMaskToolsWidget.py
silx/gui/plot/test/testPlot.py
silx/gui/widgets/FrameBrowser.py
silx/resources/__init__.py
silx/test/__init__.py
silx/test/test_sx.py

This PR:
- Fixes issues with negative scales of images in the plot
- Fixes issues with image with negative scale in the mask, closes #478 
- Fixes issues with image with negative scale in the Plot2D displayed data value
- Adds a button to mask NaN and infinity values, closes #388

[plot] addImage negative scale and mask tool fixes

---

silx/io/__init__.py
silx/io/test/test_fabioh5.py

It avoid str compare problem between Python2 and Python3

Fix fabioh5 tests

---

doc/source/Tutorials/array_widget.rst
silx/gui/data/ArrayTableWidget.py

Widget moved to `gui.data`. Close #563

[ArrayTableWidget] Fix import in documentation

---

silx/gui/plot/ImageView.py
silx/gui/qt/__init__.py

Fix a bug in the scaling of ImageView horizontal histogram when scales are set.
closes #557

[plot] Fix ImageView image scale bug

---

silx/gui/plot/Profile.py
silx/gui/plot/StackView.py

Stackview behavior improvement

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/test/testMaskToolsWidget.py

Here is the implementation of 
- I rework the load function to use more exception instead of returning messages
- Let me know what you think, i am not very satisfy
- And i implement the msk loading using fabio as an optional dependency

Support msk as input mask

---

silx/gui/plot/PlotInteraction.py

This PR adds the possibility to start drawing the zoom area on a selectable element of the plot (like a curve) closes #430

[plot] Fix zoom interaction

---

silx/math/fit/leastsq.py

[fit] Add missing argument.

---

doc/source/modules/gui/data/index.rst
doc/source/modules/gui/data/textformatter.rst
silx/gui/data/ArrayTableModel.py
silx/gui/data/ArrayTableWidget.py
silx/gui/data/DataViewer.py
silx/gui/data/Hdf5TableModel.py
silx/gui/data/RecordTableView.py
silx/gui/data/TextFormatter.py
silx/gui/data/test/__init__.py
silx/gui/data/test/test_textformatter.py

- Clean up get/set format to use only TextFormatter
- TextFormatter provides signal on format changed
- Update models when the format changed
- Plus few unittest for TextFormatter
It should help to fix #565. There is way way to provide a common widget to custom different widgets at a same time.

Improve text formatter

---

silx/image/sift/match.py

- Fix warning on docstring
- Few other typo

[doc] Typo on sift module

---

examples/hdf5widget.py
silx/gui/data/DataViewer.py

It is useful to display extra informations from HDF5Tree
Basically local name (and not the name using path from external h5 file)

Support h5node to dataviewer

---

silx/gui/data/DataViewer.py
silx/gui/data/DataViewerFrame.py
silx/gui/data/DataViewerSelector.py
silx/gui/data/RecordTableView.py
silx/gui/data/TextFormatter.py
silx/gui/data/test/test_dataviewer.py

Clean up the DataViewer API
- It would be more easy to custom the viewer to provide custom view
- RawView is now a real view which select one of ArrayView, RecordView, ScalarView (it allows to remove SUPPORTED_IF_NOTHING_BETTER)
- Numpy scalar records are now displayed using RecordView
- Fix regression, h5 dataset are displayed using RawView (it was broken by a previous commit)

Import DataViewer

---

examples/hdf5widget.py
silx/gui/data/DataViewer.py
silx/gui/data/Hdf5TableModel.py
silx/gui/data/RecordTableView.py

Few other fixes
- Support CTRL-C where it is useful
- Fix and improve display with dataset using external compression plugins
- Do not propose Plot3D when 3d data have a dimension =1

Improve DataViewer

---

ci/appveyor.yml

[CI] Install fabio for appveyor tests

---

silx/gui/fit/FitWidget.py
silx/gui/plot/PlotActions.py

[FitAction] remove fitted curve prior to fitting the same data again

---

silx/gui/plot/Plot.py

Fix histogram values when moving to log scale. Histogram wasn't record in the params dictionnary

Fix pixel intensities histogram

---

silx/gui/plot/PlotActions.py

Fix PlotAction parent

---

silx/gui/plot/Profile.py

Cherry-picks of https://github.com/silx-kit/silx/pull/625
+ Plus few typo and comments

[ProfileToolBar] bugfix for eventfilter missing plot attribute (cleaned)

---

silx/io/spech5.py
silx/io/spectoh5.py

Improve handling of soft links when converting spec file to hdf5 file. This is to prepare for a unique spech5 + fabioh5 to hdf5 converter (#609).

[spectoh5] Improve handling of links

---

silx/gui/plot/Plot.py
silx/gui/plot/PlotActions.py

- Avoid to display warning message if it is not expected
- Fix axes labels
- Fix window histogram parent
- Fix histogram x-normalization according to colormap of the source image

Improve plot histogram

---

silx/gui/plot/PlotWindow.py
silx/gui/plot/Profile.py
silx/utils/decorators.py

Improve deprecated decorator

---

examples/viewer3DVolume.py
silx/gui/plot3d/Plot3DWidget.py
silx/gui/plot3d/SFViewParamTree.py
silx/gui/plot3d/ScalarFieldView.py
silx/gui/plot3d/glutils/Texture.py
silx/gui/plot3d/scene/cutplane.py
silx/gui/plot3d/scene/interaction.py
silx/gui/plot3d/scene/primitives.py

This PR updates ScalarFieldView and associated param tree widgets:
- Fix setLevel when min == max, closes #612 
- Fix pan of object/cut plane when zoom is closed + use picked position as center for rotation interaction when over an object, closes #572 
- Add an option to change cut plane interpolation between nearest and linear, closes #561

[plot3d] Add nearest/linear interpolation option to cut plane + fixes

---

silx/gui/plot/PlotActions.py
silx/gui/plot/PlotTools.py

This probably closes #644 . 
Some testing and expert review is still needed to ensure the modification from pixels to data does not introduce side effects.

[PositionInfo] Crosshair snap: switch back to data coordinates

---

silx/gui/plot/StackView.py

useful for exploring 3D stacks

replace=False preserve mask in StackView when updating frame number

---

silx/gui/plot/PlotWindow.py
silx/math/medianfilter/medianfilter.cpp
silx/math/medianfilter/medianfilter.pyx

Add tabbed widget

---

examples/stackView.py
silx/gui/plot/Profile.py
silx/gui/plot/StackView.py

Probably an undetected conflict.

Fix bug/typo in StackView

---

silx/gui/console.py
silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/LegendSelector.py
silx/gui/plot/MaskToolsWidget.py

[plot] raise on show dock widgets

---

doc/source/install.rst

Add fabio, pyopencl and Mako as dependencies + rename Mac OS X to MacOS

[doc] Update installation instructions

---

silx/gui/plot/Colors.py
silx/gui/plot/PlotActions.py
silx/gui/plot/test/testColors.py

This PR adds a function `applyColormapToData` which convert a numpy array to an array of RGBA colors by using a colormap. Data can be of any dimension.

[plot] Function to convert data to colors with a colormap

---

silx/gui/plot/AlphaSlider.py
silx/gui/plot/Plot.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/items/__init__.py
silx/gui/plot/items/core.py
silx/gui/plot/items/curve.py
silx/gui/plot/items/image.py
silx/gui/plot/items/scatter.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testAlphaSlider.py
silx/gui/plot/test/testPlot.py

[plot] Scatter object

---

requirements.txt

Relative to https://github.com/silx-kit/silx/issues/598

Specify a fabio version (close #598)

---

silx/sx/_plot.py

Make sx.plot style match the longest color name possible

---

silx/io/fabioh5.py
silx/io/test/test_fabioh5.py

Relative to https://github.com/silx-kit/silx/issues/680

fabioh5: Fix float precision from headers

---

doc/source/modules/gui/plot/dev.rst
doc/source/modules/gui/plot3d/_font.rst
doc/source/modules/gui/plot3d/dev.rst
doc/source/modules/gui/plot3d/glutils.rst
doc/source/modules/gui/plot3d/utils.rst
doc/source/modules/math/medianfilter.rst

Some rst files of the doc where not updated in PR #692, this PR synchronize the rst files with current project structure + rename medianfilter to medfilt2d.
Closes #724

Fix documentation

---

doc/source/virtualenv.rst

minor improvement of venv doc

---

silx/io/spech5.py
silx/io/test/test_spech5.py

[spech5] Support UB matrix

---

run_tests.py

Closes #308 (maybe. To be tested on linux)

[coverage] Add an exclusion for plugin modules imported during tests

---

silx/app/view.py
silx/gui/data/DataViews.py
silx/gui/data/test/test_dataviewer.py

- create menus: open, exit, about
- update viewer on selection changed
- always use raw mode if it is not requested (it is an update of the DataViewer behaviour)

Improve viewer script

---

silx/gui/_glutils/font.py
silx/gui/plot3d/Plot3DWidget.py
silx/gui/plot3d/SFViewParamTree.py
silx/gui/plot3d/scene/text.py
silx/gui/plot3d/scene/window.py

This PR:
- Change shape to size in parameter tree to match order of offset and scale (closes #694)
- Fix starting on HighDPI screen and moving window to second screen makes mouse interaction only working in the corner of the window (see #669) + display text with a consistent size

[plot3d] Some fixes

---

silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/PlotWindow.py

Add documentation for the API to get the ROI information

---

silx/io/fabioh5.py
silx/io/spech5.py
silx/io/test/test_fabioh5.py
silx/io/test/test_spech5.py

Update to NeXus conventions.

---

silx/gui/data/DataViews.py
silx/gui/data/test/test_dataviewer.py

This implementation only filter data with numpy.absolute in case of complex.
The toolbar do not display the raw data, but the filtered result
close #775

Support complex for curve, image, cube and stack

---

setup.py

- The `Build` class allow to catch options from the build command
- The `BuildExt` class take care of the cytonization and filter flags for OpenMP
- No more global
- No more command-line parsing and hack of sys.args
- No more process outside the setup() function
- Command-line argument have the priority on env variables
- Env variables are parsed (0/1/true/false... else are ignored)
```
python setup.py build --no-cython --no-openmp
python setup.py build --force-cython --openmp
export FORCE_CYTHON=yes
export WITH_CYTHON=True
export WITH_OPENMP=1
python setup.py build
export FORCE_CYTHON=no
export WITH_CYTHON=False
export WITH_OPENMP=0
python setup.py build
```
Limitation: Build options must be after `build` argument.

Rework setup.py for cython and openmp

---

silx/io/spech5.py
silx/io/test/test_spech5.py

[spech5] substitute / with % in motor names and detector labels

---

silx/opencl/common.py

Add `mf` fallback removed in PR #815.

[opencl] Add fallback mf class

---

silx/image/test/test_medianfilter.py
silx/math/__init__.py
silx/opencl/test/test_medfilt.py

Two of the tests were relying on scipy.

Remove median filters hard scipy dependency

---

silx/gui/plot/test/testPlot.py

Minimalistic test of the old API.

---

bootstrap.py

- Importing a module already execute the code

[bootstrap] Log beginning before import_module

---

copyright

Update copyright file for colormaps

---

silx/resources/__init__.py
silx/test/test_resources.py

os.environ.get(None) fails in python3 ...
This enforces the creation of a default value

close #835

---

silx/gui/plot/PlotActions.py

Fix bug in save image as PNG

---

silx/gui/plot/items/histogram.py

Flag histogram as updated when data have changed

---

setup.py
silx/gui/plot/StackView.py
silx/gui/plot/test/testStackView.py

[StackView] Add a setTitleCallback method to customize title

---

package/debian8/control
package/debian9/control
silx/third_party/_local/enum.py
silx/third_party/enum.py

The `enum` package will be used by PR #726.

Add backport of python3.4 enum package in third_party

---

silx/gui/plot/Plot.py
silx/gui/plot/items/histogram.py

This PR fixes issues with changing axes scale to log which was not filtering <=0 values (e.g., for histograms).
Closes #874

[Plot] Fix switching to log scale

---

silx/gui/plot/Plot.py
silx/gui/plot/actions/io.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/glutils/PlotImageFile.py

replace PR #877 , fix conflicts.

[Plot] Fix SaveAction with OpenGL backend

---

silx/io/fabioh5.py
silx/io/test/test_fabioh5.py

- Data from single frame images does not return anymore an extra dim (it returns an image instead of a list of a single image: a cube)
- Fix frame containing a cube
- Fix concatenation of heterogeneous frames
Closes #881

Fix cube and heterogeneous frames

---

silx/app/view.py

Add nx file extensions to the open dialog

---

silx/gui/_glutils/font.py
silx/gui/plot/backends/glutils/GLText.py

- closes #790
- Avoids useless calls to rasterText in OpenGL plot backend

Fix macos OpenGL widgets text display

---

silx/io/spech5.py
silx/io/test/test_spech5.py

Fixed bugs introduced in #859. This PR should close  #858, but I'm unable to test this patch at the moment.

[spech5] handling open files

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/PlotTools.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/items/__init__.py
silx/gui/plot/items/image.py

- Create an item to store masks in the plot: `MaskImageData`
- Use that information to display right data under the mouse cursor on the status bar
- When a pixel is masked the status bar displays `0.256, Masked`, instread of just the value of the image `0.256`
Closes #620 
Closes #848

[plot] Create mask image item

---

silx/io/fabioh5.py
silx/io/spech5.py
silx/io/test/test_fabioh5.py
silx/io/test/test_spech5.py

The hdf5tree view was not anymore working when using EDF files
Closes #902

Fix getlink API

---

doc/source/modules/gui/plot/plotwidget.rst
silx/gui/plot/ImageView.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/StackView.py
silx/gui/plot/__init__.py
silx/gui/plot/actions/fit.py
silx/gui/plot/items/__init__.py

Fix documentation references to defunct class Plot.
Document item getters.
Fix a broken import in fit action.

Plot documentation

---

silx/math/combo/combo.c
silx/math/combo/combo.pyx
silx/math/combo/isnan.h
silx/math/test/test_combo.py

This would be needed for PR #898 to improve colormap autoscale when there is inf in the image data.

Add finite argument to min_max

---

.travis.yml
ci/appveyor.yml
run_tests.py

run_tests: Replace -i,--insource option by --installed

---

ci/appveyor.yml

Force PyQt5==5.8.2 to see if tests pass.

[debugging AppVeyor] Force PyQt5==5.8.2

---

examples/plotItemsSelector.py
silx/gui/plot/ItemsSelectionDialog.py
silx/gui/plot/actions/fit.py

Closes #854 and implements `ItemsSelectionDialog`
In case there is a single fitable item (single curve, single histo, active curve), the action selects it.
In ambiguous cases, a dialog is shown to prompt the user to select which curve or which histogram is to be fitted.

[FitAction] Handle histograms and ambiguous cases

---

silx/opencl/medfilt.py
silx/opencl/sift/test/test_keypoints.py
silx/opencl/sift/test/test_matching.py
silx/opencl/sift/test/test_transform.py
silx/resources/opencl/sift/transform.cl

This PR aims at addressing #944 and #943. 
It also makes the fix proposed in #945.

[sift] transform module and test

---

silx/opencl/medfilt.py

This PR fixes a clumsy "Unfix" which was canceling #942

Reset kernel size in median filter

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/items/core.py

Change management of plot items to update asynchronously to respect update order.
Also add support of dict in item `setColormap`

[plot] Fix plot order

---

doc/source/modules/gui/plot/items.rst
silx/gui/plot/items/__init__.py
silx/gui/plot/items/axis.py
silx/gui/plot/items/core.py
silx/gui/plot/items/curve.py
silx/gui/plot/items/histogram.py
silx/gui/plot/items/image.py
silx/gui/plot/items/marker.py
silx/gui/plot/items/scatter.py
silx/gui/plot/items/shape.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testItem.py
silx/gui/test/utils.py

This PR adds a per-item signal notifying changes of plot items with doc and tests.
It DOES NOT use those signals in silx.
Closes #689

[plot] Add sigItemChanged to plot items

---

silx/opencl/backprojection.py
silx/opencl/test/test_backprojection.py

This PR adds another bug fix in the Backprojection class, and adds a unit test to ensure that multi-slice reconstruction goes smoothly.

FBP: Bugfixes and tests

---

silx/gui/plot/PlotWidget.py

This PR Fix colorbar synchronisation when colormap is changed from colormap dialog (or set through image item setColormap).
Closes #966 and closes #889 (last 2 remaining points).

[plot] Forward item's sigItemChanged to PlotWidget.sigActiveItemChanged

---

examples/viewer3DVolume.py
silx/gui/data/DataViews.py
silx/gui/plot3d/SFViewParamTree.py
silx/gui/plot3d/ScalarFieldView.py
silx/gui/plot3d/scene/primitives.py
silx/gui/plot3d/test/testScalarFieldView.py

- Add support of data sets with NaN and/or inf.
- Add some tests for it + add parameter tree to the test
- Update dummy data set in plot3d example.
Closes #972

[plot3d] Add support of not finite data

---

README.rst

This isn't ready yet, the package hasn't been accepted yet, but it should be soon.

WIP: Install via conda

---

README.rst

Changing release documentation link to www.silx.org

[README] Update documentation links

---

copyright
setup.py
silx/io/specfile/include/Lists.h
silx/io/specfile/include/SpecFile.h
silx/io/specfile/include/SpecFileP.h
silx/io/specfile/include/locale_management.h
silx/io/specfile/src/locale_management.c
silx/io/specfile/src/sfdata.c
silx/io/specfile/src/sfheader.c
silx/io/specfile/src/sfindex.c
silx/io/specfile/src/sfinit.c
silx/io/specfile/src/sflabel.c
silx/io/specfile/src/sflists.c
silx/io/specfile/src/sfmca.c
silx/io/specfile/src/sftools.c
silx/io/specfile/src/sfwrite.c

Specfile license

---

LICENSE
MANIFEST.in

Closes #843
Please feel free to improve the text. Probably #990 needs to be approved first.

Add LICENSE file.

---

silx/opencl/common.py
silx/opencl/sift/alignment.py
silx/opencl/sift/match.py
silx/opencl/sift/plan.py

[opencl] Stop the process if no device found

---

examples/syncaxis.py
silx/gui/plot/items/axis.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testUtilsAxis.py
silx/gui/plot/utils/__init__.py
silx/gui/plot/utils/axis.py

[plot] Sync axes

---

silx/gui/plot/LegendSelector.py

Based on https://github.com/silx-kit/silx/pull/1025 to rebase working CI

Highlight legend of active curve (2)

---

silx/io/specfile.c
silx/io/specfile.pyx

Typo on specfile

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/test/testPlotWidget.py

- Implemented on the Matplotlib backend
- Not yet implemented on the OpenGL backend
Closes #631

Add setAxesDisplayed to the plot

---

silx/gui/plot/ImageView.py

`axis.isInverted(inverted)` --> `axis.setInverted(inverted)`

[ImageView] Typo causing bug

---

silx/gui/plot/PlotInteraction.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/shape.py

Cherry-pick of common fixes from https://github.com/silx-kit/silx/pull/726
It was accepted by @t20100

Normalize backend picking

---

ci/appveyor.yml

- while there is a problem with appveyor

Do not test the GUI on Appveyor

---

examples/customHdf5TreeModel.py
silx/gui/hdf5/Hdf5Item.py

Example to custom Hdf5Tree model

---

silx/gui/plot/_BaseMaskToolsWidget.py

Replace zoom button in drawing tools by PanModeAction

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/backends/glutils/GLPlotFrame.py

Implement setAxesDisplayed for plot OpenGL backend

---

silx/opencl/setup.py
silx/opencl/test/__init__.py

Patch from Frederic-Emanuel Picca from Soleil.
Closes #1014

[debian] Be able to remove sift from the library

---

ci/close_popup.py

Relative to this compilation https://travis-ci.org/silx-kit/silx/jobs/272055405#L7113

Improve popup detection in Mac OS X

---

silx/opencl/setup.py

sift was no more installed...
closes #1098

Fix setup.py for sift installation

---

doc/source/conf.py

Clean up html_static_path

---

silx/gui/plot/StackView.py
silx/io/utils.py

[StackView] Fix bug when h5py is missing

---

silx/io/commonh5.py
silx/io/test/test_spech5.py

[test_spech5] remove wrong test_logging decorator

---

silx/utils/deprecation.py
silx/utils/test/test_deprecation.py

- Display the right backtrace
- Log a single time but for each specific locations
Closes #1110

Fix deprecation warnings

---

silx/app/convert.py

Interpret * under windows.

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/_BaseMaskToolsWidget.py

Warning : this bring to an API modification BaseMaskToolsDockWidget(self, parent=None, plot=None, name='Mask') -> BaseMaskToolsDockWidget(self, plot, parent=None, name='Mask')

[plot] assert plot not none on the _BaseMasktoolsWidget

---

silx/image/test/__init__.py
silx/image/test/test_tomography.py
silx/image/tomography.py

[image] add P. Paleo tomography functions

---

silx/app/view.py
silx/gui/plot/PlotInteraction.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/items/image.py

This PR makes a 4 bug fix that were needed for next release.
See per commit messages for the content.

[plot] Fixes for the plot and silx view

---

silx/math/combo.c
silx/math/combo.pyx

should /close #1146 
But they might have a less time consuming solution...

[fix] min_max big/little endian issue

---

silx/app/convert.py
silx/app/test/__init__.py
silx/app/test/test_convert.py
silx/app/test/test_view.py
silx/io/convert.py
silx/io/spech5.py
silx/test/__init__.py

[silx convert] unittests

---

silx/gui/data/DataViews.py
silx/gui/data/test/test_dataviewer.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/items/image.py
silx/gui/plot/test/testPlotWidget.py

This PR:
- Adds conversion of `complex` to absolute value in `PlotWidget` 2D image API, closes #1190
- Adds support of 2D boolean array in `silx view` and in `PlotWidget` API (conversion to `uint8`), closes #1177

[plot] Add support of boolean and complex images in PlotWidget

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/axis.py
silx/gui/plot/test/testPlotWidget.py

This PR emits `Axis.sigLimitsChanged` when a `PlotWidget` is resized.
closes  #911

[plot] Send sigLimitsChanged when resizing PlotWidget

---

silx/gui/data/RecordTableView.py

Fix the numpy.fields order

---

doc/source/modules/gui/plot/imageview.rst
doc/source/sample_code/index.rst
silx/gui/plot/ImageView.py
silx/gui/plot/backends/BackendMatplotlib.py

This PR update ImageView to support both dict and Colormap in setColormap method.
It also updates ImageView documentation and add a test file for ImageView that was missing.
Closes #1185

[ImageView] Fix support of dict/object Colormap

---

silx/app/view.py
silx/gui/plot/ColormapDialog.py
silx/gui/plot/ComplexImageView.py
silx/gui/plot/PlotTools.py
silx/gui/plot/_BaseMaskToolsWidget.py
silx/gui/plot3d/SFViewParamTree.py
silx/gui/widgets/FloatEdit.py
silx/gui/widgets/PrintGeometryDialog.py
silx/math/chistogramnd.pyx
silx/math/histogram.py

- Force C locale from `silx view`
- Create a simple `FloatEdit` widget (it shoul be improved for a better feedback)
- Fix many tools using `FloatEdit`
Closes #1200

Fix float widget according to locale

---

silx/io/test/test_utils.py

Fabio do not release bad files.
This fix is a workaround.

Fix unittest on silx.io

---

silx/gui/data/DataViewer.py
silx/gui/data/DataViews.py

[silx view] Fix empty shape and interpretations

---

silx/gui/data/DataViews.py

Histogram is a very useful tool.
This PR enable it for 2D images and complex.
Closes #1204

[silx view] Enable histogram for image views

---

silx/gui/plot/ImageView.py
silx/gui/plot/Profile.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testImageView.py

This PR adds some tests for `ImageView`.
It has some issues with matplotlib 2.1.0rc1 on macOS python2.7, PyQt4 where QWidget recursive repaint and Cocoa errors occurs.

[plot] Add tests for Imageview

---

examples/viewer3DVolume.py

This PR avoids segfault when closing viewer3DVolume.py with PyQt5 on debian 8.
Closes #992

[plot3d] Avoid seg fault when closing viewer3DVolume.py

---

silx/io/commonh5.py
silx/io/fabioh5.py
silx/io/test/test_fabioh5.py

- Avoid to store metadata headers only used to decode the input file format
- Robustness on raw header

Filter fabio metadata

---

examples/tomographyReconstruction.py

Call qt.qApp.processEvents prior to ask for command line input. closes #1254

[examples] tomographyReconstruction.py display fix

---

CHANGELOG.rst

Please double-check, in case I forgot a new feature or an important bug fix..

Changelog v0.6

---

silx/gui/data/NXdataWidgets.py
silx/io/test/test_utils.py

for monotonically decreasing x values.
Also, fix `ArrayCurvePlot.setCurveData` when ylabel is None (this should never happen, because there is always at least a signal dataset whose name can be used). 
Closes #1207

[NXdataView] display curve instead of scatter

---

README.rst
doc/source/index.rst
version.py

and fix DOI of latest release.

Update version number to 0.7.0-dev

---

silx/gui/plot/Profile.py

This should fix the issue #1256 
But I wonder why the showProfileMainWindow of the profile has such a complicated behavior.
From my point of view having it displayed close to the mouse would be good too no ?

[Profile] fix #1256

---

silx/gui/plot/items/core.py
silx/gui/plot/test/testPlotWidget.py

This PR fixes a bug when updating curve colors when color is given for each point.
Closes #1268

[plot] Fix update curve colors

---

silx/io/specfile.c
silx/io/specfile.pyx
silx/io/spech5.py

- Provide an explicit close function for specfile
- Use it with SpecH5
Closes #1274

Fix close of spec files

---

setup.py
silx/opencl/codec/byte_offset.py
silx/opencl/codec/setup.py
silx/opencl/codec/test/__init__.py
silx/opencl/codec/test/test_byte_offset.py
silx/opencl/common.py
silx/opencl/processing.py
silx/opencl/setup.py
silx/opencl/test/__init__.py
silx/resources/opencl/codec/byte_offset.cl

This is an implementation of the byte offset decompression in OpenCL. It may accelerate the reading of CBF files on high end GPUs (to be validated)

Byte offset in OpenCL

---

silx/opencl/codec/test/test_byte_offset.py

Set fabio to None if failed to import

---

silx/gui/plot/backends/BackendMatplotlib.py

Cherry pick PR #1335 into branch 0.6 for release 0.6.1. 
PR already accepted in master.

0.6.1]Cherry picks #1335

---

silx/gui/widgets/test/test_threadpoolpushbutton.py

Relative to #936
Relative to #1344

Clean up global thread pool

---

silx/io/dictdump.py

small fix relative to #1338 . /closes #1338

dictdump - dicttoh5 - add missing case if key already exists

---

silx/gui/plot3d/SFViewParamTree.py

This PR adds 2 sliders to control the light direction in the param tree.
The sliders control azimuth and altitude angles.
To test, use examples/view3DVolume.py and go to  Style-> Light Direction in the param tree widget.

[plot3d] Add light direction control from param tree

---

silx/gui/plot/backends/glutils/GLPlotCurve.py
silx/gui/plot3d/Plot3DWidget.py
silx/gui/plot3d/ScalarFieldView.py
silx/gui/plot3d/scene/__init__.py
silx/gui/plot3d/scene/cutplane.py
silx/gui/plot3d/scene/primitives.py
silx/gui/plot3d/scene/window.py

This PR adds new rendering primitives and updates existing ones.
It is a step towards #1311

[plot3d] Add new primitives to OpenGL internal scene structure

---

silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testCurvesROIWidget.py

The functionality was implemented, but not publicly exposed.

[CurvesROIDockWidget]add a setter to activate the middle ROI marker

---

silx/gui/plot/PlotWidget.py

This seems to be the simplest way to address #178.

[PlotWidget] display tooltip with legend when selecting curve

---

silx/gui/hdf5/test/test_hdf5.py

Use dedicated function to sync instead of wait

---

silx/gui/plot/backends/BackendMatplotlib.py

Cherry-pick from https://github.com/silx-kit/silx/pull/1328
Better to merge it here instead of waiting for this PR.

Fix missing numpy.float128

---

silx/app/view.py
silx/io/__init__.py
silx/io/fabioh5.py
silx/io/utils.py

A convenient way to expose supported format.
We also can talk about refactoring this thing using a descriptor class per codec. It can be very useful to provides more informations.

Expose supported extensions

---

ci/amd_sdk.sh

Fix AMD_SDK URL

---

silx/gui/dialog/ImageFileDialog.py
silx/io/utils.py

`C:/foo.h5` should not be consider as an URL from the `C` scheme :-)

Fix url on Windows

---

silx/gui/data/TextFormatter.py

bug which shows off in some dataset from Soleil

close #1405

---

silx/gui/data/TextFormatter.py
silx/gui/data/test/test_textformatter.py

This support few special cases of cp1252 in case the string is not an ascii.
For example the degree character.
It would be anyway better to fix the bad files.
Relative to #1405

Support cp1252 in very special case

---

silx/gui/plot/actions/histogram.py

Using thomas function `min_max` instead of numpy.nanmin and numpy.nanmax

fix histogram action in the case contain some infinite value.

---

silx/io/utils.py

Now the content of debugging_info is anyway displayed.
Close #1417

Move debugging_info into a try/finally block

---

silx/gui/hdf5/_utils.py

- Fix an error relative to ntype.

Fix undefined property

---

ci/amd_sdk.sh

Yet another update of AMD SDK download.

[CI] Fix Travis-Linux download of OpenCL SDK

---

examples/hdf5widget.py
silx/app/view.py
silx/gui/hdf5/Hdf5TreeView.py

Fix popup checks on HDF5 tree

---

bootstrap.py
setup.py

It should help to catch faster error instead of spending time to reach it

More checks on setup/bootstrap subprocess execution/result

---

silx/app/convert.py
silx/gui/dialog/ImageFileDialog.py
silx/io/fabioh5.py
silx/io/test/test_fabioh5.py
silx/io/utils.py
silx/utils/launcher.py

Closes #1127 
Depends on #1387

[convert] Handle file series as a multiframe file

---

silx/utils/launcher.py

- An explicit message is not needed here we suppose it is a bug on the application module
- Thus the application module have to be patched

Clean up import application module

---

silx/io/fabioh5.py
silx/io/test/test_fabioh5.py

Here is a patch of `fabioh5` to normalize positioners/counters types by default.
- Now it always use a signed type with at least 32 bits (int32, float32, complex64)
- It do not normalize all the counters/positioners altogether (only use 64bit if expected by one dataset, for example) as also proposed in the same issue.
Close #1450

Improve fabioh5 used types

---

silx/gui/plot/Colormap.py
silx/gui/plot/ColormapDialog.py
silx/gui/plot/test/testColormap.py
silx/gui/plot/test/testColormapDialog.py
silx/utils/exceptions.py

Colormap read only

---

examples/colormapDialog.py
silx/gui/plot/ColormapDialog.py
silx/gui/plot/ComplexImageView.py

- Use a non-editable colormap from complex phases
- Plus some clean up relative to colormap dialog and complex view
Closes #1485
Closes #1495

Fix complex view

---

doc/source/modules/utils/index.rst
doc/source/modules/utils/testutils.rst
silx/io/nxdata.py

Plus a small warning on nxdata.
Closes #1488

Update doc relative to testutils

---

silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py

This PR:
- Change matplotlib backend polylines rendering to render closed polylines when first and last points are the same
- Enable polylines item in OpenGL backend
Closes #1489

[plot] Fix plot polylines

---

silx/gui/plot/ComplexImageView.py
silx/gui/plot/items/__init__.py
silx/gui/plot/items/complex.py
silx/gui/plot/items/core.py
silx/gui/plot3d/_model/items.py
silx/gui/plot3d/items/core.py
silx/gui/plot3d/items/scatter.py

This PR provides a refactoring of `ComplexImageView` widget.
This provides:
- A new plot item: `ImageComplexData`
- The `ComplexImageView` uses this item and part of its API is now a proxy to this item.
This should ease treatment specific to complex (e.g., #1493)

[plot] Refactoring of ComplexImageView

---

silx/opencl/codec/byte_offset.py

fix byte offset test

---

silx/opencl/codec/byte_offset.py

Revert "fix byte offset test"

---

silx/gui/hdf5/Hdf5Formatter.py

Display compound dtype sorted

---

examples/customDataView.py
silx/gui/data/DataViewerSelector.py
silx/gui/data/DataViews.py

- Fix the issue
- Provide an example
Closes #1183

Update buttons on the DataViewSelector when available views change

---

silx/app/convert.py

[convert] Escape \ when building regular expression from file path

---

examples/hdf5widget.py
silx/gui/data/DataViews.py
silx/io/nxdata.py

Add a viewer for invalid (malformed) NXdata.
Add additional tests to detect malformed curves, images and stacks, with axes of wrong lengths (closes #1430).

[DataViewer] Add a viewer for invalid NXdata

---

silx/opencl/sift/test/test_keypoints.py
silx/utils/testutils.py

Clean up parametric tests

---

ci/close_popup.py
examples/customHdf5TreeModel.py
examples/hdf5widget.py
silx/gui/plot/actions/medfilt.py
silx/gui/widgets/MedianFilterDialog.py
silx/gui/widgets/PrintPreview.py
silx/opencl/sift/match.py
silx/third_party/EdfFile.py

This PR fixes a few typos reported as errors by landscape.io (https://landscape.io/github/silx-kit/silx/797).

Fix a few typos found by landscape.io

---

package/debian9/control

Packaging issue on debian9

---

examples/hdf5widget.py
silx/gui/data/DataViewerSelector.py
silx/gui/data/DataViews.py
silx/gui/data/NXdataWidgets.py
silx/gui/plot/Colormap.py
silx/gui/widgets/FrameBrowser.py
silx/io/nxdata.py
silx/io/test/test_nxdata.py

This PR adds support for the `@auxiliary_signals` attribute in NXdata groups.

[nxdata] Implement auxiliary signals

---

silx/gui/plot/test/testColormapDialog.py

Correct test.

---

silx/app/view.py

Load hdf5plugin before h5py

---

silx/gui/plot/actions/io.py

[plot save] Add three more digits

---

requirements.txt
silx/gui/dialog/FileTypeComboBox.py
silx/io/fabioh5.py

Fix fabio 0.6

---

doc/source/Tutorials/convert.rst
doc/source/Tutorials/io.rst
doc/source/Tutorials/specfile_to_hdf5.rst
doc/source/applications/convert.rst
doc/source/tutorials.rst

Reorganize IO tutorials, split _Reading SPEC as HDF5_ and _Converting various data files_.
Closes #1490

[doc] IO tutorials

---

silx/gui/plot/ColormapDialog.py

Fix colormap dialog range

---

silx/opencl/sift/utils.py

This PR fixes an incompatibility with numpy < 1.14

[sift] support numpy < 1.14

---

silx/gui/dialog/test/test_datafiledialog.py
silx/gui/dialog/test/test_imagefiledialog.py
silx/io/test/test_fabioh5.py
silx/io/test/test_spech5.py
silx/io/test/test_spectoh5.py
silx/io/test/test_utils.py

Assume we are using at least fabio 0.6
Previously, corrupted files was not cleanly closed by fabio.
If this PR fail on Windows, there is still something to clean somewhere.
Closes #1562

Clean up fabio

---

silx/gui/plot3d/ParamTreeView.py
silx/gui/plot3d/Plot3DWidget.py
silx/gui/plot3d/SceneWidget.py
silx/gui/plot3d/_model/items.py

This PR adds `sigStyleChanged` to `Plot2DWidget` to notify general style changes ( background/foreground, etc...) in the OpenGL scene.
It also fixes the ParamTreeView that was not updated upon changes.
Closes #1481

[plot3d] Add Plot3DWidget.sigStyleChanged

---

silx/gui/data/DataViews.py
silx/io/nxdata.py

Closes #1583:
- rename `nxdata.get_NXdata_in_group` -> `nxdata.get_default`
- make axes optional in `nxdata.save_NXdata` 
- change default signal name "y" -> "data"

[nxdata] API change

---

silx/opencl/test/test_image.py

Closes #1601 
It seems there was a completion error from the editor

closes #1601

---

examples/hdf5widget.py

Usual issues with sequences of unicode not handled by h5py.

fix PY3 bug when generating NXdata examples in hdf5widget

---

silx/gui/plot/test/testUtilsAxis.py
silx/gui/plot/utils/axis.py

- Looks to be to only clean up internal weakrefs
Closes #1590

More weakref to avoid syncaxis exception

---

silx/io/utils.py

Fix indentation

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py

This PR changes plot backend picking API to avoid useless picking with OpenGL backend by filter by item kind before picking items rather than after...
closes #1617

[plot] Improve backend picking

---

silx/gui/data/NXdataWidgets.py
silx/io/nxdata.py

closes #1595 
This also forces the PY2 encoding of attrs to utf-8

[save_NXdata] write NX_class = "NXentry" when creating entry

---

silx/io/nxdata.py
silx/io/test/test_nxdata.py

[save_as_NXdata]Fix axes_names=None case

---

examples/hdf5widget.py
silx/gui/plot/actions/io.py

Hopefully closes #1596, but it needs to be tested on linux again. 
The file dialog on windows already appended the first extension, which made this issue apparent (only .h5 was treated properly).

[SaveAction] fix extension bug

---

silx/gui/plot3d/ParamTreeView.py

This PR fixes a Qt5/Qt4 API compatibility issue
Related to #1630

[plot3d] Fix Qt4 compatibility issue

---

silx/gui/data/DataViewer.py
silx/gui/data/test/test_dataviewer.py
silx/utils/property.py

This PR introduce a `classproperty` and use it to deprecated const defined inside a class.
Closes #1647

Fix deprecated api

---

package/debian8/rules
package/debian9/rules
package/desktop/org.silx.SilxView.desktop
package/desktop/silx.xml

Update silx-view mime type association

---

doc/source/conf.py
silx/gui/data/DataViewer.py
silx/utils/deprecation.py

- Ignore deprecation warnings when building the doc
- Fix message displayed by deprecated classproperties

Fix deprecation warning

---

silx/gui/plot3d/_model/core.py
silx/gui/plot3d/_model/items.py

This PR fixes issues when using PySide in the model of the plot3d SceneWidget
closes #1655

[plot3d] fix pyside support in model

---

silx/opencl/codec/byte_offset.py
silx/opencl/codec/test/test_byte_offset.py
silx/opencl/processing.py
silx/opencl/test/test_image.py

Fix a couple of tests on OpenCL/AMD/Windows

---

examples/plotUpdateFromThread2d.py

Based on plotUpdateFromThread.py, create 2d-fake data and plots as Image.
Fake data is 2d Gaussian peak that shifts slightly from update to update, superimposed with weak noise.

New example: plotUpdateFromThread2d.py

---

examples/syncaxis.py

[0.7] Fix syncaxes example

---

examples/icons.py

[0.7] fix icon example

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/items/__init__.py

Now it is OK for all kinds of data we support.

[plot] More fix for resetzoom

---

examples/scatterMask.py
silx/gui/data/NXdataWidgets.py
silx/gui/plot/ImageView.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/StackView.py
silx/gui/plot/test/testColormapDialog.py
silx/gui/plot/test/testPlotWidget.py
silx/gui/plot/test/testPlotWidgetNoBackend.py
test/colorbar.py

This PR change addImage replace argument default value and update code accordingly.
closes #1555

[plot] Change addimage replace argument default value to False

---

ci/before_install-osx.sh

This should fix macOS build, broken after update of brew making python3 the default.

[CI] Fix travis-macOS CI env

---

silx/io/spech5.py

Behavior introduced in PR #1538

Update spech5 docstring to be consistent with 'title' behavior

---

silx/gui/plot3d/SceneWidget.py
silx/gui/plot3d/_model/items.py

This PR fixes a bug in `SceneWidget.clearItems`.

[plot3d] Fix SceneWidget.clearItems bug

---

silx/gui/data/DataViews.py
silx/io/nxdata.py
silx/io/test/test_nxdata.py
silx/math/chistogramnd.c

Closes #1767 (issue with None assigned to arry of strings)
Also modifies the controversial function `get_attr_as_string` to always return unicode, rather than native python str (bytes in PY2 and unicode in PY3).

[nxdata] fix bug with undefined axis

---

silx/sx/__init__.py

This PR:
- Does not load gui features is $DISPLAY is not set on linux: closes #1747 
- Create QApplication even if imported from a script: closes #1748

[sx] Loading gui fixes

---

package/desktop/silx.xml
silx/io/utils.py

Support ".hdf5" as default HDF5 extensions

---

silx/math/combo.pyx

Convert float16 to float32 in min_max combo function

---

silx/gui/data/Hdf5TableView.py
silx/gui/hdf5/Hdf5Formatter.py

Add tooltip to display HDF5 attribute type

---

silx/gui/plot/matplotlib/__init__.py

Reduce matplotlib warnings

---

silx/sx/_plot.py

[plot] Use origin=upper as default for imshow

---

silx/third_party/EdfFile.py

Fix EDF header size in Python3

---

.gitignore

This cleans-up `git status` output.
closes #1822

Add cythonized files to gitignore

---

silx/app/view/Viewer.py

Fix fabio optional

---

silx/gui/data/HexaTableView.py

Uses data if tobytes is not available

---

silx/gui/data/DataViews.py

Check shape before checking size

---

silx/gui/data/Hdf5TableView.py

- Exception occurring in the redraw loop disable the data
Closes #1818

Avoid infinite loop of exception

---

silx/gui/dialog/ColormapDialog.py
silx/gui/dialog/test/test_colormapdialog.py

Fix empty image in colormapdialog

---

silx/app/test/test_view.py
silx/app/view/ApplicationContext.py
silx/app/view/Viewer.py
silx/app/view/__init__.py

- Implement `--fresh` to start the application from fresh user preferences
- Allways use ini file, for all platforms (Windows will use APPDATA directory)
Relative to #1746

[silx view] Improve user preferences

---

silx/app/view/__init__.py
silx/gui/qt/_qt.py

I fix the issue by catch SIGINT in `silx view`. KeyboradInterrupt is therefore not displayed.
It's enough fine for me.
Closes #1815

Ignore keyboard interrupt

---

silx/gui/data/NXdataWidgets.py
silx/gui/plot/ScatterView.py

closes #1847 
This PR also makes some needed adjustments to ScatterView to work with the viewer:
- widget flag
- add set/getColormap

[NXdataViews] Use a ScatterView

---

examples/plot3dSceneWindow.py
silx/gui/plot3d/_model/items.py

This PR ignore scales set to 0 from the GUI in the plot3d SceneWindow parameter tree.
closes #1731

[plot3d] Ignore setting scale to 0 from parameter tree

---

doc/source/Tutorials/writing_NXdata.rst
doc/source/tutorials.rst

[doc] writing NXdata

---

silx/gui/plot/StackView.py

The valueChanged signal needs to be disconnected before clearing the slider range..

[StackView] Fix bug in clear()

---

doc/source/Tutorials/Image.ipynb
doc/source/Tutorials/convert.rst
doc/source/Tutorials/fit.rst
doc/source/Tutorials/io.rst
doc/source/Tutorials/specfile_to_hdf5.rst
doc/source/modules/gui/hdf5/getting_started.rst
qtdesigner_plugins/README.rst

Last contribution from Claudio....

[doc] English proof-reading

---

silx/utils/number.py
silx/utils/test/test_number.py

Do not uses bits but nexp+nmant

---

silx/app/view/About.py
silx/app/view/__init__.py

Remove hdf5plugin warning

---

silx/gui/plot/tools/roi.py
silx/gui/plot/tools/test/testROI.py

This PR:
- Moves the max number of ROI management to `InteractiveRegionOfInterestManager` subclass
- Add the ROI to the list at the beginning of draw interaction so one can follow ROIs update while they are drawn.

[plot] Update ROI

---

silx/app/view/CustomNxdataWidget.py

Fix test failed with PySide due to delegate being deleted

---

silx/gui/plot/backends/BackendMatplotlib.py

This PR changes the frame used for y pixel coordinates with matplotlib to use the same as Qt.
matplotlib pixel coordinates origin is the lower-left corner of the figure (i.e., widget), while Qt widgets (and the OpenGL plot backend) origin it their upper-left corner.
This worked fine as pixel coordinates were received from and interpreted by matplotlib.
There was still an issue: The `PlotWidget` methods `pixelToData`, `dataToPixel` and `getPlotBoundsInPixel` do not have a consistent behavior between both backends (one using lower-left origin and the other upper-left origin)...

Use Qt widget origin (top) rather than matplotlib origin (bottom)

---

silx/gui/plot/StatsWidget.py

- Fix the issue #1905
- Plus some clean up
Closes #1905

[stat] Fix kind if item when the plot content change

---

examples/plotWidget.py
silx/app/view/Viewer.py
silx/gui/plot/ImageView.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/ScatterView.py
silx/gui/plot/tools/roi.py
silx/gui/plot3d/SFViewParamTree.py
silx/gui/widgets/PrintGeometryDialog.py
silx/sx/_plot3d.py
test/colorbar.py

- Try to remove widget without parents (it should not change anything)
- Do not store signals from items as it is own by the items anyway

Fix few things

---

silx/gui/data/DataViews.py
silx/io/nxdata/parse.py

Support None axis for NXdata scatters

---

silx/gui/plot/StatsWidget.py

Minor proofreading issues. I will keep the PR in WIP for today, in case I find other minor things to fix.

minor tooltip fix

---

silx/gui/plot/PlotInteraction.py
silx/gui/plot/tools/PositionInfo.py

Take care of high DPI display when using Qt5:
- For curve snapping threshold: closes #1933 
- For polygon edition end point size: closes #1932

[plot] Improve high DPI screen support

---

silx/gui/plot/ScatterMaskToolsWidget.py
silx/gui/plot/ScatterView.py

This PR:
- Adds a title to ScatterView mask tool, closes #1931 
- Reduces the size of scatter mask symbols, closes #1930

Minor fix for ScatterView

---

silx/gui/plot/actions/mode.py

This PR checks that plot widget is still valid before using it in Zoom and Pan actions.
closes #1937

Check that plot is still valid in zoom and pan actions

---

silx/gui/icons.py

Fix SVG rasterization

---

silx/io/convert.py
silx/io/fabioh5.py

The goal of this PR is to read and write one frame at a time when converting a EDF file series into a HDF5 3D dataset.
Closes #1925

[silx convert] don't load complete file series into memory

---

silx/sx/__init__.py

[sx] Add sx.enable_gui() function to load silx widgets from the notebook

---

silx/gui/data/TextFormatter.py

- Should support any vlen dtypes
- Display compound types prefixed by field name
- Fix on complex types
Closes #1951

Improve dtype support

---

silx/app/view/Viewer.py
silx/gui/hdf5/NexusSortFilterProxyModel.py

- Enable NXentry sorting by start/end time
- Enable case insensitive sorting
- Fix bug with vectorial icons

Improve silx view tree sorting

---

silx/opencl/sift/test/test_algebra.py
silx/opencl/sift/test/test_align.py
silx/opencl/sift/test/test_convol.py
silx/opencl/sift/test/test_gaussian.py
silx/opencl/sift/test/test_image_functions.py
silx/opencl/sift/test/test_image_setup.py
silx/opencl/sift/test/test_keypoints.py
silx/opencl/sift/test/test_matching.py
silx/opencl/sift/test/test_preproc.py
silx/opencl/sift/test/test_reductions.py
silx/opencl/sift/test/test_transform.py

Optional scipy

---

silx/gui/plot/Profile.py

This PR scales horizontal and vertical profile x coordinates according to image origin and scale.
It does nothing for free line profile and nothing for stack profile.
related to #1642

Image profile coordinates

---

ci/appveyor.yml
ci/requirements-pinned.txt

[ci] update appveyor config

---

requirements.txt

update fabio version in requirements

---

doc/source/modules/gui/plot/items.rst
doc/source/modules/gui/plot/tools.rst
silx/gui/plot/items/roi.py
silx/gui/plot/tools/roi.py

This PR updates the doc for ROI in the plot

[doc] Update ROI documentation

---

silx/io/fabioh5.py

Avoid to reach the full file data.

fabioh5: Reach both dtype and shape from the first frame

---

.travis.yml
silx/gui/dialog/AbstractDataFileDialog.py
silx/gui/plot/StatsWidget.py
silx/gui/plot/test/testMaskToolsWidget.py
silx/gui/plot/test/testPlotWidget.py
silx/gui/plot/test/testScatterMaskToolsWidget.py
silx/gui/plot3d/ParamTreeView.py
silx/gui/qt/_pyside_dynamic.py
silx/gui/qt/_qt.py
silx/gui/qt/_utils.py
silx/gui/test/utils.py

This PR upgrades supportof PySide2 in silx.
It fixes a few issues, modifies a bit the tests and adds PySide2 to travisCI config

[gui] PySide2 support

---

.travis.yml
doc/source/install.rst
doc/source/modules/gui/plot/getting_started.rst
doc/source/virtualenv.rst
requirements.txt
silx/gui/dialog/AbstractDataFileDialog.py
silx/gui/plot/StatsWidget.py
silx/gui/plot/test/testMaskToolsWidget.py
silx/gui/plot/test/testPlotWidget.py
silx/gui/plot/test/testScatterMaskToolsWidget.py
silx/gui/plot3d/ParamTreeView.py
silx/gui/qt/__init__.py
silx/gui/qt/_pyside_dynamic.py
silx/gui/qt/_qt.py
silx/gui/qt/_utils.py
silx/gui/test/utils.py

Merge PR #1997 first!
This PR:
- adds a deprecation warning when loading PySide,
- moves PySide to the last probed Qt binding
- removes PySide from the documentation.
Are you OK with this?

[gui] Deprecate PySide Qt binding

---

silx/gui/data/RecordTableView.py
silx/gui/hdf5/Hdf5Item.py
silx/gui/hdf5/Hdf5LoadingItem.py

- Fix files created with new HDF5 lib and loaded with old HDF5 lib
- Fix ndim compound types
- Fix display of threaded load of files
#2002
#2003

Fix bunch of GUI issues

---

silx/gui/utils/_image.py
silx/third_party/EdfFile.py
silx/third_party/TiffIO.py

This addresses a deprecation warning in numpy 1.14. See https://github.com/numpy/numpy/pull/9487

Replace numpy.fromstring with numpy.frombuffer when reading binary data

---

silx/math/medianfilter/include/median_filter.hpp
silx/math/medianfilter/median_filter.pxd
silx/math/medianfilter/medianfilter.pyx
silx/math/medianfilter/test/test_medianfilter.py

Add a constant mode to median filter

---

README.rst
doc/source/index.rst
doc/source/install.rst

Fixed some English mistakes in the docs.

added some english corrections

---

bootstrap.py
run_tests.py

This PR makes bootstrap.py and run_tests.py works with multiprocessing application on Windows where care is needed for things to occur in `if __name__ == "__main__"` section or one ends up with new processes creating new processes infinitely....

Make bootstrap and run_tests work with multiprocessing on Windows

---

doc/source/conf.py
doc/source/modules/sx.rst

This is the case for our nightly builds (and maybe also for debian)

Make silx.sx doc build without display

---

doc/source/modules/gui/plot/getting_started.rst
silx/gui/dialog/ColormapDialog.py
silx/gui/plot/ColorBar.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/ScatterView.py
silx/gui/plot/backends/BackendBase.py

[doc] Fix Colormap references

---

ci/requirements-pinned.txt

Attempt to workaround #2074 to make CI work again.

unpin numpy and pin PyOpenGL

---

silx/gui/plot/MaskToolsWidget.py
silx/gui/plot/_BaseMaskToolsWidget.py

Mitigate the problem.
I still have annoying behaviour on the pyFAI integration, but it's much better.
Closes #2077

Only reset the tool if a specific mask tool is activated

---

silx/gui/data/RecordTableView.py

Fix pyside2 CI

---

silx/gui/plot/items/histogram.py

Looks to fix  #2079 but i dont know if it is the right way.
Closes  #2079

Invalidate plot datarange when histogram data changes

---

examples/plotInteractiveImageROI.py

This PR improves ROI sample code when hiding the roi tools dock widget
closes #2033

Stop interaction when hiding roi tools dock widget

---

silx/gui/hdf5/Hdf5Item.py

display the Nexus class name into the tooltip & datatype for HDF5groups

---

silx/gui/data/RecordTableView.py

[silx view] fix RecordTableView for viewing simple arrays of unicode

---

silx/gui/plot/test/testStats.py

Issue was most probably in PySide as it is the binding which fails.
This is a workaround for it.
closes  #2091

Make test pass on pyside

---

.travis.yml
silx/gui/qt/_qt.py

Set sip API v2 for everything with PyQt4
closes #2101

[gui] Set all sip API to v2

---

silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/marker.py

This PR adds linestyle and linewidth to X and Y line markers.
Partially implement #2089

[plot] Add line style and width to line markers

---

requirements.txt

add platform_machine restriction on pyopencl in requirements.txt

---

silx/opencl/common.py

[opencl] Reduce logging level

---

ci/requirements-pinned.txt
doc/source/install.rst
requirements.txt
setup.py

.. and update doc accordingly
The associated code clean-up is not part of this PR (see issue #2120)
closes #2024

Add h5py and fabio as strong dependencies

---

silx/gui/colors.py
silx/gui/test/test_colors.py

Robustness on colormap arguments

---

examples/colormapDialog.py
silx/gui/plot/StatsWidget.py
silx/gui/plot/utils/axis.py
silx/gui/plot3d/ParamTreeView.py
silx/gui/qt/inspect.py
silx/gui/widgets/FloatEdit.py

Merge PR #2156 first!
Test examples with pyside2
closes #2025

Make example works with Pyside2

---

silx/gui/hdf5/_utils.py
silx/gui/hdf5/test/test_hdf5.py

HDF5: bug when acquiring physical target of relative links.

---

silx/opencl/codec/byte_offset.py

(order of arguments changed)
close #2168

relace pyopencl.enqueue_copy_buffer with pyopencl.enqueue_copy 

---

silx/gui/data/NXdataWidgets.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/StackView.py
silx/gui/plot/actions/PlotToolAction.py
silx/gui/plot/actions/fit.py
silx/gui/plot/actions/histogram.py
silx/gui/plot/actions/medfilt.py

The PlotAction manage to displayed tool, and hide it if expected.
Applyed on histo, medfilt, and fit actions
Closes #2109

Hide displayed tools when the plot is not anymore visible

---

silx/_config.py
silx/gui/plot/PlotWidget.py

Use silx.config.DEFAULT_COLORLIST in PlotWidget

---

silx/gui/plot/PrintPreviewToolButton.py
silx/gui/widgets/PrintPreview.py

Closes #2186 : bug if printer selection dialog is canceled.

[PrintPreview] don't open PrintPreview if printer is not set 

---

doc/source/index.rst
doc/source/troubleshooting.rst

[doc] Add a trouble shooting documentation page with opengl over ssh info

---

silx/gui/fit/FitConfig.py

Hopefully closes #2174 (still to be tested)

[FitConfig]fix bug when clicking Default button

---

silx/app/view/DataPanel.py

Improve datapanel header

---

doc/source/modules/gui/plot/items.rst
doc/source/modules/gui/plot/plotwidget.rst
silx/gui/plot/LegendSelector.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/items/core.py
silx/gui/plot/items/curve.py
silx/gui/plot/test/testPlotWidget.py
silx/gui/plot/tools/CurveLegendsWidget.py

This PR adds the option to set not only the colour, but also line style, line width, symbol and symbol size.
This adds `PlotWidget.get|setActiveCurveStyle` methods.
TODO:
closes #2119

[plot] Add more options for active curve style

---

silx/gui/plot/ScatterMaskToolsWidget.py

This fixes a bug when setting the mask on a ScatterMaskToolsWidget which was not yet shown 
```
File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/plot/ScatterMaskToolsWidget.py", line 216, in setSelectionMask
if self._data_scatter.getXData(copy=False).shape == (0,) \
<type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'getXData'
```
I checked that this bug does not affect the image mask tool (because it does not store an active  data item, it stores an empty numpy array).

[ScatterMask] fix bug when setting selection mask

---

silx/gui/plot/test/testMaskToolsWidget.py
silx/gui/plot/test/testScatterMaskToolsWidget.py

[fix] fix unit test for masks when drawing

---

setup.py
silx/io/specfile.pyx
silx/math/chistogramnd.pyx
silx/math/colormap.pyx
silx/math/combo.pyx
silx/math/fit/filters.pyx
silx/math/fit/functions.pyx
silx/math/fit/peaks.pyx
silx/math/marchingcubes.pyx
silx/math/medianfilter/medianfilter.pyx

Makes it work with cython language_level=3, issues with absolute/relative imports of .pxd files.
closes #2191

Use Cython language_level=3

---

build-deb.sh

Installed on debian10 beta ...

compatibility with debian10 ... just debian9+ right now

---

silx/gui/plot/ColorBar.py

This PR fixes the issue with colorbar display while in log scale.
closes #2221

Fix colorbar glitch with log scale

---

silx/gui/colors.py

This PR changes place where to look for matplotlib colormaps

Make sure to access all colormaps from matplotlib

---

silx/math/fit/filters.pyx

This PR updates the reference to snip articles to add the title and a DOI link

[doc] Update reference to snip articles

---

silx/app/view/main.py

Allow to use --help without Qt

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendMatplotlib.py

- The background color under the data was wrong when axis was not displayed
- The bg getter was returning objects with wrong data

Fix plot background colors

---

silx/gui/widgets/RangeSlider.py

- Display default slider background if no picture
- Update controls with mouse hover
- Fix image background location
- When mouse moving, move the center of the handler at the mouse location
Closes #2250

Improve range slider

---

examples/plot3dSceneWindow.py
silx/gui/plot3d/_model/items.py

This PR fixes the update of `SceneWidget` item labels in the associated parameter tree.

[plo3d] Fix label update in param tree

---

run_tests.py

- The real exception backtrace is helpful

Rework the import error message for testing lib

---

silx/resources/__init__.py

This PR adds the possibility to load external resources in a subdirectory

Add the possibility to download an external resource in a subdir

---

silx/gui/plot3d/SceneWidget.py

[SceneWidget]missing parent

---

silx/gui/dialog/AbstractDataFileDialog.py

`DEFAULT_SIDEBAR_URL` is provided in case it really have to be disabled.
Closes #1688

Feed the sidebars with default URLs

---

silx/gui/qt/_pyside_dynamic.py

It was not available with `PySide2`, at least. I guess it was not available with `PySide` too.
Example:
```
<customwidget>
<class>ElidedLabel</class>
<extends>QLabel</extends>
<header>pyFAI.gui.widgets.ElidedLabel</header>
</customwidget>
```

Allow to use custom widget with ui files

---

silx/gui/plot/PlotInteraction.py

This added a `THRESHOLD` to the zoom interaction
Relative to #2261, maybe it is enough, maybe not.
Closes #2261

Add a threshold to the zoom interaction

---

silx/gui/plot3d/items/scatter.py

fix logger

---

silx/gui/plot/_BaseMaskToolsWidget.py

Uses array_equal

---

silx/gui/plot/MaskToolsWidget.py

[mask] If single mask mode, set only 1 level when loading

---

silx/gui/hdf5/Hdf5Item.py

This PR fixes a @NX_class decoding issue by using a safe formatter rather than trying to guess every possible input type.
Closes #2292

Fix NX_class decoding issue

---

silx/gui/plot/PrintPreviewToolButton.py
silx/gui/widgets/PrintPreview.py

Closes #2279 
This method seems to work better with PyQt5.

[PrintPreviewDialog]Fix resizing in PyQt5 

---

silx/gui/plot/PlotWindow.py
silx/gui/plot/backends/BackendMatplotlib.py

This PR fix the `ColorBar` background according to the plot state.
Relative to comment https://github.com/silx-kit/silx/issues/2220#issuecomment-448607217
It also fixes small issues and typo

Synchronize ColorBar with plot background colors

---

silx/gui/widgets/PrintPreview.py

- Remove print statement
- The comment was never at left position but centered when asking LEFT position

Respect left alignment.

---

silx/test/__init__.py
silx/test/utils.py

Fix gui import

---

silx/io/specfile/src/sftools.c

Added test of read return value.

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/PlotWindow.py
silx/gui/plot/test/testPlotWidget.py

Fix colorbar background

---

silx/opencl/statistics.py
silx/opencl/test/__init__.py
silx/opencl/test/test_stats.py
silx/resources/opencl/kahan.cl
silx/resources/opencl/statistics.cl

OpenCL statistics

---

.travis.yml
silx/gui/plot/tools/roi.py

This should fix issues with PySide2 related to: https://bugreports.qt.io/browse/QTBUG-72547?jql=text%20~%20%22FT_Get_Font_Format%22
Issue first mentioned in: https://github.com/silx-kit/silx/pull/2298#issuecomment-448900921

[CI] Bump travis Linux OS to ubuntu 16.04

---

silx/io/test/test_utils.py
silx/io/url.py
silx/io/utils.py

Add a function to create external dataset for .vol file

---

doc/source/conf.py
requirements-dev.txt
requirements-doc.txt

I though this was merged into PR #2264 but is apparently not.

Minor clean-up after PR #2264

---

silx/gui/plot/PlotWindow.py

Background color is sync but not  foreground.

Add support of foreground color for colorbar in PlotWindow

---

silx/math/fft/npfft.py

Make it compatible with 1.8
closes #2329

[math] FFT with numpy 1.8 and 1.9

---

silx/gui/plot/actions/io.py
silx/gui/plot/test/testSaveAction.py

[plot.io] Possibility to specify filter order

---

silx/gui/plot/PlotWidget.py

Fix docstring typo spotted in https://github.com/silx-kit/silx/pull/2332#issuecomment-453931525.

Fix docstring types in PlotWidget

---

silx/app/view/Viewer.py
silx/gui/utils/projecturl.py

Link to doc

---

doc/source/ext/snapshotqt_directive.py

[doc][snapshot qt] fix 2351

---

silx/gui/plot/items/histogram.py

Fix bug with histogram bounds with log scaled X axis

---

examples/plotStats.py
silx/gui/plot/StatsWidget.py

This PR updates to StatsWidget module with:
- Added proxy methods instead of using attributes to do the proxies
- Updated docstings
- Added `getPlot` and use of a `weakref` to the `PlotWidget`.

[plot] Rework of StatsWidget

---

silx/gui/dialog/FileTypeComboBox.py

Support compressed Fabio extensions

---

silx/io/specfile/src/sfdata.c
silx/math/fit/filters/include/filters.h

This PR fixes build warnings on macOS.

Fix build warnings

---

silx/gui/plot/test/testStats.py

This PR should fix random test failure of testEmptyStatsWidget with PySide2

Fix random test failure with PySide2

---

silx/io/test/test_utils.py
silx/io/utils.py

rawfile_to_h5_external_dataset:
- vol_file -> bin_file
- vol_dtype -> dtype

[silx.io.utils]hdf5 external helper function: modify parameters names

---

silx/io/utils.py

Also use OrderedDict to keep format order.
closes #2385

Add cxi extension to supported files

---

silx/gui/plot/CurvesROIWidget.py

if ROI is ICR then set back default marker color to black and hide middle - marker

fix 2390 - ICR roi color and middle marker visibility

---

silx/opencl/processing.py
silx/opencl/statistics.py
silx/opencl/test/__init__.py
silx/opencl/test/test_kahan.py
silx/resources/opencl/kahan.cl

2327 opencl kahan

---

silx/gui/plot/Profile.py

This PR updates the image/stack profile tool to use coordinates from the initial plot as X coordinates in the profile.
closes #1642

Make profile coordinates use plot coords + rework title

---

silx/gui/plot/StatsWidget.py

Stats widget optimization

---

CONTRIBUTING

Add a page to bootstrap contributions

---

silx/gui/data/DataViewer.py

Clean up deprecated

---

.travis.yml
setup.py
silx/opencl/test/test_stats.py

two bug-fixes ... before the release

2404 pip import error

---

silx/gui/plot/backends/BackendMatplotlib.py

Fix right axis with matplotlib

---

silx/gui/plot/ScatterView.py

Add proxy to get/setSelectionMask in ScatterView

---

silx/app/view/main.py
silx/utils/files.py

Support magic for windows

---

ci/requirements-pinned.txt

Makes CI happy again.. until we investigate issues with pyqt5 5.12.

pinpoint pyqt5 to 5.11.3

---

silx/resources/__init__.py

Some re-factorisation on top of the patch from Jerome
Improve #2434

Fix getuser

---

silx/app/view/Viewer.py

Closes #2382
F5 is not working on my windows laptop

Improve viewer shortcuts

---

silx/math/fft/basefft.py
silx/math/fft/clfft.py
silx/math/fft/cufft.py
silx/math/fft/fft.py
silx/math/fft/fftw.py
silx/math/fft/npfft.py
silx/math/fft/test/test_fft.py
silx/opencl/sinofilter.py

math.fft: Use template= keyword instead of data=

---

silx/opencl/sinofilter.py

Dont use dtype= argument for numpy.linspace with numpy < 1.9

---

silx/io/specfile/src/locale_management.c

Clean up unused var

---

silx/gui/data/DataViews.py
silx/gui/data/NXdataWidgets.py

This PR adds a specific view for NXdata with complex image signal.
related to #2406

Add a NXdata for complex images

---

silx/gui/plot/StatsWidget.py

Management of lazy import if OpenGL is not installed.
closes #2461

[StatsWidget] fix issue when fail to import OpenGL

---

silx/sx/test/test_sx.py

[unit test] skip some test if OpenGL is not installed.

---

silx/gui/data/DataViews.py
silx/gui/data/test/test_dataviewer.py

Pull request to the branch 0.10

Fix dataviewer when PyOpenGL is not available

---

silx/sx/test/test_sx.py
silx/test/utils.py

Test OpenGL availaibility once during tests

---

CHANGELOG.rst
requirements.txt
setup.py

Advertise numpy >= 1.12 required

---

.travis.yml
silx/gui/qt/inspect.py

This PR load PySide2 from pypi rather than from nightly build, andwait for window exposed in stat widget test.

[ci] Use PySide2 from pypi

---

silx/gui/hdf5/Hdf5TreeModel.py
silx/gui/hdf5/test/test_hdf5.py

Fix Hdf5TreeModel removeIndex on branch 0.10

---

silx/gui/hdf5/Hdf5TreeModel.py
silx/gui/hdf5/test/test_hdf5.py

Fix Hdf5Model removeIndex

---

silx/gui/plot3d/SceneWidget.py
silx/gui/plot3d/_model/items.py
silx/gui/plot3d/items/__init__.py
silx/gui/plot3d/items/mixins.py
silx/gui/plot3d/items/volume.py
silx/gui/plot3d/test/__init__.py
silx/gui/plot3d/test/testSceneWidgetPicking.py
silx/gui/plot3d/test/testSceneWindow.py

This PR adds a few tests for the SceneWindow/SceneWidget plot3d widgets.

[plot3d] Add some tests for  SceneWindow/SceneWidget

---

doc/source/modules/gui/plot/index.rst
doc/source/modules/gui/plot/utils.rst

There it is : #2532
Not sure if you want it there, let me know.
closes  #2532

SyncAxes doc

---

silx/gui/plot/_BaseMaskToolsWidget.py

It's not about a crying mask.
Sorry for that.

[mask] Typo

---

silx/opencl/backprojection.py
silx/opencl/sinofilter.py
silx/opencl/test/test_backprojection.py

This PR aims at fixing #2534 .

Backprojection: disallow odd numbers when computing FFT plan

---

silx/gui/plot/matplotlib/__init__.py

This PR reworks the initialization of `matplotlib` to make it compatible with `matplotlib` 3.1 and also to simplify it.

Simplify matplotlib init and make compatible with matplotlib3.1

---

examples/plotLimits.py

The docstring was identical to syncaxes.py

[examples.plotLimits] fix description in docstring

---

doc/source/modules/gui/plot3d/glutils.rst

Fix qtcontext to remove doc warnings

---

silx/gui/qt/_qt.py

This PR fixes a typo introduced in #2571.

Fix typo in qt binding loading

---

silx/gui/console.py

This PR adds a workaround for the console widget for ipykernel v5.0 and 5.1.0.
closes #2581

workaround ipykernl 5.0, 5.1.0 issue

---

doc/source/modules/gui/plot/statswidget.rst
examples/plotStats.py
silx/gui/plot/StatsWidget.py
silx/gui/plot/test/testStats.py

Add update mode (auto, on manual request) for StatsWidget

---

silx/gui/plot/CurvesROIWidget.py

fix #2598   (Fail to update the ROI of ID 0 from the marker)

[RoiStatsWidget] fix typo in condition

---

silx/gui/dialog/AbstractDataFileDialog.py

I was not able to reproduce the error obtain in #2478 
Anyway this should close #2478

[AbstractDataFileDialog] 2478

---

silx/gui/plot/ScatterView.py

This PR snaps `ScatterView` profile to points: if there is a `Data` and `Index` displayed, then the `X` and `Y` info is that of the data point rather than that of the mouse. Otherwise, the mouse coordinates is used.
When the scatter plot is displayed as a surface, the snapping is with the scatter plot point closest to the mouse when inside the convex hull.
closes #2643

snap scatter profile to points

---

ci/appveyor.yml
version.py

Update silx version after 0.11.0 release.

Update version.py and appveyor.yml

---

silx/gui/plot/test/testStats.py

[stats][unit test] make TestStatsHandler inherit from TestCaseQt

---

build-deb.sh

This PR fixes the bpo (backport) suffix for buster.

Fix debian10

---

silx/gui/plot/actions/fit.py

This PR avoids an issue with the `Dismiss` button of the `FitWidget` in `FitAction` to hide the widget "forever" afterwards as it was embedded in a `QMainWindow` and the `Dismiss` button was closing both the `FitWidget` and the `QMainWindow`... while on action triggered only the `QMainWindow` was shown again....
This PR solves this by removing the (useless) `QMainWindow`.
It also removes the `fit_widget` attribute which duplicates `_getToolWindow()`.
closes #2664

[plot] Fix FitAction dismiss button

---

silx/gui/plot/PlotWidget.py

Not sure if I should create PR for such a small thing.

[plot] Trivial typo in docstring

---

silx/gui/plot/tools/roi.py

This PR adds missing doc of `useManagerColor` argument.
closes #2676

[plot] Add missing doc

---

silx/gui/plot/PlotWindow.py

This PR adds `PlotWindow` dock widgets to dock area when they become visible rather than when they are created.
This allows to take the window size into account to decide where to put them
closes #1629

[plot] Defer addition of dock widgets to main window

---

package/debian10/changelog
package/debian10/control
package/debian10/rules
silx/math/fft/test/test_fft.py

Provide backports for debian buster even on Python2

Py2 packaging on buster

---

silx/math/fft/clfft.py
silx/opencl/common.py
silx/opencl/convolution.py
silx/opencl/linalg.py
silx/opencl/projection.py
silx/opencl/reconstruction.py
silx/opencl/sift/test/test_algebra.py
silx/opencl/sift/test/test_image.py
silx/opencl/sift/test/test_keypoints.py
silx/opencl/sift/test/test_matching.py
silx/opencl/sift/test/test_reductions.py
silx/opencl/test/test_addition.py
silx/opencl/test/test_convolution.py
silx/opencl/test/test_kahan.py
silx/opencl/test/test_linalg.py
silx/opencl/test/test_sparse.py

close #2696 
All OpenCL tests are passing on x86-64+PoCL but the one requiring textures ... which is known unsupported.

Replace pyopencl.array.zeros with empty + fill

---

silx/utils/testutils.py

Disable to false, the restore the previous state.

Make sure the logger is enabled before testing

---

silx/opencl/processing.py

2707 ocl garbage collection

---

silx/gui/plot/PlotInteraction.py

This PR remove/fix TODOs that where introduced in PR #2602 about plot events content.

Clean-up some TODOs about plot event creation

---

silx/opencl/sinofilter.py

[OpenCL] SinoFilter: explicitly use CLFFT, don't import scikit-cuda

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/complex.py
silx/gui/plot/items/curve.py
silx/gui/plot/items/histogram.py
silx/gui/plot/items/image.py
silx/gui/plot/items/marker.py
silx/gui/plot/items/scatter.py
silx/gui/plot/items/shape.py

Merge PR #2730 and #2731 first!
This PR removes the now useless `legend` argument in the plot backend.
This does NOT change the `PlotWidget` and its items, it just changes the backends.

Plot: remove legend argument in backends

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/marker.py
silx/gui/plot/test/testPlotWidget.py

This PR allows to define a marker with an yAxis (left or right).
It introduce an `yaxis` argument to the public API `addMarker`, `addXMarker`, `addYMarker` of the `PlotWidget`. Plus internal changes.
Closes #2738

Marker with yaxis

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/test/testPlotWidget.py

Fix backend loop

---

silx/gui/data/DataViewer.py
silx/gui/data/NumpyAxesSelector.py

Merge PR  #2701 and #2697 first!
This PR reworks `DataViewer` and `NumpyAxesSelector`.
This follows addition of `blockSignals` and update of `NumpyAxesSelector`.
It uses `blockSignals`, update a few docstrings and a few small patches.

Refactoring

---

silx/gui/plot/ColorBar.py
silx/gui/plot/tools/PositionInfo.py
silx/gui/widgets/FrameBrowser.py

QFontMetrics.width(str) -> QFontMetrics.boundingRect(str).width()

remove some deprecation warning 

---

silx/image/shapes.pyx

Check the input data, and raise an exception if it is not valid.

[shapes] ValueError if the array do not have the right shape

---

examples/scatterview.py

Hi,
I notice there was no example for the scatter view widget.
Here is one, if you like.

Create an example for the ScatterView widget

---

silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/items/roi.py
silx/gui/plot/tools/roi.py
silx/gui/plot3d/tools/PositionInfoWidget.py

add a common base class for ROI and regionOfInterest

---

silx/gui/_glutils/OpenGLWidget.py

This PR takes extra care with first call to OpenGL, as exception can occur here.
closes #2797

Add try except around first OpenGL call

---

doc/source/modules/opencl/convolution.rst
silx/gui/colors.py
silx/gui/data/NumpyAxesSelector.py
silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/StatsWidget.py
silx/gui/widgets/RangeSlider.py
silx/opencl/sinofilter.py

This PR fixes some warnings during the build of the doc and also renames `_BasicGridStatsWidget` to `BasicGridStatsWidget` in sample code of the docstring.

Fix doc build warnings

---

silx/opencl/common.py

allows using PortableCL driver with Nvidia GPU (like on the Power9)

2695 tesla pocl

---

silx/gui/plot/items/core.py
silx/gui/plot/items/scatter.py

This PR allows to provide parameters for the regular grid visualization, that when provided replace the guessing.
Those parameters are:
- `GRID_ORDER`: 'C' or 'F' as in numpy for row- or column- major order
- `GRID_BOUNDS`: ((x, y) of first point, (x, y) of last point)
- `GRID_SIZE`: (width, height) number of grid cells in each dimension
`GRID_BOUNDS` and `GRID_SIZE` can be wider than the current number of points, so one can provide the final values of those and only update the data (e.g., for live monitoring...)
Still to do: Use `GRID_BOUNDS` as the bounds of the item when provided?
related to #2743

Scatter regular grid visualization parameters

---

silx/gui/dialog/ColormapDialog.py
silx/gui/widgets/ColormapNameComboBox.py

Move `ColormapNameComboBox` from `ColormapDialog` to the public API `silx.gui.widgets`.

Expose ColormapNameComboBox in silx.gui.widgets

---

silx/io/specfile/src/sflabel.c

A user had an ID26 file with ~220 motors.

[IO] Specfile. Increase maximum number of motors

---

silx/gui/utils/test/__init__.py
silx/gui/utils/test/test_testutils.py
silx/gui/utils/testutils.py

I guess it will not work for python<3.4
Let see the CI
Closes  #2816

Robustness on testutils

---

silx/gui/plot/items/core.py
silx/gui/plot/items/scatter.py
silx/gui/plot/test/testPlotWidget.py

This PR makes some rework of PR #2815 according to some comments there and add some tests for regular grid visualization.

Scatter regular grid update

---

silx/gui/plot/items/complex.py
silx/gui/plot/items/core.py
silx/gui/plot3d/_model/items.py
silx/gui/plot3d/items/volume.py
silx/gui/plot3d/scene/primitives.py

This PR adds the possibility to display a 3D field of complex data as a colormapped isosurface.
The parameter tree is updated accordingly.
closes #2323

[plot3d] Add colormapped isosurface to ComplexField3D

---

doc/source/modules/gui/icons.rst
examples/dropZones.py
examples/fileDialog.py
examples/plotStats.py
silx/gui/data/DataViewer.py

This PR provides a few fixes spotted while testing the sample codes:
- Update list of icons in doc
- Remove debug message from sample code
- Fix `plotStats.py`
- Change log level in dataviewer.

Fixes for 0.12.0

---

CHANGELOG.rst
version.py

This PR updates the changelog and version to release.
To be merged after PR #2868

Prepare 0.12 release

---

CHANGELOG.rst
doc/source/modules/gui/icons.rst
examples/dropZones.py
examples/fileDialog.py
examples/plotStats.py
silx/app/view/main.py
silx/gui/data/DataViewer.py
silx/gui/dialog/ColormapDialog.py
silx/gui/fit/FitWidget.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/ProfileMainWindow.py
silx/gui/plot/StatsWidget.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/items/shape.py
silx/gui/plot/tools/profile/_BaseProfileToolBar.py
silx/gui/plot3d/tools/PositionInfoWidget.py
silx/math/fit/fitmanager.py
silx/math/fit/test/test_fitmanager.py
silx/sx/_plot.py

This PR ports changes made on the 0.12 branch for release v0.12.0.
It contains the following PRs:  #2839, #2849, #2851, #2852, #2853, #2857, #2860, #2861, #2864, #2867, #2868, #2869

Port v0.12.0 latest changes

---

doc/source/overview.rst
doc/source/troubleshooting.rst

update debian version of silx.org debian repo

---

silx/gui/plot/PlotInteraction.py
silx/gui/plot/items/marker.py
silx/gui/plot/items/roi.py

Add feedback on item darg & drop

---

silx/gui/plot/backends/BackendBase.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/items/complex.py
silx/gui/plot/items/curve.py
silx/gui/plot/items/histogram.py
silx/gui/plot/items/image.py
silx/gui/plot/items/scatter.py
silx/gui/plot/items/shape.py

This PR clean-up the `z` argument from plot backend `add*` method which is no longer used.

plot backend clean-up

---

silx/gui/data/Hdf5TableView.py

The chunks cell did not display anything in silx view. A conversion from tuple to string seems to be necessary.

fix display of chunks in silx view

---

silx/gui/plot/backends/BackendBase.py

This `check` argument is not implemented by the backend implementations.

Clean up backend base

---

silx/gui/colors.py
silx/gui/dialog/ColormapDialog.py
silx/gui/dialog/test/test_colormapdialog.py
silx/gui/plot/CurvesROIWidget.py
silx/gui/plot/PlotWidget.py
silx/gui/plot/items/histogram.py

Closes #2908
- Fix few bugs
- Fix few warnings
- Display lut in the logscale plot using markers
- Use continuous histo in log when data input range is uint8

Improve colormap dialog

---

bootstrap.py

Small PR reworking `bootstrap.py` to add start of jupyter notebook with right `sys.path` with `python boostrap.py -j`.

bootstrap.py working with jupyter

---

silx/app/view/Viewer.py

This PR adds a `Close All` action to the `File` menu of `silx view`.
closes #2945

[silx view] Add Close All menu

---

silx/gui/plot/backends/BackendMatplotlib.py

This PR fixes a regression on the handling of plot background colors following PR #2964.
closes #2967

Fix handling of PlotWidget background color

---

silx/gui/plot/actions/fit.py
silx/gui/plot/test/testStats.py

This PR makes the `FitAction` work with curves on the right Y axis.
It also deprecates the `legend` attribute.
closes #2968

Fix FitAction support of Y right axis 

---

ci/appveyor.yml
silx/io/nxdata/parse.py
silx/io/test/test_nxdata.py

[io] NXdata support signal_dataset_name_errors for signal_dataset_name

---

silx/gui/plot/test/testCurvesROIWidget.py
silx/gui/plot/test/testStats.py

Fix tests using assertEqual

---

examples/imageStack.py
silx/gui/plot/ImageStack.py
silx/gui/plot/test/__init__.py
silx/gui/plot/test/testImageStack.py
silx/gui/widgets/UrlSelectionTable.py

[ImageStack] Add ImageStack.py file

---

silx/io/url.py

Fix not equal test

---

ci/before_install-osx.sh

This PR aims at fixing CI broken for macos.

Fix download link for miniconda on macos

---

silx/gui/plot/ProfileMainWindow.py

This PR ensures the profile window remains on top of the plot window.
closes #2935

[plot] Keep profile window always on top

---

silx/gui/plot/test/testCurvesROIWidget.py

Small PR to remove few print in the tests.

Remove print

---

silx/gui/colors.py
silx/gui/dialog/ColormapDialog.py
silx/gui/dialog/test/test_colormapdialog.py
silx/gui/plot/ColorBar.py
silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/backends/glutils/GLPlotImage.py
silx/gui/plot/matplotlib/Colormap.py
silx/gui/plot3d/scene/function.py

This PR is a first step to add more normalization to `Colormap` and add a `sqrt` normalization.
Tasks:

[plot] Add support for more colormap normalization

---

silx/gui/plot/tools/roi.py

There was a typo in one of the previous PR.

[roi] Fix unknown method

---

setup.py
silx/third_party/_local/scipy_spatial/qhull.pyx

There are issues within the qhull code which is not cython3-ready.

Setup.py modifications to make the code Cython3 compatble

---

setup.py

have man pages generated in a reproducable manner

---

silx/gui/plot/items/roi.py
silx/gui/plot/tools/test/testROI.py

This PR fixes issue #3043 
In some circumstances with PySide2, the use of `self.sender()` returns None.
- It looks like it is the case for some private methods
- Maybe only for signals without values
Closes #3043

[roi] Fix HandleBasedROI with PySide2

---

silx/opencl/sift/alignment.py

correct destructor

---

doc/source/conf.py
doc/source/modules/gui/plot/tools/profile.rst
silx/gui/plot/items/roi.py
silx/gui/plot/tools/profile/rois.py
silx/gui/plot/tools/roi.py

As the complexity of the project grow up, it would be nice to have a better idea to what we have.
Here is a spinx module to create automatically diagrams.
Yet it is not a very convenient tool, the ROI diagram is quite "ok", but the profile one is horrible. Maybe i will take a look at their code.
Anyway it's maybe better with than without.

Inheritance diagram

---

silx/gui/plot/items/roi.py

This PR fixes an issue in master branch regarding some missing renaming of `_HandleBasedROI` to `HandleBasedROI`

Fix issue with _HandleBasedROI

---

silx/gui/colors.py
silx/gui/dialog/ColormapDialog.py
silx/gui/plot/backends/glutils/GLPlotImage.py
silx/gui/plot3d/scene/function.py

Merge PR #3054 first!
This PR adds `arcsinh` normalization to colormap normalizations.
closes #2133

Colormap arcsinh normalization

---

silx/math/colormap.pyx

Avoid cython compilation warning

---

silx/gui/dialog/ColormapDialog.py

Fix use of Qt>=5.12 only method used in ColormapDialog

---

silx/gui/plot/items/roi.py
silx/gui/plot/tools/roi.py
silx/gui/plot/tools/test/testROI.py

Few changes to make the polygon ROI behaving like others.

Polish roi look and feel

---

version.py

THis PR creating a beta release for technical use.

Bump version to beta 1

---

silx/gui/plot/tools/test/testProfile.py

Fix deprecation warnings in the profile tests

---

silx/gui/plot/tools/profile/manager.py

This is mostly cosmetic, but since this is the only way to customize the ProfileWindow, I thought that the methods should be public.

Make public some methods in the ProfileWindow

---

silx/gui/plot/tools/profile/editors.py

This PR returns the roi profile from the editor action.
I need that to clean up my menus.

Returns the roi profile from the editor action

---

silx/gui/widgets/ElidedLabel.py
silx/gui/widgets/test/test_elidedlabel.py

This PR fixes an inconsistency, valided by few tests.

Fix unsynchronized tool tip in ElidedLabel

---

ci/appveyor.yml
version.py

Bump version to 0.14.0-dev on master after creation of 0.13 branch.

bump version to 0.14.0-dev

---

silx/math/fft/test/test_fft.py

Close #3121 
(Merge request into 0.13)

[math] Rework FFT tests

---

examples/plotCurveLegendWidget.py
silx/gui/plot/backends/BackendOpenGL.py
silx/image/medianfilter.py

fix future deprecation warning

---

silx/gui/dialog/ColormapDialog.py

The adaptative spinner for gamma connection was very convinient.
This PR add it back, only if it is available.

Adaptative spiner if available

---

silx/gui/plot/PlotWindow.py

This PR fixes the displayed information in `Plot2D`'s `PositionInfo` widget when there is a mask.
This is a regression from PR #2913
closes  #3134

fix Plot2D position info with masks

---

setup.py

Advertises minimal supported python version: 3.5

---

doc/source/sample_code/index.rst
examples/dropZones.py

This PR update the `dropZone.py` sample code to be standalone and provide more information about how to use it.
closes #3100

Updating drop example

---

silx/opencl/convolution.py
silx/opencl/test/test_convolution.py

Disable textures for Nvidia Fermi GPUs

---

CHANGELOG.rst
version.py

This PR updates the changelog for release next release.
Please update/correct if need be!
I'd keep this PR open until the release so we can add bug fixes PR there.

update changelog for 0.13.0

---

silx/gui/plot/tools/profile/rois.py

This PR provides support for more Image item classes than `ImageData` and `ImageRgba`.

silx.gui.plot.tools.profile: Improved image profile tool to support PlotWidget item extension

---

silx/gui/dialog/ColormapDialog.py
silx/gui/dialog/test/test_colormapdialog.py

This PR backports PR #3153 to branch 0.13.

silx.gui.plot.dialog: Fixed ColormapDialog custom range input

---

CHANGELOG.rst
silx/math/colormap.pyx

This PR fixes the cythonization failure with current tip of cython master branch on silx branch 0.13 (see issue #3161)

Build: Fixed cython 3 compatibility

---

silx/gui/data/DataViews.py

At one point selection is not None and filename is.

[gui][DataViews] fix titleForSelection

---

doc/source/applications/view.rst

This PR update silx view command line options description in the doc.
related to  #3169

documentation: Update silx view command line options documentation

---

copyright
silx/gui/utils/signal.py

rework a bit to fit silx.
Use a default Qtimer and submitToQtMainThread instead of a ThreadsafeTimer
Was also distributed as MIT code.

[gui][utils] add signalproxy from pyqtgraph.

---

.github/pull_request_template.md

This PR proposes to add a PR template aiming at automating/easing the generation of the changelog for releases.
closes #3141

Added github Pull Request template

---

CHANGELOG.rst
doc/source/applications/view.rst
silx/app/view/Viewer.py
silx/app/view/main.py
silx/gui/data/DataViews.py
silx/gui/plot/items/core.py
silx/gui/plot/items/scatter.py
silx/gui/plot/test/testPlotWidget.py
silx/gui/utils/glutils.py
version.py

This PR backports the following PRs to branch 0.13, update the changelog and bump version to 0.13.2.
Backported PRs: #3171, #3173, #3175, #3176, #3180, #3184

Prepare v0.13.2: Backports selected PR, update changelog, bump version

---

silx/gui/widgets/test/test_legendiconwidget.py

Here is a few test coverage for LegendIconWidget.

Add test for legend icon widget

---

ci/requirements-pinned.txt

PR #3240 fixed issue #3218, pin-pointing added in PR #3231 no longer needed.

CI: Remove pin-pointing to h5py<3

---

silx/io/test/test_url.py
silx/io/url.py

silx.io.url.DataUrl: Fixed slice provided as python slice string

---

silx/gui/colors.py

Here is a very small fix when converting image value to color.

Reduce memcopy

---

silx/opencl/sift/plan.py

Let it fail ... if it shall
Note the commented code to prevent this "good" non-working idea.
Close #3241 
Changelog: Fix Sift test on modern GPU

Fix SIFT test on modern GPU

---

silx/opencl/processing.py

Does not address #3258.
I suspect the bug is in pyopencl as our caches should be clean.
Changelog: report error if encountered in destructor.

Emit a warning when there is an issue in the Ocl destruction

---

silx/gui/plot/backends/BackendOpenGL.py

silx.gui.plot.PlotWidget: Added support of right axis label with OpenGL backend

---

silx/gui/plot/actions/control.py

Deprecation warning in 3.9

---

silx/gui/plot/ImageStack.py

simple fix if no url to be set

[gui][Imagestack] fix setUrls if no url provided

---

silx/opencl/sift/plan.py

Fix the sift algorithm 

---

silx/gui/plot/actions/control.py
silx/opencl/sift/plan.py

Backports PR #3306 and #3305  to branch 0.14.

Deprecation warning in 3.9 & Fix the sift algorithm

---

silx/math/fft/test/test_fft.py

This PR relaxes the FFT tests tolerance. It seems that Cuda and FFTW do not provide consistent results from one machine to another (even using the same software versions).
Changelog: 
Fix FFT tests tolerance

Relax FFT tests tolerance

---

silx/io/setup.py
silx/io/specfile/src/locale_management.c

[specfile] use locale.h on Windows

---

silx/gui/plot/backends/BackendMatplotlib.py

This PR makes the matplotlib backend  using Qt "logical" pixel coordinates for its API, i.e., mouse events, `dataToPixel`, `pixelToData`, `pickItems` and `getPlotBoundsInPixel`.
Closes #2914
Closes #3317

silx.gui.plot.PlotWidget: Enhanced matplotlib backend high-dpi screen support by using Qt coordinates

---

silx/io/test/test_utils.py
silx/io/utils.py

compare integers, not strings

---

silx/io/test/test_utils.py
silx/io/utils.py

Use the `calc_hexversion` for ultimate security

This times it is belt & suspenders

---

silx/opencl/processing.py

Changelog: Expose the minimum workgroup size

Expose minimum (reasonable) workgroup size

---

silx/gui/plot/LegendSelector.py

Changelog: Update model's data without erasing existing legend Items.
closes  #3345

Update without erasing existing legend

---

silx/gui/plot/PlotWidget.py

Here is a small typo on the documentation.
The method is defined as:
```addCurve(replace=False)```

Consistency code/doc

---

silx/gui/plot/items/complex.py

The issue was that `ComplexImage.setData` refreshes the colormapped data with the previous data (silx/gui/plot/items/complex.py L267).
closes #3363

silx.gui.plot.PlotWidget: Fixed issue with complex image first displayed mode

---

silx/gui/plot/items/core.py
silx/gui/plot/items/scatter.py
silx/gui/plot/test/testPlotWidget.py

silx.gui.plot.PlotWidget: Enhanced curve and scatter items resilient to complex data input

---

silx/gui/widgets/FlowLayout.py

silx.gui.widgets: Fixed `FlowLayout` issue

---

silx/opencl/codec/test/test_byte_offset.py
silx/opencl/processing.py

Changelog: Print statics of OpenCL kernel execution time
Close #3394

3394 opencl statistics

---

silx/gui/plot/PlotWidget.py
silx/gui/plot/test/testPlotWidget.py

Convenient wrapper over `removeItem` to avoid try/except block.

silx.gui.plot: Added `Plotwidget.discarditem` method

---

silx/gui/plot/actions/histogram.py
silx/gui/plot/test/testPixelIntensityHistoAction.py

This PR adds basic stats (min, max, mean, std, sum) at the bottom of the histogram window of PixelIntensitiesHistoAction
closes #3215

silx.gui.plot: Added some statistic indicators in `PixelIntensitiesHistoAction` action

---

silx/gui/plot/StatsWidget.py
silx/gui/plot/stats/stats.py

Fix stats histo 2

---

CHANGELOG.rst
version.py

This PR updates the changelog and bump to version 0.15.0rc1.

Prepare 0.15.0rc1: Updated changelog and bumped version

---

silx/__main__.py
silx/app/view/test/test_launcher.py

Avoid fork-bomb when running `silx test` with Windows fat binary.
closes #3410

Misc: Fixed `silx test` application on Windows

---

silx/io/test/test_h5py_utils.py
silx/utils/retry.py
silx/utils/test/test_retry.py

Closes #3420
* Fix the issue: `Process.is_alive` can return `True` indefinitely when a *forked* subprocess segfaults. Solution: spawn subprocesses instead of forking (forking is the default on UNIX).
* Fix the issue: create a new `Queue` instance for every new subprocess
* Refactor retry tests: the timeouts (either sufficiently long or sufficiently short) were based on the retry periods which is not very clear.

Fix retry timeout tests

---

silx/io/test/test_h5py_utils.py
silx/utils/retry.py
silx/utils/test/test_retry.py

Backport PR #3422 to branch 0.15

silx.utils.retry: Fixed subprocess retry on Linux -backport 0.15

---

CHANGELOG.rst
version.py

Misc: Updated changelog and bump version

---

CHANGELOG.rst
examples/stackView.py
silx/__main__.py
silx/app/view/test/test_launcher.py
silx/gui/data/ArrayTableModel.py
silx/gui/data/RecordTableView.py
silx/gui/data/test/test_arraywidget.py
silx/gui/plot/backends/BackendMatplotlib.py
silx/gui/plot3d/scene/primitives.py

This PR ports changes made on the `0.15` branch until release `v0.15.0` (except changes made to `version.py`).
It includes the following PR: #3427, #3416. #3419, #3418, #3414, #3411, #3409.
It does not includes PR #3426 since it was a backport of PR #3422 merged on the master branch.

Port v0.15.0 changes from 0.15 branch

---

src/silx/gui/plot/actions/histogram.py

This PR makes use of `PlotWidget.selection` in `PixelIntensitiesHistoAction` in order to remove duplication of code handling selection of active item.

silx.gui.plot.actions.histogram: Refactor `PixelIntensitiesHistoAction` to use `PlotWidget.selection`

---

src/silx/io/url.py

In this case simply return False.
close #3436

[io][url] fix is_absolute in the case the file_path() returns None

---

src/silx/gui/plot/ImageStack.py

[gui][ImageStack] improve _PlotWithWaitingLabel thread management.

---

src/silx/gui/plot/ImageStack.py

add function to insure safe "ceinture and bretelles" when stopping the animation thread

WIP: Improve image stack

---

silx/gui/plot/backends/BackendOpenGL.py
silx/gui/plot/backends/glutils/GLPlotCurve.py
silx/gui/plot/backends/glutils/GLPlotImage.py
silx/gui/plot/backends/glutils/GLPlotItem.py
silx/gui/plot/backends/glutils/GLPlotTriangles.py

This merge request is a backport of #3445 to the branch 0.15.
Changelog: 
- silx.gui.plot: Fixed PlotWidget OpenGL backend memory leak

Change remove item from backend to avoid issue with paintGL not being

---

CHANGELOG.rst
version.py

Update changelog and bump version

Prepare release 0.15.1

---

src/silx/gui/colors.py
src/silx/gui/plot/ImageStack.py
src/silx/gui/widgets/UrlSelectionTable.py

This fixes logger names so that they are sub loggers of `silx`.

Fixed logger names

---

setup.py

Fixed support of numpy 1.21

---

CHANGELOG.rst
setup.py
silx/gui/colors.py
silx/gui/plot/ImageStack.py
silx/gui/widgets/UrlSelectionTable.py
silx/io/spech5.py
version.py

This PR backports PR #3469, #3463, #3476 on branch 0.15.
It also updates the changelog accordingly and bumps to version 0.15.2
closes #3470

[0.15 branch] Prepare v0.15.2

---

CHANGELOG.rst
silx/gui/plot/items/_arc_roi.py

related to #3470
backport of #3492 to branch 0.15

Backports to 0.15: silx.gui.plot: Fixed ArcROI.setGeometry 

---

CHANGELOG.rst
silx/opencl/statistics.py
silx/opencl/test/__init__.py
silx/opencl/test/test_doubleword.py
silx/opencl/test/test_kahan.py
silx/opencl/test/test_stats.py
silx/resources/opencl/doubleword.cl
silx/resources/opencl/statistics.cl

I have rebased all commits relative to the doubleword library ...

0.15.2 doubleword

---

CHANGELOG.rst

This PR adds versions `0.14.1`, `0.15.1` and `0.15.2` to the changelog in the main branch.

Misc.: Updated changelog

---

ci/requirements-pinned.txt
src/silx/conftest.py
src/silx/gui/plot/test/utils.py

This PR should fix CI by updating a pytest fixture and removes a warning by fixing a typo.
closes #3524

Misc: Fixed tests

---

src/silx/math/colormap.pyx

This PR improves error messages raised when `data` or `colors` are not supported.
It also cast `colors` to supported types (with a warning) whenever possible.
closes  #3520

`silx.math.colormap`: Improved `cmap` error messages

---

src/silx/gui/plot/ImageView.py

This PR allows to pass `numpy.array([[]])` to `ImageView.setImage`.

`silx.gui.plot.ImageView`: Added empty array support to `setImage`

---

src/silx/opencl/common.py

Support for latest GPU from Nvidia
Changelog: 
- describe compute capabilities for Ampere generation GPU from Nvidia

Provide with the compute capabilities of new GPUs

---

src/silx/io/specfile.pyx

Point to accessible location.
closes #3433

[DOC] Update location of the SpecFile library manual

---

ci/appveyor.yml
examples/colormapDialog.py
src/silx/gui/dialog/ColormapDialog.py

~~Merge PR #3540 first!~~
This PR fixes:
- an issue following method renaming `isValid` -> `is_valid`
- an issue in the `ColormapDialog` example

`silx.gui.dialog`: Fixed `ColormapDialog`

---

ci/appveyor.yml
doc/source/modules/gui/icons.rst

~~Merge PR #3540 first!~~
This PR updates the list of icons displayed in the doc.

documentation: Updated list of icons

---

requirements-dev.txt
setup.py

add hdf5plugin to requirements-dev.txt

---

src/silx/gui/plot/backends/BackendOpenGL.py

Selects black or white transparent background depending on the color of the text
closes #3564

silx.gui.plot: Improved text label background rendering with OpenGL backend

---

CHANGELOG.rst

Here are the change logs for 1.0. Please have a look and if you see anything missing or that could be ignore let me know :)

update changelog for v1.0.0

---

CHANGELOG.rst
README.rst
doc/source/applications/view.rst
doc/source/index.rst
doc/source/install.rst
src/silx/gui/plot/backends/BackendOpenGL.py
src/silx/io/nxdata/parse.py

those are commits from PR done on the 1.0 branch during the release process

WIP: Integrate modifications from 0 1

---

src/silx/utils/ExternalResources.py

Prevent any inplace modification/corruption
Changelog: Store checksum of downloaded data to prevent unexpected failure of tests due to corrupted data.
This commonly occurs in pyFAI when one calibrates test-data, the poni-file gets modified and this leads to failing tests later on.
The checksum function is SHA256 but it can easily be changed (defined at a single place). Maybe Pierre has an opinion on this ?

store the checksum of downloaded data

---

ci/requirements-pinned.txt
src/silx/gui/plot/items/axis.py

~~Merge PR #3583 first!~~
This PR fixes compatibility issues found by the CI with PySide6 >= 6.2.2.
closes #3584

Fixed `PySide6`>= 6.2.2 support

---

.github/workflows/ci.yml
src/silx/app/view/About.py
src/silx/gui/data/ArrayTableModel.py

Test latest ubuntu and qt bindings with Python 3.10

[GUI] Test Python 3.10

---

src/silx/gui/plot/backends/glutils/GLPlotImage.py

This PR fixes an issue in the OpenGL backend when displaying colormapped image of `uint8` and `uint16` with the `arcsinh` scale.
With `uint8` and `uint16`, the texture is seen from the shader as normalized values in [0, 1].
Previous implementation was normalizing the bounds of the colormap range in this case before providing it to the shader. While this is fine for linear, log, sqrt an gamma scale (which are special cases), it fails for arcsinh (and in the general case).
Instead of relying on special cases, this PR changes the implementation by reverting the normalization in the shader to perform the normalization with the data rather than the normalized one.

silx.gui.plot.PlotWidget: Fixed OpenGL image rendering of arcsinh colormap for uint8 and uint16

---

bootstrap.py

Fixing issue introduced by PR #3585

Fixed bootstrap.py script

---

src/silx/gui/plot/items/_arc_roi.py

Patch from @vallsv 
closes #3610

silx.gui.plot: Fixed arc roi display

---

setup.py

Merge PR #3653 first!
This PR removes the patching of compilation flags in `setup.py` in an effort to simplify `setup.py` as much as possible.
IMO, I'd let `setuptools` do the job (and eventually fix it).
Related to #3652

Build: Removed patching compilation flags in `setup.py`

---

src/silx/gui/plot/tools/profile/editors.py

This should fix issues regarding unconnected signal
closes #3691

silx.gui.plot.profile: Handle disconnect exception

---

package/debian10/rules
package/debian11/rules

Fixed Debian/Ubuntu packaging

---

src/silx/gui/plot/tools/profile/rois.py

Formatting was missing for stacks
closes #3696

silx.gui.plot.tools.profile: Fixed label formatting for 2D profile tool

---

src/silx/gui/plot/tools/profile/rois.py

Fix computation of the slice profile.
Changelog: 
- Fix computation of the slice profile

Fix slice profile

---

CHANGELOG.rst
ci/appveyor.yml
src/silx/_version.py
src/silx/gui/_glutils/font.py
src/silx/gui/_glutils/gl.py
src/silx/gui/plot/_BaseMaskToolsWidget.py
src/silx/gui/plot/actions/histogram.py
src/silx/gui/plot/backends/BackendOpenGL.py
src/silx/gui/plot/backends/glutils/GLText.py
src/silx/gui/plot/items/_band_roi.py
src/silx/gui/plot/items/core.py
src/silx/gui/plot/items/shape.py
src/silx/gui/plot/tools/profile/rois.py
src/silx/gui/plot/tools/test/testROI.py
src/silx/gui/utils/matplotlib.py

This PR ports PRs done on `1.1` branch and bumps version to `1.2.0dev`:
- #3709
- #3708
- #3707
- #3704
- #3702
- #3701

Port v1.1.0 PRs from 1.1 branch and bumps version to `1.2.0dev`

---

src/silx/gui/data/Hdf5TableView.py
src/silx/io/h5link_utils.py
src/silx/io/test/test_h5link_utils.py

Changelog: Fix HDF5TableView virtual and external dataset information

Fix HDF5TableView virtual and external dataset information

---

doc/source/Tutorials/writing_NXdata.rst
src/silx/io/test/test_utils.py
src/silx/io/utils.py

Changelog: fix h5todict fixed-length string issue

3747 h5todict string issue

---

src/silx/gui/qt/_pyside_dynamic.py

Changelog: Fix PySide2 deprecation with Python>3.9

close 3778

---

src/silx/utils/launcher.py

launcher: Better error message

---

src/silx/gui/constants.py
src/silx/gui/hdf5/_utils.py

Changelog: 
- Expose URI used to drag and drop `DataUrl`

gui: Expose silx dnd uri

---

src/silx/gui/colors.py
src/silx/gui/data/DataViews.py
src/silx/gui/plot/ComplexImageView.py
src/silx/gui/plot/CurvesROIWidget.py
src/silx/gui/plot/PlotWidget.py
src/silx/gui/plot/PlotWindow.py
src/silx/gui/plot/PrintPreviewToolButton.py
src/silx/gui/plot/actions/io.py
src/silx/gui/plot/items/_roi_base.py
src/silx/gui/plot/items/complex.py
src/silx/gui/plot/items/curve.py
src/silx/gui/plot/tools/PositionInfo.py
src/silx/gui/plot/tools/toolbars.py
src/silx/gui/plot3d/items/scatter.py
src/silx/gui/widgets/FrameBrowser.py
src/silx/io/nxdata/__init__.py
src/silx/io/nxdata/_utils.py
src/silx/opencl/backprojection.py
src/silx/opencl/sinofilter.py

Second round of deprecated features removal marked as such since at least January 2020.

 Removed features deprecated from v0.8 to v0.12

---

src/silx/gui/dialog/ColormapDialog.py
src/silx/gui/plot/PlotWidget.py
src/silx/gui/plot/Profile.py
src/silx/gui/plot/StackView.py
src/silx/gui/plot/actions/fit.py
src/silx/gui/plot/actions/histogram.py
src/silx/gui/plot/items/core.py
src/silx/gui/plot/stats/stats.py
src/silx/gui/plot/tools/profile/ScatterProfileToolBar.py
src/silx/gui/plot/tools/test/testProfile.py

Another round of deprecated features removal marked as such since at least March 2021.

Removed features deprecated from v0.13 to v0.15

---

src/silx/app/test/test_convert.py
src/silx/gui/_glutils/Texture.py
src/silx/gui/plot/PlotWindow.py
src/silx/gui/plot/actions/io.py
src/silx/gui/plot/backends/glutils/GLPlotImage.py
src/silx/gui/plot/backends/glutils/PlotImageFile.py
src/silx/gui/plot/items/core.py
src/silx/gui/plot/items/histogram.py
src/silx/gui/plot/items/image.py
src/silx/gui/plot3d/items/scatter.py
src/silx/gui/plot3d/scene/primitives.py
src/silx/gui/utils/test/test_testutils.py
src/silx/io/commonh5.py
src/silx/io/configdict.py
src/silx/io/specfile.pyx
src/silx/io/test/test_specfile.py
src/silx/io/test/test_specfilewrapper.py
src/silx/io/test/test_spech5.py
src/silx/io/utils.py
src/silx/math/fit/fitmanager.py
src/silx/math/test/test_histogramnd_error.py
src/silx/sx/_plot.py
src/silx/sx/_plot3d.py
src/silx/utils/deprecation.py
src/silx/utils/test/test_enum.py

This PR removes most of the remaining code for supporting Python 2.
I have not removed code with a comment stating it's for supporting Python which can be hard to test under all conditions.

Remove python2 support

---

src/silx/opencl/convolution.py

Replacing Python2 compatible code with commented Python3-only code.

silx.opencl.convolution: Removed Python 2 compatible code

---

src/silx/gui/hdf5/Hdf5TreeModel.py
src/silx/gui/plot/ImageView.py
src/silx/gui/plot/items/_arc_roi.py
src/silx/gui/plot/items/_roi_base.py
src/silx/gui/plot/items/complex.py
src/silx/gui/plot/items/image.py
src/silx/gui/plot/items/roi.py
src/silx/gui/qt/_utils.py
src/silx/gui/test/test_colors.py
src/silx/gui/widgets/LegendIconWidget.py
src/silx/math/fit/test/test_fitmanager.py
src/silx/opencl/codec/byte_offset.py

It's like mushrooms, I spotted one and found mainy...

Fixed typo: 4 `"` quotes instead of 3.

---

src/silx/app/view/Viewer.py

This PR adds Ctrl+O, Ctrl+W shortcuts for open/close all.
closes #3851

silx view: Added keyboard shortcuts for open/close all

---

src/silx/opencl/atomic.py
src/silx/opencl/common.py

close #3594
Changelog: new checking for atomic32 and atomic64 operation.

[OpenCL] atomic operation

---

src/silx/gui/plot/test/testPlotWidget.py

This PR fixes CI that was broken with PR #3862
closes  #3867

silx.gui.plot.PlotWidget: do not reset zoom when changing axes scales - follow-up

---

src/silx/io/test/test_utils.py

silx.io: Fixed small/big endian support in test

---

src/silx/gui/plot/items/_arc_roi.py

This PR makre sure the handle are now hoverable by the mouse.
Closes #3875 
Changelog:

ArcROI: Hide the handler instead of hidding the symbol

---

doc/source/modules/utils/html.rst
doc/source/modules/utils/index.rst

There is no such file

---

src/silx/opencl/common.py

Changelog: defer to pyopencl the interpretation of `PYOPENCL_CTX`

3932 pyopencl ctx

---

bootstrap.py

tools: Clean-up Python2 support code

---

src/silx/gui/plot/tools/roi.py

This PR reworks the implementation of `RegionOfInterestTableWidget` signal management.
Beforehand, it was updating the content of the whole table at each modification, leading to some layout issues of the delete button.
With this PR, the whole table is only updated when a new ROI is added or inserted. Otherwise only the modified information is updated.
This looks to fix the layout issue and should be more efficient since it decreases the number of updated information to only what is needed. This is at the expense of a more complex implementation.
closes #3929

silx.gui.plot.tools.roi: Fixed `RegionOfInterestTableWidget` glitch

---

src/silx/gui/plot/actions/histogram.py
src/silx/gui/widgets/RangeSlider.py

Changelog: RangeSlider compatibility with PyQt6

[GUI] Histogram Action. QHoverEvent does not have attribute pos

---

ci/appveyor.yml
ci/requirements-pinned.txt
src/silx/gui/utils/testutils.py

Keep testing latter versions under windows.

[CI] Test latest Python 3.12

---

src/silx/gui/plot3d/ParamTreeView.py
src/silx/gui/widgets/FloatEdit.py

Python typing done while working on #3971.
This also removes some unused signals in ParamTreeView editors.
I splitted it in 2 PRs to make it easier to review.

silx.gui.plot3d.ParamTreeView and silx.gui.widgets.FloatEdit: Added typing + cleanup

---

src/silx/gui/plot/items/image.py

minor improvement on silx.gui.plot.image checks

silx.gui.plot.items.image: improve handling of data ndim and shape

---

src/silx/gui/plot/backends/glutils/GLPlotCurve.py

Let's always draw smooth lines.
closes #3992

silx.gui.plot.PlotWidget: Fixed line rendering with OpenGL

---

src/silx/gui/widgets/RangeSlider.py

Correct error under PyQt6 with Qt 6.6.1

[GUI] PyQt6 compatibility

---

ci/appveyor.yml
src/silx/_version.py

Bump to 2.0.dev

---

src/silx/gui/plot/backends/BackendMatplotlib.py

Fixed mpl marker without background

---

CHANGELOG.rst
src/silx/_version.py

This PR prepares the changelog for the v2 release

Updated changelog and bump to v2.0.0

---

.github/workflows/ci.yml
doc/source/install.rst
setup.cfg

This PR removes supports and CI tests for Python3.7.

Removed support of Python3.7

---

src/silx/gui/widgets/LegendIconWidget.py

silx.gui.widget.LegendIconWidget: Fixed logging: removing `print`

---

CHANGELOG.rst
requirements.txt
setup.py
src/silx/_version.py
src/silx/gui/hdf5/test/test_hdf5.py
src/silx/io/utils.py

Checklist:
<hr>
This PR prepares for a v2.0.1:
- Backport PR #4074 
- Request `numpy<2`
- Update changelog and bump version to 2.0.1

Release: Prepare v2.0.1

---

README.rst

Checklist:
<hr>
Moves the appropriate links to /latest
Fixes #4095

README: Fixed some links to documentation

---

src/silx/app/view/CustomPlotSelectionWindow.py

Name display changed from path to name. 
Added a toolTip to display the name, path and filename.
Added modification of plot label X, which changes according to dataset name

silx.app.view.CustomPlotSelectionWindow : Added tooltip for name and display file name only

---

src/silx/io/h5py_utils.py

h5py_utils: Fixed base exceptions cannot be h5py exceptions

---

CHANGELOG.rst
src/silx/_version.py

Checklist:
<hr>
Update changelog and bump version to 2.2.1

Documentation: Prepare version 2.2.1

---

setup.py

setup.py: avoid sphinx 8.2

---

CONTRIBUTING.rst

doc: update release note. How to handle workflow resources build failure

---

testdata/placeholder

'testdata': remove placeholder

---

src/silx/gui/plot/MaskToolsWidget.py

Checklist:
<hr>
Suppress the warning about signal disconnection which appears when switching from `pyqt5` -> `pyside6`
close #4247

MaskToolsWidget: suppress warning in PySide6

---

CHANGELOG.rst
src/silx/_version.py
src/silx/gui/plot/_utils/__init__.py
src/silx/gui/plot/backends/BackendMatplotlib.py
src/silx/gui/plot/backends/BackendOpenGL.py
src/silx/io/h5py_utils.py
src/silx/io/test/test_h5py_utils.py
src/silx/opencl/common.py
src/silx/opencl/test/test_addition.py
src/silx/opencl/test/test_processing.py

Checklist:
<hr>
This PR updates the changelog, bump to version 2.2.2 and backports the following PRs to `2.2` branch:
- #4256
- #4246
- #4242
- #4245
closes #4257

Release: Prepare 2.2.2

---

.github/workflows/ci.yml

Checklist:
<hr>
This PR proposes to temporarily reduce the number of tests run for each PR 
closes #4238

CI: Reduced amount of tests run for each Pull Request

---

src/silx/gui/plot/_BaseMaskToolsWidget.py

silx.gui.plot: Fixed wrong tooltip description for elipse mask

---

src/silx/io/nxdata/_utils.py
src/silx/io/nxdata/parse.py
src/silx/io/nxdata/write.py

silx.io.nxdata: add typing

---

.flake8
.flake8_nb
.gitignore

Checklist:
<hr>
We don't have flake8 coverage yet but this reduces the errors when you run it.

linting: add flake8 configuration compatible with black

---

.readthedocs.yaml

.readthedocs: update source of the doc

---

.github/actions/setup-system/action.yml
.github/workflows/ci.yml

Move CI to use ubuntu-latest
~~close #4206~~

CI: use ubuntu-ci for linux test instead of ubuntu-20.04

---

src/silx/gui/plot/tools/roi.py

RegionOfInterestManager: make sure drawnROI is dropped

---

src/silx/gui/colors.py

To make it work with Flint + most of internal typing
Checklist:
<hr>

silx.gui.colors: Added typing

---

src/silx/gui/utils/glutils/__init__.py
src/silx/image/bilinear.pyx
src/silx/image/marchingsquares/_mergeimpl.pyx
src/silx/image/shapes.pyx
src/silx/io/specfile.pyx
src/silx/math/_colormap.pyx
src/silx/math/chistogramnd.pyx
src/silx/math/chistogramnd_lut.pyx
src/silx/math/combo.pyi
src/silx/math/combo.pyx
src/silx/math/fit/filters.pyx
src/silx/math/fit/functions.pyx
src/silx/math/fit/peaks.pyx
src/silx/math/interpolate.pyx
src/silx/math/marchingcubes.pyx
src/silx/math/medianfilter/medianfilter.pyx

This PR is an attempt to solve visibility of cython function from mypy
```python
import numpy
from silx.math.combo import min_max
arr = numpy.array([0, 1, 2, 3, 4, 5, 6])
r = min_max(arr)
print(r)
print(r.minimum + 1.0)
print(r.min_positive + 1.0)  # <- Error
```
```
$ mypy test_combo.py 
test_combo.py:11: error: Unsupported operand types for + ("None" and "float")  [operator]
test_combo.py:11: note: Left operand is of type "float | None"
Found 1 error in 1 file (checked 1 source file)
```
That's more or less what we expect.
Checklist:
<hr>

Draft: Improve combo

---

doc/source/conf.py
doc/source/modules/gui/widgets/overlaywidgets.rst
src/silx/gui/plot/items/axis.py

Documentation: Fixed build warnings

---

doc/source/conf.py
package/debian12/control
package/debian13/control
pyproject.toml

Checklist:
<hr>
Merge PR #4322 first !
https://github.com/silx-kit/silx/commit/8f3702b8cf50376893a54bcdf55933713fcca0ae adds the usage of https://sphinx-copybutton.readthedocs.io/en/latest/ which is convenient.
This dependency is available in debian: https://packages.debian.org/search?suite=all&searchon=names&keywords=sphinx-copybutton

Documentation: Added button to copy code blocks to clipboard

---

pyproject.toml

Checklist:
<hr>
Follow-up of #4277 , this PR reworks/updates the project dependencies and optional dependencies.

Build: Updated dependencies

---

.github/workflows/ci.yml

Checklist:
<hr>
This PR move the black checking to the check job so it is run once.

CI: Updated black checking

---

examples/compareBackends.py
examples/customDataView.py
examples/customHdf5TreeModel.py
examples/dropZones.py
examples/findContours.py
examples/hdf5widget.py
examples/viewer3DVolume.py

Checklist:
<hr>
This PR fixes warnings raised by flake8 in the examples scripts

silx.examples: Fixed flake8 warnings

---

src/silx/image/test/test_bilinear.py
src/silx/math/fit/__init__.py
src/silx/math/fit/test/test_fit.py

silx.image, silx.math: Fixed flake8 warnings

---

src/silx/resources/__init__.py
src/silx/third_party/EdfFile.py
src/silx/third_party/TiffIO.py

silx.resources, silx.third_party: Fixed flake8 warnings

---

src/silx/io/__init__.py
src/silx/io/configdict.py
src/silx/io/dictdump.py
src/silx/io/nxdata/__init__.py
src/silx/io/nxdata/parse.py
src/silx/io/octaveh5.py
src/silx/io/test/test_commonh5.py
src/silx/io/test/test_fabioh5.py
src/silx/io/test/test_fioh5.py
src/silx/io/test/test_nxdata.py
src/silx/io/test/test_specfilewrapper.py
src/silx/io/test/test_spech5.py
src/silx/io/utils.py

silx.io: Fixed flake8 warnings 

---

src/silx/gui/plot/PlotWidget.py

silx.gui.plot.PlotWidget: Fix _getItem (and derived methods) typing

---

src/silx/gui/plot/CurvesROIWidget.py
src/silx/gui/plot/MaskToolsWidget.py
src/silx/gui/plot/PlotWidget.py
src/silx/gui/plot/ROIStatsWidget.py
src/silx/gui/plot/StackView.py
src/silx/gui/plot/StatsWidget.py
src/silx/gui/plot/_utils/__init__.py
src/silx/gui/plot/actions/__init__.py
src/silx/gui/plot/backends/BackendMatplotlib.py
src/silx/gui/plot/items/__init__.py
src/silx/gui/plot/items/_roi_base.py
src/silx/gui/plot/items/histogram.py
src/silx/gui/plot/items/image.py
src/silx/gui/plot/items/scatter.py
src/silx/gui/plot/stats/__init__.py
src/silx/gui/plot/test/test_imagestack.py
src/silx/gui/plot/test/test_masktoolswidget.py
src/silx/gui/plot/test/test_plotwidget.py
src/silx/gui/plot/test/test_scattermasktoolswidget.py
src/silx/gui/plot/test/test_utilsaxis.py
src/silx/gui/plot/tools/PositionInfo.py

silx.gui.plot: Fixed flake8 issues

---

src/silx/__main__.py
src/silx/_version.py
src/silx/conftest.py

silx: Fix flake8 in `src/silx/*.py`

---

.flake8

flake8: fix ini syntax

---

pyproject.toml

pyproject.toml: add flake8
