silx/gui/plot/items/core.py, silx/gui/plot/items/scatter.py, silx/gui/plot3d/items/scatter.py
This PR provides an extra visualization of scatter plots as image for cases where the points are on a regular grid.
related to #2743
TODOs: Better guessing of the image dimension, including handling points on a single line, backward direction for both axes, y as fast moving dimension
=> Scatter plot regular grid visualization mode

silx/gui/plot/StackView.py, silx/gui/plot/actions/io.py
This PR adds a filter in the `SaveAction` of `StackView` which makes possible to save all the stack in an hdf5 file.
We need to specify that the 'IMAGE_STACK_FILTER_NXDATA' is an 'Append' action to the file.
If 'IMAGE_STACK_FILTER_NXDATA' should be stored in StackView then we need to add an 'addAppendFilter' function.
/close #2812
=> Add action to save stack of images

silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py
This PR makes the plot picking code compatible with numpy 1.12 where the `axis` argument of `numpy.flip` has no default value.
=> [plot] Make code compatible with numpy 1.12

silx/gui/plot/items/core.py, silx/gui/plot/items/scatter.py
This PR adds an irregular grid mode to scatter plot visualization.
It provides a way to visualize the data as an irregular grid.
I would consider it an experimental feature to see what it can provide.
Todo: testing, picking.. optimization probably
closes #2743
=> Add an irregular grid rendering mode for scatter plots

silx/gui/plot/PlotWidget.py, silx/gui/plot/items/__init__.py, silx/gui/plot/items/shape.py, silx/gui/plot/test/testPlotWidget.py
This PR introduce a `BoundingRect` item.
It is a kind of shape, which is not displayed but considered as part of the data.
This can be used to custom the expected visible region of the plot.
=> Create BoundingRect item

silx/gui/plot/PlotInteraction.py
The documentation says a tuple is expected although the colors.rgba method deals with arrays just fine.
=> [plot] A four-element array leads to a comparison error.

silx/gui/plot/StackView.py
Should fix #2809 but there is probably plenty of cases where the stack colormap might fail.
from @t20100 : For now the best option seems to be to add a button to update vmin and vmax from the stack values.
=> [gui][StackView] fix autoscale=True option

.travis.yml, ci/appveyor.yml, ci/requirements-pinned.txt, requirements-dev.txt, requirements.txt
This PR updates the continuous integration matrix and requirements file to stop testing python < 3.5.
=> Stop testing python2.7 + simplify requirements file

silx/gui/plot/items/shape.py
Here is a fix to avoid to fail when `BoundRect` is None and the plot is in log.
=> Fix none and log bound

silx/gui/plot/backends/BackendMatplotlib.py
This PR includes and supersedes PR #2843 by taking care of casting to int or not depending on the usage.
It casts to int for mouse events, and leaves it as float for `dataToPixel` and `pixelToData`.
It also fixes types for `getPlotBoundsInPixels` as this is documented to be `int`.
=> [mpl backend] Fix mouse-y location to integer

silx/gui/dialog/ColormapDialog.py
This PR makes sure plot items from the `ColormapDialog` are render in the right order by giving them a `z`.
Beforehand the rendering order was not guaranteed.. and it turned out to break with plot rendering/picking refactoring.
closes  #2850
=> [plot] ColormapDialog: Add z order to plot items to ensure rendering order

silx/gui/plot/PlotWidget.py
This PR fixes the addition of items with `PlotWidget._add` that are not visible.
There was an issue with the update of the dirty flag in this case. 
closes #2844
=> [plot] Fix plot add invisible item

silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes the rendering of the crosshair with the matplotlib backend which was due to the refactoring of the plot rendering and the fact that the right axes are on top of the left ones.
closes #2841
=> [plot] Fix matplotlib crosshair rendering

silx/gui/plot3d/tools/PositionInfoWidget.py, silx/sx/_plot.py
This PR fixes issues with renaming ROI's `get|setLabel` to `get|setName`:
- Renaming was not done in `sx.ginput` while it is needed.
- Renaming has been done accidentally in `plot3d` where it is not done (and can wait another release).
=> Fix renaming of  get|setLabel to get|setName

silx/app/view/main.py
This PR makes `silx view` no longer locking opened HDF5 files.
It also adds a  `--hdf5-file-locking` option to re-enable the file locking (which is the current behaviour).
What happens when someone removes stuff from the HDF5 file from another process is undefined, though quick tests shows that it does not crash.
See discussion and details here: https://gitlab.esrf.fr/bliss/bliss/issues/1241
closes #2859
=> Disable hdf5 file locking by default, add option to enable it

silx/io/test/test_dictdump.py
This PR avoids an `h5py` deprecation warning during the tests
=> Avoid h5py warning during tests

silx/gui/plot/tools/profile/_BaseProfileToolBar.py
This PR avoid to show the profile when the user click on the 'clear profile' action.
=> Show the profile window only if there is data to display

silx/gui/fit/FitWidget.py, silx/gui/plot/ProfileMainWindow.py, silx/math/fit/fitmanager.py, silx/math/fit/test/test_fitmanager.py
This PR adds support of not finite values in fit by ignoring them.
It also fixes some calls to not existing `warnings.warning` function in `FitWidget`, and add top and bottom margins in the profile 1D plot.
=> Add support of not finite values in the fit

.travis.yml, ci/appveyor.yml
This PR avoids running CI on branches other than master and x.y.
This prevents to run CI on branches (so running twice) when pull requests are created from the github web interface.
=> [CI] only run CI on master and x.y branches

silx/app/view/Viewer.py
Closes  #2879
Without this fix the action to `expand all/collapse all` is not working.
This could be part of fix for 0.12
=> Fix typo in depth of collapse/expand

silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/Profile.py, silx/gui/plot/StackView.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/shape.py, silx/gui/plot/test/testItem.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/testPlotWidgetNoBackend.py
This PR:
- Creates a method `addShape` to replace `addItem`
- Add deprecation warning to fix use of `addItem`
- Replace `addItem` with `addShape` in the base code
Related to #2830
=> Create addShape, deprecate addItem

silx/gui/plot/backends/BackendMatplotlib.py
Closes  #2883
This patch disable the use of an offset in the axis to display the real value.
From matplotlib feedback, this way do display the axes is named `scientific` style. I don't really know what is the purpose of `useOffset`.
The following rendering is no more available:
=> Display the real value in the axis

silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/items/complex.py, silx/gui/plot/items/image.py, silx/gui/plot/items/scatter.py
! Merge PR #2876 first !
This PR provides some rework of PR #2876 in order to avoid passing the item to the backend.
Instead, for autoscale colormaps, provides a copy of the item colormap with the range set to what the autoscale has computed.
This leverages the item's range cache without changing the backend.
=> Update backend following colormap min/max cache

silx/gui/plot/matplotlib/__init__.py
This PR removes the following warning, and makes the plot compatible with `matplotlib` v3.3.
```
WARNING:py.warnings:C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\matplotlib\__init__.py:59: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
matplotlib.use(backend, warn=warn, force=force)
```
If we are to make a v0.12.1, this should go into it.
=> make code compatible with matplotlib 3.3

doc/source/modules/gui/hdf5/getting_started.rst, examples/viewer3DVolume.py, silx/app/view/test/test_view.py, silx/gui/data/test/test_arraywidget.py, silx/gui/dialog/DataFileDialog.py, silx/gui/hdf5/test/test_hdf5.py, silx/io/utils.py
This PR makessure all call to `h5py.File` within silx provides the `mode` argument.
This prepare the code for `h5py` v3.0 and remove a deprecation warning.
closes #2892
=> Set the mode of h5py.File to remove deprecation warnings

silx/gui/_glutils/font.py, silx/gui/plot/ColorBar.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot3d/SFViewParamTree.py, silx/gui/utils/testutils.py, silx/gui/widgets/RangeSlider.py
This PR fixes the following deprecation warning with python 3.8:
```
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
```
Those were found in CI logs (see https://ci.appveyor.com/project/ESRF/silx/builds/30254806/job/p3800jrftcqxa9sr?fullLog=true), this PR does not fix this can of warning of Qt related calls.
=> Fix implicit int cast deprecation warning with python 3.8

silx/gui/colors.py, silx/gui/dialog/ColormapDialog.py, silx/gui/plot/actions/control.py, silx/gui/plot/items/core.py, silx/gui/test/test_colors.py
Closes #2739
The PR #2876 have to be merged first
This PR provides a new autoscale for image using standard deviation.
- Add `autoscaleMode` to the `Colormap`
- Add `STDDEV3` to compute range from data using: `mean ± 3 * std`
- Allow to set a plot item to the `ColormapDialog`
- Use colormap API from the dialog to compute the range
Note:
- The autoscale mode edition in the `ColormapDialog`will be part of another PR
=> Provide stddev autoscale

silx/gui/colors.py, silx/gui/plot3d/_model/items.py
This PR follows PR #2877 and integrates the autoscale mode in the `plot3d` parameter tree.
The parameter tree doesn't like `numpy.float64`, so I cast the stddev3 colormap range to `float` (as is the minmax range).
=> Add colormap autoscale mode to plot3d parameter tree

silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes an issue with the crosshair being displayed with an offset when the right y axis is on.
The issue was due to matplotlib events being received in right Y axes, while crosshair lines are displayed in the left Y axes.
closes #2899
If we make a 0.12.1, this should be included in it.
=> [plot] Fix crosshair offset issue with right axis

silx/gui/data/Hdf5TableView.py
This PR aims at making the text of the `HDF5TableView` selectable, so that it is clearer what should be done to copy it.
It is an alternative to #2898 (as proposed by @vallsv in #2898).
The way it is done sounds like doing arm-twisting to Qt: Using read-only editor and playing around with the way `QlineEdit` automatically set selection to overcome it.
=> Make text selectable in Hdf5TableView

silx/gui/_glutils/OpenGLWidget.py, silx/gui/plot/PlotWidget.py, silx/gui/test/__init__.py, silx/gui/utils/glutils.py, silx/gui/utils/qtutils.py, silx/gui/utils/test/test_glutils.py
This PR adds a `isOpenGLAvailable` function in a `silx.gui.utils.glutils` module.
This function checks whether a specific version of OpenGL (2.1 by default as it is used by `silx`) is really available.
It does different checks and end-up running a small Qt OpenGL widget in a subprocess...
TODOs:
closes #2866
=> Check Opengl availability

silx/gui/plot/Interaction.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/test/testInteraction.py
This PR adds pan with middle button for all available interaction modes.
This is achieved by extending the `ClickOrDrag` class to configure which button supports interaction.
The structure of the interaction code can be improved (it's a bit of a mix of things now), but the feature is there.
superseed PR #2885
=> Pan with middle button

examples/fftPlotAction.py, examples/plotCurveLegendWidget.py, examples/plotItemsSelector.py, silx/gui/plot/ComplexImageView.py, silx/gui/plot/ItemsSelectionDialog.py, silx/gui/plot/LegendSelector.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/ScatterMaskToolsWidget.py, silx/gui/plot/StatsWidget.py, silx/gui/plot/actions/fit.py, silx/gui/plot/actions/medfilt.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/image.py, silx/gui/plot/items/roi.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/testPlotWidgetNoBackend.py, silx/gui/plot/test/testPlotWindow.py, silx/gui/plot/tools/CurveLegendsWidget.py
This PR completes the objet orient plot item API by making `add|removeItem` the public version of `_add` and `_remove`, so one can instanciate and item and add it to the plot.
With `sigItemAdded`, `sigItemAboutToBeRemoved` and `getItems` to me, the API is completed.
Compatibility of `add|removeItem` is maintained (with a deprecation).
TODO:  handle item legends: init with a unique default legend.
=> Plot item objet API

silx/gui/dialog/ColormapDialog.py
This PR renames a call to `PlotWidget._add` to `PlotWidget.addWidget` to avoid a deprecation warning.
=> Use PlotWidget.addItem instead of _add

silx/gui/plot/PlotWindow.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/items/_pick.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testPlotWidget.py
This PR improves the implementation of image picking in the `PlotWidget`.
Beforehand, getting the picked array indices was done in the `Image` item itself, and the backends had different behaviours: the OpenGL was also doing it, but not the matplotilb one.
This PR makes both backends returning the picked indices in the array and removes the implementation in the `Image` and `Scatter` items. This avoids duplicating the image picking in each item that needs it.
=> Consistent plot backend image picking

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/items/core.py, silx/math/test/test_colormap.py, silx/math/test/test_combo.py
Whenever possible, this PR replaces the use of `warnings.catch_warning` by `numpy.errstate` which is more specific.
=> Use numpy.errstate to ignore warnings

silx/gui/dialog/ColormapDialog.py
This PR makes sure the dialog is still valid in Qt whan called from weakref callbacks.
closes #2921
=> Fix ColormapDialog weakref callback issue

silx/gui/plot/items/scatter.py
This PR makes the `Scatter` item `REGULAR_GRID` visualization mode resilient to:
- Number of scatter points being higher than the number of element of the given grid shape (closes #2916)
- NaNs in the X and Y coordinates.
=> Makes scatter plot regular grid display more resilient

silx/gui/dialog/ColormapDialog.py
This PR allows to sync the repaint of the histogram
Both markers and histogram and range are set at the same time, which avoid blinking when the image is often updated.
This can be checked with `example/examples/plotUpdateImageFromThread.py` by using auto scale and maybe adding random peaks.
=> Call _updateMarkerPosition inside the paintEvent

silx/gui/plot/Profile.py
This PR avoids to move the profile window after the first display.
This is to make it friendly with live update of the plot.
closes #2931
=> Avoid to move profile after first display

silx/io/utils.py, silx/utils/ExternalResources.py
This PR removes a few more deprecation warning related to python 3.8
related to #2929
=> fix py3.8 DeprecationWarning: invalide escape character

silx/gui/plot/PlotWidget.py, silx/gui/plot/items/__init__.py, silx/gui/plot/items/shape.py, silx/gui/plot/test/testPlotWidget.py
This PR adds 2 items to the `PlotWidget` items: `XAxisExtent` and `YAxisExtent` which allows to define data extent along each axis to be taken into account by reset zoom. Those items do not display anything.
Those are similar to the `BoundingRect` item except that they only interfere with the data range on a single axis.
closes #2926
=> PlotWidget XAxisExtent and YAxisExtent items

CHANGELOG.rst, requirements.txt, setup.py, version.py
This PR updates the Changelog and fabio minimum required version to 0.9 (needed after PR #2930).
It also bumps the version to 0.13.0beta0
=> Update changelog, requirements to prepare 0.13.0beta0 tag

silx/gui/plot/ItemsSelectionDialog.py, silx/gui/plot/PlotToolButtons.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/StatsWidget.py, silx/gui/plot/actions/fit.py, silx/gui/plot/items/axis.py, silx/gui/plot/test/testCurvesROIWidget.py, silx/gui/plot/test/testPlotWidgetNoBackend.py, silx/gui/plot/tools/PositionInfo.py
This PR replace the use of `PlotWidget._getAllMarkers` and `PlotWidget._getItems` by `PlotWidget.getItems` and deprecates the former private methods.
Following PR #2904, this reduces the amount of methods used and moves towards using the item-based API internally.
=> [plot] Replace usage of PlotWidget's _getAllMarkers and _getItems by getItems

silx/gui/dialog/ColormapDialog.py, silx/gui/dialog/test/test_colormapdialog.py
This PR catch the `DeferredDelete` to avoid to edit sub widget after the execution of the `exec`.
Without this patch, C++ exception is raised, cause the widget children do not exist any more.
Note that the use of `exec` is not recommanded by Qt, especially cause of this kind of problems.
=> Fix ColormapDialog when deleted while waiting for exec result

silx/gui/_glutils/OpenGLWidget.py
This PR keeps a reference on the wrapper of the returned OpenGL context, else PyQt5 returns a new python object for each call (as opposed to PySide2).
This was messing up the management of the life cycle of OpenGL resources and apparently creating a memory leak.
Hopefully closes  #2956
=> Fix OpenGL context management

silx/gui/plot/backends/BackendMatplotlib.py
This PR uses matplotlib `Axes.set_frame_on` rather than `set_axis_on|off` to show/hide the axes as it keeps the grid.
closes #2943
=> [plot] Use set_frame_on to keep grid while hiding axes

silx/gui/fit/FitWidget.py, silx/gui/plot/ItemsSelectionDialog.py, silx/gui/plot/actions/fit.py
!!! Merge PR #2960 first !!!
This PR provides:
- Simpler message in pop-up when estimate/fit fails.
- Fix issue when plot is cleared while the user is choosing the curve to fit.
- Deprecates `FitAction`'s `x`, `y`, `xlabel` and `ylabel` attributes.
- Adds `FitAction.get[X|Y]Data` methods.
- Hides the `FitWidget` when the user `Cancel` the curve selection.
- Makes `handle_signal` resilient to being called while it should not.
closes #2952
=> Some fixes and minor improvements for FitAction

silx/gui/plot/PlotWindow.py, silx/gui/plot/test/testPlotWindow.py
This PR fixes the handling of tabbed dock widget in the `PlotWindow` by overriding `removeDockWidget` and adds a small test  for it.
closes #2940
=> Fix PlotWindow tabbed dock widget management

silx/io/test/test_url.py, silx/io/url.py
if data_slice is not an iterable simply convert it to str instead of calling '",".join([slice_to_string(s) for s in self.__data_slice])' which fails if data_slice is not an iterable
closes #2972
=> [io][url] fix path() when data_slice is not an iterable.

examples/customSilxView.py, silx/app/view/Viewer.py, silx/app/view/main.py, silx/gui/data/DataViews.py
This example allow to add custom behavior to silx view.
- Create a hook on the `DataViewer` to allow to custom the widgets in the application side
- Create a silx view factiory for `Viewer` (the main window) and `ApplicationContext` (a single instance object which basically share the context of the application)
- Create an example to add an action to custom the `Plot1D` background color
It can be tested this way:
```
./bootstrap.py examples/customSilxView.py foo.h5
```
Or this way (i guess)
```
python -m silx.examples.customSilxView foo.h5
```
=> Create an example to custom silx view

silx/gui/data/DataViewer.py, silx/gui/data/DataViews.py
This PR adds a title to plots in silx view taking the dataset path and slicing information into account.
This paves the way to have a configurable way of deciding what the title is built from.
Initially proposed in PR #2978 by @vallsv 
related to PR #2974
=> [silx view] add title to plots

silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes an issue with matplotlib backend returning indices outside of the bounds of the image when on the edge.
closes #2990
=> Fix out-of-bound row/column indices

silx/gui/plot/PlotToolButtons.py, silx/gui/plot/ScatterView.py, silx/gui/plot/items/core.py, silx/gui/plot/items/scatter.py, silx/gui/plot/test/testPlotWidget.py
Merge PR #2912 first!
This PR adds the option to select the reduction function (mean, count, sum for now) for the histogramming visualization of the scatter plot.
This PR also renames the "histogram" visualization mode to "binned_statistic" which is more generic.
=> Add option to select the reduction function for "histogram" of scatter plot

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/plot/Profile.py, silx/gui/plot/StackView.py, silx/gui/plot/items/image.py, silx/gui/plot/test/testProfile.py, silx/utils/array_like.py
This is a small refactoring to allow to clean up other part of Silx, basically the profiles (#2988).
This PR creates an `ImageStack` in order to store in the plot a model of the stack.
An `ImageStack` is only an extends of `ImageData`. That's a 3D stack, in which only a single frame is displayed.
Storing the stack in the plot allows to rework other part of the GUI with this extra information. The profile do not need anymore a dependency to this `StackView` view in order to display a profile in the 3D depth. Other tools can also benefit to it, like a generic statusbar, for example.
=> Rework the StackView with a stack image plot item

silx/gui/plot/backends/BackendMatplotlib.py
This PR makes matplotlib backend resilient to PlotWidget being destroyed before leave event is handled in  the backend.
closes  #2983
=> [plot] Make mpl backend resilient in case PlotWidget already destroyed

silx/gui/data/NXdataWidgets.py
This PR avoid appending the dataset name to the plot title when the `title` attribute is defined.
closes #2998
=> [silx view] When NXdata title is defined, do not append dataset name

silx/gui/plot/items/marker.py
This PR proposes to add a `isDragged` method to plot marker items.
Indeed  there is 2 signals for start and end of dragging, but no method to retrieve the current dragging state.
=> Add a isDragged method to plot marker items

silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py
This PR fixes `PlotWidget.getInteractiveMode` that was not returning the correct mode when in "select-draw" mode.
This does not changes the API, it just fixes that... even though it would be worth using objects rather than dicts to describe the interactive modes.
=> [plot] Fix PlotWidget.getInteractiveMode

silx/io/url.py
This PR fixes a warning from Python 3.7:
If silx supports Python >= 3.3, it's fine.
```
/.../lib/python3.7/site-packages/silx/io/url.py:33: DeprecationWarning:
Using or importing the ABCs from 'collections' instead of from 'collections.abc'
is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Iterable
```
=> Fix import

silx/gui/plot/CurvesROIWidget.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/items/core.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py, silx/gui/plot/tools/test/testROI.py
This PR allows to select a ROI from the plot.
- A ROI provides `setSelectable` and `setSelectionProxy`
- When an anchor is clicked, or a ROI created, the manager update the current selected ROI
- Plus other small things relative to ROIs
- Create `sigInteractiveRoiCreationFinished` to know when the manager create a new ROI (and is not just added)
- Create `sigAboutToRemove` to allow the ROIs to clean up things
=> [roi] Allow to select a ROI

silx/gui/plot/PlotWidget.py
Here is a proposal to allow to easily set back the previously used default interactive mode.
It is useful to know what to do if we want to abort or deselect a custom interactive mode.
Now profile uses ROI, i would like to desactive the tool at the end of the interaction (in order to only deal with existing markers). And this method simplifies it.
I also did it twice on pyFAI, so i think it can be useful to share a common API for that.
You can check #3006, it can be implemented outside of the plot, but when it is used few times, i think it's better to provide it as part of the plot. 
What do you think?
=> [plot] Helper to set back the previous mode used

silx/io/dictdump.py, silx/io/test/test_dictdump.py
Merge #3013 first
This PR add test to be sure there is no regression with subtree as key in `dicttonx` and `dicttoh5`.
As the documentation said it was forbidden, but the implementation was allowing to use it, the other solution is to add assertion in case of use of `/` in the keys. Let me know if you prefer this way.
Related to @vasole  comment on #3013
=> Test dicttoh5 flat dict

silx/gui/plot/tools/roi.py
This PR rework the QAction of the ROI manager in order to have independent actions.
As result:
- 2 actions using the same ROI class will not be triggered simultaneously
- It is possible custom the way each actions behave
- Resolve the issue with parent and `getInteractionModeAction`
=> [roi] Provide an action to create new ROIs

silx/gui/plot/PlotWidget.py, silx/gui/plot/items/roi.py
Closes #3019
This PR rework the ROI architecture to normalize the handling of item events, and to reduce the the amount of creation of items.
It looks like there is now way to simplify a little mode the ROI architecture, so, i think i will spend some time on it, in order to simplify the item composition.
This PR can be reveiwed as it is else i will add some more commits.
=> Improve internal roi objects

silx/io/test/test_dictdump.py
This PR avoids usage of in memory hdf5 file in the tests since it is not available on debian 10.
closes #3021
=> Fixes compatibility with h5py <2.9  (and debian10)

silx/io/dictdump.py
This PR adds support of the `list` of `str` as attributes for `dicttoh5` (and `dicttonx`) with `h5py` < `2.9.0` (e.g., for debian 10).
closes #3030
=> Make dicttoh5/nx supports list of str attributes with h5py<2.9.0.

silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot3d/scene/function.py
This PR updates the OpenGL shaders of `plot` and `plot3d` to avoid using `uniform struct` since it is buggy in some version of mesa.
Fixes #2985
=> [gl] Workaround uniform issue with some version of mesa

silx/gui/plot/Interaction.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/actions/control.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/tools/roi.py
This PR improve the behavior of the polygon draw interaction.
- Provide another action to the context menu to close the polygon while there is the draw interaction
- The context menu is now provided by the widget, not by the backend (then it can be overwrited)
It fixes 3 issues:
- During polygon creation, using the mouse right click to open the context menu was also triggering the PlotInteraction focus class, as result it was not anymore possible to interact with the plot markers
- During polygon creation, closing the context menu was not updating the polygon while the mouse was not again moved
- Restart the plot interaction if the current drawn ROI was removed (this avoid to have a strange behavior with a recreated ROI while it was explicitly removed)
There is remained small issue:
- It …
=> Improve polygon closure

silx/gui/dialog/ColormapDialog.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/profile/rois.py, silx/gui/plot/tools/roi.py, silx/gui/plot/tools/test/testROI.py, silx/gui/utils/__init__.py
This PR aim to rework the ROIs object in order to help working with composition.
This should reduce the complexity of the code, by allowing split and of the code, and by removing complex design needed to provide magic helpers.
- `RegionOfInterest` is now abstract
- Add `_connectToPlot`/`_disconnectFromPlot` to help to manage composition
- ROIs based on simple markers became really simple classes (point, hrange, vline, hline)
- Create `_HandleBasedROI` for complex anchor management (rect, polygon...)
- The `ArcROI` was cleaned up
=> [roi/profile] Improve internal ROI objects

silx/gui/data/DataViews.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/actions/fit.py
This PR proposes to change the behavior of the `FitAction` in `Plot1D` and `silx view` to use the behaviour of live update introduced in PR #2960.
It also proposes to keep the `FitWidget` always on top (only when started from the `FitAction`), related to #2935.
=> Change FitAction behavior in silx view and Plot1D

examples/plotInteractiveImageROI.py, silx/gui/plot/PlotInteraction.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py
This PR reuse concept from `Curve` and the `CurveStyle` object to custom the highlighted state of ROIs.
I wanted to make obvious which ROI was selected. So now it's the case.
If it's fine, i still have to update the profile with it.
Possible improvements:
- Make the shapes selectable
- Make the shapes draggable
=> [roi] Create an highlighted style for ROIs

silx/gui/plot/items/roi.py, silx/gui/qt/_qt.py
This is changing the behavior of `QObject` with PyQt5 regarding multiple-inheritance to make it behave as the other bindings (i.e., PySide2 and PyQt4) by NOT isolating its call to `super().__init__(**kwargs)`
See https://www.riverbankcomputing.com/static/Docs/PyQt5/multiinheritance.html
closes #3051
=> Change behavior of QObject mulit-inheritance

silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/test/testPlotWidget.py
uint16 RGB seems to be already supported in the OpenGL backend, except for these 2 lines.
I have been testing it for a few days, now.
To test it: 
```
from silx.gui import qt
from silx.gui.plot import PlotWidget
import numpy
img_rgb = numpy.empty((300, 300, 3), dtype=numpy.uint16)
img_rgba = numpy.empty((300, 300, 4), dtype=numpy.uint16)
max_uint16 = numpy.iinfo(numpy.uint16).max
r, g = numpy.meshgrid(numpy.arange(0, max_uint16, max_uint16 / 300),
numpy.arange(max_uint16, 0, - max_uint16 / 300))
b = (r + g) / 2
a = b.T
img_rgb[..., 0] = r
img_rgb[..., 1] = g
img_rgb[..., 2] = b
img_rgba[..., 0:3] = img_rgb
img_rgba[..., 3] = a
app = qt.QApplication([])
pw = {}
for be in "gl", "mpl":
pw[(be, "rgb")] = PlotWidget(backend=be)
pw[(be, "rgba")] = PlotWidget(backend=be)
pw[(be, …
```
=> support uint16 RGB images with the OpenGL backend

silx/gui/plot/tools/profile/core.py, silx/gui/plot/tools/profile/manager.py, silx/gui/plot/tools/profile/rois.py, silx/gui/plot/tools/test/testProfile.py, silx/gui/widgets/MultiModeAction.py
This PR fix small issue relative to profile area update at the update of the active item.
- It extracts areas from the profile ROIs into an independent shape
- It creates a link from the profile ROI to the item
As result it is now possible to design this profiles by composition. But i have burned more than the time i wanted to spend here.
Most of ROIs could be merged together, reducing by 3 the amount of classes; by 3 the amount of actions. Reducing by far the complexity of the profile ROIs.
=> [profile] Split area shape from profile ROIs

silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes the name of the property used to add margin between vline/hline and text.
=> Typo on text margin property

silx/math/colormap.pyx
This small PR limits the number of OpenMP threads to at most 4 instead of using all the cores of the machine.
Previous behavior was an issue on machines with many cores for live images (e.g., in flint) where it was consuming an excessive amount of resources.
This PR provides a trade off that I hope would fit most situations...
=> limit the number of threads used to compute the colormap

silx/gui/plot/PlotWidget.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py, silx/gui/plot/tools/test/testROI.py
This PR clean up ROI when one of its item was removed from the plot.
This allows to use `plot.clear()` to also remove the ROIs, and not only the shape of the ROIs.
Closes #3065
=> Clean up roi manager

.travis.yml, silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py
This PR replaces the `iterChild` and `iterHandles` methods with `getItems` and `getHandles`.
Interest of iterator here is limited and that would be more inline with the rest of the API (and with a `Group` item).
=> Plot ROI: Replaces iterChild|Handles with getChild|Handles

.travis.yml, silx/gui/plot/items/roi.py
This PR reworks the `PlotWidget` ROI items to avoid updating and emitting the `sigRegionChanged` signal when a setter is called with the same parameters as the current ones.
This is done for all ROIs but `ArcROI` which is far more complicated than the others.
This is useful e.g., if one wants to synchronize ROI on different plots.
For `EllipsisROI`, I changed the API of `EllipsisROI.setGeometry` has changed (@PiRK is it an issue?), but now, the anchors no longer "jumps" when released after a drag.
For `HorizontalRangeROI`, I changed the order of the marker so on can enlarge the ROI when it is colapsed (before it was only possible to move it around).
closes #3071
=> Rework PlotWidget ROI items handling of events/updates

silx/gui/data/DataViews.py
Update to match change from `getPlot` to `getPlotWidget` in `StackView`.
=> Fix use of deprecated method in silx view

.travis.yml
This PR updates the OS to ubuntu18.04 and it drops testing of python3.5 since it is not available on the test image.
=> [CI] Update OS to ubuntu18.04 + update python 3.5 to 3.6

.travis.yml
This PR adds missing dependencies to run Qt with "xcb" platform.
closes #3080
=> [CI] Fix travis CI with latest Qt bindings

silx/gui/plot/ScatterView.py, silx/gui/plot/actions/histogram.py
Closes #2840 
This PR update the intnesity histogram action to support scatters
- Instead of creating `sigActiveItemChanged`, it is managed out side of the plot.
- Rework `PixelIntensitiesHistoAction`
- Uses `sigActiveItemChanged`
- Uses item, not legend
- Uses Data update
- Supports scatter (basic histogram from `getValueData`)
- Add the histogram action to the `ScatterView`
This also fixes glitsh on `silx view` when opening the histo, closing it, changing the dataset, opening again the histo window.
=> Support intensity histogram for scatter (2)

silx/io/dictdump.py, silx/io/test/test_dictdump.py
This PR fixes a warning on dicttoh5 when a path is set and the data is a dict.
In this case we expect to create a group.
```
ddict = {
("", "NX_class"): 'NXcollection',
}
with h5py.File(self.h5_fname, "w") as h5file:
dictdump.dicttoh5(ddict, h5file, h5path="foo/bar")
```
The warning was complaining that a group will be implicitly created. But as it is requested, that's an explicit action.
```
WARNING:silx.io.dictdump:key (foo/bar/) does not exist. attr NX_class will be written to .
```
=> Fix dicttoh5 warn

silx/gui/plot/tools/profile/rois.py
This PR fixes few issues related to profile
- Skip cancelled interpolators
- Do not access to `item.getPlot`, in case the item was already removed from the plot
Closes #3096
=> Mitigate concurent profiles

silx/gui/plot/actions/histogram.py, silx/gui/plot/test/testPixelIntensityHistoAction.py
This PR fixes issue on the new scatter histogram.
There was a typo on item change.
This PR fix the issue and add test to check that the histogram is updated when the active plot item changes.
=> Fix histogram when item changes

silx/gui/plot/items/scatter.py, silx/gui/plot/test/testPlotWidget.py
This PR improves the rendering of the scatter plot irregular grid visualization by no longer clipping the data to a grid, falling back to points for a single data point, and handling data as a single row/column.
closes  #2828
=> Improves scatter irregular grid visualization

examples/simplewidget.py, silx/gui/widgets/ElidedLabel.py, silx/gui/widgets/test/__init__.py, silx/gui/widgets/test/test_elidedlabel.py
This PR provides an elidable label widget.
The source code come from PyFAI, with few clean up, documentation, and test.
An example is provided as part of our "simple" widgets.
=> Provides an ElidedLabel

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/io/nxdata/parse.py, tools/create_h5_sample.py
This PR adds support of `SILX_style` hdf5 attribute storing a json string describing the plot.
For now it only supports a `axis_scale_types` key with a list of 'linear' or 'log' value:
`@SILX_style = {'axis_scale_types': ['linear', 'log']}`
Are you OK with this syntax (inspired by https://github.com/nexusformat/NIAC/issues/29)?
This is supported for curves and 2D scatters.
Display of json in silx view is ugly because of escape `\` escape characters.
related to  #2100
closes #2928
=> Add support of SILX_style attribute to tune default NX plot

silx/gui/widgets/LegendIconWidget.py
This PR fixes a glitch while displaying the colormap LUT of the legend widget.
The region used for the repaint request was used instead of the size of the widget.
As result the widget was glitching when used together with a scrollbar, for example when it was embedded in a table view.
=> Fix mismatch between widget rect and paint update rect

silx/gui/plot/MaskToolsWidget.py
This PR fixes an issue with the rectangle mask tool when drawing on the left side of the image due to negative indices in slicing.
closes #3123
=> Fixes rectangle mask drawn outside image

examples/plotInteractiveImageROI.py
This PR removes the toggle of editable ROI when selecting a mode to draw a ROI since this is hard to understand when running the sample code.
=> Sample code: Remove auto-edit behavior when adding ROIs

silx/gui/plot/backends/glutils/PlotImageFile.py, silx/gui/plot3d/utils/mng.py, silx/opencl/codec/byte_offset.py, silx/opencl/codec/test/test_byte_offset.py, silx/third_party/EdfFile.py, silx/third_party/TiffIO.py
This PR avoids numpy 1.19.x deprecation warnings about `tostring` being renamed `tobytes` (introduced in numpy 1.9).
=> Fix numpy ndarray.tostring deprecation warning

silx/gui/plot/items/roi.py
This PR allows to edit rectangular ROI an move the anchors freely without moving the other anchors even when "reverting" the rectangle (i.e., moving top-left anchor to be either the bottom-left or top-right one).
=> [ROI] Allow to move anchors to the other side of the rect

silx/gui/colors.py
Sorry, this triggers me for a while.
I have grouped together mono, perceptual, and other stuffs
=> Reorder colormaps: mono, perseptual, garbage

silx/gui/colors.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot3d/items/mixins.py, silx/gui/plot3d/scene/function.py, silx/gui/test/test_colors.py
NaN values in images were displayed differentely with the matplotlib backend (transparent) and the opengl one (as lowest bound of the colormap). 
This PR fixes this difference by making the OpenGL backend behave as the matplotlib one.
Furthermore, it adds `Colormap.get|setNaNColor` methods to allow to change the color used for NaN and it supports it in both `PlotWidget` and `plot3d`.
=> silx.gui.colors: Added `Colormap.get|setNaNColor` to change color used for NaN

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLPlotItem.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py
This PR is a small refactoring of the OpenGL backend which adds a `GLPlotItem` base class to rendering primitives.
Along with `PlotWidget.addItem`, this allows writing user's defined plot items with their own OpenGL rendering implementation.
=> silx.gui.plot: Refactored PlotWidget OpenGL backend to enable extensions

silx/gui/plot3d/items/core.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/scene/transform.py
This PR:
- fixes an issue in rendering/picking of none square 2D images (due to using not reversed shape),
- allows to toggle keep aspect ratio on/off for `Orthographic` (i.e., parallel) projection.
=> silx.gui.plot3d: Bug fix and minor improvement in scene rendering

silx/gui/colors.py, silx/gui/plot/backends/BackendMatplotlib.py
This PR avoids deprecation warnings raised by matplotlib 3.3.0rc1 during tests.
closes #3144
=> silx.gui: Fixed matplotlib 3.3.0rc1 deprecation warnings

silx/gui/dialog/ColormapDialog.py, silx/gui/dialog/test/test_colormapdialog.py
This PR fixes 2 issues on the `ColormapDialog` which was forbid the user to custom the levels of the colormap when the image was often refreshed.
It was still possible to custom the values during the time of a single frame.
This PR:
- Make sure the result of the histogram range edition is used (it was not the case)
- Make sure the handle moved bu the user are to reset during the interaction
Closes #3148
=> Fix custom levels colormap dialog

silx/image/tomography.py
The module `silx.image.tomography` uses a function `get_next_power()` which, given an integer `n`, finds the next "friendly" power of `(2, 3, 5 ,7)`. This is used for padding data before performing FFT.
The current implementation builds a sorted list of numbers in the form `(2**a)*(3**b)*(5**c)*(7**d)`, and finds the "next friendly power" by bisection. 
Building this list takes some time, which can be noticeable if `get_next_power()` is needed many times. In this PR, the list of powers is cached in a LRU structure.
=> Speed up image.tomography.get_next_power()

silx/app/view/main.py, silx/gui/colors.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/matplotlib/__init__.py, silx/gui/utils/matplotlib.py
This PR follows PR #3145 and fixes an issue it introduced (dut to the import of `matplotlib.pyplot`).
This required to move `silx/gui/plot/matplotlib/__init__.py` outside of `silx.gui.plot`, and it was moved to `silx/gui/utils/`.
closes  #3157
=> silx.gui: Deprecated `silx.gui.plot.matplotlib` module (use `silx.gui.utils.matplotlib` instead)

silx/gui/plot/items/core.py, silx/gui/plot/test/testPlotWidget.py
This PR ignores infinite values when computing the bounds of curves thus avoiding to compute infinite plot limits.
It adds a few tests for this particular case.
closes #3174
=> silx.gui.plot.PlotWidget: Fixes support of curves with infinite data

doc/source/applications/view.rst, silx/app/view/Viewer.py, silx/app/view/main.py
This PR prevents from completely hiding the left panel and adds the `-f` option to silx view as a short-cut for `--fresh`.
I choose to solve issue #3169 by disabling collapsing of the spliter since it is a simple an clean way to solve it.
The alternative of making sure the browsing panel  is visible sounds more complicated for little improvement if any.
closes #3169
=> silx view: Prevent collapsing browsing panel, Added `-f` command line option

silx/gui/utils/glutils.py
This PR fixes the runtime check of OpenGL by removing `sys.path[0]` when running the subprocess since it contains the directory of the "script", here it is `silx/gui/utils/` which also contains `signal` and `concurrent` which conflicts with python modules....
There is a check in case something is already messing around with `sys.path` (e.g., through `PYTHONSTARTUP`).
closes #3182
Some alternatives for the record:
- Copying (or creating) the script in a temporary folder
- Creating a `silx.gui.glutils` package with only `__init__` and the check script.
=> silx.gui.utils: Fix `glutils.isOpenGLAvailable` issue

silx/gui/plot/tools/roi.py
This PR avoids an exception with ROI when changing mode while a ROI is currently added.
closes #3185
=> silx.gui.plot.tools.roi: Fixed issue when changing ROI mode while a ROI is being created

silx/gui/plot/items/core.py, silx/gui/plot/items/scatter.py
This PR adds `VisualizationParameter.DATA_BOUNDS` to set the histogram range for binned statistics.
As it is, it is completely decoupled from `GRID_BOUNDS`, but it could be related, e.g., using `GRID_BOUNDS` if `DATA_BOUNDS` is not defined.
It would be cleaner to replace `GRID_BOUNDS` with `DATA_BOUNDS` as in this PR and a `GRID_DIRECTION` or `GRID_ORIENTATION` providing the information about whether X and Y increase or decrease from one point to the next, i.e., `(y direction, x direction)`... but that would change the API or make it redundant.
closes #3177
=> silx.gui.plot.items: Added `DATA_BOUNDS` visualization parameter for `Scatter` item histogram bounds

silx/gui/plot/items/roi.py
This PR triggers the refresh of the style on more events when highlighted to make sure the style is refreshed.
closes #3191
=> silx.gui.plot: Fixed `RegionOfInterest` refresh when highlighted

silx/gui/_glutils/utils.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotImage.py
This PR adds support for passing float16 data to the texture if supported by pyopengl.
This is not yet the case, see https://github.com/mcfletch/pyopengl/issues/51
It also avoids duplicating some conversion/information dicts from pyopengl.
=> silx.gui.plot.PlotWidget: Added support of float16 texture in OpenGL backend

silx/gui/plot/_utils/dtime_ticklayout.py
This PR fixes a PlotWidget issue with time serie axis when the extent of the axis is small (< 2.5us).
There was 2 issues:
- range < 2.5us as in #3192
- range << 1us
closes #3192
=> silx.gui.plot.PlotWidget: Fixed time serie axis for range < 2.5 microseconds

doc/source/modules/gui/plot/plotwidget.rst, silx/gui/plot/PlotWidget.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/actions/control.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/backends/BackendMatplotlib.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotFrame.py, silx/gui/plot/test/testPlotWidget.py
This PR adds `PlotWidget.setAxesMargins(left, top, right, bottom)` and `PlotWidget.getAxesMargins` methods for controlling the margins in which the axes and labels are displayed.
It is implemented for both matplotlib and OpenGL backends.
closes #3193 
closes #2681
=> silx.gui.plot.PlotWidget: Added `get|setAxesMargins` methods to control margin ratios around plot area

CHANGELOG.rst, silx/gui/plot/_utils/dtime_ticklayout.py, version.py
This PR backports PR #3195 to branch 0.13, updates the changelog and bumps version to v0.13.3b0.
=> Prepare v0.13.3b0: Backport selected PR, update changelog, bump version number

bootstrap.py, run_tests.py, version.py
Changelog: Switch to Python3 for all development tools.
=> use Python3 for all developer tools

silx/gui/plot/backends/BackendOpenGL.py
This PR initializes the size of the OpenGL backend with it's `sizeHint` rather than (0, 0).
This avoids retrieving a null size at the beginning (and it is consistent with matplotlib backend).
=> silx.gui.plot.PlotWidget: Fixed initial size of OpenGL backend

silx/gui/data/Hdf5TableView.py, silx/gui/hdf5/Hdf5Item.py, silx/gui/hdf5/test/test_hdf5.py, silx/io/commonh5.py
closes #3214 
Add support for external data (virtual and raw, nothing to do with external links) to `silx view`:
* add "Virtual" or "ExtRaw" to the Link column (added tests)
* add "external sources" section to the table view (no tests for this)
Data generated with [this script](https://gitlab.esrf.fr/-/snippets/226) looks like this:
=> silx view VDS and external data

silx/io/dictdump.py, silx/io/test/test_dictdump.py, silx/io/utils.py
closes #3213 
HDF5 link support:
* `dicttoh5`: values `h5py.SoftLink` and `h5py.ExternalLink` are supported
* `h5todict`: `dereference_links` option. `True` by default, otherwise the dict will contain `h5py.SoftLink` and `h5py.ExternalLink` instances.
HDF5 attribute support:
* `h5todict`: `include_attributes` option. `False` by default, otherwise the dict will contain attributes as tuple keys.
Nexus wrappers: support `">"` notation and refactor
* `h5_to_nexus_dict`:
* convert tuple keys to `"@"` key notation
* convert `h5py.SoftLink` and `h5py.ExternalLink` values to `">"` key notation (value is a URL as a string)
* `nexus_to_h5_dict`:
* convert `"@"` key notation to tuple keys
* convert `">"` key notation (value is a URL as a string) to  `h5py.SoftLink` and `h5py.ExternalLink` values
* …
=> dictdump: support HDF5 link preservation

silx/gui/hdf5/test/test_hdf5.py
@vallsv  Locally I have this test failing (not sure if it is related to my changes).
```python
======================================================================
ERROR: testSynchonized (silx.gui.hdf5.test.test_hdf5.TestHdf5TreeModelSignals)
----------------------------------------------------------------------
File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/test/test_hdf5.py", line 440, in testSynchonized
self.model.synchronizeH5pyObject(self.h5)
File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/Hdf5TreeModel.py", line 613, in synchronizeH5pyObject
self.synchronizeIndex(qindex)
File "/users/denolf/dev/silx/build/lib.linux-x86_64-3.8/silx/gui/hdf5/Hdf5TreeModel.py", line 591, in synchronizeIndex …
```
=> silx.gui.hdf5.test.test_hdf5: forgot to add TestH5Item to `suite`

silx/io/dictdump.py, silx/io/test/test_dictdump.py
This PR makes the `h5todict` function resilient to issues in the HDF5 file such as broken soft or external links or corrupted datasets, and in those cases it prints an error message and skip the link/dataset instead of raising an exception.
It also prints an error if the `path` argument is not in the file and returns an empty dict.
Basically this turn exceptions to print an error and skip.
Do we want to do that?
closes #3160
attn @vasole
=> silx.io.dictdump: Make `h5todict` resilient to issues in the HDF5 file

MANIFEST.in, pyproject.toml
This PR adds a `pyproject.toml` to the project to comply with [PEP 518](https://www.python.org/dev/peps/pep-0518/).
This enables `pip` to install `silx` in a fresh virtualenv without numpy already installed.
=> build: Added pyproject.toml to comply to PEP 518

.travis.yml
This PR should fix CI that is broken since PR #3227 (having a pyproject.toml changes the way to install from source).
=> Build: Fixed continuous integration after addition of pyproject.toml

silx/gui/plot/items/__init__.py, silx/gui/plot/items/complex.py, silx/gui/plot/items/core.py, silx/gui/plot/items/curve.py, silx/gui/plot/items/histogram.py, silx/gui/plot/items/image.py, silx/gui/plot/items/shape.py
This PR reworks PlotWidget items by adding a `DataItem` base class for items having a "data extent" in the plot.
It allows to mutualise some code and fix some minor inconsitencies between the previous different copies...
It also prepares for support of plot items updating their content depending on their visible extent.
=> silx.gui.plot.items: Refactoring PlotWidget items by adding a DataItem base class

ci/requirements-pinned.txt
Only for CI to pass, does not fix anything....
=> Build: Fixed CI by temporarily using h5py2 for tests

silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/test/testItem.py
This PR adds method `Item.getVisibleBounds`~~`Extent`~~ to PlotWidget items to retrieve the visible extent of the item bounding box in the plot area.
It also adds a private API to enable tracking changes of this visible extent through the `Item._sigVisibleBounds`~~`Extent`~~`Changed` signal.
This signal is only triggered when enabling "visible extent tracking" through `Item._setVisibleBounds`~~`Extent`~~`Tracking` and which can be retrieved through`Item._isVisibleBounds`~~`Extent`~~`Tracking`.
=> silx.gui.plot.items: Added item visible bounds feature to PlotWidget items

silx/gui/plot3d/scene/cutplane.py
This PR fixes a typo in the handling of transparency: Both alpha and transparency of the colormap should be taken into account.
=> silx.gui.plot3d: Fixed handling of transparency of cut plane

silx/gui/_glutils/OpenGLWidget.py, silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotFrame.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLPlotItem.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py, silx/gui/plot/backends/glutils/GLText.py, silx/gui/plot/backends/glutils/__init__.py
This PR reworks the `PlotWidget` OpenGL backend with a goal to improve high DPI screen support by taking into account the `devicePixelRatio` between Qt "logical" pixel and "device" pixel.
WIth this PR:
- Text is displayed with a similar size on high-dpi and standard dpi screens.
- Marker size and line width is defined in points rather than screen pixels.
closes #789
closes #2773
closes #2914
This required some internal restructuring, so rendering is now passing a `RenderContext` object for providing condition of the rendering to backend items.
It adds an `OpenGLWidget.getDotsPerInch` method.
Changelog: 
- silx.gui.plot.PlotWidget: Improved support of high-DPI screen in OpenGL backend
- silx.gui.plot.PlotWidget: Use points rather than pixels for marker size and line width with OpenGL …
=> silx.gui.plot.PlotWidget: Improved support of high-DPI screen in OpenGL backend

silx/gui/plot/backends/BackendMatplotlib.py
This PR restore behavior of silx 0.11.0 regarding sorting of items and grid with the matplotlib backend.
Items with a z value <= 0 are displayed below the grid, items with a z value >= 1 are displayed above.
Images have a default z value of 0 while curves have a default z value of 1.
closes #3233
=> silx.gui.plot: Fixed PlotWidget image items displayed below the grid by default

silx/gui/utils/testutils.py
There is no reason not to keep the QApplication once we created it, and this is causing troubles.
closes #3228
=> silx.gui.utils.testutils: Fixed handling of QApplication instance in tests.

silx/gui/widgets/ElidedLabel.py
This PR reduce memory allocation by using already defined `fontMetrics` instread of creating a new one.
=> Use widget QFontMetrics

silx/app/test/test_convert.py, silx/gui/data/test/test_textformatter.py, silx/io/dictdump.py, silx/io/nxdata/parse.py, silx/io/test/test_dictdump.py, silx/io/test/test_spectoh5.py, silx/io/test/test_utils.py, silx/io/utils.py
closes #3218 
More than just accommodating the H5T_STRING decoding changes in h5py 3.0.0rc1, this MR makes H5T_STRING decoding uniform for h5py>=2.8.0. Also the decoding behavior of datasets and attributes is made uniform.
`silx.io.test.test_utils.TestH5Strings` demonstrates the behavior.
Implementation
--------------------
Inspired by the `AsStrWrapper` of h5py 3.0 this MR introduces 2 utility classes and 3 utility methods:
* `H5pyDatasetReadWrapper`:
* wraps any dataset, regardless of the `dtype`
* NON-ASCII H5T_STRING: decode
* ASCII H5T_STRING: decode when requested
* when decoding fails, return the bytes
* `H5pyAttributesReadWrapper`:
* wraps an AttributeManager
* NON-ASCII H5T_STRING: decode
* ASCII H5T_STRING: decode when requested
* when decoding fails, return the bytes
* …
=> HDF5 strings: handle h5py 2.x and 3.x

silx/gui/plot/backends/glutils/GLPlotImage.py
This PR fixes a typo which causes a bug for displaying all zeros image with sqrt colormap normalization in the OpenGL backend of the PlotWidget.
closes #3242
=> silx.gui.plot.PlotWidget: Fixed OpenGL backend image display with sqrt colormap normalization

silx/gui/plot/tools/profile/manager.py
Here is a workaround for #3244. This remove the use of `tryTake` in a lazy way.
If we want to create a bug fix release, I suggest to only apply that in the branch, and update the supported Qt version on the master branch.
I still have to setup a Qt5.7 env to check it manually.
Changelog: 
- Fix use of `QThreadPool.tryTake` to be Qt5.7 complient
=> Workaround to use only Qt5.7 API

silx/io/dictdump.py, silx/io/test/test_dictdump.py
First check if the array is a numpy array of 'number' else do the previous treatment.
Otherwise the test added (testDumpNumpyArray) fails with h5py 3.0:
======================================================================
ERROR: testDumpNumpyArray (silx.io.test.test_dictdump.TestDictToH5)
----------------------------------------------------------------------
File "/home/payno/dev/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 239, in testDumpNumpyArray
dictdump.dicttoh5(ddict, h5file)
File "/home/payno/dev/silx/build/lib.linux-x86_64-3.7/silx/io/dictdump.py", line 226, in dicttoh5
create_dataset_args=create_dataset_args)
File "/home/payno/dev/silx/build/lib.linux-x86_64-3.7/silx/io/dictdump.py", line 255, in dicttoh5
data=data) …
=> [io][dictdump] handle providing numpy arrays of 'numbers'

silx/gui/plot/items/roi.py
Use `linspace` to make sure start end end points are part of the shape
=> Fix arc roi shape

silx/gui/data/TextFormatter.py, silx/gui/data/test/test_textformatter.py, tools/create_h5_sample.py
First, this PR extends the  `tools/create_h5_sample.py` to create more text datasets to test with.
Then, it makes the `TextFormatter` work across `h5py` 2 and 3.
Finally it reverts changes made in PR #3240 about `test_textformatter.py` to test wht this PR provides.
It looks to work fine in `silx view` from what I tested with both h5py 2.10 and 3.
closes #3245
=> silx.gui.data: Make TextFormatter compatible with h5py>=3

silx/gui/plot/ColorBar.py, silx/gui/plot/ImageView.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/PlotWindow.py, silx/gui/plot/backends/BackendBase.py, silx/gui/plot/test/testPlotWidget.py, silx/gui/plot/test/testPlotWindow.py
This PR allows to switch the backend of a `PlotWidget` while using it.
It adds 2 methods: `setBackend` and `getBackend` to provide this feature.
It was a lot simpler to do than expected (and than when I first tried to do it a while ago).
It should already provide "full" support of state switching.
From what I quickly tested it looks to work fine.
There is an issue with widgets messing up with `PlotWidget`'s central widget (e.g., adding the colorbar there), that needs be to fixed somehow.
It also requires adding a few automated tests, but it is already ready for early testers.
closes #3159
=> silx.gui.plot.PlotWidget: Added `PlotWidget.[get|set]Backend` enabling switching backend

silx/gui/_glutils/FramebufferTexture.py, silx/gui/_glutils/Texture.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLText.py, silx/gui/plot/backends/glutils/GLTexture.py, silx/gui/plot3d/scene/function.py, silx/gui/plot3d/scene/primitives.py, silx/gui/plot3d/scene/text.py
This PR reworks the way OpenGL textures are managed through the `Texture` class by enabling lazy updates.
This does not provide additional publicly available feature, but it is really convenient for extensions requiring direct control over the texture.
=> silx.gui: Added lazy update handling of OpenGL textures

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/test/testPlotWidget.py
This PR adds support of sub-shapes (separated with Not-A-Number) to shape drawing in OpenGL backend.
It is done by splitting the input points at not finite values into multiple shapes that are rendered independently.
This fixes the display of closed arc ROI: closes #3256
=> silx.gui.plot.PlotWidget: Fixed support of shapes with multiple polygons in the OpenGL backend.

silx/gui/plot/PlotWidget.py
This PR expose PlotWidget colors as Qt properties. That's a low cost addition to be able to custom style using qss syntax
Here is an example to edit the style of the whole plots.
```
styleSheet = """
PlotWidget {
qproperty-backgroundColor: #19232d;
qproperty-dataBackgroundColor: #19232d;
qproperty-foregroundColor: #B0B0B0;
}"""
qapp.setStyleSheet(styleSheet)
```
Here we can see that the plot from the colormap dialog was also patched.
Changelog: 
- Expose PlotWidget colors as Qt properties
=> Add Qt properties for plot widget colors

README.rst
This PR changes the travis badge to reflect the change of CI service to travis-ci.com (since travis-ci-org will soon reach its end-of-life).
=> Build: Change continuous integration from travis-ci.org to travis-ci.com

silx/opencl/backprojection.py, silx/opencl/common.py, silx/opencl/convolution.py, silx/opencl/processing.py, silx/opencl/projection.py, silx/opencl/test/test_backprojection.py, silx/opencl/test/test_convolution.py, silx/resources/opencl/backproj.cl, silx/resources/opencl/proj.cl
This PR adds a mechanism for checking textures (openCL "images") availability.
Depending on the underlying openCL implementation, we can never be sure that textures are actually available, before explicitly trying to create one.  
For example, with `pocl`:  `backprojector.ctx.devices[0].get_info(cl.device_info.IMAGE_SUPPORT)`  returns `1` while `backprojector.check_texture_availability()` returns `False`.
Close #2700, #3243
Changelog: OpenCL: add textures availability check
=> [OpenCL] Check textures availability

examples/plotInteractiveImageROI.py, silx/gui/plot/PlotWidget.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/roi.py
This MR provide multi interaction mode for ROIs, and especially for arc ROI.
The arc ROI have to provide a way to setup the cercle with 3 points and with polar values.
That's useful to match different use cases (when the center is visible or not, for instance)
To manage that this requires too much handles, which make the result unusable.
So this PR provides a way to switch from an interaction mode to another.
As result the arc ROI provides for now
- `curvature` mode, 3-points to define a circle
- `polar`, which can move start and stop angles + the radius  
- `move` which only provides handle to move the shape (in case the center is not visible), (which could be removed one day when we will be able to dnd the shape itself)
Changelog: 
- Added multi interaction mode for ROIs (can be …
=> Polar arc roi

silx/math/colormap.pyx
This PR makes use of 1 thread if less than 1000 items need to be converted.
Also, the number of threads used is at most `min(4, OMP_NUM_THREADS)`, so one can avoid using OpenMP here by setting `OMP_NUM_THREADS` to 1.
The 1000 items threshold is arbitrary (i.e, it is the threshold when OpenMP becomes useless/detrimental on my machine).
The benchmark was: 1000 items: 1.5x speed-up, 10k items: 3x speed-up, 100k, 1M items: 4x speed-up.
closes #3268
=> silx.math.colormap: Improved performances for small datasets

silx/gui/plot/StackView.py, silx/gui/plot/test/testStackView.py
This PR deprecates the `autoscale` argument of `StackView.setColormap` which triggers the scaling of the colormap to the whole stack when `setColormap` or `setStack` is called, and so it is NOT use the whole stack when in autoscale mode as on would expect.
A `scaleColormapRangeToStack` method is added to which sets the range of the colormap to that of the stack.
This does not prevent adding a true autoscale to stack later.
If someone has a better idea to name the `scaleColormapRangeToStack` method, I'd take it.
To me it closes #2835
=> silx.gui.plot.Stackview: Replaced `setColormap` `autoscale` argument by `scaleColormapRangeToStack` method

silx/gui/colors.py, silx/gui/test/test_colors.py
This PR changes the 3*STDDEV autoscale in order to improve the contrast on range where there is no data.
The result of the 3*STDDEV is now clamped with the minmax data (the real range of the data).
As result is the data is only positive close to 0, the 3*STDDEV will not be netagtive (or smaller than the data).
I still ask if it is better to change the 3*STD or to create another algorithm (in order to be able to use or not this clamp).
If you have an opinion.
Tests still have to be fixed.
Bellow we can see that we win some contrast.
Changelog:
- Update stddev*3 autoscale algorithm
- Clamp it with the minmax data in order to improve the contrast
=> Clamp stddev*3 with minmax of the data

silx/gui/plot/PlotInteraction.py
This PR adds pan interaction to `PlotWidget`'s `select-draw` interaction mode.
The implementation is ugly, yet it looks to work fine and does not change the implementation of other interaction modes.
Having grown quite a bit, PlotWidget interaction needs to be refactored, but that's another story.
closes #3178
=> silx.gui.plot.PlotWidget: Add pan interaction to ROI authoring (`select-draw`) interaction mode

silx/gui/colors.py
This fixes issues in the `stddev3` autoscale mode of the `Colormap`.
closes #3294
closes #3288
=> silx.gui.colors: Fixed issue in Colormap stddev3 autoscale mode and avoided warnings

version.py
This PR restores the use of "candidate" for `version_info` to follow same convention as Python [sys.version_info](https://docs.python.org/3/library/sys.html#sys.version_info) and use `rc` for all other versions information.
It's also good as it is now.
=> Version: Use "candidate" in `version_info`

silx/opencl/common.py, silx/opencl/test/test_addition.py
This allows ahead of time work-group optimization
Changelog: Expose function to probe kernel and optimize work repartitions
=> [OpenCL] Expose the workgroup size min, max and memory usage

silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/ScatterMaskToolsWidget.py, silx/gui/plot/_BaseMaskToolsWidget.py
This PR update small stuffs in the silx mask tool.
- Use getter/setter for mask directory (for consistency)
- Setup a program_name for mask saved as EDF
- Fix inhibited message when there was a problem while saving
- Rework the message box when there is a problem while saving
I have used `program_name` as defined in https://manual.nexusformat.org/classes/base_classes/NXentry.html
It is feeded with `silx-mask`
```
In [1]: import fabio                                                                                                                                                                
In [2]: img = fabio.open("mask.edf")                                                                                                                                                
In [3]: img.header …
```
=> Few clean up on mask tool

silx/gui/data/NXdataWidgets.py
Easy to fix.
There is still a small issue though: with matplotlib backend (fine with OpenGL), when starting `silx view <file.edf>`, the image is display not as if resetzoom was called. I guess it is due to matplotlib handling the aspect ratio.
To me it does not prevent  
closes #3309
=> silx view: Changed NXdata image to keep data aspect ratio by default for images

silx/gui/plot/MaskToolsWidget.py
This PR added a `masked_value` header to the created EDF mask files in order to provide something kind of generic for Lima.
=> Add masked_value in created EDF masks

silx/gui/plot/PlotWidget.py
This PR fixes a typo in `PlotWidget.setBackend` which prevented to keep Y axis inverted when changing the backend.
Closes #3319
=> silx.gui.plot.PlotWidget: Fixed `setBackend` method.

silx/gui/plot/ColorBar.py
This PR restores previous `PlotWindow` behavior that colorbar is hidden by default.
closes #3329
=> silx.gui.plot: Fixed `PlotWindow` display of the colorbar

silx/gui/hdf5/Hdf5Item.py
Fix handling of `nexusClassName` property from `silx.gui.hdf5.hdf5item.Hdf5Item` if node contains an `NX_class` unrecognized.
closes #3332
=> Fix 3332 - issue with silx view when NXclass attribute is not recognized

silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/plot/test/testPlotInteraction.py, silx/gui/plot/test/testScatterMaskToolsWidget.py, silx/gui/plot/tools/test/testROI.py
This PR fixes interactive tests that were failing under Windows10 during 0.14 testing.
This currently targets 0.14 branch. For me, it is not critical to embed but still nice to have (provided it does not break those tests on other platforms.
So far tested on Windows10 with PyQt5 and PySide2.
=> Fixed interactive tests on Windows10

CHANGELOG.rst, silx/gui/plot/items/_roi_base.py, silx/gui/plot/items/roi.py, silx/gui/plot/tools/test/testROI.py
This PR fixes crashes on right click with profiles and ROIs by implementing `contains` methods.
Those methods are exact, so their use in interaction might not be ideal since it is almost impossible.
Still todo: ellipse and testing.
closes #3335
=> silx.gui.plot: Fixed RegionOfInterest `contains`

silx/image/bilinear.pyx, silx/image/test/test_bilinear.py
Provide a mask in the numerical kernel in charge of bilinear interpolation.
Returns Nan when no underlying pixel is unmasked. Interpolates approximately then 1, 2 or 3 underlying pixels are masked.
This is part of #3285
=> Implement mask for bilinear interpolation

silx/test/__init__.py
Minor PR allowing to pass arguments to [`unittest.TextTestRunner`](https://docs.python.org/3/library/unittest.html#unittest.TextTestRunner) through `silx.test.run_tests` (e.g., `verbosity=1`).
=> silx.test: Enhanced `run_tests` taking arguments to configure test execution.

silx/gui/data/NXdataWidgets.py
Simple fix to avoid zoom reset when scrolling a stack viewed with `_NXdataImageView`.
closes  #3350
=> silx view: Fixed zoom reseting when scrolling a NXdata 3D stack

silx/gui/setup.py, silx/gui/utils/glutils.py, silx/gui/utils/glutils/__init__.py
Should fix issues with import when running `isOpenGLAvailable`. PR 3184 was apparently not enough.
It still needs testing.
Alternative can be to import `subprocess` lazily in `def _runtimeOpenGLCheck(version)`
Related to #3182
=> silx.gui.utils.glutils: Fixed `isOpenGLAvailable`

.github/workflows/ci.yml, ci/info_platform.py, ci/requirements-pinned.txt
=> Misc.: Use github action to run CI on linux and macos

CHANGELOG.rst, silx/gui/setup.py, silx/gui/utils/glutils/__init__.py, version.py
Backport PR #3356 to 0.14 branch, and prepare for a 0.14.1b0 tag.
=> Backport silx.gui.utils.glutils.isOpenGLAvailable fix to 0.14 branch

ci/requirements-pinned.txt
Pin-point pyopencl on macos since v2021.1 requires macos11.
This should fix CI.
=> Misc. CI: Fixed testing on macos

silx/gui/dialog/ColormapDialog.py
This PR proposes an alternative to #3349. Compared to it it also supports mean+/-3std and takes a smaller footprint in the `ColormapDialog`.
It provides 2 on-demand colormap range scaling:
- From the currently visible area of the item that is registered to the `ColormapDialog`
- From a rectangular selection on the registered item. When pressing the "Selection" button, its text changes to "Draw area..." with a waiting icon and waits for user input. This mode is cancelled by pressing again the button or changing the plot interaction mode (e.g., select zoom mode).
Both uses the current autoscale mode (i.e., min/max or mean+/-3std).
It works for `Scatter` and `ImageData`.
closes #2429
=> silx.gui.dialog.ColormapDialog: Added scale to visible or selected area buttons

ci/requirements-pinned.txt
Remove pin-pointing of pyopencl on macos since issue should be fixed in latest release.
=> Misc. CI: Removed pyopencl pin-pointing on macos

doc/source/Tutorials/io.rst, doc/source/modules/io/h5py_utils.rst, doc/source/modules/io/index.rst, doc/source/modules/utils/index.rst, doc/source/modules/utils/retry.rst, silx/io/h5py_utils.py, silx/io/test/__init__.py, silx/io/test/test_h5py_utils.py, silx/utils/retry.py, silx/utils/test/__init__.py, silx/utils/test/test_retry.py
Closes #3354
Tested with h5py 2.8, 2.9, 2.10, 3.1
Stress tests: https://gitlab.esrf.fr/denolf/concurrent_h5py
The main API:
* `silx.io.h5py_utils.File`: replace `h5py.File` mainly to handle file locking
* `silx.io.h5py_utils.retry`: retry the method whenever you get an HDF5 IO exception
* `silx.io.h5py_utils.retry_in_subprocess`: retry in a subprocess to capture segfaults
* `silx.io.h5py_utils.retry_contextmanager`: retry entering the context manager
The retry logic can also be used for other things than HDF5 reading:
* `silx.utils.retry.retry`
* `silx.utils.retry.retry_in_subprocess`
* `silx.utils.retry.retry_contextmanager`
Common use case of `silx.io.h5py_utils` for processing a Bliss Nexus file:
```python
import silx.io.h5py_utils
@silx.io.h5py_utils.retry()
def process_scan(filename, …
```
=> Concurrent h5py

silx/gui/plot/tools/profile/core.py
This occurs sometimes in `silx view` with the profile tool, when one draws a profile and change the displayed dataset or the visualization, the profile window remains open with the last profile, but when closing it it raises an exception:
```
ERROR:silx.gui.qt._qt:<class 'ValueError'> RegionOfInterest does not belong to this instance   File "silx/gui/plot/tools/profile/core.py", line 170, in __profileWindowAboutToClose
roiManager.removeRoi(self)
File "silx/gui/plot/tools/roi.py", line 748, in removeRoi
'RegionOfInterest does not belong to this instance')
```
Not an elegant fix, but it does the job.
=> silx.gui.plot: Fixed profile tool issue when closing profile window after attaced PlotWidget

silx/gui/plot3d/scene/primitives.py
This is only an internal fix, it is useful to define plot3d items that are not (yet?) available in silx.
=> silx.gui.plot3d: Added support for RGB colored points in internal scene graph. 

silx/gui/plot/actions/histogram.py, silx/gui/plot/items/complex.py, silx/gui/plot/items/image.py, silx/gui/plot/tools/profile/rois.py
This PR adds a `getValueData` method to all image items.
This method returns a 2D array of float (or int). It allows to simplify code requiring 2D data by avoiding handling RGBA to intensity conversion at multiple places.
It also paves the way to mask associated to an image, since it allows to return the masked array (with NaNs where masked) rather than having to do this at multiple places.
This PR is extracted from PR #3369 in order to split the changes in smaller chunks.
=> silx.gui.plot: Added `getValueData` method to PlotWidget image items

silx/gui/data/DataViews.py, silx/gui/data/NXdataWidgets.py, silx/gui/dialog/ColormapDialog.py, silx/gui/plot/Colormap.py, silx/gui/plot/MaskToolsWidget.py, silx/gui/plot/_BaseMaskToolsWidget.py, silx/gui/plot/actions/control.py, silx/gui/plot/actions/histogram.py, silx/gui/plot/items/complex.py, silx/gui/plot/items/core.py, silx/gui/plot/items/image.py, silx/gui/plot/test/testMaskToolsWidget.py, silx/gui/plot/tools/profile/manager.py, silx/gui/plot/tools/profile/rois.py
Changelog: Associate a mask to the plotting of the image
closes #3263
closes #3124
closes #3285
This PR includes and superseeds PR #3289.
It adds:
- Support for data size change while mask is set.
- Support of all image items (i.e., complex, stack and RGBA images) by adding a `ImageBase.getValueData` method (If one has a better name I'll take it!) which returns a 2D array of data no matter of the kind of image and with mask applied.
TODO:
=> silx.gui.plot: Added mask support to Image items and use it in plot tools (histogram, profile, colormap)

silx/gui/plot/ImageView.py
This PR follows PR #3380 and  #3369 and addresses https://github.com/silx-kit/silx/pull/3369#issuecomment-784212703:
> The mask is not used for the profile sum, which could be done later (to avoid ocnflict with my branch)
Item mask information is used for both default integrated profiles and line profiles.
=> silx.gui.plot.ImageView: Enhanced using mask for computing profiles

silx/gui/utils/glutils/__init__.py
Changing the WindowFlags allows to avoid the blinking icon in the app bar at least on debian10.
It does not prevent it on macos.
closes #3339
=> silx.gui.utils.glutils: Enhanced `isOpenGLAvailable` function: avoid blinking icon in the app bar on linux

silx/io/dictdump.py, silx/io/test/test_dictdump.py
Closes #3226 
Add missing features so the Bliss Nexus writer can use `dicttonx` from `silx`.
- `dicttoh5` has a new `existing` argument to specify overwrite behavior: 
* **add**: Existing HDF5 items are untouched. Nodes from the dict tree are added to the HDF5 tree when the existing HDF5 tree allows it.
* **update**: Existing HDF5 items may be updated or deleted explicitly by assigning them to `None`. The dict tree will be a subtree of the HDF5 tree.
* **overwrite**: Existing HDF5 items may be overwritten or deleted. The HDF5 tree will be exactly the dict tree, except for already existing top-level items that were not deleted explicitly by assigning them to `None`.
- A `None` value in the dict of `dicttoh5` will never create anything (previously it was creating an empty HDF5 group). When …
=> dicttoh5 overwrite behavior

silx/utils/test/test_testutils.py, silx/utils/testutils.py
On fails `TestLogging` returns no the logging records together with the exception.
Changelog: 
- TestLogging returns now the logging records when there is mismatch
=> Returns the records together with the logging exception

doc/source/modules/gui/plot3d/items.rst, silx/gui/plot3d/items/__init__.py, silx/gui/plot3d/items/image.py, silx/gui/plot3d/test/testSceneWindow.py, silx/gui/plot3d/tools/PositionInfoWidget.py
This PR adds 2 items to `plot3d` scene to provide a first display of height maps.
Both take a 2D data array that is used as the height of points based on a 2D regular grid and a second array for the colors:
- `HeightMapData` for a height map with colormapped data
- `HeightMapRGBA` for a height map with RGBA colors.
If both arrays (height and color) have different shapes, one is interpolated to match the other.
It can definitely be improved and provide more visualization modes (e.g., a display as a real surface), but it is already useable as it is.
closes #3379
TODO:
=> silx.gui.plot3d: Added `HeightMapData` and `HeightMapRGBA` items

silx/gui/plot3d/items/image.py
Fix following PR #3386 : stupid typo, didn't tested with not square height map
Thanks @juliagarriga for spotting it!
=> silx.gui.plot3d: Fixed height map items picking

silx/gui/plot/actions/histogram.py
This PR removes the displayed histogram when there is no active image or scatter.
Before, when cleaning the plot, the histogram was not synchronized.
From a look at the code, it didn't sounds the expected behaviour.
=> silx.gui.plot: Fixed histogram action by removing histogram when there is no active image or scatter

silx/gui/plot/stats/stats.py
I fixed stats issues related to histogram widgets for the basic case and the 'stats on visible area' by copy-pasting the curve implementation since it sounds similar, but not sure it is the best way to fix it.
closes #3392
=> silx.gui.plot.stats: Fixed stats for histogram plot items

silx/gui/plot/ColorBar.py
Makes sure that PlotWidget still exists at C++ level before disconnecting signals.
This can occur when closing python.
closes #3402
=> silx.gui.plot.ColorBar: Fixed issue when deleting attached PlotWidget

silx/gui/plot/PlotWidget.py, silx/gui/plot/test/testPlotWidget.py
This PR adds a `PlotWidget.selection()` method giving access to an object handling selection in the `PlotWidget` in a way that is compatible with current active item management.
The selection object provides:
- `getCurrentItem` and `sigCurrentItemChanged` to retrieve and track a single current item which is the latest item in the plot to have been "activated".
- `getSelectedItems` which provides the list of all activated items ordered from latest to oldest "activated" item.
- `setCurrentItem`which updates active items accordingly.
The selection object is instantiated on demand so it does not interfere if not used.
This is aimed to help features requiring management of active items of different kinds.
=> silx.gui.plot.Plotwidget: Added unified `selection` handler compatible with active item management

silx/gui/plot/tools/PositionInfo.py
This PR allows `PositionInfo` field to be smaller... yet keep their default size, this makes `Plot2D` default size the same, but it can be shrinked down by removing space between the fields.
To me, it is another way to close #2997
Default and min:
=> silx.gui.plot: Enhanced `PositionInfo` information labels layout

silx/gui/plot/actions/histogram.py, silx/gui/plot/items/histogram.py, silx/gui/plot/tools/PositionInfo.py
This PR:
- Fixes histogram picking and returned indices
- Enables snapping to histogram items in the PositionInfo widget
There is still an issue with the OpenGL backend where the filled part is not taken into account for picking.
=> silx.gui.plot: Fixed histogram picking, Enabled `PositionInfo` snapping to histogram

silx/gui/plot3d/scene/primitives.py
This PR fixes a typo on transparency composition.
closes #3413
=> silx.gui.plot3d: Fixed `ImageRgba` alpha channel display

silx/gui/data/RecordTableView.py
This PR allows to overcome the limited number of items supported by QTableView by clipping 1D array when it is above a threshold.
This makes sure the application does not seg fault.
I set threshold to 1 million, but we can make it 10 millions.
Clipping is displayed as follow with a tooltip on the `...`:
closes #3417
=> silx view: Support very large 1D datasets in "Raw" table view

silx/gui/data/ArrayTableModel.py, silx/gui/data/test/test_arraywidget.py
Related to issue #3417 and similar to PR #3418 but for `ArrayTableWidget`.
This PR adds clipping of dimensions with a size > 10e6.
=> silx.gui.data.ArrayTableWidget: Added support of array clipping if data is too large

examples/stackView.py, silx/gui/plot/backends/BackendMatplotlib.py
This PR does 2 things:
- Enables usage of image mask in tools (histogram, colormap autscale and profiles) in `examples/stackView.py`.
- Fixes a bug in text rendering in the matplotlib backend when the widget as a width of 0.
To reproduce the bug, use the `examples/stackView.py` from this PR, create a horizontal profile and then open the mask tools.
This leads to:
```
File "silx/gui/plot/backends/BackendBase.py", line 343, in postRedisplay
plot.replot()
File "silx/gui/plot/PlotWidget.py", line 3137, in replot
self._backend.replot()
File "silx/gui/plot/backends/BackendMatplotlib.py", line 1517, in replot
self.draw()
File "silx/gui/plot/backends/BackendMatplotlib.py", line 1501, in draw
self._drawOverlays()
File …
```
=> silx.gui.plot.PlotWidget: Fixed rendering; Doc: Updated sample code.

doc/source/Tutorials/writing_NXdata.rst
The interpretation attribute is duly documented by NeXus. It never was a silx thing.
=> [DOC] Correct documentation concerning the interpretation attribute.

silx/gui/plot/backends/BackendOpenGL.py, silx/gui/plot/backends/glutils/GLPlotCurve.py, silx/gui/plot/backends/glutils/GLPlotImage.py, silx/gui/plot/backends/glutils/GLPlotItem.py, silx/gui/plot/backends/glutils/GLPlotTriangles.py
Under some conditions (PlotWidget in a not visible tabbed DockWidget + some condition not yet clearly defined...) it happens that `PlotWidget.replot` is called (since `PlotWidget.isVisible()` is True) but `BackendOpenGL.paintGL` is not.
This can leads to new items to be created in the backend (in `PlotWidget.replot`) and never discarded (in `BackendOpenGL.paintGL`)
This PR workarounds this issue by adding the list of backend items to "discard " (which is done lazily in `paintGL`) only the ones that really needs to free some GPU resources (i.e., that has already been displayed).
It has the advantage of only modifying the OpenGL backend.
Related to #3443
=> Fixed leak of OpenGL backend items on branch 0.14

src/silx/gui/plot/items/scatter.py, src/silx/gui/plot/test/testItem.py, src/silx/gui/plot/test/testPlotWidget.py
This PR fixes an issue when updating the data of a scatter plot while in `BINNED_STATISTIC` visualization mode.
closes  #3450
=> silx.gui.plot.PlotWidget: Fixed update of `Scatter` item binned statistics visualization

src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py, src/silx/gui/plot/backends/glutils/GLPlotImage.py, src/silx/gui/plot/backends/glutils/GLPlotItem.py, src/silx/gui/plot/backends/glutils/GLPlotTriangles.py
This PR ports changes made in `0.14` and `0.15` regarding a memory leak in the `PlotWidget` OpenGL backend under specific circumstances. 
While PR #3449 also fixes this issue in a completely different way, the change made here will not hurt: "ceinture et bretelles".
closes #3443
=> silx.gui.plot.PlotWidget: Fixed OpenGL backend memory leak

src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py
This PR reworks the management of PlotWidget backend updates.
Behavior of the matplotlib backend should be the same, but the OpenGL backend now has one indirection less and this should avoids issues such as #3443
closes #3443
=> silx.gui.plot.PlotWidget: Enhanced control of repaint

.github/workflows/ci.yml
Makes CI tests pass on macos until #3456 is eventually fixed
=> Misc: Disable OpenCL continuous integration tests on macos

.github/workflows/ci.yml, silx/gui/plot/ImageView.py, silx/gui/plot/Profile.py, silx/gui/plot/tools/profile/manager.py
Related to #3454
Backport of PR #3455  and PR #3457 but for the deprecation of `ImageView.profile`.
=> [0.15 branch] silx.gui.plot.ImageView: Fixed profile window, added setProfileWindowBehavior method

src/silx/io/spech5.py
This PR allows to have less values in `#P` than in `#O` as it is the case in #3459.
In such case, it logs a warning and sets the value to `inf`. I choose to do so since when `#P` is completely missing `inf` is used for all values.
Disclaimer: I'm not used to spec at all!
closes #3459
=> silx.io.spech5: Enhanced robustness for missing positioner values

silx/io/url.py
backport of https://github.com/silx-kit/silx/pull/3437/commits/9bfc2f52d309647a3f9742b44ebc5b55a8686d90 on 0.15
=> Backport of fix 'DataUrl.is_absolute' 

src/silx/gui/colors.py
This PR avoids duplicated logs when vmin/vmax are not valid for the current colormap normalization (e.g., negative values with log scale).
=> silx.gui.colors: Fixed duplicated logs when colormap vmin/vmax are not valid

src/silx/app/view/About.py
simple update of the "about" window of silx view
- close #3473
=> [silx view] update about window: add h5py and HDF5 version

src/silx/app/view/Viewer.py, src/silx/gui/colors.py, src/silx/gui/plot/CompareImages.py
This PR prepares for Qt6 support by changing implementation for obsolete/inconsistent features that does not require Qt6 specific code:
- `QAction.setMenu` is obsolete in Qt6, so when it is used, `QAction` needs to be replaced with `QMenu` or `QToolButton`.
- `QColor.getRgbF` is not exactly consistent across Qt5 and Qt6 (precision, rounding change?), so use `QColor.getRgb` instead
Related to #3432
=> silx.gui: Prepare for Qt6 support

src/silx/app/view/CustomNxdataWidget.py, src/silx/gui/_glutils/font.py, src/silx/gui/data/ArrayTableModel.py, src/silx/gui/data/Hdf5TableView.py, src/silx/gui/data/HexaTableView.py, src/silx/gui/data/RecordTableView.py, src/silx/gui/dialog/AbstractDataFileDialog.py, src/silx/gui/fit/FitWidget.py, src/silx/gui/fit/FitWidgets.py, src/silx/gui/hdf5/Hdf5HeaderView.py, src/silx/gui/hdf5/Hdf5TreeView.py, src/silx/gui/plot/CurvesROIWidget.py, src/silx/gui/plot/ROIStatsWidget.py, src/silx/gui/plot/StatsWidget.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/tools/roi.py, src/silx/gui/plot3d/ParamTreeView.py, src/silx/gui/plot3d/Plot3DWidget.py, src/silx/gui/plot3d/SFViewParamTree.py, src/silx/gui/utils/testutils.py, src/silx/gui/widgets/PrintPreview.py, src/silx/gui/widgets/UrlSelectionTable.py, src/silx/gui/widgets/test/test_hierarchicaltableview.py
This PR cleans-up Qt4 support that is related to using `qt.qVersion()` and `setSectionResizeMode`.
It is mostly (but not only) related to `QHeaderView.setSectionResizeMode`  and `beginResetModel`/`endResetModel`.
Related to #3432
=> silx.gui: clean-up Qt4 support code

src/silx/gui/plot/tools/profile/manager.py
This PR fixes an issue with `ImageView` profile window display.
To reproduce the issue: python bootstrap.py examples/imageview.py
Draw a horizontal line profile on the image and then draw a free line profile.
related to  #3454
=> silx.gui.plot.ImageView: Fixed issue with profile window size

src/silx/gui/plot/ImageView.py, src/silx/gui/plot/Profile.py, src/silx/gui/plot/test/testImageView.py
This PR:
- restores previous behavior for displaying profile windows (i.e., pop-up)
- adds `ImageView.get|setProfileWindowBehavior` method to change it to embed horizontal, vertical and cross profiles on the side widgets.
- adds `ImageView.getProfileToolBar` and deprecates `ImageView.profile` attribute.
closes  #3454
=> silx.gui.plot.ImageView: Fixed profile window, added `setProfileWindowBehavior` method

src/silx/opencl/test/test_doubleword.py, src/silx/resources/opencl/doubleword.cl
Minor improvement over existing PR: just rename 3 functions
=> 3451 doubleword

src/silx/gui/plot/items/_arc_roi.py
This PR removes `assert` from `ArcROI.setGeometry`.
From what I tested, it works fine, you can create `ArcROI` with any angle range.
Only issue is that if angle range is >2π, then when you start interacting with the ROI, the arc area jumps, which is not really nice.
closes #3489
=> silx.gui.plot: Fixed `ArcROI.setGeometry`

src/silx/gui/plot/ImageView.py, src/silx/gui/plot/test/testImageView.py
This PR release constraints on `setImage` to allow to set RGB and RGBA images.
Few other places were fixed, like statusbar display, but not much.
Changelog: 
- Added support of RGB and RGBA images to ImageView
=> Supports RGB and RGBA in ImageView

src/silx/gui/plot/items/scatter.py
This PR adds an optimisation of scatter when rendered as regular grid with the OpenGL backend.
In this case, it avoids computing the colormap on the CPU if it is possible (i.e., float data and no alpha data).
=> silx.gui.plot.PlotWidget: Optimize regular grid visualisation of scatters

src/silx/app/view/Viewer.py, src/silx/gui/plot/tools/roi.py
This PR prepares for Qt6 support by changing implementation for obsolete/inconsistent features that does not require Qt6 specific code, completes PR #3481:
`QAction.setMenu` is obsolete in Qt6, so when it is used, `QAction` needs to be replaced with `QMenu` or `QToolButton`.
This 2 fixes were not highlighted by tests.
Related to #3432
=> silx.gui: Prepare for Qt6 support (follow-up)

src/silx/gui/plot/PlotWindow.py
This MR fixes probably a typo on the plot API.
Changelog: 
- Fix returned action from `getKeepDataAspectRatioAction`
=> Fix returned keepDataAspectRatioAction

src/silx/gui/plot/_utils/__init__.py, src/silx/gui/plot/_utils/panzoom.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py, src/silx/gui/plot/items/axis.py, src/silx/gui/plot/test/testPlotWidget.py
This PR removes an `assert` about axis limits in the `PlotWidget` OpenGL backend and replaces it with a change of the range in case of issue.
The code validating the limits range is the same as the `Axis` one and has been modified to ensure the limits are within the supported range even if the range is changed from the API or through `resetZoom` (which was not the case before).
It also adds some basic tests of out-of-bound limits.
closes #3501
=> silx.gui.plot: Fixed OpenGL issue with out-of-bouds axes limits

src/silx/io/dictdump.py
Changelog: string conversion for key hdf5 by casting the variable key to string in dicttoh5 function of dictdump.py file.
=> string conversion for key hdf5

src/silx/io/spech5.py, src/silx/io/test/test_spech5.py
This PR makes `SpecH5` resilient to `#G1` and `#G3` having less values than expected.
closes #3506
=> silx.io.spech5: Make SpecH5 resilient to malformed #G1 and #G3 header lines

src/silx/gui/widgets/test/test_threadpoolpushbutton.py, src/silx/io/test/test_dictdump.py, src/silx/math/fit/test/test_fit.py, src/silx/math/test/test_histogramnd_nominal.py
This PR fixes warnings that are raised by the test code.
It should fix:
```
build_venv/lib/python3.9/site-packages/silx/utils/testutils.py:116
/builds/9qviVUiL/0/silx/bob/silx/build_venv/lib/python3.9/site-packages/silx/utils/testutils.py:116: PytestCollectionWarning: cannot collect test class 'TestLogging' because it has a __init__ constructor (from: build_venv/lib/python3.9/site-packages/silx/gui/widgets/test/test_threadpoolpushbutton.py)
class TestLogging(logging.Handler):
build_venv/lib/python3.9/site-packages/silx/utils/testutils.py:116
/builds/9qviVUiL/0/silx/bob/silx/build_venv/lib/python3.9/site-packages/silx/utils/testutils.py:116: PytestCollectionWarning: cannot collect test class 'TestLogging' because it has a __init__ constructor (from: …
```
=> Tests: Fixed warnings raised by the test themselves

pyproject.toml, setup.py
This makes `pip` install from source with `--pre` to work with pip v21.2.1 and should fix CI.
closes #3512
=> Misc.: Updated build config to fix support for `pip` v21.2.1

src/silx/gui/plot/CompareImages.py
vmin and vmax values are forced when we want to display both image A and image B.
But this should not be the case for the other modes.
This commit attempt to fix this issue.
Changelog: 
CompareImages: fix colormap: avoid forcing vmin and vmax when not in HRIZONTAL_LINE or VERTICAL_LINE mode
=> Darft: [gui][ComapreImages] fix forcing vmin and vmax values

src/silx/gui/_glutils/utils.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py, src/silx/gui/plot/tools/test/testTools.py, src/silx/gui/plot3d/items/image.py
Fixes the following warnings raised in CI on Windows when running the tests:
```
venv_test\lib\site-packages\silx\utils\testutils.py:116
C:\projects\silx-7wjwv\venv_test\lib\site-packages\silx\utils\testutils.py:116: PytestCollectionWarning: cannot collect test class 'TestLogging' because it has a __init__ constructor (from: gui/plot/tools/test/testTools.py)
class TestLogging(logging.Handler):
gui/plot/test/testPlotWidget.py::TestPlotCurve_Gl::testPlotCurveInfinite
C:\projects\silx-7wjwv\venv_test\lib\site-packages\silx\gui\plot\backends\glutils\GLPlotCurve.py:1147: RuntimeWarning: invalid value encountered in subtract
self.yData = (yData - self.offset[1]).astype(numpy.float32)
gui/plot/test/testPlotWidget.py::TestPlotCurveLog_Gl::testPlotCurveErrorLogXY …
```
=> Misc.: Fixed invalid value, deprecation and test warnings

src/silx/app/test/test_convert.py, src/silx/gui/plot/tools/test/testProfile.py, src/silx/gui/plot/tools/test/testTools.py, src/silx/gui/widgets/test/test_threadpoolpushbutton.py, src/silx/io/test/test_dictdump.py, src/silx/io/test/test_specfile.py, src/silx/io/test/test_spech5.py, src/silx/math/fit/test/test_fit.py, src/silx/utils/test/test_debug.py, src/silx/utils/test/test_deprecation.py, src/silx/utils/test/test_number.py, src/silx/utils/test/test_testutils.py, src/silx/utils/testutils.py
This renaming is to avoid pytest test gathering possible issue with functions/classes that starts with `test`/`Test` but are not tests.
It follows https://github.com/silx-kit/silx/pull/3515#issuecomment-889282524
=> `silx.utils.testutils`: Renamed `TestLogging` and `test_logging` to `LoggingValidator` and `validate_logging`

src/silx/io/commonh5.py, src/silx/io/convert.py, src/silx/io/test/test_utils.py, src/silx/io/test/test_write_to_h5.py, src/silx/io/utils.py
This PR allows to provide a HDF5 file as input to `write_to_h5`.
This was not possible before because `commonh5.visititem` had a different API than it's `h5py` equivalent and was disabled as part of #1385.
To achieve this, this PR adds a `silx.io.utils.visitall` function that provides a visitor of all items including links that works for both `commonh5` and `h5py`. This function is used by `write_to_h5` implementation.
It also provides some basic tests.
Current limitation: External links in input file are ignored (with a warning).
closes #3468
=> `silx.io.convert`: Added `write_to_h5` supporting HDF5 file as input 

src/silx/gui/data/NXdataWidgets.py
For NxData with nD dataset displayed as curves, this PR keeps curves setting (visibility, Y axis) when changing the selected dimensions.
The active is curve is NOT preserved and reset what's in NxData `signal`.
closes #3518
=> silx view: Keep curve legend selection with changing dimensions

examples/compareImages.py, examples/exampleBaseline.py, examples/fileDialog.py, examples/findContours.py, examples/icons.py, examples/imageStack.py, examples/periodicTable.py, examples/plot3dContextMenu.py, examples/plot3dSceneWindow.py, examples/plotClearAction.py, examples/plotCurveLegendWidget.py, examples/plotInteractiveImageROI.py, examples/plotLimits.py, examples/plotStats.py, examples/plotUpdateCurveFromThread.py, examples/printPreview.py, examples/shiftPlotAction.py, examples/stackView.py
This PR does more `exec_` to `exec` renaming that where missed in PR #3486
=> silx.gui: Renamed exec_ methods to exec for compatibility with Qt6

src/silx/gui/plot/items/__init__.py, src/silx/gui/plot/items/image.py, src/silx/gui/plot/items/image_aggregated.py, src/silx/gui/plot/test/testItem.py
This PR adds a plot item that allows to aggregate image data before display.
By default it displays the data image as `ImageData` but the `setAggregationMode` allows to reduce the data image before display depending on the current level of details displayed.
For now the aggregation is done in a fast/approximate manner, a second more accurate mode could also be added.
Which "aggregation modes" are needed? For now it provides "none" (no aggregation), "min" (nanmin), "max" (nanmax), "mean" (nanmean)
See https://gitlab.esrf.fr/bliss/bliss/-/merge_requests/3838
=> silx.gui.plot: Added `ImageDataAggregated` item

examples/plotUpdateImageFromThread.py, src/silx/gui/plot/actions/histogram.py, src/silx/gui/widgets/RangeSlider.py
This PR adds 2 widgets to set the number of bins and the range of the histogram in the plot from the histogram action.
The number of bins is guessed by default (and displayed as placeholder text) and when the user inputs it, it is kept when data is updated (e.g., browsing a stack of image in silx view). To fallback to bin number guessing, the user has to delete the input text.
Updates are done on "Enter".
The absolute range is NOT persisted when changing data, instead the "relative range" is persisted (i.e., the histogram bounds in the data are changed but the positions of the thumb on the range slider are not).
I see it hard to keep the absolute range since it can fall outside of the data range when changing data.
At the same time, it might be useful to keep some similar range from one …
=> silx.gui.plot.actions.histogram: Added controls to change histogram nbins and range

ci/requirements-pinned.txt, src/silx/io/h5py_utils.py, src/silx/io/test/test_h5py_utils.py
This PR handles unsupported versions of libhdf5 regarding the change of behaviour of file locking by:
- skipping tests for unsupported versions.
- Logging a critical message in `h5py_utils.File` for unsupported versions of h5py.
It removes h5py version pin-pointing introduced in PR #3526
closes #3523
=> silx.io.h5py_utils: Log a critical message for unsupported versions of libhdf5

.github/workflows/ci.yml, run_tests.py, src/silx/conftest.py, src/silx/gui/dialog/test/test_colormapdialog.py, src/silx/gui/plot/CompareImages.py, src/silx/gui/plot/test/testCurvesROIWidget.py, src/silx/gui/plot/test/testMaskToolsWidget.py, src/silx/gui/qt/_qt.py, src/silx/gui/test/test_icons.py, src/silx/gui/test/test_qt.py, src/silx/gui/utils/testutils.py
This PR makes sure the chosen Qt binding is loaded by importing it as early as possible, else this can cause issues if multipe Qt bindings are available.
=> Misc.: Fixed `run_test.py --qt-binding` option

src/silx/gui/plot/actions/fit.py
This PR proposes to update the behaviour of the plot's `FitAction` "fitted item auto update mode":
- Current this modes tracks the active curve.
- This PR propose that when there is no active curve, if there is only one curve or one histogram in the plot, this item is used as the fitted item.
To me it is fine to change this since it is an "auto mode", and it sounds better to add this selection fallback.
closes #3531
=> silx.gui.plot.actions.fit: FitAction: Updated behaviour of fitted item auto update

ci/appveyor.yml
`pywin32` v302 wheel for python3.6 on Windows seems to have an issue, this PR just exchange the version of python used for pyqt5/pyside2 tests.
=> Switch python version used for pyside2 test

src/silx/app/view/main.py
This PR set the max number of opened files at `silx view` start-up to mitigate issue of too many file descriptors opened.
It's been successfully tested on the file from issue #3537 under linux.
It still needs to be tested on Windows and macos to check that the fix does not create errors on those OS.
closes  #3537
=> silx view: Set max number of opened file at start-up

ci/appveyor.yml, src/silx/gui/_glutils/FramebufferTexture.py, src/silx/gui/data/Hdf5TableView.py, src/silx/gui/data/HexaTableView.py, src/silx/gui/plot/MaskToolsWidget.py, src/silx/gui/plot/PlotWindow.py, src/silx/gui/plot/actions/histogram.py, src/silx/gui/plot/actions/io.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/tools/profile/rois.py, src/silx/gui/plot3d/Plot3DWidget.py, src/silx/gui/plot3d/actions/io.py, src/silx/gui/plot3d/scene/window.py, src/silx/gui/widgets/FloatEdit.py
Merge PR #3542 first!
This PR fixes:
- histogram action issue when the whole image is masked
- An error on macOS 11 with 3D display in `silx view` by avoiding rendering with OpenGL when size is (0, 0)
=> silx.gui.plot3d, silx.gui.plot.actions.histogram: Fixed issues

run_tests.py, src/silx/app/view/About.py
This PR removes `h5py` and `fabio` from advertised optional dependencies.
It also remove `import resource` from `run_tests.py` since it is not used.
=> silx view: Updated About dialog

src/silx/gui/plot3d/Plot3DWidget.py, src/silx/gui/plot3d/_model/items.py, src/silx/gui/plot3d/actions/mode.py
This PR fixes 2 issues in `plot3d`:
- An issue with PySide private signals in the parameter tree
- An issue with picking coordinates on highDPI screens (closes #3206)
=> silx.gui.plot3d: Fixed picking on highdpi screen, Fixed issue in parameter tree

src/silx/gui/data/Hdf5TableView.py, src/silx/gui/data/HexaTableView.py, src/silx/gui/plot/MaskToolsWidget.py, src/silx/gui/plot/PlotWindow.py, src/silx/gui/plot/actions/io.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/tools/profile/rois.py, src/silx/gui/plot3d/Plot3DWidget.py, src/silx/gui/plot3d/actions/io.py, src/silx/gui/widgets/FloatEdit.py
~~Merge PR #3540 first!~~
This PR fixes a couple of Qt6/PySide6 compatibility issues spotted while testing `silx view`:
- Adapt to Qt6 API changes
- PySide6 bug workaround with private methods used as signals
- Avoid to raise exception with scatter profiles expecting a regular grid while a grid cannot be guessed.
related to #3432
=> Fixes PySide6/Qt6 support

src/silx/app/view/ApplicationContext.py
When changing from PyQt5 to PySide6 (or the other way around), the settings are not correctly recovered and the backend is set to `None`... This PR ignores the value in this case.
Related to #3542
=> silx view: Fixed settings when switching between PyQt5/PySide6

src/silx/gui/dialog/ColormapDialog.py, src/silx/gui/fit/FitWidget.py, src/silx/gui/plot/tools/test/testTools.py
- silx.gui.fit: Typo affecting PySide2<5.14 since later versions provide `QComboBox.textActivated`
- silx.gui.dialog.ColormapDialog: Fixed bug with non editable colormaps (close #3524)
- silx.gui.plot.tools.test: Fixed test with PySide2
=> silx.gui: Minor bug fixes

src/silx/io/h5py_utils.py, src/silx/io/test/test_h5py_utils.py
Closes #3541
I tested  `src/silx/io/test/test_h5py_utils.py` against different h5py/libhdf5 on Ubuntu
```
h5py: 2.8.0, hdf5: 1.10.4
h5py: 2.9.0, hdf5: 1.10.4
h5py: 2.10.0, hdf5: 1.10.4
h5py: 2.10.0, hdf5: 1.10.6 CONDA
h5py: 3.1.0, hdf5: 1.12.0
h5py: 3.2.0, hdf5: 1.12.0
h5py: 3.3.0, hdf5: 1.12.0
h5py: 3.3.0, hdf5: 1.10.6 CONDA
h5py: 3.4.0, hdf5: 1.12.1 REMARK
h5py: 3.5.0, hdf5: 1.12.1
```
and on Windows
```
h5py: 2.10.0, hdf5: 1.10.5
h5py: 3.1.0, hdf5: 1.12.0
h5py: 3.2.0, hdf5: 1.12.0
h5py: 3.3.0, hdf5: 1.12.0
h5py: 3.4.0, hdf5: 1.12.1 REMARK
h5py: 3.5.0, hdf5: 1.12.1
```
No manual tests done on Mac.
REMARK: skips `test_modes_multi_process` due to  "Versions of libhdf5 and h5py use incompatible file locking behavior"
=> Support new h5py has a "locking" argument

src/silx/io/nxdata/parse.py
An exception is raised by `silx view` when accessing old NXdata convention (where `axes` are defined on the signal dataset) with a missing `axes` dataset.
This PR adds a validation check for this case.
To reproduce the issue, open https://github.com/silx-kit/silx-training/blob/master/python/io/data/test.h5 with `silx view` and go to: `/diff_map_0000/data`
=> Fixed erroneous old NXdata convention support

README.rst, doc/source/applications/view.rst, doc/source/index.rst
I am not a big fan of the layout but with rst hard to do something more 'fancy'.
if needs to be reused at one point
https://user-images.githubusercontent.com/12907796/142628021-b554f620-ede9-438f-85c0-34953d7345d7.mp4
=> Add silx-view.gif to documentation

src/silx/math/fit/peaks.pyx
This PR clarifiy the returned type of peak indices (`float`, not `int` as one can expect for indices).
closes #3579
=> Enhanced `peak_search` documentation

.github/workflows/ci.yml, ci/appveyor.yml, ci/info_platform.py, ci/requirements-pinned.txt, pyproject.toml, requirements.txt
This PR constraints `setuptools` to versions < 60.0.0 in `pyproject.toml`, `requirements.txt` and CI to avoid compatibility issues between recent `setuptools` version and `numpy.distutils`, due to `setuptools` now using it's own fork of `distutils` rather than the one from Python.
This is one step towards fixing CI:
- It also pin-point `PySide6` to version 6.2.1 in CI to avoid failures.
- It avoids `ci/info_platform.py` to import multiple Qt libs by running Qt checks in subprocesses.
=> Fixed build by NOT using setuptools>=60.0.0

src/silx/gui/plot/backends/BackendOpenGL.py
=> `silx.gui.PlotWidget` OpenGL backend: Make text label background less transparent

src/silx/gui/qt/_qt.py
Crashes appearing with PySide2 at the end of the tests.
=> [GUI] Prevent crashes on exit when deriving QApplication

src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py, src/silx/gui/plot/backends/glutils/GLPlotItem.py
This PR reworks the OpenGL curve rendering to improve dashed curve display.
Beforehand dashes were correctly rendered only for aspect ratio Y/X = 1.
This PR checks if the aspect ratio of the plot changed since previous rendering and if the change is above 5%, it re-compute the distances along the curve used to render the dashes.
The 5% tolerance is to avoid continuous re-computation while resizing the plot.
closes #3595
=> silx.gui.plot.PlotWidget: Fixed dashed curve rendering with the OpenGL backend

src/silx/math/fft/clfft.py, src/silx/math/fft/cufft.py, src/silx/math/fft/fft.py, src/silx/math/fft/fftw.py, src/silx/math/fft/npfft.py, src/silx/math/fft/test/test_fft.py
(see #3439 discussion)
This PR fixes opencl/cuda contexts being created unnecessarily.
Changelog: FFT: avoid creating opencl/cuda contexts when not needed
=> FFT: avoid creating opencl/cuda contexts when not needed

src/silx/gui/plot/_utils/dtime_ticklayout.py, src/silx/gui/plot/_utils/test/test_dtime_ticklayout.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py
This PR fixes 2 issues causing exceptions related to time axis:
- When the initial range of the plot is out of the range supported by Python `datetime`. In this case, there is no tick and values displayed: no ideal, but definitely better than an exception.
- When the data range leads to "nice" ticks outside of the `datetime` range. In this case, those ticks are ignored, but others are still displayed.
closes  #3570
=> silx.gui.plot.PlotWidget: Fixed time axis with values outside of supported range ]0, 10000[ years

setup.py
This PR adds the `SILX_INSTALL_REQUIRES_STRIP` env. var. to strip a list of packages from the `install_requires`.
close #3601
=> build: Added SILX_INSTALL_REQUIRES_STRIP build configuration environment variable

setup.py
This PR removes some now useless code (IMO) from `setup.py`.
A lot of changes in `setuptools` are to be expected (including #3574), so silx's `setup.py` will have to be updated.
This PR is preparing this by doing some clean-up first:
- removes python2 compatibility code
- removes lazy imports and dry-run: nowadays with wheels/conda and  `pyproject.toml` the main ways of installing packages do not need this.
=> Build: `setup.py` cleanup

src/silx/gui/_glutils/font.py, src/silx/gui/utils/matplotlib.py
This PR adds support for math syntax in plot texts (labels, title, etc...) with the OpenGL backend.
It does so by leveraging `matplotlib` parser (if present) to raster the text instead of using Qt.
It also fixes an issue in Qt raster which was producing larger image than necessary.
closes #845
=> silx.gui.plot.PlotWidget: Added support of math syntax to text with OpenGL

src/silx/gui/plot/backends/BackendMatplotlib.py
This PR adds a test in `replot` method to make sure the underlying matplotlib backend is valid before reploting.
This can occur because of the async execution of `replot` through `__deferredReplot`.
@vallsv let me know whether it fixes your issue or not?
closes #3589
=> silx.gui.plot.PlotWidget: Fixed matplotlib backend replot failure under specific conditions

src/silx/io/specfile/src/sflabel.c
This PR makes the temporary buffer larger (256 chars) and cuts the string in case of overflow.
There is certainly a better way to fix this by copying directly the right part of `buf` into the newly allocated `onelabel` buffer and avoiding the use of a temporary buffer, but it involves more code changes.
closes #3621
=> silx.io.specfile: Fixed buffer overflow for too long motor or label

src/silx/io/specfile/src/sfmca.c
Fixed the problem that the last data was not loaded if there was a non-numeric trailing character when loading mca data.
Please refer to https://github.com/silx-kit/silx/issues/3611#issue-1170627169.
=> Fix missing data if there is a trailing space in the mca array

src/silx/gui/utils/testutils.py
Reported (for PyMca) in https://github.com/vasole/pymca/issues/889
For the implemented solution see:
https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method
=> Update for Python 3.11

src/silx/test/__init__.py, src/silx/utils/test/test_external_resources.py
This PR fixes small issues with running tests:
- A typo in selected test functions
- An issue when `resources` tests are run in parallel in multiple processes at the same time (Yes, I managed to get that!): The same folder was used by all concurrent processes
=> Fixed running tests

src/silx/gui/console.py, src/silx/gui/plot/CurvesROIWidget.py, src/silx/gui/plot/LegendSelector.py, src/silx/gui/plot/PlotWindow.py, src/silx/gui/plot/_BaseMaskToolsWidget.py
This PR reworks the handling of the tools embedded in dock widgets in the `PlotWindow` to fix it when `PlotWindow` is displayed inside a tab and the visibility of the tab change.
- All opened tabbed dock widgets remain opened (it was not the case for the "Curves Stats" and the "Console" tabs)
- Dock widgets are only raised when it is shown due to a user action. Before the raised dock widget was changed when switch back and forth from a tab containing a `PlotWindow`.
attn @woutdenolf @vallsv 
closes #3629
=> silx.gui.PlotWindow: Fixed management of DockWidgets when showing/hiding the PlotWindow

.github/workflows/ci.yml, ci/appveyor.yml, src/silx/gui/dialog/test/test_datafiledialog.py, src/silx/gui/dialog/test/test_imagefiledialog.py, src/silx/gui/plot/CurvesROIWidget.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/test/testCurvesROIWidget.py, src/silx/gui/plot3d/test/testGL.py, src/silx/gui/plot3d/test/testScalarFieldView.py, src/silx/gui/plot3d/test/testSceneWidget.py, src/silx/gui/plot3d/test/testSceneWidgetPicking.py, src/silx/gui/plot3d/test/testSceneWindow.py, src/silx/gui/plot3d/test/testStatsWidget.py, src/silx/gui/utils/testutils.py, src/silx/sx/__init__.py
This PR fixes compatibility with the upcoming matplotlib version 3.6.0 and the display of `silx.sx` widgets which requires to enable matplotib (here through pylab) with matplotlib >=3.5.2 which uses PySide6 by default.
Tested on Linux with matplotlib v3.0 to v3.6.
It also updates tests and CI config to fix failing tests.
=> silx.sx: Fixes compatibility with matplotlib>=3.6.0 and PySide6; Fixed continuous integration

src/silx/gui/plot/_utils/delaunay.py
This PR removes the error message displayed when `delaunay` fails when displaying a scatter plot as a mesh.
It changes `delaunay` error log from error to debug level (returns None in case of error anyway)
closes #3608
=> silx.gui.plot: Removed error logs for scatter triangle visualisation with aligned points

src/silx/io/nxdata/parse.py
Regarding parsing of `NXData`, this PR:
- fixes the parsing of axes `@uncertainties` where a fallback was loading `signal`'s `@uncertainties`: This is removed since it's nowhere in the specification and in contradiction with  [`NXcanSAS`](https://manual.nexusformat.org/classes/applications/NXcanSAS.html) application definition.
- adds support of [`NXcanSAS`](https://manual.nexusformat.org/classes/applications/NXcanSAS.html) signal's  `@uncertainties`. The implementation does not check whether it's inside a `NXcanSAS` application definition.
=> silx.io.nxdata: Fixed parsing of `NXcanSAS`'s `@uncertainties`

src/silx/gui/plot/stats/stats.py, src/silx/gui/plot/stats/statshandler.py
This PR fixes deprecation warnings in `StatFormatter` that occur when all the data of an item is outside the Stat computation region.
It also updates the display to show: `--` instead of `None` or `masked` (for numpy `MaskedConstant`).
The `StatCOM` also check for completely masked array to return `NaNs` in this case.
closes #3607
=> silx.gui.plot.stats: Fixed warnings when all data is outside the selected stats region

src/silx/gui/hdf5/Hdf5Item.py
This PR fixes the infinite recursion in case of an unsupported hdf5 entity like a [`Datatype`](https://github.com/h5py/h5py/blob/master/h5py/_hl/datatype.py#L19).
It does not add support for `Datatype` though.
closes #3635
=> silx.gui.hdf5: Fixed issue with unsupported hdf5 entity (e.g. datatype)

src/silx/io/nxdata/parse.py, src/silx/io/test/test_nxdata.py
This PR changes behavior of `silx.io.nxdata.get_default`.
The search of `@default` `NXdata` now recursively follows `@default`.
It also stop checking `NX_class` along the way (i.e., `NXroot/NXentry/NXdata`) and only checks for `NX_class="NXdata"` to find the `NXdata` group.
I'm wondering if the `silx.io.nxdata` functions: `is_group_with_default_NXdata`, `is_NXentry_with_default_NXdata`, `is_NXroot_with_default_NXdata` that were used by `get_default` are used anywhere (they're no longer used in silx), I'm tempted to deprecate them...
It still needs a bit of testing.
closes #3605
=> silx.io.nxdata: Updated `get_default` to be more permissive and follow `@default` recursively

src/silx/app/view/main.py, src/silx/io/test/test_utils.py, src/silx/io/utils.py
This PR adds "*" support for `silx view` `files` argument for filename even when a data path is provided and for data path. Some examples of supported syntax:
`myfiles_*.h5::/data`, `myfiles_*.h5::/entry_*/data`, `myfile.h5::/entry_*/data/*`
It also adds a `silx.io.utils.match` function to find data path matching a pattern in a file.
It is similar to PR #3615 and borrows some of the approach.
closes  #3577
=> silx view: Improved wildcard support in filename and data path

src/silx/io/nxdata/parse.py
As discussed in PR #3657, this removes the support of `@uncertainties` on the signal as described in the `NXcanSAS` application definition, and instead stick to `NXdata` `<signal>_errors`.
Related to #3657
=> silx.io.nxdata: removed support of `NXcanSAS` signal `@uncertainties`

doc/source/Tutorials/io.rst, src/silx/io/h5py_utils.py, src/silx/io/test/test_h5py_utils.py, src/silx/utils/retry.py, src/silx/utils/test/test_retry.py
We already had retry decorators for functions and context managers
```python
@retry()
def method(...):
....
@retry_contextmanager()
def method(...):
yield ...
```
This PR adds a decorator for generator functions
```python
@retry()
def method(...):
yield ...
yield ...
```
=> Retry for generator functions

doc/source/install.rst, doc/source/modules/io/commonh5.rst, doc/source/modules/io/fioh5.rst, doc/source/modules/io/index.rst, doc/source/modules/io/spech5.rst, requirements-dev.txt, setup.py
Merge PR #3649 first!
This PR cleans-up/removes features from `setup.py` since:
> running python setup.py directly as a script is considered deprecated. This also means that users should avoid running commands directly via python setup.py \<command>.
https://setuptools.pypa.io/en/latest/deprecated/commands.html
We can look at packages such as [invoke](https://www.pyinvoke.org/) for this.
This PR:
* Removes `setup.py` commands:
- Remove `python setup.py test` (https://github.com/silx-kit/silx/commit/84b3d7047ccb74f1a7bca1e62258a63209181695): There is `run_test.py` for it.
- Remove `python setup.py build_doc` &cie and document how to call sphinx directly (https://github.com/silx-kit/silx/commit/ea1d920da1964075886c75c1b5e0419872a39f7b): [Sphinx setuptools integration is …
=> Build: Simplified `setup.py`

setup.py
Merge PR #3651 first!
This PR:
- removes code for compatibility with macos 10.8 during the build.
- removes the patch of `PyMODINIT_FUNC` durign build for `manylinux1` support
closes #3652
=> Build: Simplified `setup.py`, removed support of `manylinux1`

src/silx/gui/widgets/ElidedLabel.py, src/silx/gui/widgets/test/test_elidedlabel.py
This PR fixes the ElideLabel API inherited from QLabel.
For consistency and interoperability purpose.
Closes #3641
Changelog: 
- ElideLabel: Fix API inherited from QLabel
=> ElideLabel: Fix API inherited from QLabel

doc/source/install.rst, doc/source/modules/gui/plot/getting_started.rst, doc/source/virtualenv.rst, requirements.txt, src/silx/gui/qt/__init__.py, src/silx/gui/qt/_qt.py
This PR marks `PySide2` as deprecated but does not remove its support nor the tests.
It also tries to load `PySide6` before `PySide2` and removes reference to `PySide2` in the documentation (except for the `silx.gui.qt` module).
closes #3645
=> silx.gui.qt: Deprecated `PySide2` support

src/silx/math/chistogramnd_lut.pyx
This adds unit16 as a support type for weights and fixes a typo.
This would allow to remove a [duplicated implementation in xsocs](https://gitlab.esrf.fr/kmap/xsocs/-/blob/1f78899354a3693c7085cee0d4db49a0f37e65f1/xsocs/util/filt_utils/histogramnd_lut.pyx) (where the histogram lut was initially implemented).
=> silx.math.histogram: Added support of uint16 weights for LUT histogram

src/silx/gui/data/DataViews.py, src/silx/gui/data/NXdataWidgets.py
This PR does not keep aspect ratio by default in the case the 2 axes of an image have different `@units` (either both are defined and different or only one is defined).
In all other cases, the aspect ratio is kept by default.
This is done for the image and complex image widgets, and not for the stack or 3D views.
closes #3626
=> silx.gui.data: Do not keep aspect ratio in `NXdata` image views when axes `@units` are different

bootstrap.py, run_tests.py
This PR fixes `bootstrap.py` and `run_tests.py` no longer working with latest versions of `setuptools` since the build path has changed from e.g., `build/lib.linux-x86_64-3.7` to `build/lib.linux-x86_64-cpython-37`...
As a result, the path added to `sys.path`/`PYTHONPATH` was no longer the right one.
This PR fixes it by forcing the `--build-lib` directory to the previous one (e.g., `build/lib.linux-x86_64-3.7`) so the scripts know where it is.
closes #3676
=> Misc: Fixed development scripts compatibility with `setuptools`

src/silx/gui/data/DataViews.py, src/silx/gui/data/NXdataWidgets.py
This PR activates the plot grid by default when plotting curves and `NXdata` view displaying curves and (x, y) scatters. It is activated neither for (x, y, value) scatters nor for images.
closes #3355
=> silx view: Enabled plot grid by default for curve plots

src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/scatter.py, src/silx/gui/plot/test/testPlotWidget.py
This PR:
- Fix the documentation of `xerror` and `yerror` to match the implementation regarding 2xN arrays
- Take error bars into accounts when computing the bounding box
closes #3606
=> silx.gui.plot.PlotWidget: Take errorbars into account for item bounds

src/silx/gui/data/DataViewer.py, src/silx/gui/data/DataViewerFrame.py, src/silx/gui/data/test/test_dataviewer.py
This PR adds a `selectionChanged` signal to `DataViewer` and `DataViewerFrame`.
This signal is triggered after the selection has changed. The selection change can be the result of:
- An update of the selection by the user.
- A change to a view which support different dimensionality (e.g., moving from image to curve view).
- A change of data with a different shape.
closes #3628
=> silx.gui.data.DataViewer: Added `selectionChanged` signal

src/silx/gui/utils/glutils/__init__.py, src/silx/gui/utils/test/test_glutils.py
Allow to check `AA_ShareOpenGLContexts` in `isOpenGLAvailable`
Default is false.
Changelog: 
- Allow to check AA_ShareOpenGLContexts in isOpenGLAvailable
=> Allow to check AA_ShareOpenGLContexts in isOpenGLAvailable

src/silx/gui/data/Hdf5TableView.py
Closes #3571
The first virtual source is
```
/data/id21/inhouse/eduardo/out/fitted_EP_701_1_859_12158.h5::/2.1/blisspymca.1/results/parameters/Al_K
```
Alternatively this could also be
```
.::/2.1/blisspymca.1/results/parameters/Al_K
```
I prefer the first (absolute path) because it might not be clear that a "dot" refers to the current file and not to the current directory.
=> HDF5 table view bug for virtual datasets in the same file

src/silx/io/dictdump.py, src/silx/io/test/test_dictdump.py
f24df26ad86f3a470c04fdaa1da5e884260223f4: This PR avoids warnings when passing `pint.Quantity` to `dicttoh5` by using the `.magnitude`.
641c0d0fb5b2008820bf1c9f334a849bf67f6c4f: This PR also proposes to store `pint` units as `@units` HDF5 attributes when calling `dicttonx`.
There is an issue here since [pint units string formatting](https://pint.readthedocs.io/en/stable/formatting.html#unit-format-specifications) is not strictly compatible with NeXus (see https://manual.nexusformat.org/nxdl-types.html?highlight=units#unit-categories-allowed-in-nxdl-specifications, https://manual.nexusformat.org/datarules.html#nexus-data-units): For example power is either `**` or `^`. BTW does anyone have a link to the specification of Nexus units format?
What do you think? Should I remove support in …
=> silx.io.dictdump: Added support of `pint` in `dicttoh5` and `dicttonx`

src/silx/opencl/processing.py, src/silx/opencl/sift/test/test_image_setup.py
A memory leak was found when keeping all events from PyOpenCL for profiling purposes.
https://github.com/inducer/pyopencl/issues/625
This PR extracts earlier the timing info to avoid keeping references on input buffers.
Changelog: 
New OpenCL profiling (fix memory leak)
=> Eventless OpenCL profiling

src/silx/app/view/Viewer.py, src/silx/gui/hdf5/Hdf5Item.py, src/silx/gui/hdf5/Hdf5LoadingItem.py, src/silx/gui/hdf5/Hdf5Node.py, src/silx/gui/hdf5/Hdf5TreeModel.py, src/silx/io/utils.py
This PR fixes the refresh of selected files for files which where opened with a subpath (e.g., `file.h5::/entry/data`)
closes #3616
=> silx view: Fixed refresh for content opened as `file.h5::/path`

src/silx/gui/qt/_qt.py
This raise a clear exception early rather than waiting for other exceptions later.
closes #3618
=> silx.gui.qt: Raise exception when using PyQt5 incompatible with Python 3.10

ci/requirements-pinned.txt, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py
This PR changes the way anchors are rendered which was causing issues with some GPUs.
It is now passing vertex attributes directly from memory (the old way) as the other rendering do rather than creating/deleting a vertex buffer object.
closes #3681
=> silx.gui.plot.PlotWidget: Fixed OpenGL rendering

src/silx/gui/_glutils/font.py, src/silx/gui/plot/backends/glutils/GLText.py, src/silx/gui/utils/matplotlib.py
This is fixed at 2 levels: 
- Make raster text functions works with whitespace only strings
- Do not render whitespace only text in plot
closes  #3700
=> silx.gui.plot.PlotWidget: Fixed OpenGL empty text rendering

src/silx/gui/plot/_BaseMaskToolsWidget.py
Switch from home directory to current working directory.
closes  #3703
=> `silx.gui.plot.MaskToolsWidget`: Changed mask load/save default directory

.github/workflows/ci.yml, ci/appveyor.yml, ci/info_platform.py, doc/source/install.rst, doc/source/license.rst, doc/source/modules/gui/plot/getting_started.rst, doc/source/virtualenv.rst, requirements.txt, setup.py
Better to merge PR #3711 first!
- Drop Python3.6: closes #3654
- Remove `PySide2` from CI: related to #3666
=> Dropped python 3.6 support, Removed CI for `PySide2`

requirements.txt, src/silx/io/dictdump.py
This PR fixes `silx.io.dictdump` support of `pint` for versions >= 0.20.
At the same time, older versions of `pint` where `Quantity` is not available through `pint.Quantity` but through `pint.quantity.Quantity` are no longer supported (it's possible to add it if needed).
`pint` is also added to `requirements.txt` and so it is installed when running the CI... This would have spotted the removal of `pint.quantity` (see #3724).
closes #3724
=> Fixed support of `pint` >= 0.20

CHANGELOG.rst, src/silx/_version.py
This PR prepares a v1.1.1 version.
=> Updated changelog, bump to version 1.1.1

src/silx/gui/plot/MaskToolsWidget.py, src/silx/gui/plot/ScatterMaskToolsWidget.py, src/silx/gui/plot/_BaseMaskToolsWidget.py
This PR fixes the reset of interaction mode when closing the scatter or image mask tool.
It now resets to the previous interaction mode (`pan` or `zoom`).
To backport to 1.x branch.
closes #3718
=> silx.gui.plot: Fixed reset of interaction when closing mask tool

.github/workflows/ci.yml, ci/appveyor.yml, requirements-dev.txt, setup.py, src/silx/gui/_glutils/gl.py, src/silx/gui/_glutils/test/__init__.py, src/silx/gui/_glutils/test/test_gl.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py
I found that the GL version was not properly parsed.
It was returning `51, 48` for a string version `3.0`.
Because the string was bytes and indexes was returning ordinal of char `3` and `0`
This parsing issue was probably broken in python 3 since the beginning. Or it is a change in the behavior of PyOpenGL.
This PR create a dedicated function to return this version.
Changelog: 
- Fix GL version parsing
=> Dedicated function to parse gl version

src/silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes an issue when rendering a PlotWidget with width or height of 0.
closes #3719
=> silx.gui.plot: Fixed issue when PlotWidget has a size of 0

src/silx/gui/plot/MaskToolsWidget.py, src/silx/gui/plot/actions/io.py, src/silx/gui/plot3d/actions/io.py
This PR solves issue #3730 for `QFileDialog`.
I also checked similar cases for all `QDialog` and inherited classes.
closes #3730 even if there is probably other enum issues but the one reported should be fixed.
=> silx.gui: Fixed support of PySide6.4 enums

src/silx/gui/colors.py, src/silx/math/fft/test/test_fft.py, src/silx/math/medianfilter/test/test_medianfilter.py, src/silx/math/test/test_colormap.py, src/silx/math/test/test_combo.py, src/silx/opencl/medfilt.py, src/silx/opencl/sift/match.py, src/silx/opencl/sift/plan.py, src/silx/opencl/sift/test/test_align.py, src/silx/opencl/sift/test/test_convol.py, src/silx/opencl/sift/test/test_image_setup.py, src/silx/opencl/sift/test/test_keypoints.py, src/silx/opencl/sift/test/test_matching.py, src/silx/opencl/sift/test/test_preproc.py, src/silx/opencl/sift/test/test_transform.py, src/silx/opencl/test/test_array_utils.py, src/silx/opencl/test/test_convolution.py, src/silx/opencl/test/test_linalg.py, src/silx/opencl/test/test_medfilt.py, src/silx/resources/opencl/sift/transform.cl
This PR removes some deprecation warnings issued during the tests.
I does not remove the deprecation warning for `scipy.misc.ascent` since the replacement (`scipy.datasets.ascent`) requires an extra dependency (`pooch`) which is not available in older Debian, but it makes the test code ready for the removal of `scipy.misc.ascent`.
closes #3734
closes #3715
=> Fixed `numpy`, `scipy`, `matplotlib` deprecation warnings

src/silx/gui/plot/ImageView.py
This PR fixes the `setSideHistogramDisplayed(False)` when the widget or one of the ancestor is not visible.
`isVisible()` is one of the property which is not symmetric to `setVisible()`.
As result `isSideHistogramDisplayed` was false is some cases for false reason.
Which was inhibiting `setSideHistogramDisplayed`.
Changelog: 
- Fix ImageView histogram visibility
=> Fix histogram visibility

src/silx/math/_colormap.pyx
This PR makes silx build with cython3.0.0b1 regarding the support of power `**`.
This PR makes direct use of the `pow` function from `libc.math` since this looks to work across different versions of cython (0.29.x and 3.0).
Some background information for the record:
See https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#power-operator
Also cython 3.0.0b1 introduced a `cpow` [compiler directive](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) to use the C `pow` function for `**`... but this directive is not available in previous versions of Cython.
<details>
<summary>Details of different behaviors from cython.cpow doc</summary>
Type of a | Type of b | cpow==True | cpow==False
-- | -- | -- | --
C integer …
=> Fixed support of cython 3.0.0b1

src/silx/gui/data/NXdataWidgets.py, src/silx/math/calibration.py, src/silx/math/test/test_calibration.py
This PR updates the `calibration` to raise exceptions for empty arrays and it takes it into account for NXData views in silx view.
It also moves the signal connections before updating the plot so they are registered even if an exception occurs later, just in case.
closes #3766
=> [silx view] Fixed support of NXData image with 0-length axis

build-deb.sh
This PR provides a small fix to retrieve the version information without starting Python from the `src/silx` folder to avoid issues with e.g. `import io` during Python start-up.
closes #3771
=> Fixed `build-deb.sh`: Avoid to run Python from `src/silx`

src/silx/io/h5py_utils.py
For some reason(?) we ended-up in a situation where checking that an exception was coming from `h5py` failed because `__package__` was not defined in `f_locals` in this function:
https://github.com/silx-kit/silx/blob/16888f095a247b508c7627b410b60a6231267fd9/src/silx/io/h5py_utils.py#L114-L122
This PR proposes to fix this by also looking for `__package__` == "h5py" in the frame's `f_globals`.
Not sure it is the right way to fix it, but looking in `f_globals` fixed the issue at hand.
attn @vallsv
=> Fixed `silx.io.h5py_utils.retry`

src/silx/opencl/codec/bitshuffle_lz4.py, src/silx/opencl/codec/test/test_bitshuffle_lz4.py
This PR adds support for `Array` and `Buffer` as `raw` arguments to `BitshuffleLz4.decompress`.
It adds some tests for it.
It also reworks the tests to use `pytest` and fixtures rather than `unittest`.
=> `silx.opencl.codec` : Added support of pyopencl's `Buffer` and `Array` to `BitshuffleLz4.decompress`

.github/workflows/ci.yml, src/silx/conftest.py, src/silx/gui/data/TextFormatter.py, src/silx/gui/data/test/test_textformatter.py, src/silx/io/test/test_dictdump.py
Attributes have a different way to handle types and it is possible to read an array with dtype `object` which actually contains `str`. This case was not supported.
Closes #3789
=> silx.gui.data: Fixed issue with hdf5 attributes string formatting

src/silx/gui/widgets/UrlSelectionTable.py
This PR fixes an exception raised when click on the text cell of `UrlSelectionTable`.
This is due to the `UrlSelectionTable.setSelection` that overrides `QTableView.setSelection` which has different arguments.
This PR deprecates `get|setSelection` in favor of `get|setUrlSelection` to avoid the conflict.
It also avoids this exception by checking the type of `setSelection` arguments.
closes #3758
=> silx.gui.widget.UrlSelectionTable: Fixed exception with interaction, renamed `get|setSelection` to `get|setUrlSelection`

src/silx/gui/dialog/ColormapDialog.py
This PR makes `ColormapDialog` stretch consistent between with/without histogram cases.
closes #3710
=> silx.gui.dialog.ColormapDialog: Fixed ColormapDialog layout

src/silx/gui/colors.py
Changelog: 
- `Colormap.setVRange` raises an exception if the range is not finite
=> color: Exception if vrange is not finite

src/silx/io/dictdump.py, src/silx/io/test/test_dictdump.py
This PR removes `dicttoh5`'s `overwrite_data` argument that is deprecated since v0.15.0.
Do you think it's OK, or it's best to keep maximum compatibility here?
=> silx.io.dictdump: Removed `dicttoh5` `overwrite_data` argument

src/silx/opencl/common.py, src/silx/opencl/test/test_medfilt.py
using PortableCL... disable it for now.
Changelog: skip test on broken platform
=> This test fails on edna site with a CPU device

src/silx/gui/fit/FitWidget.py, src/silx/gui/icons.py, src/silx/gui/plot/CurvesROIWidget.py, src/silx/gui/plot/PlotWindow.py, src/silx/gui/plot/Profile.py, src/silx/gui/plot/StackView.py, src/silx/gui/plot3d/scene/interaction.py, src/silx/io/convert.py, src/silx/io/spech5.py
This is a first round of deprecated features removal marked as such since at least March 2018.
It also removes outdated docstrings.
=> Removed features deprecated since <=0.7.0

src/silx/gui/widgets/UrlSelectionTable.py, src/silx/gui/widgets/test/test_urlselectiontable.py
Changelog: 
- `UrlSelection`:
- Rework the look and feel
- Allow to drop an URL from `silx view`
- Fixes typos on variable names
=> Improve url selection

.github/workflows/ci.yml, src/silx/gui/plot/StackView.py, src/silx/gui/plot/test/testStackView.py
This PR removes the `autoscale` argument of `StackView.setColormap` that is marked as deprecated since  v0.14.
=> silx.gui.plot.StackView: Removed `setColormap` `autoscale` argument

src/silx/gui/plot/items/image_aggregated.py
This just silent all-NaN value warnings from `numpy`'s `nanmin`, `nanmax` and `nanmean` function.
Those functions return NaN in this case.
closes #3746
=> `silx.gui.plot.items`: Remove `ImageDataAggregated` all-NaN warning

src/silx/math/colormap.py, src/silx/math/test/test_colormap.py
This PR adds a `normalize` function that converts an array to an array of `uint8` by applying a normalization as done for applying colormaps.
closes #3769
=> `silx.math.colormap`: Added `normalize` function to normalize to `uint8`.

src/silx/app/view/About.py, src/silx/conftest.py, src/silx/gui/fit/FitWidget.py, src/silx/gui/plot/test/testPlotWindow.py, src/silx/gui/plot/tools/profile/manager.py, src/silx/gui/plot3d/ParamTreeView.py, src/silx/gui/plot3d/tools/PositionInfoWidget.py, src/silx/gui/qt/__init__.py, src/silx/gui/qt/_qt.py, src/silx/gui/qt/_utils.py, src/silx/gui/qt/inspect.py, src/silx/gui/test/test_qt.py, src/silx/gui/utils/glutils/__init__.py, src/silx/gui/utils/image.py, src/silx/gui/utils/matplotlib.py, src/silx/gui/utils/testutils.py, src/silx/gui/widgets/ElidedLabel.py, src/silx/gui/widgets/WaitingPushButton.py
As announced in v1.1.0.
This PR clean-up codes for supporting `PySide2` (except for the `loadUi` function done in PR #3783).
closes #3666
=> Drop support of PySide2

src/silx/gui/_glutils/OpenGLWidget.py, src/silx/gui/_glutils/gl.py
This PR:
- Only init OpenGL extensions when needed, i.e., with OpenGL v2
- Check if there is a possible compatibility issue between Qt and pyopengl. This can occurs if one uses X11 and the other wayland which is supported since pyopengl v3.1.6.
Related to #3733
=> silx.gui: Added a warning about pyOpenGL and Qt compatibility

copyright, src/silx/gui/qt/__init__.py, src/silx/gui/qt/_pyside_dynamic.py
This PR updates `PySide6`'s `loadUI` implementation according to upstream.
It also removes support for `PySide2` in it (no longer supported by `silx`).
closes #3778
=> `silx.gui.qt`: Updated PySide6 `loadUi` function

src/silx/gui/data/DataViews.py
This should no longer be needed.
=> silx.gui.data.DataView: Removed patch for pymca <v5.3.0 support

src/silx/gui/widgets/UrlSelectionTable.py
Split the URL column in 3 columns for filename/datapath/slice.
This is just for readability.
And it make it easy to hide one of the columns from the API.
I have removed the `URL_COLUMN`, but we also can restore it by default if you prefer.
So it could be easy to display it and to hide the others on your side.
Changelog: 
- UrlSelectionTable: Split the URL column in 3 columns
=> Urlselectiontable with 3 columns

src/silx/io/nxdata/parse.py
This PR removes a validation check that is too strict an fails under correct condition if one dimension of the signal is `1`.
closes #3781
=> `silx.io.nxdata.parser`: Fixed `NXdata` validation

src/silx/gui/plot/items/curve.py, src/silx/gui/plot/items/image.py
This PR deprecates the access of Curve and Images PlotWidget Items as sequence-like that was there initially.
The same information is accessible through those Item's API, so let's deprecate the compatibilty mechanism.
attn @vasole do you rely on this compatibility in pymca?
=> silx.gui.plot: Deprecate PlotWidget's Curve and Image sequence-like access

src/silx/__main__.py, src/silx/app/compare/CompareImagesWindow.py, src/silx/app/compare/__init__.py, src/silx/app/compare/main.py, src/silx/app/compare/test/__init__.py, src/silx/app/compare/test/test_compare.py, src/silx/app/compare/test/test_launcher.py, src/silx/gui/plot/CompareImages.py, src/silx/gui/plot/test/testCompareImages.py
This PR introduce a `silx compare` UI to make is easy to use.
```
silx compare --help
usage: silx compare [-h] [--debug] [--use-opengl-plot] [files [files ...]]
GUI to compare images
positional arguments:
files              Image data to compare (HDF5 file with path, EDF files,
JPEG/PNG image files). Data from HDF5 files can be
accessed using dataset path and slicing as an URL:
silx:../my_file.h5?path=/entry/data&slice=10 EDF file
frames also can can be accessed using URL:
fabio:../my_file.edf?slice=10 Using URL in command like
usually have to be quoted: "URL".
optional arguments:
-h, --help         show this help message and exit
--debug            Set logging system in debug mode
--use-opengl-plot  Use OpenGL for plots (instead of matplotlib)
```
```
silx compare …
```
=> [silx compare] Create a dedicated app to compare images

src/silx/app/compare/CompareImagesWindow.py, src/silx/app/compare/main.py, src/silx/app/utils/parseutils.py, src/silx/gui/plot/CompareImages.py
Here is few fixes to make the UI a bit more usable.
This also includes a refactoring the to toolbuttons used to selection the modes (in order to expose them).
Main changes are:
- save/restore settings
- expose toolbutton as public
- `getActionFromMode`, for general use case
- `setVisibleModes`, for convenience
- fix broken `--use-opengl-plot`
- plus polish
=> Polish image compare app

src/silx/gui/conftest.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/test/testPlotWidget.py, src/silx/gui/plot/test/testPlotWidgetDataMargins.py
This PR adds a `margins` argument to `PlotWidget.setLimits` which allows to choose between:
- `margins=True`: to apply the "default" margins from `PlotWigdet.getDataMargins()`
- `margins=False`: to apply no margins
- `margins=4-tuple of float`: to apply provided margins.
To achieve this, it moves some logic from `_forceResetZoom` to `setLimits`.
There is a few more minor things (see the different commits):
- Added typing to a few methods and some tests related to `get|setDataMargins`.
- To write those, I added a `qWidgetFactory` fixture to handle the life-cycle of QWidget in tests.
- Fix a warning in the tests 
closes #3753
=> `silx.gui.plot`: Added `margins` argument to `PlotWidget.setLimits`

src/silx/gui/plot/ImageStack.py
This PR replaces `isVisible` with `isVisibleTo` to make it symmetrical with `setVisible` for `_ToggleableUrlSelectionTable.toggleUrlSelectionTable` to behave as a toggle in all conditions.
This is a minor fix, since conditions leading to an issue are not supposed to happen: this method should only be called from a button click... so `isVisible` should return True if it was set to True... but correct behavior relied on this assumption.
closes #3744
=> `silx.gui.plot`: Fixed `ImageStack` handling of visible state

src/silx/gui/plot/PlotWindow.py
Fix for those 2 actions of `PlotWindow` that were not added the the action group and thus not to the toolbar... They are hidden by default to be consistent with the previous behaviour.
=> `silx.gui.plot`: Fixed display of `PlotWindow` zoom in/out actions

src/silx/gui/dialog/FileTypeComboBox.py, src/silx/io/fabioh5.py, src/silx/io/test/test_fabioh5.py
This PR removes code for support of fabion <0.9 since there is already a requirement `fabio>=0.9` in `setup.py`.
https://github.com/silx-kit/silx/blob/d398b00d1d9dfe039dcc6d80a3c80b0582c684c8/setup.py#L496-L504
closes #2497
=> Remove code for support of fabio<0.9

doc/source/modules/gui/plot/items.rst, src/silx/gui/plot/items/_roi_base.py
This PR adds missing ROI classes in the doc: base class of ROIs , and  `ArcROI` and `BandROI`
closes #3756
=> Documentation: Added `silx.gui.plot.items.roi` base classes to documentation

src/silx/gui/colors.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/test/test_colors.py
~~! Merge PR #3835 first!~~
This PR should close #3755.
It adds support for `color{index}` name in both `colors.rgba` function and `PlotWidget.addCurve|Histogram`.
To do so, `rgba` takes an extra optional `colors` argument
It all sounds a bit complex to me (e.g., to use `PlotWidget.getDefaultColors()` at some place and use `silx.config.DEFAULT_PLOT_CURVE_COLORS` everywhere else). So need to check how this is going to be used and maybe consider adding a `silx.config.DEFAULT_COLORS`.
Maybe that's better as a `PlotWidget.addCurve|Histogram` only feature at first...
=> silx.gui.colors, silx.gui.plot: Added indexed color names in `rgba` and `PlotWidget`

src/silx/gui/dialog/ColormapDialog.py, src/silx/gui/dialog/test/test_colormapdialog.py
This PR fixes the update of the `ColormapDialog` when the associated item is updated.
closes #3745
=> `silx.gui.dialog`: Fixed `ColormapDialog` state when updating `Item`

src/silx/gui/plot/tools/profile/rois.py
Closes #3844
Make sure the ROI description is extracted once, in order to be thread safe when multiple profiles have to be computed (i.e. profiles on R, G, B)
Changelog: 
- Fixed concurrency issue with RGB profiles
=> Fix rgb profile

doc/source/modules/gui/plot/plotwidget.rst, pytest.ini, src/silx/gui/plot/PlotInteraction.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/_utils/__init__.py, src/silx/gui/plot/_utils/panzoom.py, src/silx/gui/plot/actions/control.py
This PR aims at allowing to configure zoom on the different axes independently.
With this PR, only zoom on wheel is managed.
To provide more control over the interaction, it adds a `PlotWidget.interaction` method to retrieve the interaction handler.
For now it only allows to toggle zoom on wheel and to select which axes can be zoomed.
This paves the way for adding more control over the interaction.
Related to #3743
=> `silx.gui.plot`: Added per-axis toggle of `PlotWidget` zoom

src/silx/gui/plot/CompareImages.py, src/silx/gui/plot/items/image.py, src/silx/gui/plot/tools/compare/core.py
Feature a consistent autoscale for the CompareImage.
Now
- the autoscale statistics are computer globally for the 2 images
- it is also computed on the raw image (instead of in the sliced left/right image)
- This makes the autoscale usable, from the ColormapDialog, including 3stddev
- subsequently when you are about to slice, the statistics are not recomputed -> that's faster
Changelog: 
- CompareImage: Colormap autoscale is now global to the 2 raw images to compare
- CompareImage: `updateColormap=` was dropped, this can be set with `getColormap()`
=> CompareImage: Feature a consistent autoscale

examples/plotContextMenu.py, src/silx/gui/plot/PlotInteraction.py, src/silx/gui/plot/PlotWindow.py, src/silx/gui/plot/actions/mode.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/items/axis.py, src/silx/gui/plot/test/testItem.py, src/silx/gui/plot/test/testPlotInteraction.py, src/silx/gui/plot/tools/menus.py
Merge PR #3842 first !
This PR adds support for per-axis zoom toggle for zoom on mouse selection.
It also adds an optional menu to `ZoomModeAction` to interactively select which axis should be zoomed.
This menu can be enabled with `ZoomModeAction.setAxesMenuEnabled`.
This feature needed to know whether the Y axis on right is visible or not, so I added an `Axis.isVisible` method.
Since there is a conflict between keeping data aspect ratio and disabling zoom on some axes, when keep aspect ratio is enabled, all axes are zoomed, no matter of the zoomOnAxes config.
related to #3743
=> silx.gui.plot: Added per axes zoom to `PlotWidget`

src/silx/_config.py
Closes #3850
This PR updates the color cycle with the one from matplotlib 2.0.
Changelog: 
- Update the color cycle with the one from matplotlib 2.0
=> Update the curve color cycle

src/silx/_config.py, src/silx/gui/plot/PlotWidget.py
Closes #3849
This PR uses linewidth2 as default selected style
Changelog:
- Added `DEFAULT_PLOT_ACTIVE_CURVE_COLOR` to `silx.config`
- Added `DEFAULT_PLOT_ACTIVE_CURVE_LINEWIDTH` to `silx.config`
- Changed default active curve style as linewidth=2
=> Use linewidth2 as default selected style

src/silx/gui/plot/CompareImages.py, src/silx/gui/plot/tools/compare/core.py
The previous implementation was trying to constraint the data on the same data range, anyway the visualization mode.
This approach is fine for most of the modes, except A-B.
- Now A-B is handled in a special way, in order to use the basic operation `A-B`
- The colormap is now updated (when we switch between the visualization mode) in order to stay in the same data range
- Plus an RGB improvement to use any colormap normaization (before it was only a linear scale)
No changelog is needed as it's just a kind of partial revert of the previous change
Changelog:
=> CompareImages: Fix the A-B visualization mode

src/silx/app/compare/CompareImagesWindow.py, src/silx/io/utils.py
This PR move back a feature from `CompareImagesWindow` to the core `silx.io.utils.get_data`.
Closes #3852
Changelog: 
- Added support of bare file from `silx.io.utils.get_data` with `check_schemas=True`
=> Get data without schema

src/silx/gui/colors.py, src/silx/gui/test/test_colors.py
This change is done to match the matplotlib syntax "CN".
See https://matplotlib.org/stable/tutorials/colors/colors.html#cn-color-selection
Changelog: 
- Changed indexed color pattern to match "CN" color selection from matplotlib
=> Use "C" prefix to identify a color from the default palette

src/silx/gui/plot/items/axis.py, src/silx/gui/plot/test/testAxis.py, src/silx/gui/plot/test/testItem.py
This PR replace the previous unconditional `resetZoom` when switching plot axes scales to one  that tries to preserve axis limits as much as possible:
- When switching from "log" to "linear" scale, limits are not updated
- When switching from "linear" to "log" scale:
- Only the axis that has a scale change is updated.
- If limits are positive, they are kept
- If min limit is negative, the data range is used for setting it and the max value is kept if positive and having data below it.
closes #2825
=> silx.gui.plot.PlotWidget: do not reset zoom when changing axes scales

src/silx/gui/colors.py, src/silx/gui/plot/tools/compare/profile.py
This tune the compare image profile to use the default palette.
I have picked colors with a good distance, but without a very difference between the intensity. For example C0/C1 was really horrible.
No need change log for that because it's a fine tune on a new feature.
Plus a fix on `rgba` in order to provide a better message when the string is wrong.
Changelog: 
- `silx.gui.colors.rgba` now raises a `ValueError` instead of an assertion error
=> compareimage: tune diff profile colors

src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/actions/control.py
Added `sigBackendChanged` to `PlotWidget`
Related to #3876 
Closes #3883
Changelog: 
- Added `sigBackendChanged` to `PlotWidget`
=> PlotWidget: Added sigBackendChanged

src/silx/gui/plot/PlotInteraction.py
This PR fixes the update of the mouse cursor when finishing an interaction with a ROI.
This is an alternative to PR #3893.
Compared to PR #3893, it does not need to use a global variable, removes a blinking cursor (set to default in `__terminateDrag` and changed in `Idle.enterState`) and updates the cursor according to the item that interaction will occur on (= the top-most marker) rather than the last one used for interaction.
closes #3892
=> silx.gui.plot: Fixed PlotWidget mouse cursor update

src/silx/gui/dialog/ColormapDialog.py
Closes #3857 
Make the colormap dialog safe with derivated image item.
Changelog: 
- Robustness on `ColormapDialog` tool with derivated `ImageBase`
=> Fix colormap dialog data bound

src/silx/gui/plot/backends/BackendMatplotlib.py
This PR fixes the display of `Shape` items with the matplotlib backend when they are display with dash and a background color.
It does so by changing the implementation of the feature to avoid using a proxy item in the backend
closes #3879
=> silx.gui.plot.PlotWidget: Fixed display of `Shape` with dashes and a background color

src/silx/app/view/ApplicationContext.py, src/silx/app/view/Viewer.py, src/silx/app/view/main.py, src/silx/gui/_glutils/OpenGLWidget.py, src/silx/gui/utils/glutils/__init__.py
This PR updates `isOpenGLAvailable` to check the compatibility between Qt and pyopengl selected platforms.
It also updates `silx view` and `silx compare` to fallback on matplotlib if OpenGL is selected but not available.
closes #3630
=> silx.gui: Check Qt/pyopengl platform compatibility; silx view/compare: Use matplotlib if OpenGL is not available

src/silx/gui/plot/PlotWidget.py
This allows to add use custom items in a plot widget like `Group` as proposed in PR #3898
Taken from PR #3898
=> silx.gui.plot.PlotWidget: Added support for 'other' kind of plot items

doc/source/modules/math/fit/functions.rst, src/silx/math/fit/fittheories.py, src/silx/math/fit/functions.pyx, src/silx/math/fit/functions/include/functions.h, src/silx/math/fit/functions/src/funs.c, src/silx/math/fit/functions_wrapper.pxd, src/silx/math/fit/test/test_peaks.py
Allows the Lorentzian fraction to be different on the left and on the right of the centroid:
Closes https://github.com/silx-kit/silx/issues/3901
Changelog: add split pseudo-voigt with split lorentzian fraction
=> add split pseudo-voigt with split lorentzian fraction

.github/workflows/ci.yml, ci/appveyor.yml, pyproject.toml, requirements.txt
This PR removes the constraint of using `setuptools<60` that was introduced in PR #3583 to avoid issues with `numpy.distutils`.
`silx` no longer relies on `numpy.distutils`, so let's lift this constraint which should no longer be needed.
This PR also modernises CI config to use `python -m build` rather than `python setup.py`
=> Build: Removed constraint on `setuptools` version

ci/appveyor.yml, doc/source/applications/view.rst, src/silx/app/utils/parseutils.py, src/silx/app/view/main.py, src/silx/gui/data/DataViewer.py, src/silx/gui/hdf5/Hdf5TreeModel.py, src/silx/gui/plot/tools/profile/core.py, src/silx/io/_sliceh5.py, src/silx/io/test/test_sliceh5.py, src/silx/io/utils.py
This PR adds the option to pass multiple integers for displaying slices with `silx view` through a `--slice` option.
To do so, it adds a `DatasetSlice` class to expose the opened slice as a dataset and makes the necessary changes to make it work.
The content of this PR is adapted from PR #3677 (which was hard to rebase).
It is a simpler version of PR #3677 since it only provides `--slice` and not URL `#fragment` support which could be added later if needed.
=> silx view: Added `--slices` option

src/silx/gui/plot/items/_roi_base.py, src/silx/gui/plot/tools/roi.py
Closes #3882
This PR provides a `populateContextMenu`  plus a rework of the default context menu in order to move actions from a dedicated ROI in to a dedicated submenu.
This also fixes 2 bugs:
- The context menu was not properly dropped for ROIs based on a single marker (for example the profiles)
- The `remove` action was also included when the mouse was not hovering the ROI (which is counter intitive for a context menu)
Changelog: 
- Added `populateContextMenu` to the ROIs (including profile ROIs)
=> Added populateContextMenu to ROIs

src/silx/opencl/common.py
This PR changes the way to initialise `mf` in order to hopefully simplify reading the code by separating probing the the import of `pyopencl` from `mf` init.
There should be no difference in behavior.
closes #3878
=> `silx.opencl.common`: Reworked initialisation of the module

src/silx/opencl/atomic.py
Changelog: prevent crash at init when loading silx with PortableCL + Cuda devices. Work-around
=> Do not probe GPU interfaced with PoCL

src/silx/io/dictdump.py, src/silx/io/test/test_dictdump.py
Changelog: better error message for dicttoh5 with non-serializable data
=> [dicttoh5] better error message for non-serializable data

src/silx/resources/opencl/doubleword.cl
To validate this, one needs to run the test of pyFAI on platform PoCL+CUDA
```
PYOPENCL_CTX=port:nvidia ./run_tests.py  pyFAI.opencl.test.test_openCL.TestDoubleWord
```
Changelog: Fix regression in PoCL
#close 3934
=> Fix order of floating point operations

src/silx/app/compare/CompareImagesWindow.py
Fix python `set(3,4)` command with `set([3,4])`.
=> Issue #3942 - silx compare typo

src/silx/gui/hdf5/test/test_hdf5.py, src/silx/io/utils.py
Changelog: io.utils.open: do not lock the file
Closes #3938
=> io.utils.open: do not lock the file

src/silx/app/view/Viewer.py, src/silx/gui/hdf5/Hdf5TreeModel.py, src/silx/gui/hdf5/test/test_hdf5.py
This PR aims at opening the vis at startup when providing a data path along with the file to open: closes  #3916
To achieve so, this PR adds an extra argument to `Hdf5TreeModel.sigH5pyObjectLoaded` in order to pass the full filename used to open the item.
=> silx view: Fixed setting focus at startup when opening a dataset

src/silx/app/view/Viewer.py, src/silx/app/view/main.py
This PR makes `silx view` using a dedicated `sys.excepthook` to stop showing a `QMessageBox` for each exception.
Instead, it keeps logging the error and adds a "permanent" widget in the application status bar.
I hesitated with a temporary error message, but since the effects of an exception might make the application unstable afterwards, I decided to use a permanent message instead.
closes #3880
=> silx view: Stopped displaying a message box for each error

src/silx/_config.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py, src/silx/gui/plot/backends/glutils/GLText.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/marker.py, src/silx/gui/utils/matplotlib.py
This PR adds:
- Control over marker text's `QFont` through `MarkerBase.get|setFont` methods.
- General configuration of marker text's `QFont` through `silx.config.DEFAULT_PLOT_MARKER_TEXT_FONT`
A marker QFont can be `None` (the default) to use the default. This is useful for letting `matplotlib` pick its own default.
closes #3931
=> silx.gui.plot.items: Added Marker item font configuration; silx.config: Added `DEFAULT_PLOT_MARKER_TEXT_FONT_SIZE` config

src/silx/gui/_glutils/font.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/glutils/GLText.py, src/silx/gui/plot/items/marker.py, src/silx/gui/utils/image.py, src/silx/gui/utils/matplotlib.py
Merge PR #3956 first!
This PR adds some Python typing on existing functions/methods done while working on PR #3956.
To make it easier to review I splitted it in 2 PRs.
This one only containing the typing once PR #3956 is merged
=> silx.gui.plot: Added Python typing

src/silx/gui/dialog/ColormapDialog.py, src/silx/gui/plot/LegendSelector.py
Replace `qt.QPalette.Normal` by `qt.QPalette.Active` to support pyqt6
closes #3962
=> silx.gui: Fixed PyQt6 support by not using deprecated `qt.QPalette.Normal`

src/silx/gui/plot3d/ParamTreeView.py, src/silx/gui/plot3d/_model/items.py, src/silx/gui/plot3d/items/clipplane.py, src/silx/gui/plot3d/items/core.py, src/silx/gui/plot3d/items/mixins.py, src/silx/gui/plot3d/items/volume.py
This PR fixes many issues in `plot3d`'s `ParamTreeView` with PySide6/PyQt6
Tested with `examples/plot3dSceneWindow.py` with PyQt6.6.0, PySide6.6.0, PyQt5.15.10 (on macos) and PyQt5.9.2 (on linux).
closes #3951
=> silx.gui.plot3d.ParamTreeView: Fixed Qt6 support

examples/imageStack.py, src/silx/gui/plot/ImageStack.py, src/silx/gui/plot/test/testImageStack.py, src/silx/gui/widgets/UrlList.py
when the UrlList is set editable the selection mode is set to `qt.QAbstractItemView.ExtendedSelection`
Here are two screenshots of the feature:
* removing a single item
* removing several items ()
closes #3911
Changelog: 
- gui.ImageStack.UrlList: allow removal of url from the list (if the list is editable only)
=> UrlList: allow removal of url from the list

src/silx/gui/data/DataViews.py, src/silx/gui/dialog/ColormapDialog.py, src/silx/gui/plot/actions/control.py
The goal of this PR is to allow user select the display mode of the ColormapDialog for the min / max value (`data histogram` or `data range`)
Changelog: 
move _DataInPlotMode to public API.
close #3963
=> ColormapDialog: upgrade `_DataInPlotMode` to `DisplayMode`

src/silx/gui/_glutils/gl.py
This PR adds a monkey patch of `pyopengl` fix for python 3.12 (https://github.com/mcfletch/pyopengl/pull/100) for versions of pyopengl that do not have it.
This allows to start using python 3.12 without waiting for a pyopengl release.
closes #3977
=> silx.gui: Fixed support of OpenGL with python3.12 and pyopengl <=3.1.7

src/silx/utils/retry.py
Prevent issues with the multiprocessing module with frozen applications
=> Lazy-loading of multiprocessing module

src/silx/io/h5py_utils.py
The message is:
`H5pyDeprecationWarning: h5py.get_config().swmr_min_hdf5_version is deprecated. This version of h5py does not support older HDF5 without SWMR.`
=> Get rid of h5py 3.10.0 deprecation warning

src/silx/gui/colors.py, src/silx/gui/plot/items/core.py
This PR adds typing to `silx.gui.colors` and defines input and output types for `colors.rgba`.
Since this function is used everywhere for colors, it should help to type colors in the plot API.
=> silx.gui.colors: Added typing

src/silx/gui/qt/__init__.py, src/silx/gui/qt/_qt.py
This PR adds support for selecting the Qt binding with `QT_API` env. var. (case-insensitive) the same way as [matplotlib](https://matplotlib.org/stable/api/backend_qt_api.html#qt-bindings) and close to [qtpy](https://github.com/spyder-ide/qtpy#requirements) - which is case sensitive.
=> silx.gui: Added support for `QT_API` environment variable

src/silx/io/h5py_utils.py
Calls to multiprocessing fail when using PyInstaller frozen applications
=> Do not call multiprocessing module in frozen binaries

.github/workflows/ci.yml, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/test/testItem.py
This PR is changing the way items are stored inside a `PlotWidget`. This aims at making it simpler and solves issues like #3896. On the down side, it might change the behaviour of item management when not using the `PlotWidget.add*` methods...
Still needs testing
closes #3896
=> silx.gui.plot.PlotWidget: Refactored item management

examples/scatterMask.py, src/silx/gui/plot/ColorBar.py, src/silx/gui/plot/ScatterMaskToolsWidget.py, src/silx/gui/plot/actions/control.py, src/silx/gui/plot/test/testPlotWidgetNoBackend.py, src/silx/gui/plot/test/testScatterMaskToolsWidget.py, src/silx/gui/plot/tools/PositionInfo.py
There is no point using a private API when there is a public one for it.
=> silx.gui.plot: Use `PlotWidget.get|setActiveScatter` instead of `PlotWidget._get|setActiveItem(kind="scatter"..)`

doc/source/install.rst, src/silx/gui/_glutils/font.py, src/silx/gui/utils/image.py, src/silx/gui/utils/test/test_image.py
Using grayscale8 QImage (available in Qt>=5.5) avoids some array copies/conversion when dealing with text in the OpenGL backend.
This moves minimum required version from Qt5.3 to Qt5.5... I documented minimum version to 5.6 ton Linux to be inline with Windows and macOS. BTW, we don't test with an old version of pyQt... so the effective min version requirement is probably higher.
Small improvement/clean-up done while working on PR #3956
=> silx.gui.utils.image: Added support of `QImage.Format_Grayscale8` to `convertQImageToArray`

src/silx/gui/plot/ColorBar.py, src/silx/gui/plot/LegendSelector.py
[QMouseEvent.globalPos](https://doc.qt.io/qt-6/qmouseevent-obsolete.html#globalPos) is deprecated in Qt6 and removed from PyQt6.
=> silx.gui: Fixed `QMouseEvent.globalPos()` not available with PyQt6

src/silx/gui/plot/tools/roi.py
This PR change the interaction mode used to create ROI to avoid selection of items that prevents creating ROI.
closes #3874
=> silx.gui.plot.tools.roi.RegionOfInterestManager: Changed interaction mode for ROI creation

src/silx/gui/plot/items/_roi_base.py
This PR makes sure a highlighted ROI receives interaction first by changing the Z layer of its items.
This is a simple fix with one limitation: It does not work if ROI's item Z value is changed which is not the case so far in implemented ROIs.
A neater way to fix this woud be to have a `Group` item (see #3077).
closes #3927
=> silx.gui.plot.items: Make highlighted RegionOfInterest take priority for interactions

src/silx/gui/hdf5/test/test_hdf5.py
Just adds a test that is expected to fail. Does not solve #3219. Upstream problem: https://github.com/h5py/h5py/issues/1706
=> Add test for H5Node soft link to an external link bug

doc/source/modules/gui/plot/plotsignal.rst, examples/plotCurveLegendWidget.py, src/silx/gui/plot/CompareImages.py, src/silx/gui/plot/ComplexImageView.py, src/silx/gui/plot/LegendSelector.py, src/silx/gui/plot/PlotEvents.py, src/silx/gui/plot/PlotInteraction.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/StackView.py, src/silx/gui/plot/StatsWidget.py, src/silx/gui/plot/test/conftest.py, src/silx/gui/plot/test/testPlotWidget.py, src/silx/gui/plot/test/testPlotWidgetActiveItem.py, src/silx/gui/plot/test/testPlotWidgetDataMargins.py
~~Merge PR #3987 first!~~
This PR follows PR #3986 and enable passing items rather than only their legend to `PlotWidget.setActiveCurve|Image|Scatter`.
=> silx.gui.plot.PlotWidget: Refactored management of active items

examples/plotWidget.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/test/testItem.py, src/silx/gui/plot/test/testPlotWidget.py, src/silx/gui/plot/test/testPlotWidgetNoBackend.py, src/silx/gui/plot/test/testStats.py
Merge PR #3988 first!
This PR introduces a breaking API change: `PlotWidget.add*` methods (namely `addCurve`, `addImage`, `addHistogram`, `addScatter`, `addShape`, `addMarker`, `addXMarker`, `addYMarker`) now returns the created/updated PlotWidget item instead of its legend.
To mitigate this API break, `PlotWidget.remove*` methods and `PlotWidget.get*` methods were update to accept an item instance as their `legend` attribute. Together with `setActive*` methods accepting item, this should make the API change seamless for code that was using the legend as an identifier of the item in the `PlotWidget` without using it otherwise.
`PlotWidget.get*` methods log a warning when passed an item instance since this call is no longer needed.
Changes to `examples/` and tests were minimal and actually …
=> `silx.gui.plot.PlotWidget`: Changed add* methods return value to return the item instead of its legend

src/silx/gui/plot/_utils/dtime_ticklayout.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py
This PR reworks the way ticks and labels are computed for timeseries when displayed as microseconds:
The "density" of ticks is adjusted in this case, the 'nice numbers' list has been extended and the formatting updated to strip leading/trailing "0".
closes #3949
=> silx.gui.plot.PlotWidged: Fixed tick display of timeseries

src/silx/gui/qt/_pyqt6.py
This PR fixes issues with PyQt6 enums encountered with Python3.12 on macos (other conditions not tested): some (not all) of the Qt enum members were missed when making them available in the class containing the enum (e.g., `Qt.Widget`, `Qt.AlignCenter`).
Actually, iterating over the enum no longer returns all of its values...
=> `silx.gui.qt`: Fixed `PyQt6` support

src/silx/gui/plot/PlotInteraction.py, src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/shape.py
This PR renames `Shape` items second color of line to use the same API as `Curve` and `Histogram`.
Previous methods, argument are kept with deprecation warnings.
closes #3998
=> silx.gui.plot.items.Shape: Changed Shape.get|setLineBgColor to get|setLineGapColor

examples/floatedit.py, src/silx/gui/widgets/FloatEdit.py, src/silx/gui/widgets/test/test_floatedit.py
Added a `widgetResizable`/`setWidgetResizable` to `FloatEdit` in order to always display the full value
- With this flag the widget width will grow/shrink during the user typing
- `sizeHint` is reimplemented as result the default layout also fit the content
- The implementation is based on `minimumSize` to inforce the parent layout to resize them self (windows and dialog will also grow and shrink)
- The property name `widgetResizable` was picked from `QScrollBar`
Changelog: 
- Added `widgetResizable` to `FloatEdit` (default is false)
=> FloatEdit: Added widgetResizable

examples/stackedprogressbar.py, src/silx/gui/widgets/StackedProgressBar.py, src/silx/gui/widgets/test/test_stackedprogressbar.py
Closes #3985 
This PR added a `StackedProgressBar` widget.
This allow to display a bit more complex information than the default Qt progress bar.
The designed and API was based on the bootstrap progress bar.
This can be tested this way:
Changelog: 
- Added a `StackedProgressBar`
=> Added StackedProgressBar

src/silx/gui/conftest.py, src/silx/gui/widgets/test/test_floatedit.py
Do not return a weakref proxy but the widget itself so it can be added e.g. to a Qt layout.
=> silx.gui: improved `qWidgetFactory` test fixture

src/silx/gui/plot/ColorBar.py
This happens to me few time.
It's just a protection against division by zero.
Changelog: 
- Protect ColorBar from division by zero
=> Robustness on the colorbar

src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLText.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/marker.py
Related to #4005 #4010
Previously an automatic background color was added to the marker text of the OpenGL backend to try to improve the readability of the text. That's unfortunately not enough, so better to let it open to the designer.
- Now the background is used for both backend
- And designer can specify it as `marker.setBackgroundColor("red")`
- The automatic background was dropped
```
label = Marker()
label.setPosition(50, 50)
label.setText("Foo bar\nmmmmmmmmmmmmmmmmmmmm")
label.setBackgroundColor("#FFFFFF44")
plot.addItem(label)
label2 = Marker()
label2.setPosition(70, 70)
label2.setText("Foo bar")
label2.setColor("red")
label2.setBackgroundColor("#00000044")
plot.addItem(label2)
label3 = Marker()
label3.setPosition(10, 70)
label3.setText("Pioupiou")
label3.setColor("yellow") …
```
=> Added background color for markers

src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py, src/silx/gui/utils/matplotlib.py
This PR changes the configuration of matplotlib tick label `ScalarFormatter` to enable offset, scientific notation and math text to format tick labels.
The behavior of the formatter has changed over time and here are some examples of the behavior as of today: no offset/scientific notation | scientific notation only around 0 | ofset + scientific notation
closes #3997
=> silx.gui.plot.PlotWidget: Updated plot axes tick labels behavior

src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py
This PR reworks the rendering of dashed lines in the OpenGL backend to make it more consistent with the matplotlib backend.
It aims at making dashes behaves the same as the matplotlib backend and the same between `Shape` and `Curve`.
There is a limitation due to OpenGL is that the available line width can be limited by the OpenGL implementation (this PR does not aim at mitigating that).
It also paves the way in the OpenGL backend to provide the line style as `(offset, dash pattern)` by centralizing the conversion of `linestyle` to dash pattern early.
related to #4010
=> silx.gui.plot.PlotWidget: Improved line dash rendering for OpenGL backend

src/silx/gui/plot/LegendSelector.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotCurve.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/curve.py, src/silx/gui/plot/test/testItem.py, src/silx/gui/plot/tools/test/testCurveLegendsWidget.py, src/silx/gui/widgets/LegendIconWidget.py
This PR adds support in both `PlotWidget` backends of line style as `(offset, (dash pattern))` the same way matploltib Line2D supports it.
Previous string based styles (e.g., '--', '-.') are still supported.
related to #4005 and #4010, follow up of #4015
~~This still need some tests.~~
=> silx.gui.plot.PlotWidget: Added support of line style defined as `(offset, (dash pattern))`

examples/plotWidget.py, src/silx/gui/plot/PlotToolButtons.py, src/silx/gui/plot/items/_roi_base.py, src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/curve.py, src/silx/gui/plot/items/roi.py, src/silx/gui/plot/tools/PlotToolButton.py, src/silx/gui/plot/tools/RulerToolButton.py
This PR improve the ruler from the plot with a default fixed dashed style
No need changelog, it's a new feature
- Move PlotToolButton as an independent module
- Move RulerToolButton as an independent module
- Move inner class as a private class
- Update the style
=> Improve ruler

src/silx/gui/plot/backends/glutils/GLPlotCurve.py, src/silx/gui/plot/items/core.py
Reworks few opengl markers to use distance function.
This allow to implement easily antialiasing and fix some floating point glitches.
Changelog: 
- Fixes glitches on OpenGL marker rendering
=> Antialiasing on opengl markers

src/silx/image/bilinear.pyx, src/silx/image/marchingsquares/_mergeimpl.pyx, src/silx/math/_colormap.pyx
Remove compilation warnings
close #4019
=> cython3 compatibility

src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLText.py
Alternative implementation of PR #4011
This PR adds padding around text displayed by markers for the display of borders.
Instead of relying on 2 rendering as in PR #4011, it plays with the texture coordinates.
=> silx.gui.plot.PlotWidget: Improved text background rendering for OpenGL backend

.github/workflows/ci.yml, ci/appveyor.yml, pyproject.toml
Small PR following PR #4033 to update build dependencies.
Using `oldest-supported-numpy` should fix building `manylinux2010` wheels which is now broken since the build tries to build the latest numpy and fails.
=> build: Updated build dependencies

MANIFEST.in, doc/source/applications/index.rst, doc/source/conf.py, doc/source/index.rst, doc/source/install.rst, doc/source/modules/index.rst, package/debian12/control, requirements-dev.txt, setup.py
This PR reworks the documentation landing page to use `sphinx-panels` tabs and grid.
I used the `sphinx-panels` package which is deprecated rather than `sphinx-design` (its successor) to be compatible with debian 12 which do not provide `sphinx-design`.
=> Documentation: Updated landing page

src/silx/gui/_glutils/OpenGLWidget.py
This avoids display issues when the reported screen DPI is obviously wrong.
This has been seen with Dell U4919DW screen on ubuntu20.04 where xrandr reports a "physical" screen size of 1mm x 1mm leading to crazy dpi.
I set the threshold to 1000dpi which is higher than the highest smartphone screen resolution as of today.
=> silx.gui.plot: Added workaround for erroneous DPI reported by Qt

package/windows/README.rst, package/windows/pyinstaller.spec, requirements-dev.txt
This PR fixes the spec file which was no longer generating a working fat binary
closes #4040
=> Build: Fixed support of PyInstaller v6

src/silx/gui/conftest.py, src/silx/gui/dialog/test/test_colormapdialog.py, src/silx/gui/plot3d/scene/viewport.py
This PR reworks the colormap dialog tests to make them more pytest-ish. It's an attempt to address CI failures (see #4032)
closes #4032
=> silx.gui.dialog.ColormapDialog: Updated tests

run_tests.py, src/silx/test/__init__.py
This PR runs `pytest` in a subprocess for both `silx.test.run_tests` and `run_tests.py`.
Previous way of running tests had issue with pytest 8.0.0rc1 apparently because of the module path. Since `pytest` is playing with the imports, it is anyway best IMO to run it separately.
Failing CI:
- https://ci.appveyor.com/project/ESRF/silx/builds/48931383/job/bgbw7jaa9wq9tjnt
- https://gitlab.esrf.fr/silx/bob/silx/-/jobs/910150
=> Tests: Fixed test execution

src/silx/gui/plot3d/scene/viewport.py
This PR reverts some debug changes that were included in PR #4044 and it removes a deprecation warning.
=> silx.gui.plot3d: Revert unwanted change and fixed deprecation warning

requirements.txt, setup.py, src/silx/gui/_glutils/font.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py, src/silx/gui/plot/backends/glutils/GLText.py, src/silx/gui/plot3d/Plot3DWidget.py, src/silx/gui/plot3d/scene/axes.py, src/silx/gui/plot3d/scene/text.py, src/silx/gui/plot3d/scene/window.py, src/silx/gui/utils/matplotlib.py
This PR reworks the way to raster text in with OpenGL to (1) take into account the screen DPI and (2) use matplotlib math text parsing.
In `PlotWidget` OpenGL backend, the default font from matplotlib is used for all text in axes and title.
This requires `matplotlib>=3.1`.
It also removes a usage of `QScreen.logicalDotsPerInchY` which might returned a wrong value (this complement PR #4038)
BTW, `compareBackends.py` (PR #4031) is very useful!
Related to #4025 and #4007
=> silx.gui.plot and plot3d: Updated font management

src/silx/io/test/test_url.py, src/silx/io/url.py
fix some typo when dealing with `DataUrl` file_path
=> DataUrl: fix: allow file_path to be None

src/silx/io/test/test_utils.py, src/silx/io/utils.py
This PR fixes support of `h5py_read_dataset` with empty arrays (It was raising an exception) and updates tests to check it (related to PR #3748).
Changelog:
=> [2.0] silx.io.utils.h5py_read_dataset: Fixed support of empty arrays

src/silx/gui/plot/items/_roi_base.py, src/silx/gui/plot/tools/test/testRoiCore.py
This PR fixes and issue with ROI when passing the manager as parent when creating the ROI and adds a test for it.
This should fix issue spotted by bliss CI: https://gitlab.esrf.fr/bliss/bliss/-/jobs/927560
=> [2.0] silx.gui.plot: Fixed ROI initialisation with parent

src/silx/io/specfile/src/sfinit.c, src/silx/math/marchingcubes.pyx
This PR fixes compilation warnings reported by debian packaging:
- Remove previous workaround in cython that was there to avoid warnings but is now causing some...
- Use read value: Now skip erroneous cases where it would have read random buffer anyway
closes #4060
=> silx.io.specfile, silx.math.marchingcubes: Fixed compilation warnings

.github/workflows/release.yml, setup.py
This PR proposes to add a github actions release workflow based on [cibuildwheel](https://cibuildwheel.readthedocs.io/).
This workflow generates the source tarball, the wheels and the documentation before uploading the tarball and wheels to pypi (this still needs some configuration on both pypi and github side). The documentation can be retrieved from the workflow artifacts.
The release workflow can be triggered either manually or when publishing a release on github (and will be set to only start for tags with a `v` as first letter).  When the workflow is started manually, the upload to pypi is skipped. When started on a release, a confirmation is requested before publishing to PyPi.
This PR also removes `bitshuffle` from `full` requirements: There is no wheel and it does not build on …
=> CI: Added release workflow

doc/source/applications/compare.rst, doc/source/applications/convert.rst, doc/source/applications/view.rst, doc/source/conf.py, doc/source/index.rst, doc/source/modules/gui/index.rst, doc/source/modules/io/index.rst, doc/source/modules/math/index.rst, doc/source/modules/opencl/index.rst, doc/source/user_guide.rst, package/debian12/control, requirements-dev.txt, setup.py
This PR switches the documentation from `sphinx-panels`  to `sphinx-design`.
This is at the expense of no longer building the documentation with Debian12 since it does not provide `sphinx-design`.
closes #4062
=> Documentation: Updated to use `sphinx-design` instead of `sphinx-panels`

.github/pull_request_template.md, CONTRIBUTING.rst
Checklist:
<hr>
This PR proposes to change the guidelines of how to provide information in PRs for the release notes.
The goal is:
- (1) to keep it simple and easy so we are not bored to do it for each PR (e.g., adding a specific file to each PR to document the changes or filling the changelog.rst file for each PR),
- (2) to ease the authoring of release notes. It's quite long to manually sort PRs by subpackages and by kind of changes, while with a formatting convention it can be automated.
I'd take any better approach/convention for naming the kind changes/etc! and if there is something already existing, even better!
What do you think?
=> Documentation: Changed guideline to provide changelog in PR

src/silx/gui/hdf5/test/test_hdf5.py, src/silx/io/utils.py
Checklist:
<hr>
This PR reverts PR #3939 which disabled HDF5 file locking when opening a file with `silx.io.open`.
Disabling HDF5 file locking is causing trouble (see #4071) because there is an issue with external links when file locking is disabled (see https://forum.hdfgroup.org/t/external-link-and-file-locking-disabled-issue/12012).
So as of today, disabling file locking when opening a HDf5 file is not safe and IMO shouldn't be the default.
Looking at the [Larch](https://github.com/xraypy/xraylarch/blob/master/larch/io/specfile_reader.py) link in the issues PR #3939 solved(see issues #3938, #3936), it looks it is calling directly `h5py_utils.File` instead of `silx.io.open` for hdf5 file so it should not be affected.
attn @woutdenolf @maurov
=> silx.io: Changed `open` function behavior: lock HDF5 files when opening them

package/debian12/rules
Checklist:
<hr>
Following PR #4063, documentation no longer build on Debian12. This PR removes the build of documentation during the packaging that should have been removed in PR #4063.
=> Build: Fixed Debian12 packaging by removing build of documentation

requirements.txt, setup.py, src/silx/resources/__init__.py
Checklist:
<hr>
This PR replaces usage of `pkg_resources` with `importlib_resources` backport package for Python<3.9
Closes #4075
=> `silx.resources`: Changed dependency from deprecated `pkg_resources` to `importlib_resources` for Python<3.9

examples/plotProfile.py, examples/scatterview.py, src/silx/math/fit/test/test_functions.py, src/silx/opencl/sift/test/test_gaussian.py
Checklist:
<hr>
This PR replaces `scipy.signal.gaussian` with `scipy.signal.windows.gaussian` (will be removed in scipy 1.13.0)
Close #4086
=> Imports: changed scipy.signal.gaussian, replaced with scipy.signal.windows.gaussian

src/silx/gui/widgets/ElidedLabel.py
Checklist:
<hr>
This PR avoids a deprecation warning with Qt5 >= 5.11
closes #4085
=> silx.gui.widgets.ElidedLabel: Fixed deprecation warning with Qt5>=511

src/silx/gui/data/RecordTableView.py
Checklist:
<hr>
The base-color for the _MultiLineItem cell is always set to white if it is not selected and there is no brush in the backgroundrole. So when viewing a string dataset with the OS set to dark mode, you can't read it anymore. For me, this happens with NULLPAD ASCII STRING.
=> silx.gui.data.RecordTableView: Fixed cell background color in dark mode

src/silx/gui/plot/items/core.py, src/silx/gui/plot/items/scatter.py, src/silx/gui/plot/test/testPlotWidget.py
Checklist:
<hr>
This PR fixes issues occurring in when negative values are passed as errors:
- In case of a negative error value, matplotlib raises an exception (issue #4066) and the OpenGL backend make the error bar go the other way...
- In case all error values lead to negative bound of the error bar, the computation of the item bounding box failed for log axes.
With this PR:
- error values are clipped to `[0, inf[` before being passed to the rendering backend
- bounds are ignoring error values leading to negative bound of the error bar.
closes #4066
=> `silx.gui.plot.PlotWidget`: Fixed support of negative error values for curves and scatter plot 

doc/source/description/sift.rst
resolving (ish) https://github.com/silx-kit/silx/issues/4098
Checklist:
<hr>
=> Documentation: Added how to override `silx.opencl.sift` parameters

.github/workflows/ci.yml, ci/appveyor.yml, ci/requirements-pinned.txt, src/silx/gui/plot/items/core.py, src/silx/math/fit/filters.pyx, src/silx/math/fit/filters/include/filters.h, src/silx/math/fit/filters/src/strip.c, src/silx/math/fit/filters_wrapper.pxd, src/silx/math/medianfilter/medianfilter.pyx
Checklist:
<hr>
This PR aims at having CI pass
=> Dependencies: Fixed numpy v2 support on Windows; Continous integration: Added tests with numpy v2; Fixed test by using PySide<6.7

src/silx/image/marchingsquares/_mergeimpl.pyx
Checklist:
<hr>
This PR fixes a cython code generation warning with cython 3.0.10.
I checked that the generated C++ code is the same and that it's OK with a previous version of Cython (3.0.6).
closes #4105
=> silx.image.marchingsquare: Fixed cython warning

src/silx/io/commonh5.py, src/silx/io/test/test_commonh5.py
Checklist:
<hr>
This PR replaces the local implementation of `_MappingProxyType` (For python 2 support) by `types.MappingProxyType`
closes #4049
=> silx.io.commonh5: Improved code to use built-in types

src/silx/gui/plot/PlotWidget.py
Checklist:
<hr>
From #4133 
This PR fixed the way the addCurve requests color and style (examples)
Test code:
```
from silx.gui.plot import Plot2D
import numpy as np
from PyQt5.QtWidgets import QApplication, QMainWindow
if __name__ == "__main__":
app = QApplication([])
mw = QMainWindow()
plot = Plot2D()
x = np.linspace(0,10,10)
y = [x*ii for ii in range(20)]
for _ in range(20):
color, style = plot._getColorAndStyle()
print(f"color index is {plot._colorIndex}, style index is {plot._styleIndex}")
plot.addCurve(x,y[_], legend=_ , 
#color='black',
color=color,
linestyle=style,
)
mw.setCentralWidget(plot)
mw.show()
app.exec_()
```
- If a color is requested before to use in the plot (and maybe other plots or markers), it completes the 10 colors of the colormap before changing the linestyle
``` …
```
=> silx.gui.plot.PlotWidget.addCurve: Fixed progression in color, linestyle

src/silx/app/view/CustomPlotSelectionWindow.py
Add comments for each function, variable typing and type returns.
The comments can surely be more precise. 
And maybe some comments are missing in the functions.
=> silx.app.view.CustomPlotSelectionWindow : Added the documentation

src/silx/app/view/CustomPlotSelectionWindow.py, src/silx/app/view/Viewer.py
Added functionality to enhance the user experience.
**1. Added functionality for adding X or Y datasets directly from the main page**
To do this, simply : 
-  Open silx view
- Select a file
- Right-click on the dataset and choose one of the 2 options (see image)
- Set abscissa to plot selection
- Add ordinate to plot selection
- The "Plot Selection" page will open
**2. Add user feedback when dropping on the plot**
=> silx.app.view.CustomPlotSelectionWindow : Add dataset directly from silx + drop overlay on plot

src/silx/app/view/CustomPlotSelectionWindow.py, src/silx/app/view/test/test_plotselection.py, src/silx/conftest.py, src/silx/gui/conftest.py
**Added some tests for CustomPlotSelectionWindow**
- Testing the Drop function with a valid dataset
- Testing the Remove function
- Testing the ClearAll fonction
- Testing multiple Y additions
- Testing the drop function with an invalid dataset
=> silx.app.view.test.test_plotselection : Added test for CustomPlotSelectionWindow

src/silx/utils/ExternalResources.py
Fix #4127 
I don't think the addition of a setter is needed
=> silx.utils.ExternalResources: Allow to set data_home when instantiating the class

src/silx/opencl/convolution.py
Checklist:
<hr>
This MR adds a synchronization for separable convolution on CPU. For some reason [it failed](https://ci.debian.net/packages/n/nabu/testing/amd64/49560879) when used by nabu for "unsharp mask" operation.
=> `silx.opencl.convolution`: Fixed separable convolution on CPU that crashed in some cases

src/silx/utils/retry.py, src/silx/utils/test/test_retry.py
This fix warrants a silx release. It affects all online workflows using blissdata.
=> silx.util.retry: Fixed resetting the timeout timer when iterating

CHANGELOG.rst, src/silx/_version.py, src/silx/gui/_glutils/font.py
Checklist:
<hr>
It still needs investigation and isolation of the issue, but it seems matplotlib raster math text is causing memory leaks at least as it is used in silx OpenGL backend (see https://gitlab.esrf.fr/bliss/bliss/-/issues/4539).
In the mean time, let's restore the previous implementation which use Qt when there is no tex math syntax.
=> silx.gui: Updated OpenGL text rendering to use Qt when possible

src/silx/gui/plot/ImageStack.py
Make sure `ImageStack._urlIndexes` is always a dict.
This can be lead to errors when calling `ImageStack.getUrls` before any url is called and better for consistency.
=> silx.gui.plot.ImageStack: fix `_urlIndexes` initialization. 

src/silx/opencl/common.py, src/silx/opencl/projection.py
Use `pyopencl.create_image()` instead of `pyopencl.Image`. 
Close #4191
=> silx.opencl: Fixed deprecation warning upon texture creation

src/silx/io/specfile.pyx
cython/cython#5830 /
d7e95912b6ed7d20e190fbf1aecb9f2a997d479 in cython removed long as a valid type in favor of int at language level 3.
Checklist:
<hr>
=> MNT: use only int instead of long in cython code

src/silx/io/h5py_utils.py
When making custom retry_on_error methods I often expand on the hidden _is_h5py_exception and _retry_h5py_error method. Replying on private methods is not great. So I make them public.
=> silx.io.h5py_utils: Added is_h5py_exception and retry_h5py_error`

CONTRIBUTING.rst
=> Documentation: Small improvements to Release section of CONTRIBUTING

src/silx/gui/plot/backends/BackendMatplotlib.py
This PR is an attempt to fix a warning appearing with matplotlib 3.10
See details in #4203 
close #4203
=> gui matplotlib backend warning: fix conflict between y limits and autoscale

src/silx/gui/plot/_utils/__init__.py, src/silx/gui/plot/backends/BackendOpenGL.py
Checklist:
<hr>
This PR fixes an issue when setting the limits of the plot with some margins and log scale.
To reproduce:
```
In [1]: from silx import sx, config
In [2]: config.DEFAULT_PLOT_BACKEND='gl'
In [3]: w = sx.imshow(((0, 0), (0, 255)))
```
Then open the Colormap dialog, set to autoscale and use log scale (Related to https://gitlab.esrf.fr/bliss/bliss/-/issues/4722).
=> silx.gui.plot: Fixed PlotWidget axis for OpenGL backend

src/silx/opencl/common.py, src/silx/opencl/test/test_addition.py, src/silx/opencl/test/test_processing.py
Checklist:
<hr>
This MR addresses an issue in `opencl/common.py` when using `PYOPENCL_CTX` variable.  
When using `PYOPENCL_CTX`, a new context is always created regardless of the cache content. This contrasts with the behavior obtained when not using `PYOPENCL_CTX` (contexts are re-used whenever possible).
```python
import os
from silx.opencl.processing import OpenclProcessing
op1 = OpenclProcessing()
op2 = OpenclProcessing()
print(op1.ctx is op2.ctx) # True
os.environ["PYOPENCL_CTX"] = "0:0"
op3 = OpenclProcessing()
op4 = OpenclProcessing()
print(op3.ctx is op4.ctx) # False
```
=> OpenCL: Fix context creation through PYOPENCL_CTX environment variable

src/silx/gui/plot/ImageView.py, src/silx/gui/widgets/ElidedLabel.py
Checklist:
<hr>
`profile` was replaced with `getProfileToolBar`. This deprecation was introduced in #3457, which seems to date back to v1
=> silx.gui.plot.ImageView: Remove deprecated `profile` method

src/silx/io/h5py_utils.py
Checklist:
<hr>
Part of #4236
The `enable_file_locking` parameter was renamed `locking` in v1 (cf. #3555).
=> silx.io.h5py_utils.File: Remove deprecated `enable_file_locking` parameter

src/silx/utils/testutils.py
=> testutils: Remove deprecated `TestLogging` and `test_logging`

src/silx/gui/plot/CurvesROIWidget.py, src/silx/gui/plot/test/test_curvesroiwidget.py
Checklist:
<hr>
This signal was for backwards compatibility with silx 0.7. Prefer connecting directly to `CurvesRoiWidget.sigROISignal`.
=> silx.gui.plot.CurvesROIDockWidget: Remove deprecated `sigROISignal`

src/silx/gui/plot/CurvesROIWidget.py
Checklist:
<hr>
Trying to take #4236 a bit further by identifying functionality that is said to be deprecated in comments but not actually marked as such.
Not sure I've done this right... Let me know :wink:
=> silx.gui.plot.CurvesROIDockWidget: Effectively deprecate convenience methods to underlying `CurvesROIWidget`

src/silx/gui/data/Hdf5TableView.py
close #4252
Allowing selectALL and deselect only for QLineEdit.
Actually this part of code should hit only QLineEdit but somehow QSpinBox appears there. Could not reproduce the bug.
=> silx.gui.data.Hdf5TableView uncaught exception fixed

examples/imageview.py, src/silx/gui/plot/ImageView.py, src/silx/gui/plot/test/test_imageview.py
Checklist:
<hr>
It was renamed to `resetzoom` in #3488. I'm switching to the new name in various places too.
=> silx.gui.plot.ImageView: Warn on deprecated `reset` parameter of `setImage()`

src/silx/gui/data/NXdataWidgets.py, src/silx/gui/data/_SignalSelector.py, src/silx/gui/plot/StackView.py, src/silx/gui/widgets/SignalSelector.py
Checklist:
<hr>
- Replace slider with combo-box for signal selector of "image_2d" and "scatter_2d"
- Pass NXdata signal name for "volume_3d" 
image_2d: combo-box to select signal below plot
scatter_2d: combo-box to select signal below plot
volume_3d: NXdata signal name in plot title
=> silx view: improve NXdata signal selection

src/silx/io/nxdata/_utils.py, src/silx/io/nxdata/parse.py, src/silx/io/test/test_nxdata.py
Checklist:
Fix #2927 #4199 
The dataset name (signal or axes) is by order of priority:
- `@long_name`
- `"<dataset_name> (@units)"`
- `"<dataset_name>"`
=> silx.io.nxdata: add units to dataset name (signal/axes) when present

src/silx/gui/plot/tools/profile/manager.py
I was not able to reproduce blinking with 'recent' PyQt5 version (5.15).
PyQt5 5.14 is form december 2019 and the most recent version of python it handle is 3.8... we are now supporting 3.10 or more recent. So let's go for the clean.
No issue met with PyQt6
=> ProfileManager: remove workaround for Qt5 < 5.14

src/silx/math/colormap.py
This MR static type the module for internal and external use.
For external use i think it is fine.
For internal use, there is still typing problem
- because of the use of mixin without abstract functions (i.e..a call to `apply()`)
- no interface for `_colormap`
- And some types could be more strict by handling side cases as exception (i.e. remove `tuple[None, None]`)
Checklist:
<hr>
=> silx.math.colormap: Added static typing

src/silx/gui/plot/items/_arc_roi.py, src/silx/gui/plot/items/_roi_base.py, src/silx/gui/plot/items/axis.py, src/silx/gui/plot/items/curve.py, src/silx/gui/plot/items/image.py, src/silx/gui/plot/items/roi.py, src/silx/gui/plot/items/scatter.py, src/silx/gui/plot/items/shape.py
Improve the typing around plot items.
The types are not extremely accurate, this can be improved later.
Nothing crazy <s>except a new `AxisScale` enum. As it's a `StrEnum` i expect it to stay compatible with the previous implementation</s> (`StrEnum` is python 3.11) so i fallback to a `AxisScaleType` with literal strings.
Checklist:
<hr>
=> silx.gui.plot.items: Added static typing

setup.cfg, src/silx/sx/__init__.py, src/silx/sx/_plot3d.py, src/silx/test/__init__.py, src/silx/test/utils.py, src/silx/utils/ExternalResources.py, src/silx/utils/retry.py, src/silx/utils/test/test_array_like.py, src/silx/utils/test/test_number.py, src/silx/utils/test/test_weakref.py, src/silx/utils/weakref.py
Added # noqa: F401 to ignore valid imported modules which aren't used
Changed lines with length longer than 88 characters (according to black) to properly wrap
Fixed a typo in silx.utils.ExternalResources which may have caused bugs elsewhere
Refactored ambiguous variable "l" within silx.utils with a more descriptive name
=> silx.sx/silx.test/silx.utils: Improved code to pass flake8, black, ruff tests

src/silx/math/histogramnd/src/histogramnd_template.c
Checklist:
<hr>
Ensure the variable is initialized with a zero of the proper type.
Close #4307
=> Build: Fix compilation warning about unsafe cast under windows

package/debian12/rules, src/silx/conftest.py, src/silx/math/fft/test/test_fft.py, src/silx/test/utils.py
Checklist:
<hr>
Fix #4285 
Argument name and associated env variables were changed:
- `--low-mem` becomes `--no-high-mem`
- `SILX_TEST_LOW_MEM` becomes `WITH_HIGH_MEM_TEST` 
I tried to be consistent with other options: `--no-opengl` /`WITH_GL_TEST`, `--no-gui/`WITH_QT_TEST` but there is also `--no-opencl`/`SILX_OPENCL`. 
Should I keep the `SILX` prefix for the env variable ?
The logic was also inverted so that high memory tests are skipped unless the env variable is set.
=> Tests: replace `--low-mem` arg by `--no-high-mem` and skip high memory tests by default

src/silx/gui/data/Hdf5TableView.py
This PR update the default update mode for scrolling for the HDF5TableView as this is more convenient
close #4118
=> Hdf5TableView: use 'ScrollPerPixel' mode scrolling

src/silx/gui/widgets/FilenameCompleter.py
Checklist:
Needs #4320 to integrate the new file in the meson build
=> `silx.gui.widgets`: Added `FilenameCompleter` that provides autocompletion for file paths

run_tests.py, src/silx/conftest.py, src/silx/test/utils.py
Checklist:
<hr>
This PR is a follow-up of PR #4319.
It replaces the `--no-high-mem` test option by it's opposite since by default "high mem" tests are not run and so there was no way to run them anymore.
=> Tests: Fixed running high memory tests

.github/workflows/ci.yml, pyproject.toml
Checklist:
<hr>
This PR makes use of meson `--vsenv` to force using MSVC on Windows.
This simplifies the CI config a bit.
See:
- https://mesonbuild.com/meson-python/how-to-guides/meson-args.html#force-the-use-of-the-msvc-compilers-on-windows
- https://mesonbuild.com/Builtin-options.html#details-for-vsenv
=> Build: Added `--vsenv` meson build option

doc/source/install.rst, meson.build, meson.options, src/silx/io/specfile/meson.build
Checklist:
<hr>
This PR removes the use of env. var. to configure the build and replaces them with standard meson setup-args options.
It also updates the documentation accordingly.
=> Build: Changed way to pass build options

src/silx/utils/ExternalResources.py
Checklist:
<hr>
I use the `ExternalResources` class in another project to download test data. In my case, these are HDF5 files, so the logging message that mentions that images are being downloaded was inconsistent. It is likely also inconsistent in the case of `silx`. The replacement of references to  "image" with "file" should provide better generalization.
=> silx.utils.ExternalResources: Replace all occurrences of "image" with "file"

.github/workflows/ci.yml, .github/workflows/release.yml, doc/source/install.rst
Checklist:
<hr>
This PR :
- fixes the release workflow to work with meson and updates used actions/runner images.
- updates both PR and release workflows to call `pytest` directly 
Having `pytest_addoption` in the `conftest.py` is not really good: Depending how `pytest` is called it may or may not be taken into account....
=> CI: Updated release and test workflows

src/silx/gui/plot/backends/glutils/GLPlotImage.py, src/silx/gui/plot3d/scene/function.py
Fix #4356 
Checklist:
<hr>
This PR changes the texture wrap mode from clamp-to-edge to mirrored-repeat for the texture storing the colormap.
This fixes rendering issues on some computers (closes  #4356) and it should not impact rendering otherwise.
=> silx.gui.plot, silx.gui.plot3d: Fixed colormap out-of-bound color with OpenGL backend

src/silx/io/test/test_dictdump.py
close #4369 
- improve robustness of 'test_dicttonx_pint'
The issue looks to come from using `ureg = pint.UnitRegistry()` instead of `ureg = pint.get_application_registry()`.
Creation of registry seems kind of weak / fragile. See https://pint.readthedocs.io/en/stable/getting/pint-in-your-projects.html#having-a-shared-registry.
=> TestDictToNx: use 'pint.get_application_registry()' instead of 'pint.UnitRegistery

src/silx/gui/plot/PlotWidget.py, src/silx/gui/plot/backends/BackendBase.py, src/silx/gui/plot/backends/BackendMatplotlib.py, src/silx/gui/plot/backends/BackendOpenGL.py, src/silx/gui/plot/backends/glutils/GLPlotFrame.py, src/silx/gui/plot/items/axis.py
Checklist:
<hr>
For #4253
This PR adds the internal machinery to allow to invert X axis programatically in `PlotWidget` for both backends (see example code below).
GUI control implementation is left to completely handle #4253
```python
from silx.gui import qt
from silx.gui.plot.PlotWidget import PlotWidget
app = qt.QApplication()
X = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
Y = [x**3 for x in X]
w = qt.QWidget()
layout = qt.QHBoxLayout(w)
w1 = PlotWidget(backend="mpl")
w1.addCurve(X, Y)
w1.setXAxisInverted(True)
w1.setYAxisInverted(True)
w2 = PlotWidget(backend="gl")
w2.addCurve(X, Y)
w2.setXAxisInverted(True)
w2.setYAxisInverted(True)
layout.addWidget(w1)
layout.addWidget(w2)
w.show()
app.exec()
```
=> silx.gui.plot.PlotWidget: Allow to invert X axis

src/silx/gui/data/DataViewer.py, src/silx/gui/data/DataViews.py
Checklist:
<hr>
Follow-up of #4408 for consistency. Replaces the Stack vis for NXdata with the Image vis
=> silx.gui.data.DataViews: display NXdata stacks with _NXdataImageView

src/silx/gui/data/DataViews.py, src/silx/gui/data/NXdataWidgets.py, src/silx/gui/data/NumpyAxesSelector.py
Checklist:
<hr>
Fix #4213
When the NXdata has named axes, `silx view` will now use these as labels for the slicing sliders.
I only added it for images for now. If we agree that the implementation is sensible, I could add it to other visualizations as well.
=> silx.gui.data.NXdataWidget: Use axis names as slider labels (when present)
